### ISSUE TITLE
"Add more" url is broken

### ISSUE THREAD

**Issue by zz22394** [cloudera/hue#1006]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

What is the Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...)
CDP 1.0 (Cloudera Runtime 7.0.3)

Is there a way to help reproduce it?
<img width="414" alt="image" src="https://user-images.githubusercontent.com/516268/70099409-21f4de00-1672-11ea-8299-ea797ca4860c.png">
<img width="333" alt="Screen Shot 2019-12-04 at 8 44 37" src="https://user-images.githubusercontent.com/516268/70099509-549ed680-1672-11ea-8758-f54cb546ab51.png">

**Comment by zz22394** [comment]
The URL should be
https://gethue.com/new-sql-editor/

**Comment by romainr** [comment]
https://github.com/cloudera/hue/pull/1007?email_source=notifications&email_token=AAAEMGJQHN4D636MZ6CMFCTQW3XVLA5CNFSM4JVAQZY2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H53AVAA
