### ISSUE TITLE
how to upgrade database when upgrade hue 3.11.0 to 4.5.0

### ISSUE THREAD

**Issue by fsilent** [cloudera/hue#1008]
hello, i used hue 3.11.0 and pstgresql database， now i want to upgrade hue to 4.5.0 version。
how can i upgrade database?

**Comment by romainr** [comment]
./build/env/bin/hue migrate

Will run the migrations. As usual, do a backup of the DB before just in case

**Comment by fsilent** [comment]
3ku(thank you)
