### ISSUE TITLE
hue Integrate spark thrift server query hive data

### ISSUE THREAD

**Issue by Faiz2** [cloudera/hue#1015]

**Comment by romainr** [comment]
https://docs.gethue.com/administrator/configuration/connectors/#apache-spark-sql ?

**Comment by Faiz2** [comment]
thank you , I try to configure and install thrift_sasl got this error
![image](https://user-images.githubusercontent.com/18616592/70618223-3d04b680-1c4d-11ea-9641-94f1b75c7309.png)

**Comment by Faiz2** [comment]
Recompile in Linux and Connect using jdbc
Connect using jdbc
