### ISSUE TITLE
[hue4.5]About the problem that GatewayServer cannot be closed after using presto query

### ISSUE THREAD

**Issue by ganborui** [cloudera/hue#1018]
version - hue4.5
Each new user starts a GatewayServer process after using a presto query. How can these processes be closed?

**Comment by romainr** [comment]
Now using SqlAlchemy with pyhive is recommended instead, hav you tried it? https://docs.gethue.com/administrator/configuration/connectors/#apache-presto

**Comment by ganborui** [comment]
Can I directly modify the use of hue.ini in the hue4.5 version? Or do I need to download the latest code and compile it before using it?

**Comment by ganborui** [comment]
> Now using SqlAlchemy with pyhive is recommended instead, hav you tried it? https://docs.gethue.com/administrator/configuration/connectors/#apache-presto
Can I directly modify the use of hue.ini in the hue4.5 version? Or do I need to download the latest code and compile it before using it?

**Comment by ganborui** [comment]
Can I directly modify the use of hue.ini in the hue4.5 version? Or do I need to download the latest code and compile it before using it?

**Comment by romainr** [comment]
Yes, just modify it, just need to restart Hue

**Comment by ganborui** [comment]
Thank you very much, the problem has been successfully solved
