### ISSUE TITLE
[sqlalchemy] Only keep the last query open

### ISSUE THREAD

**Issue by ganborui** [cloudera/hue#1020]
When connecting presto through sqlalchemy, each query will generate a new uuid and save all previous results, which is not reasonable.

```
def execute(self, notebook, snippet):
    guid = uuid.uuid4().hex
    LOG.info("FDD_sql_alchemy guid is %s" % guid)
    engine = self._create_engine()
    connection = engine.connect()
    result = connection.execution_options(stream_results=True).execute(snippet['statement'])
    cache = {
      'connection': connection,
      'result': result,
      'meta': [{
          'name': col[0] if (type(col) is tuple or type(col) is dict) else col.name if hasattr(col, 'name') else col,
          'type': 'STRING_TYPE',
          'comment': ''
        } for col in result.cursor.description]
    }
    CONNECTION_CACHE[guid] = cache
```

change guid = self.user.username Is it better？

**Comment by romainr** [comment]
For sure if the close query fails, the cache stays there forever.

Those should fix that but it is not ready yet:
-  Task Server workers HUE-8738
-  Result caching and storage HUE-8787

@jdesjean maybe there is a way to pickle the ids into Django cache that automatically support expirations or make the cache a FIFO? Or just keep the previous query like suggested above?

**Comment by romainr** [comment]
Not perfect but with https://issues.cloudera.org/browse/HUE-9270

Closing the session of the user will close all the queries.
It makes sure the previously executed query gets closed before executing next.

Also it seems that Presto comes with a timeout to automarically expires idle/non closed queries: https://www.google.com/search?q=presto+expire+idle+queries&oq=presto+expire+idle+queries&aqs=chrome..69i57.5536j1j1&sourceid=chrome&ie=UTF-8
