### ISSUE TITLE
how to disable ssl renegotiate

### ISSUE THREAD

**Issue by ZHUVV** [cloudera/hue#1021]
hi all:
I am trying to fix Client-Initiated renegotiation of TLS/SSL.
It is suggested to disable tls nenegotiation.
But how to disable it??

**Comment by jdesjean** [comment]
We currently don't have a setting for this and it's only available in python 3.7 https://docs.python.org/3/library/ssl.html#ssl.OP_NO_RENEGOTIATION which we don't currently officially support.

**Comment by jdesjean** [comment]
I added new jira and patch for this: https://issues.cloudera.org/browse/HUE-9106

**Comment by jdesjean** [comment]
I pushed commit for HUE-9106, closing this for now.
