### ISSUE TITLE
[hue4.6]editor has permissions

### ISSUE THREAD

**Issue by oslet** [cloudera/hue#1022]
What is the Hue version or source ?
=> hue4.6

os ?
=> Centos 7.6 x86-64

desc ?
 => I cancelled default group All permissions, but user have edit permission after login
how to do no permissions, no login ,  like hue 3.12 ver ?

**Comment by romainr** [comment]
It did not change in Hue 4, your user is probably a Hue admin, you can uncheck the box on its profile

**Comment by oslet** [comment]
Maybe what I described is not clear,　the view module is  editor, Please look picture,
![3](https://user-images.githubusercontent.com/1573303/71302812-c6a14a80-23ea-11ea-8338-332ce7bbf1b0.png)
![2](https://user-images.githubusercontent.com/1573303/71302813-cc972b80-23ea-11ea-952d-496b33c12f5a.png)
![1](https://user-images.githubusercontent.com/1573303/71302814-cf921c00-23ea-11ea-8e01-ee068123c498.png)

**Comment by romainr** [comment]
Looks like it is with a custom interpreter that is not Hive/Impala, so it is probably not supported currently. You probably need to tweak https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/conf.py#L41 until https://issues.cloudera.org/browse/HUE-8758 gets in.

**Comment by oslet** [comment]
Thank you, I get it
