### ISSUE TITLE
modal-backdrop in front of modal form

### ISSUE THREAD

**Issue by alericmckearn** [cloudera/hue#1025]
modal-backdrop in front of modal form
![Screen Shot 2019-12-26 at 8 27 42 AM](https://user-images.githubusercontent.com/6674285/71482874-b0640780-27b9-11ea-8a98-67930c5a4c83.png)

modal-backdrop z-index - 1040
![Screen Shot 2019-12-26 at 8 10 16 AM](https://user-images.githubusercontent.com/6674285/71482954-37b17b00-27ba-11ea-8471-c87720902c60.png)

input box z-index - 1050
![Screen Shot 2019-12-26 at 8 31 09 AM](https://user-images.githubusercontent.com/6674285/71482980-4dbf3b80-27ba-11ea-8daa-5228ec5c8d31.png)

if i move the z-index of the modal-backdrop to 1009 then everything works, but it defeats the purpose of the backdrop since everything is interactive
![Screen Shot 2019-12-26 at 8 34 05 AM](https://user-images.githubusercontent.com/6674285/71483020-91b24080-27ba-11ea-9afa-c00663807a49.png)

So what is 1010 you ask?  it is the banner which has a position:relative.  by removing its z-index everything works normally.

![Screen Shot 2019-12-26 at 8 51 35 AM](https://user-images.githubusercontent.com/6674285/71483525-20c05800-27bd-11ea-9632-223589dd03a9.png)

I have no idea how you want to deal with this, but these are the repo steps.

**Comment by romainr** [comment]
Thanks for the report! +1 to remove the z-index if it fixes it. Would you send a pull request?
