### ISSUE TITLE
hue 4.6.0 start error

### ISSUE THREAD

**Issue by fsilent** [cloudera/hue#1031]
![image](https://user-images.githubusercontent.com/9815890/71873586-849e3580-315a-11ea-9dcb-0247d13a4330.png)
![image](https://user-images.githubusercontent.com/9815890/71873615-98499c00-315a-11ea-9ea0-1081e70b632b.png)
![image](https://user-images.githubusercontent.com/9815890/71873629-a26b9a80-315a-11ea-81d0-c91cc81e8cfa.png)
When change the 326 line TimeOutPIDLockFile to TimeoutPIDLockFile, it`s works.
file: hue/desktop/core/src/desktop/supervisor.py

**Comment by romainr** [comment]
Thanks!

Would you send a quick pull request with the fix?

**Comment by fsilent** [comment]
https://issues.cloudera.org/browse/HUE-9111
hello, romainr. this is the first I submit a patch，please check.

**Comment by romainr** [comment]
Thank you! Your patch was committed with a small clean-up on top: https://review.cloudera.org/r/14693/

For small issues, feel free to just send a pull request next time if it is easier!

**Comment by romainr** [comment]
Note that cherrypy is not fully ported to Python 3 yet, but any help is welcomed.
