### ISSUE TITLE
Thrift version configured by property thrift_version might be too high

### ISSUE THREAD

**Issue by stone80** [cloudera/hue#1036]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
no
What is the Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...)
4.6
Is there a way to help reproduce it?

error logs:
Thrift version configured by property thrift_version might be too high. Request failed with "Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, username:hue, configuration:{hive.server2.proxy.user=liuxiaopeng})" (code OPEN_SESSION): None
env:
hive:1.2.1
hadoop:2.7.2

thanks

**Comment by romainr** [comment]
With Hive 1 (pretty old, now Hive 3 is standard), you probably need o by  thrift_version=7 for https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L1266

**Comment by stone80** [comment]
> With Hive 1 (pretty old, now Hive 3 is standard), you probably need o by thrift_version=7 for https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L1266

got it, thanks very much!
