### ISSUE TITLE
Solr Collections dropdown enabled when access to dashboard is enabled

### ISSUE THREAD

**Issue by mansukhp96** [cloudera/hue#1047]
I'm using hue as a UI for my SolrCloud. I'm trying to disable the dropdown to select solr collections when the access for a user group that only has dashboard access enabled and oozie editor access disabled(can see only shared documents- all other access is disabled). If the user uses the dropdown, they have access to the dashboard. There seems to be no way to disable the dropdown for a user group who can just view a document and nothing else

![disable this](https://user-images.githubusercontent.com/33620662/74868370-21d8b600-5324-11ea-9d23-f30992a20549.PNG)

![permissons](https://user-images.githubusercontent.com/33620662/74868371-22714c80-5324-11ea-890d-effdc9a511b6.PNG)

**Comment by mansukhp96** [comment]
Requirement is to just view the documents shared, and the dropdown should be disabled.

**Comment by mansukhp96** [comment]
Tried using the oozie - dashboard read-only : Doesn't work for this case

**Comment by romainr** [comment]
Indeed, here if the read only access is there, we should probably only return the selected collection, not the full list.

Some pointers:

https://github.com/cloudera/hue/blob/master/desktop/libs/dashboard/src/dashboard/views.py#L89
collections should be a list with only the selected one.
