### ISSUE TITLE
Username and Password SQLAlchemy Interpolation

### ISSUE THREAD

**Issue by jamiedavenport** [cloudera/hue#1048]
## Problem

We are trying to use SparkSQL with the SQLAlchemy connector like so:
```
[[[hive]]]
    name=Databricks
    interface=sqlalchemy
    options='{"url":"databricks+pyhive://token:${PASSWORD}@<host>:<port>/default","connect_args":{"cluster":"<cluster_name>"}}'
```

This is based on the documentation [here](https://docs.gethue.com/administrator/configuration/apps/#sql-alchemy)

The first issue we encountered is that the user is not prompted for login credentials:
- Should be prompted when a request returns a `401` response
- Occurs when a `AuthenticationRequired` exception is raised
- Which happens only on line `89` in `sql_alchemy.py` in response to a MySQL specific error code

```py
if '1045' in message: # 'Access denied' # MySQL
  raise AuthenticationRequired(message=message)
```

When executing a query the options `session` key is not set resulting in a `KeyError` being raised on line `117`:

```py
for _prop in self.options['session']['properties']:
```

## Workaround

We raise an `AuthenticationRequired` exception when both the username and password are missing from the session as part of the `_create_engine` method. We also handle the `KeyError` by wrapping the entire block with a check.

```py
authenticated=False
if 'session' in self.options:
  for _prop in self.options['session']['properties']:
    if _prop['name'] == 'user':
      vars['USER'] = _prop['value']
      authenticated = True
    if _prop['name'] == 'password':
      vars['PASSWORD'] = _prop['value']
      authenticated = True

if not authenticated:
  raise AuthenticationRequired(message="Missing username and/or password")
```

As part of the `query_error_handler` decorator we allow `AuthenticationRequired` exceptions to pass through unchanged (otherwise the generic catch-all case would prevent it from reaching the api layer).

When executing a query from within `execute` we first set the session from the notebook:

```py
self.options['session'] = notebook['sessions'][0]
engine = self._create_engine()
```

**Comment by romainr** [comment]
Nice and thanks for the details. Would you be able to send a pull request?

**Comment by jamiedavenport** [comment]
Yep I'll send that over

**Comment by yinsong** [comment]
website error Missing username and/or password when i set clickhouse://${USER}:${PASSWORD}

**Comment by xiashei** [comment]
Is the way you can set username and password in hive  in here?
![image](https://user-images.githubusercontent.com/28834220/84019511-f1d91f80-a9b3-11ea-9baf-3ddb31cd97f3.png)
but how can I do the same thing in presetoSql? it's not work.
![image](https://user-images.githubusercontent.com/28834220/84019531-f69dd380-a9b3-11ea-8f04-01b790e87842.png)

**Comment by jramineni** [comment]
I am using sqlalchemy to connect to our database, when I use ${USER}:${PASSWORD}, only a message is displayed and there is no prompt to enter the username and password.

**Comment by romainr** [comment]
Indeed, e.g with 

`postgresql://hue:${PASSWORD}@localhost:5432/hue`

I tried with Editor 2, but are you with Editor 1? (execute button is the same as in above screenshot with a little triangle).

We could need to handle again the 401 status and trigger the modal asking for the credentials:

`handleAjaxError(data, callback)`

```    } else if (data.status === 401) {
      // Auth required
      this.status(STATUS.expired);
      $(document).trigger('showAuthModal', {
        type: this.dialect(),
        callback: this.execute,
        message: data.message
      });
```

![image](https://user-images.githubusercontent.com/17945/96327836-2314cc80-0ff2-11eb-9dde-0538312b7da0.png)

**Comment by romainr** [comment]
Created https://github.com/cloudera/hue/issues/1309 to track in its own issue. Please feel free to give it a try

**Comment by jramineni** [comment]
I tried both Notebook1 and Notebook2. IN both cases I do get the message "Missing Username and/or password". But no modal shows asking for credentials. We would need the modal to display to allow user to enter their own database credentials.
