### ISSUE TITLE
Feature request: messages for users from admin

### ISSUE THREAD

**Issue by nutle** [cloudera/hue#1054]
Assume several users are running Hive queries (or any other service), and for some reason a service restart is needed, which will take some time and cause downtime. It would be a usefulfeature to send a pop-up (or similar) to all users, which are currently in, say, Hive Query window, that "the service is down due to restart and that the admin knows that". This will save some time and confusion from the users, who in such cases would be copying the error and sending it to admins. 

Instead of pop-ups, a customized/override of the error messages in such cases would be a good alternative. I.e., instead of "Could not connect to ..." -> "Server restart is in progress, will be running in 5-10mins".

**Comment by romainr** [comment]
This is a good one, just obviously this can be done only when there is a load balancer in front of Hue, and configuring it currently up to the admin. With Kubernetes it will become simpler to do rolling restarts.
