### ISSUE TITLE
Presto jdbc interface error "QueryError: JavaObject object is not an iterator"

### ISSUE THREAD

**Issue by alanlyh** [cloudera/hue#1060]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? 
* No

What is the Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...) 
* open source 4.6

Is there a way to help reproduce it? 
* Use jdbc interface in Hue 4.6.0 with conf like following
```
[[[presto]]]
      interface = jdbc
      name = Presto
      options = '{"url": "jdbc:presto://...:8889/hive/default", "driver": "com.facebook.presto.jdbc.PrestoDriver", "user":"root","password":""}'

```

When opening the editor, the page shows "JavaObject object is not an iterator" on the left upper corner. Error log:
```
[05/Mar/2020 14:49:14 -0800] decorators   ERROR    Error running autocomplete
Traceback (most recent call last):
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 111, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 694, in autocomplete
    autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 41, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 153, in autocomplete
    response['databases'] = assist.get_databases()
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 204, in get_databases
    dbs, description = query_and_fetch(self.db, 'SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA')
  File "/usr/lib/hue/desktop/libs/librdbms/src/librdbms/jdbc.py", line 45, in query_and_fetch
    data = curs.fetchmany(n)
  File "/usr/lib/hue/desktop/libs/librdbms/src/librdbms/jdbc.py", line 135, in fetchmany
    while next(self.rs) and (n is None or n > 0):
QueryError: JavaObject object is not an iterator
```

Seems like this [commit for HUE-8737](https://github.com/cloudera/hue/commit/93015548435d27a580e648eadc575abb41d62fd7) changes python2 `.next()` to python3 `next()` is the cause.

I do find sqlalchemy is the recommended interface by Hue and it works when I switched, but just would like to know if this is a common issue for jdbc interface or I miss something in my configurations or patchs.

**Comment by romainr** [comment]
It indeed looks like a small bug and we should make it back to compatible with both Python. Feel free to send a pull request!

**Comment by romainr** [comment]
@alanlyh would you have time to send a PR?

**Comment by SimonkNetapp** [comment]
I have this on all JDBC Connectors ... Can we fix this please?

**Comment by alanlyh** [comment]
> @alanlyh would you have time to send a PR?

Sure. I can work on a PR. Should be a quick fix.

**Comment by alanlyh** [comment]
@romainr I have created a PR https://github.com/cloudera/hue/pull/1109

**Comment by romainr** [comment]
It is merged, thanks a lot! https://github.com/cloudera/hue/commit/baeccd42c856b874b917c551647b7b101d518499
