### ISSUE TITLE
Installation HUE 4.6.0 : conflict npm / libmysqlclient-dev

### ISSUE THREAD

**Issue by stephbat** [cloudera/hue#1064]
I'm trying to install HUE release 4.6.0 on a Ubuntu server 18.04.1
According to the dependencies list described in the installation guide, I see that the package npm is required (while it wasn't required in the previous release 4.3.0)

I have installed the package npm, and after I see that the package libmysqlclient-dev has been automatically removed and this package is listed as mandatory in the dependencies.

It seems that there is a conflict between npm and libmysqlclient-dev.

Coud you advise me on this please ?

**Comment by romainr** [comment]
Could you list the error trace?

**Comment by stephbat** [comment]
In attachment the traces of this conflict when I try to install npm and libmysqlclient-dev  :

[conflict_npm_libmysqlclient-dev.log](https://github.com/cloudera/hue/files/4318877/conflict_npm_libmysqlclient-dev.log)

**Comment by stephbat** [comment]
Fixed by installing Node.js v10, instead of Node.js v8
