### ISSUE TITLE
The table name cannot be displayed correctly in case of Hue+Hive+Sparksql scenario

### ISSUE THREAD

**Issue by AlexDing1991** [cloudera/hue#1069]
The table name cannot be displayed correctly in case of Hue+Hive+Sparksql scenario. The detail symptom is illustrated by the following screeshot.
![image](https://user-images.githubusercontent.com/62233846/76731007-762d5500-676d-11ea-871d-e3d4de2da700.png)

**Comment by romainr** [comment]
It seems like you are on a very old Hue 3.x, it is highly recommended to switch to a more recent one first. e.g. https://gethue.com/hue-4-6-and-its-improvements-are-out/
