### ISSUE TITLE
Configuration paramaters added/deleted HUE 4.6.0 vs 4.3.0

### ISSUE THREAD

**Issue by stephbat** [cloudera/hue#1077]
Hello

I have installed the release HUE 4.6.0, and I would like to identify the configuration paramaters that have been added or deleted since the the release HUE 4.3.0 (previous release installed on my server)
Is there a documentation describing this ?

Regards

**Comment by romainr** [comment]
You would have more chance on https://discourse.gethue.com/ for this type of general questions:

The config file of 4.3 in case it helps (and github probably has a way to do the diff for you):
https://github.com/cloudera/hue/blob/release-4.3.0/desktop/conf.dist/hue.ini

**Comment by romainr** [comment]
https://discourse.gethue.com/t/configuration-paramaters-added-deleted-hue-4-6-0-vs-4-3-0/131
