### ISSUE TITLE
Impala image can't be downloaded

### ISSUE THREAD

**Issue by litaobowl** [cloudera/hue#1078]
Hi, 
I used `helm install impala-engine --set-string name=finance -n finance`
to deploy an impala cluster in k8s. But the impala images can't be downloaded from the registry

`Failed to pull image "docker-registry.infra.cloudera.com/cloudera/datawarehouse/impala-statestore:v2": rpc error: code = Unknown desc = Error response from daemon: Get https://docker-registry.infra.cloudera.com/v2/: dial tcp: lookup docker-registry.infra.cloudera.com on 172.20.0.2:53: no such host`

**Comment by romainr** [comment]
I would recommend to inquire on the Impala project for their docker image: https://impala.apache.org/
