### ISSUE TITLE
Hue Notebook enhancements

### ISSUE THREAD

**Issue by varunrao** [cloudera/hue#1081]
Hue Notebooks should allow following integrations.
- Export/download
- Specify location to save (eg: S3)
- Integration with Code repos - eg: Git

**Comment by romainr** [comment]
First two are already there: 
https://docs.gethue.com/user/querying/#results
https://docs.gethue.com/user/querying/#downloading

Git is tracked on https://github.com/cloudera/hue/blob/master/docs/ROADMAP.md

**Comment by varunrao** [comment]
thanks for the response Romain. Can Hue Notebooks be in the .ipynb format? This way notebooks can work with other editors like Zepplin and Jupyter. We can use interpreters to switch between SQL and code. 
Eg: https://zeppelin.apache.org/docs/0.8.0/quickstart/sql_with_zeppelin.html

Regarding export options, here's some options supported by jupyterlab:
https://jupyterlab.readthedocs.io/en/stable/user/export.html

Where are these notebooks saved currently and which format? Can we change the storage location of these notebooks?

**Comment by romainr** [comment]
IIRC export back and forth to .ipynb was done a few years ago but I am not sure that the feature is still there. It should be relatively to add though as text export is working ;)

https://docs.gethue.com/developer/
