### ISSUE TITLE
hue4.6.0 on docker connect clickhouse error

### ISSUE THREAD

**Issue by yinsong** [cloudera/hue#1083]
hue 4.6.0 on docker
connect  clickhouse19.16.2.2 use jdbc

config:
[[[clickhouse]]]
       name=ClickHouse
       interface=jdbc
       options='{"url": "jdbc:clickhouse://xxxx.xxxx.xxx.xx:8123", "driver": "ru.yandex.clickhouse.ClickHouseDriver", "user": "default", "password": ""}'

other steps
add  clickhouse-jdbc.jar  in CLASSPATH 
edit startup.sh add export CLASSPATH=/usr/lib/jvm/java-11-openjdk-amd64/lib/clickhouse-jdbc.jar:/home/hue/clickhouse.jar:/home/hue/clickhouse-jdbc.jar:/home/hue/clickhouse-jdbc-0.2.jar:/home/hue/clickhouse-jdbc-0.2-jar-with-dependencies.jar

and ru.yandex.clickhouse.ClickHouseDriver in clickhouse.jar

but 

error log on hue web
An error occurred while calling z:java.lang.Class.forName. : java.lang.ClassNotFoundException: ru.yandex.clickhouse.ClickHouseDriver at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:315) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231) at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381) at py4j.Gateway.invoke(Gateway.java:259) at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133) at py4j.commands.CallCommand.execute(CallCommand.java:79) at py4j.GatewayConnection.run(GatewayConnection.java:209) at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by romainr** [comment]
If you need the JDBC proxy, the flag need to be set in the build: https://docs.gethue.com/developer/connectors/#custom

Any reason you would not use the SqlAlchemy connector instead? https://docs.gethue.com/administrator/configuration/connectors/#clickhouse

**Comment by yinsong** [comment]
> If you need the JDBC proxy, the flag need to be set in the build: https://docs.gethue.com/developer/connectors/#custom
> 
> Any reason you would not use the SqlAlchemy connector instead? https://docs.gethue.com/administrator/configuration/connectors/#clickhouse

SqlAlchemy connector occur other error  chinese  in editor page,but clickhouse client is ok

error log:
Code: 73, e.displayText() = DB::Exception: Unknown format TabSeparatedWithNamesAn (version 19.16.2.2 (official build))

**Comment by HuangtianyuCN** [comment]
> > If you need the JDBC proxy, the flag need to be set in the build: https://docs.gethue.com/developer/connectors/#custom
> > Any reason you would not use the SqlAlchemy connector instead? https://docs.gethue.com/administrator/configuration/connectors/#clickhouse
> 
> SqlAlchemy connector occur other error chinese in editor page,but clickhouse client is ok
> 
> error log:
> Code: 73, e.displayText() = DB::Exception: Unknown format TabSeparatedWithNamesAn (version 19.16.2.2 (official build))

请问sqlalchemy-clickhouse这个包能正常用么，我pip安装之后再启动就是包里的各种不兼容py2的问题

**Comment by romainr** [comment]
Good to close?
