### ISSUE TITLE
cdh6.3 hue 4.2.0  Truncate function doesn't work

### ISSUE THREAD

**Issue by ytousxljsj** [cloudera/hue#1084]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:

Steps to reproduce it?

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

**Comment by romainr** [comment]
Please detail more what is the problem and how to reproduce it?

**Comment by ytousxljsj** [comment]
Execute  truncate table table_name ;   in the hue interface

**Comment by ytousxljsj** [comment]
> 请详细说明问题是什么以及如何重现它？

Execute  truncate table  table_name  appearin ; in the hue interface      error: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Exception while processing   .    CDH6.3  HUE 4.2

**Comment by romainr** [comment]
Please look at the full logs of the HiveServer2 or YARN, this error is specific to your table. Maybe you are missing some permissions or there is a misconfiguration.
