### ISSUE TITLE
{"status": -1, "message": "(MySQLdb._exceptions.OperationalError) (1193, \"Unknown system variable 'tx_isolation'\")"}

### ISSUE THREAD

**Issue by chenjingyue** [cloudera/hue#1091]
hue version:4.6.0 mysql version: 8.0.19 
  [[interpreters]]
    # Define the name and how to connect and execute the language.
    # https://docs.gethue.com/administrator/configuration/editor/

 
	[[[mysql]]]
	   name=MySQL
	   interface=sqlalchemy
	   options='{"url": "mysql://user:password@localhost:3306/hue"}'
![image](https://user-images.githubusercontent.com/43103794/78548709-c8750980-7833-11ea-93ca-770dcc0032fb.png)

**Comment by romainr** [comment]
Please use the Forum for usage/configuration questions: https://discourse.gethue.com/
