### ISSUE TITLE
Markdown snippets in notebook does not work 

### ISSUE THREAD

**Issue by louisdecharson** [cloudera/hue#1116]
Hello,

I've downloaded and installed on MacOs Mojave the latest development server for Hue (release-4.7.0) using the steps described [here](http://cloudera.github.io/hue/latest/administrator/installation/dependencies/#macos).

When I try to create a snippet in a notebook, I have the following:
<img width="1280" alt="Screenshot 2020-04-29 at 18 35 55" src="https://user-images.githubusercontent.com/3234544/80622434-118e3700-8a49-11ea-894e-4692ee6170a0.png">

I've checked in `desktop/conf/pseudo-distributed.ini` and markdown was commented. Uncommenting it does not solve the bug (I have also tried `desktop/conf.dist/hue.ini`). The ini file also indicates a [webpage](https://docs.gethue.com/administrator/configuration/editor/) for configuration which returns 404 (I guess it should point to [https://docs.gethue.com/administrator/configuration/apps/](https://docs.gethue.com/administrator/configuration/apps/) instead)

Would be grateful of anyhelp !

Thank you very much !

**Comment by romainr** [comment]
It looks like the Markdown snippet has a bug. There is probably a trace in the Javacript console.

**Comment by louisdecharson** [comment]
I have  the following error:
```
{"message": "HTTPConnectionPool(host='localhost', port=7187): Max retries exceeded with url: /api/v9/interactive/entities?limit=450&offset=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dac79d0>: Failed to establish a new connection: [Errno 61] Connection refused',))"}
```
I was not able to find where the html template for the notebook and snippets are defined.

**Comment by romainr** [comment]
Awesome!

For info, port 7187 is the Cloudera Manager service API, but it should be off if commented https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L2059
