### ISSUE TITLE
Multiple variables on SQL editor

### ISSUE THREAD

**Issue by gnieto** [cloudera/hue#1118]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

I could not find any related issue

Describe the bug:

When using the SQL editor (I've tried Impala and Spark editors) with a statement containing exactly one variable, the editor seems to be working properly (even if it shows a selector which was not present on previous version. See attached image). 

![Captura de pantalla 2020-04-30 a les 11 02 53](https://user-images.githubusercontent.com/4637936/80693737-c0775500-8ad3-11ea-888b-7323e4ba2c48.png)

If another variable is added to the SQL, it does not get added to the bottom. 

![Captura de pantalla 2020-04-30 a les 11 03 22](https://user-images.githubusercontent.com/4637936/80693756-ca995380-8ad3-11ea-8c30-e16159591435.png)

I've tried the same with Hue 4.6.0 (official docker image) and it works as expected:

![Captura de pantalla 2020-04-30 a les 10 58 54](https://user-images.githubusercontent.com/4637936/80693828-e3096e00-8ad3-11ea-8297-4c20deb3b9c2.png)

Steps to reproduce it?

Start Hue on Docker, configure Spark or Impala and use 2 variables on one SQL statement.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

Does not work with gethue/hue:4.7.0,  gethue/hue:20200429-135001.
It works on:  gethue/hue:4.6.0

--- 

On the non working versions I can see a JS error:

Hue detected a Javascript error:  `https://host/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-ca7d39476e0a070525b3.bcc2121180bf.js` 11813 391 Error: Cannot find closing comment tag to match:  ko if: meta.type() == 'select' 
Error: Cannot find closing comment tag to match:  ko if: meta.type() == 'select' 

When the second variable gets added, I can see another error:

Hue detected a Javascript error:  `https:/host/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-ca7d39476e0a070525b3.bcc2121180bf.js` 11822 130 Error: You cannot apply bindings multiple times to the same element.
Error: You cannot apply bindings multiple times to the same element.

I got the feeling that the first error is the one who causes that appears the selector near to the first variable input and provokes the second error when another variable is added.

I've checked the source code near  `ko if: meta.type() == 'select'` and it seems that closing comment tag is there, but it does not seems to be there when I inspect the HTML elements.

Let me know if you need more information.

**Comment by romainr** [comment]
Weird, this might be related to a ko.js lib upgrade that happened since.

Wondering if we should do

`</select> and not <select ... />`

https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/templates/editor_components.mako#L1220

?

**Comment by JohanAhlen** [comment]
Indeed the </select>, I've fixed it with: https://issues.cloudera.org/browse/HUE-9288

**Comment by romainr** [comment]
https://github.com/cloudera/hue/commit/611ad1b12bd5db7a3979c0c41105d3b93903b289
