### ISSUE TITLE
Not able to upload file via hdfs web browser.

### ISSUE THREAD

**Issue by CHIRAG-TYAGI** [cloudera/hue#1121]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? I did not find any open issue relevant to mine.

Describe the bug: Not able to upload the file view hdfs file browser

Steps to reproduce it? 
1) Go to hdfs file browser. 
2) try to upload any file into any directory.

Error I am getting:
Error: HTTPConnectionPool(host='ip-10-0-142-155.us-west-2.compute.internal', port=9864): Max retries exceeded with url: /webhdfs/v1/user/demo/chirag/original%20(3).txt.tmp?op=CREATE&doas=demo&user.name=hue&namenoderpcaddress=ip-10-0-131-201.us-west-2.compute.internal:8020&createflag=&createparent=true&overwrite=false&permission=644 (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known',))

Hue version or source? 
I am using demo.gethue.com to try test the hue web browser.

**Comment by CHIRAG-TYAGI** [comment]
![image](https://user-images.githubusercontent.com/26747200/80858105-bb9dd700-8c74-11ea-931e-6ac5b8d748c0.png)

**Comment by romainr** [comment]
Uploads are currently disabled on demo.gethue.com
