### ISSUE TITLE
S3 Browser should accept s3a:// URI with credentials included.

### ISSUE THREAD

**Issue by rimolive** [cloudera/hue#1132]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? No

Describe the bug:

S3 Browser should list data using a URI like this: 

`s3a://<access-key>:<secret-key>@<bucket-name>`

Which will list the objects from a bucket using different S3 credentials than the ones configured in Hue.

This URI can be used in HiveQL CREATE TABLE statements, so S3 Browser could do the same.

Steps to reproduce it?

1. Go to S3 Browser
2. Access any bucket with s3 creds different than the ones configured in Hue
3. Depending on the bucket visibility you will get an error that the user is not allowed to access the bucket.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
open source 4.5

**Comment by romainr** [comment]
Good point, I know it works with public buckets but not with this format indeed.

**Comment by rimolive** [comment]
@romainr Can we reopen this issue?

**Comment by romainr** [comment]
Yes, would you have some bandwidth to work on it? Happy to guide/help on design/PR reviews to get a solution/compromise
