### ISSUE TITLE
Regular Expression DoS vulnerabilities in desktop/core/ext-py/

### ISSUE THREAD

**Issue by IncyLiu** [cloudera/hue#1136]
Describe the bug:
We are working on the [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) problem and detected several vulnerable regexes from your code.

Vulnerable regex 1:
`(?:.*,)*\s*Negotiate\s*([^,]*),?` in [link](https://github.com/cloudera/hue/tree/master/desktop/core/ext-py/urllib2_kerberos-0.1.6/urllib2_kerberos.py) and [link](https://github.com/cloudera/hue/tree/master/desktop/core/ext-py/requests-kerberos-0.12.0/requests_kerberos/kerberos_.py)
It takes forever for the regex to match the string
`",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\b"`
We suggest you change the structure `(?:.*,)*`, since "." can accept ",".

Vulnerable regex 2:
`(?:([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*list\(((?:\s*(?:(?:".*?")|(?:'.*?')|(?:[^'",\s\)][^,\)]*?))\s*,\s*)*(?:(?:".*?")|(?:'.*?')|(?:[^'",\s\)][^,\)]*?))?)\))`
in [link](https://github.com/cloudera/hue/tree/master/desktop/core/ext-py/configobj-5.0.6/validate.py)
This vulnerability can be triggered by 
`"A=list(\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\"\"\t,\",\b"`
This is because `"\"\"\t,\","` has more than one way to match `(?:\s*(?:(?:".*?")|(?:'.*?')|(?:[^'",\s\)][^,\)]*?))\s*,\s*)*`.

Vulnerable regex 3:
`.*?<H2>(<a.*a>)*[\d\.\s]*(.*?)</H2>`
in [link](https://github.com/cloudera/hue/tree/master/desktop/core/ext-py/ply-3.9/doc/makedoc.py)
This vulnerability can be triggered by 
`"<H2><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa><aa>"`
This is because `(<a.*a>)*` has more than one way to match `<aa><aa>`, you'd better change the dot to [^<>].

Vulnerable regex 4, 5, 6, and 7:
`.*?<H5>(<a.*a>)*[\d\.\s]*(.*?)</H5>`
`.*?<H4>(<a.*a>)*[\d\.\s]*(.*?)</H4>`
`.*?<H1>(<a.*a>)*[\d\.\s]*(.*?)</H1>`
`.*?<H3>(<a.*a>)*[\d\.\s]*(.*?)</H3>`
all in [link](https://github.com/cloudera/hue/tree/master/desktop/core/ext-py/ply-3.9/doc/makedoc.py)
These vulnerabilities are similar to the vulnerable regex 3.

We didn’t create a pull request because we're not sure if these cases are possible to take place in your program, we also do not understand the functionality of these regexes as you do. Thank you for your understanding.

**Comment by romainr** [comment]
Thanks, those are in old libs not used or not managed by the project.
