### ISSUE TITLE
HUE4.4 Ozzie workflow page can't see the data when there are many nodes

### ISSUE THREAD

**Issue by daisy0123** [cloudera/hue#1137]
Hi，The workflow page can't see the data when there are many nodes. When scrolling to the right, the figure is not drawn. I hope you can help me solve this problem. Thank you

![image](https://user-images.githubusercontent.com/11910330/83387210-ef5c5000-a41e-11ea-9d0a-8d125744cd41.png)

**Comment by romainr** [comment]
This is expected in some older versions of Hue, up until a certain amount of nodes. Which version and how many nodes have you?

**Comment by daisy0123** [comment]
> This is expected in some older versions of Hue, up until a certain amount of nodes. Which version and how many nodes have you?

version：4.4.0； nodes：25；Which version solves this problem ?
![image](https://user-images.githubusercontent.com/11910330/83477167-3a30a300-a4c5-11ea-9190-18c1d87ed115.png)
The content width is 250%, the width is large, and the content of data can't see when i scroll the  page.  please help me ! thanks
