### ISSUE TITLE
jenkins.sh try to use pylint in the build directory, but it doesn't exist.

### ISSUE THREAD

**Issue by sungpeo** [cloudera/hue#1142]
Describe the bug:
`jenkins.sh` try to use `pylint` in the build directory.
but any process in `jenkin.sh`  try to install the `pylint`.

```
[02/Jun/2020 21:29:13 -0700] runpylint    ERROR    Cannot find pylint at '/home/sungpeo/hue/build/env/bin/pylint'. Please install pylint first.
```

references release-4.7.0
https://github.com/cloudera/hue/blob/672437f3ea764089a4710aeb6012b27e6d884d9b/desktop/core/src/desktop/management/commands/runpylint.py#L61-L63

Steps to reproduce it?
``` sh
./tools/jenkins/jenkins.sh slow
```

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

open source 4.7.0
CentOS Linux release 7.7.1908
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)

**Comment by romainr** [comment]
Live tests via jenkins.sh was not updated in a while. Currently the recommended way is to run only the unit tests https://docs.gethue.com/developer/development/#running-the-api-tests.

However, about the error, 

`./build/env/bin/pip install pylint`

Should fix it.

**Comment by sungpeo** [comment]
@romainr I create a pull request about this issue. #1143 
Could you check it ?
