### ISSUE TITLE
how to save username and password in prestoSQL

### ISSUE THREAD

**Issue by xiashei** [cloudera/hue#1160]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
no
Describe the bug:
I can set username and passwd in hive，by use the Query setting
![微信图片_20200608181140](https://user-images.githubusercontent.com/28834220/84019511-f1d91f80-a9b3-11ea-9baf-3ddb31cd97f3.png)

but not in prestoSQL

![微信图片_20200608181205](https://user-images.githubusercontent.com/28834220/84019531-f69dd380-a9b3-11ea-8f04-01b790e87842.png)

the interface of presto is sqlalchemy.
why?
Steps to reproduce it?

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
4.5

**Comment by romainr** [comment]
Have you tried to put the ${USER} and ${PASSWORD} in the url?

e.g.
https://docs.gethue.com/administrator/configuration/connectors/#databases

**Comment by xiashei** [comment]
> Have you tried to put the ${USER} and ${PASSWORD} in the url?
> 
> e.g.
> https://docs.gethue.com/administrator/configuration/connectors/#databases

yes,here is the setting of presto:
"url": "presto://${USER}:${PASSWORD}@xxxx:por/hive/xxxx'.

and it's also why I want to save the password.
I used to use 'presto://xxxx:por/hive/xxxx',and it works,after I add ldap to presto,I need the username and password.  and the log is "'Missing username and/or password'"

**Comment by romainr** [comment]
Some Properties come from https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/js/apps/notebook/snippet.js#L96 but that might not be the good spot.

IIRC the username/password should be prompted. Persistence wise they are not saved in the browser yet.

**Comment by xiashei** [comment]
> Some Properties come from https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/js/apps/notebook/snippet.js#L96 but that might not be the good spot.
> 
> IIRC the username/password should be prompted. Persistence wise they are not saved in the browser yet.

Got it ,thank you
