### ISSUE TITLE
docker run has error: standard_init_linux.go:220: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by tulingfeng** [cloudera/hue#1182]
Hello,I use docker to run hue:
```text
docker pull gethue/hue:latest
docker run -it -p 8888:8888 gethue/hue:latest
```
But has error:
```text
standard_init_linux.go:220: exec user process caused "exec format error"
libcontainer: container start initialization failed: standard_init_linux.go:220: exec user process caused "exec format error"
```
My runtime platform is arm64, is this images built for x86_x64 platform only?

**Comment by romainr** [comment]
Weird, this is the image used by https://gethue.com. Here is the docker file https://github.com/cloudera/hue/blob/master/tools/docker/hue/Dockerfile

**Comment by tulingfeng** [comment]
> Weird, this is the image used by https://gethue.com. Here is the docker file https://github.com/cloudera/hue/blob/master/tools/docker/hue/Dockerfile

I try to build the image based on the Dockerfile, but the same error appeared in step 4:
```text
Step 4/18 : RUN apt-get update -y && apt-get install -y   build-essential   libkrb5-dev   libmysqlclient-dev   libssl-dev   libsasl2-dev   libsasl2-modules-gssapi-mit   libsqlite3-dev   libtidy-dev   libxml2-dev   libxslt-dev   libffi-dev   libldap2-dev   libpq-dev   python-dev   python-setuptools   libgmp3-dev   libz-dev   software-properties-common   curl   git   rsync   sudo   maven   gcc   swig   xmlsec1   libxmlsec1-openssl   krb5-config   krb5-user   && rm -rf /var/lib/apt/lists/*
 ---> Running in 9f38eae41544
standard_init_linux.go:220: exec user process caused "exec format error"
libcontainer: container start initialization failed: standard_init_linux.go:220: exec user process caused "exec format error"
```
What shoud I do now?

**Comment by hui-250** [comment]
disappointed

**Comment by Mashark-star** [comment]
This is too difficult. I met the same problem.
By the way,how to use Dockerfile

**Comment by bjornalm** [comment]
@Mashark-star @hui-250 @tulingfeng Sorry for the slow progress on this. We thought that the issue was resolved but it seams that it is still a problem. We are gonna look into this. Thank you for reporting.
