### ISSUE TITLE
HIVE HA : automatic failover

### ISSUE THREAD

**Issue by stephbat** [cloudera/hue#1184]
Hi

I have installed HUE 4.6.0 and configured it to work with HIVE HA (see configuration below).
If an HiveServer2 instance failed while HUE is connected, I can see that the connection is cut.
Is there a automatic failover handled by HUE in order to reconnect to the new available HiveServer2 instances inside the cluster using Zookeeper ?

[beeswax]
  hive_server_port=10000
  hive_discovery_hs2 = true
  hive_discovery_hiveserver2_znode = /hiveserver2
 
(also posted this in https://discourse.gethue.com/t/hive-ha-automatic-failover/134)

**Comment by romainr** [comment]
https://issues.cloudera.org/browse/HUE-9358
