### ISSUE TITLE
Hue 4.0.0 User 'hue' not allowed to impersonate 'Some(example_username)'

### ISSUE THREAD

**Issue by discoteka** [cloudera/hue#1185]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug: When I'm trying to open R, Scala or PySpark editor, I receive the following error: {"msg":"User 'hue' not allowed to impersonate 'Some(example_username)'."} (error 403)
Unfortunately, for now there is no option to upgrade Hue. Any ideas how can resolve it?

Steps to reproduce it? It occurs everytime, when I click it in editor (R, Scala, PySpark)

Hue version or source? Hue 4.0.0, Redhat 7.

**Comment by romainr** [comment]
This means that at the Livy level you should autorize Hue to impersonate 'bob' or disable the impersonation in the Hue settings
