### ISSUE TITLE
Hue 4.0.0 - Spark-submit Python/Scala - Execute button disabled

### ISSUE THREAD

**Issue by discoteka** [cloudera/hue#1186]
Describe the bug: When I open Spark-submit for Python or Scala and fill path for .jar or .py I'm not able to click Execute button. It looks like disabled.

Steps to reproduce it? Everytime when I want to use that options It's disabled. 

Hue version or source? Hue 4.0.0, Redhat 7.8

**Comment by romainr** [comment]
Please upgrade to at least version 4.7 which probably have a fix https://docs.gethue.com/releases/release-notes-4.7.0/
