### ISSUE TITLE
Hue 4.7 Can't login using LDAP credentials

### ISSUE THREAD

**Issue by discoteka** [cloudera/hue#1200]
Describe the bug: I've setup LDAP integration, but it doesn't work. It's copy paste from old version of Hue to newer and it was working fine.

When I provide my credentials I'm receiving on yellow background error like this:

Request Method: | POST
-- | --
http://HOSTNAME:8888/hue/accounts/login
1.11.29
TransactionManagementError
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
/usr/local/hue/build/env/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/db/models/sql/compiler.py in execute_sql, line 899
/usr/local/hue/build/env/bin/python2.7
2.7.5

Any ideas?

Steps to reproduce it? Yes, everytime when I want to login using LDAP.

Hue version or source? Hue 4.7

**Comment by annyip** [comment]
Could you share how you fixed this error?
