### ISSUE TITLE
Comment for the column of a table  is not shown

### ISSUE THREAD

**Issue by zhang-jc** [cloudera/hue#1205]
Comment for the column of a table  is not shown in table browser.

hive table:

`create table tbl_column_comment_test(
    col1 string comment 'comment1',
    col2 int comment 'this is a number'
)
stored as orc;`

![屏幕截图_10](https://user-images.githubusercontent.com/18087653/86886395-70e38400-c129-11ea-9c86-ddb52d4a2dbb.png)

The comment is shown when click the column for more detail.

![屏幕截图_11](https://user-images.githubusercontent.com/18087653/86886734-0717aa00-c12a-11ea-8f90-748bbf26b0a2.png)

- hue version: open source 4.7.1
- OS: CentoOS 7.3
- Python2.7
- hive2.1.1

**Comment by romainr** [comment]
@sreenaths Have a look why at some point?

**Comment by sreenaths** [comment]
Thanks @romainr 

Looks like a bug.
Created https://issues.cloudera.org/browse/HUE-9408 for tracking the fix.

**Comment by zhang-jc** [comment]
> Thanks @romainr
> 
> Looks like a bug.
> Created https://issues.cloudera.org/browse/HUE-9408 for tracking the fix.

Thanks a lot !

**Comment by zhang-jc** [comment]
@sreenaths Can you tell me how to fix it temporarily? Thanks.

**Comment by romainr** [comment]
https://github.com/cloudera/hue/commit/526e74ffae3c49813b591d58b9b8158df70d2201

Thanks you both!

**Comment by zhang-jc** [comment]
@sreenaths Thanks a lot!

**Comment by zhang-jc** [comment]
@sreenaths Thanks a lot! 
I tested this feature and found another problem. When I view the table info from table browser first time, comment is not shown. When I find the table from sources area and refresh, then  comment is shown. 

Here are my test steps:
step1: comment is not shown
![屏幕截图_16](https://user-images.githubusercontent.com/18087653/94121037-6a8cba80-fe83-11ea-9159-345d1f0ae79b.png)

step2:  find the table from sources area, comment is not shown
![屏幕截图_17](https://user-images.githubusercontent.com/18087653/94121248-b17ab000-fe83-11ea-8aaf-5c1169f993aa.png)

step3: refresh, comment is shown
![屏幕截图_18](https://user-images.githubusercontent.com/18087653/94121404-dd963100-fe83-11ea-9f66-f10077dc3631.png)

step4: open metastore and view table info again, comment is show
![屏幕截图_19](https://user-images.githubusercontent.com/18087653/94121838-644b0e00-fe84-11ea-95bc-471f460f5080.png)

**Comment by zhang-jc** [comment]
@sreenaths @romainr Thanks a lot!
I tested this feature and found another problem. When I view the table info from table browser first time, comment is not shown. When I find the table from sources area and refresh, then comment is shown.

Here are my test steps:
step1: comment is not shown
![](https://user-images.githubusercontent.com/18087653/94122246-e63b3700-fe84-11ea-909a-8fd671abbb08.png)

step2: find the table from sources area, comment is not shown
![](https://user-images.githubusercontent.com/18087653/94122418-197dc600-fe85-11ea-811e-a6dd3b675b41.png)

step3: refresh, comment is shown
![](https://user-images.githubusercontent.com/18087653/94122456-239fc480-fe85-11ea-9477-3af26cb437fa.png)

step4: open metastore and view table info again, comment is show
![](https://user-images.githubusercontent.com/18087653/94122545-45994700-fe85-11ea-8f60-69041e3d2982.png)

**Comment by romainr** [comment]
@zhang-jc would recommend to open a brand new issue and also reference this one there
