### ISSUE TITLE
Deleted method SparkApi.get_properties being used in notebook/views.py causing Internal Server Error

### ISSUE THREAD

**Issue by aaggarwal-cpi** [cloudera/hue#1206]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug: Deleted method SparkApi.get_properties being used in notebook/views.py causing Internal Server Error

Steps to reproduce it?
Open Notebook app 

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
https://github.com/huebuild/hue_mirror/commit/b12709aec841899d7916e2dcd49ddb2f3248844d#diff-35dde414d784cdc2211222ea3bfea5d6L154
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/views.py#L101

hue_1     | [08/Jul/2020 11:31:28 -0700] exception    ERROR    Internal Server Error: /notebook/
hue_1     | Traceback (most recent call last):
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
hue_1     |     response = get_response(request)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
hue_1     |     response = self._get_response(request)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 187, in _get_response
hue_1     |     response = self.process_exception_by_middleware(e, request)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
hue_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/utils/decorators.py", line 185, in inner
hue_1     |     return func(*args, **kwargs)
hue_1     |   File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 86, in wrapper
hue_1     |     return f(request, *args, **kwargs)
hue_1     |   File "/usr/share/hue/desktop/libs/notebook/src/notebook/views.py", line 101, in notebook
hue_1     |     'session_properties': SparkApi.get_properties(),
hue_1     | AttributeError: type object 'SparkApi' has no attribute 'get_properties'

**Comment by romainr** [comment]
Probably caused via https://github.com/cloudera/hue/commit/b12709aec841899d7916e2dcd49ddb2f3248844d#diff-d23ff2e879048aa485411a829b76cf80 @e11it ?

**Comment by aaggarwal-cpi** [comment]
yep, new method name is to_properties. So in this case we need to replace references to get_properties with to_properties. I think there is only one - https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/views.py#L101 but I maybe wrong here.

**Comment by romainr** [comment]
Indeed, it changed from https://github.com/cloudera/hue/commit/b12709aec841899d7916e2dcd49ddb2f3248844d#diff-35dde414d784cdc2211222ea3bfea5d6L154 to https://github.com/cloudera/hue/commit/b12709aec841899d7916e2dcd49ddb2f3248844d#diff-35dde414d784cdc2211222ea3bfea5d6R187 so could use `to_properties()` instead! 

Would you be able to send a pull request?

**Comment by aaggarwal-cpi** [comment]
thanks @romainr for working on this.
