### ISSUE TITLE
Broken group mapping in saml2

### ISSUE THREAD

**Issue by aaggarwal-cpi** [cloudera/hue#1207]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
djangosaml2 is calling group model to set groups given by idp in saml response but failing with following exception -
hue_1     | [08/Jul/2020 12:16:04 -0700] exception    ERROR    Internal Server Error: /saml2/acs/
hue_1     | Traceback (most recent call last):
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/exception.py", line 41, in inner
hue_1     |     response = get_response(request)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 249, in _legacy_get_response
hue_1     |     response = self._get_response(request)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 187, in _get_response
hue_1     |     response = self.process_exception_by_middleware(e, request)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/core/handlers/base.py", line 185, in _get_response
hue_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/utils/decorators.py", line 185, in inner
hue_1     |     return func(*args, **kwargs)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/views/decorators/http.py", line 40, in inner
hue_1     |     return func(request, *args, **kwargs)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/views/decorators/csrf.py", line 58, in wrapped_view
hue_1     |     return view_func(*args, **kwargs)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/djangosaml2-0.16.11-py2.7.egg/djangosaml2/views.py", line 310, in assertion_consumer_service
hue_1     |     create_unknown_user=create_unknown_user)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/contrib/auth/__init__.py", line 70, in authenticate
hue_1     |     user = _authenticate_with_backend(backend, backend_path, request, credentials)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/Django-1.11.29-py2.7.egg/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
hue_1     |     return backend.authenticate(*args, **credentials)
hue_1     |   File "/usr/share/hue/desktop/core/src/desktop/lib/metrics/registry.py", line 389, in wrapper
hue_1     |     return fn(*args, **kwargs)
hue_1     |   File "/usr/share/hue/desktop/libs/libsaml/src/libsaml/backend.py", line 52, in authenticate
hue_1     |     return super(SAML2Backend, self).authenticate(*args, **kwargs)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/djangosaml2-0.16.11-py2.7.egg/djangosaml2/backends.py", line 107, in authenticate
hue_1     |     create_unknown_user, main_attribute, attributes, attribute_mapping)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/djangosaml2-0.16.11-py2.7.egg/djangosaml2/backends.py", line 152, in get_saml2_user
hue_1     |     return self._get_or_create_saml2_user(main_attribute, attributes, attribute_mapping)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/djangosaml2-0.16.11-py2.7.egg/djangosaml2/backends.py", line 177, in _get_or_create_saml2_user
hue_1     |     user = self.update_user(user, attributes, attribute_mapping)
hue_1     |   File "/usr/share/hue/desktop/libs/libsaml/src/libsaml/backend.py", line 87, in update_user
hue_1     |     user = super(SAML2Backend, self).update_user(user, attributes, attribute_mapping, force_save)
hue_1     |   File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/djangosaml2-0.16.11-py2.7.egg/djangosaml2/backends.py", line 231, in update_user
hue_1     |     modified = user_attr(attr_value_list)
hue_1     | TypeError: __call__() takes exactly 1 argument (2 given)

Steps to reproduce it?
1. enable saml2 backend
2. set user_attribute_mapping={'groups': 'groups', 'email': 'email', 'uid': 'username'}
3. login using idp

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
https://github.com/cloudera/hue/commit/f7c68d3f2acaa320b1cbb84b351fcbd3041fa447

**Comment by romainr** [comment]
Weird, what is the value of `attr_value_list` (print(attr_value_list) before 'hue_1 | modified = user_attr(attr_value_list)')?

**Comment by aaggarwal-cpi** [comment]
It is an array. exact value is = [u'analyst']
I think the issue is user_attr is group model which is many to many and __call__ doesn't take any params.

**Comment by romainr** [comment]
Shouldn't the format of `user_attribute_mapping` be more like a dict?
```
  # A mapping from attributes in the response from the IdP to django user attributes.
  ## user_attribute_mapping={'uid': ('username', )}

```

**Comment by aaggarwal-cpi** [comment]
@romainr as per https://docs.cloudera.com/documentation/enterprise/6/6.3/topics/hue_sec_saml_auth.html it should be
`user_attribute_mapping={'uid': 'username'}`
