### ISSUE TITLE
Hue trying connecting to old hive server ip and throwing StructuredThriftTransportException

### ISSUE THREAD

**Issue by bhaskarroy19** [cloudera/hue#1215]
Hue version: 3.9.0
Logs:
`[27/Jul/2020 14:46:46 +0530] dbms         DEBUG    Query Server: {'server_name': 'beeswax', 'transport_mode': 'socket', 'server_host': '10.48.50.247', 'server_port': 10000, 'http_url': 'http://10.48.50.247:10001/cliservice', 'principal':
None}
[27/Jul/2020 14:46:46 +0530] thrift_util  INFO     Thrift exception; retrying: Could not connect to 10.50.210.130:10000
[27/Jul/2020 14:46:46 +0530] thrift_util  INFO     Thrift exception; retrying: Could not connect to 10.50.210.130:10000
[27/Jul/2020 14:46:46 +0530] thrift_util  WARNING  Out of retries for thrift call: GetSchemas
[27/Jul/2020 14:46:46 +0530] thrift_util  INFO     Thrift saw a transport exception: Could not connect to 10.50.210.130:10000
[27/Jul/2020 14:46:46 +0530] api          ERROR    error in <function execute at 0x7f7f88fd9aa0>
Traceback (most recent call last):
  File "/var/lib/hue/apps/beeswax/src/beeswax/api.py", line 52, in decorator
    return view_fn(request, *args, **kwargs)
  File "/var/lib/hue/apps/beeswax/src/beeswax/api.py", line 287, in execute
    query_form = get_query_form(request)
  File "/var/lib/hue/apps/beeswax/src/beeswax/api.py", line 635, in get_query_form
    databases = [(database, database) for database in db.get_databases()]
  File "/var/lib/hue/apps/beeswax/src/beeswax/server/dbms.py", line 129, in get_databases
    return self.client.get_databases()
  File "/var/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 956, in get_databases
    return [table[col] for table in self._client.get_databases()]
  File "/var/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 587, in get_databases
    res = self.call(self._client.GetSchemas, req)
  File "/var/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 555, in call
    res = fn(req)
  File "/var/lib/hue/desktop/core/src/desktop/lib/thrift_util.py", line 378, in wrapper
    raise StructuredThriftTransportException(e, error_code=502)
StructuredThriftTransportException: Could not connect to 10.50.210.130:10000 (code THRIFTTRANSPORT): TTransportException(u'Could not connect to 10.50.210.130:10000',)`

************************************************************************************
here 10.48.50.247 is the current hive server2 IP and 10.50.210.130 is the old one.

**Comment by romainr** [comment]
There is indeed an old bug about this when updating the Hive host. One workaround is to click to close the session so that it will pick up the fresh one.

This will be fixed properly via https://issues.cloudera.org/browse/HUE-8758

**Comment by bhaskarroy19** [comment]
>>>One workaround is to click to close the session so that it will pick up the fresh one.
In the Hue database, there are two session tables present, 1. beeswax_session, and 2. django_session. So does close the sessions mean clear all the entries from those tables or only clear django_session table or only clear beeswax_session?.

**Comment by bhaskarroy19** [comment]
@romainr , another note that during my debugging I also came to conclusions that probably the django session is creating this problem, so I deleted a few sessions for a blocked user but the problem of thrift server calling to old hive server. One thing I am suspecting that our django_session table has lots of rows and we don't delete them manually, so it may happen that for a user there are too many session rows and hue getting old hive server IP from those sessions. 
Also, I want to tell you that this problem happening only for few users out of more than 5k users and it is happening regularly even after multiple restarts of the hue server(means the problem resolve for them temporarily and it hit back again after some days and I have to restart my HUE servers).

**Comment by romainr** [comment]
`beeswax_session` should be the table that matters only, it is storing the "old hostnames" of the HiveServer.

`django_session` should not have any effect on this issue (except logging out the Hue user).

Do you often change the hostname of the HiveServer? This will be fixed properly via https://issues.cloudera.org/browse/HUE-8758

**Comment by bhaskarroy19** [comment]
update: I cleared all entries of beeswax_session but it didn't work.
>>> Do you often change the hostname of the HiveServer?
not often. it is happening after long time.

**Comment by romainr** [comment]
How often do you change the hive server hostname?

**Comment by bhaskarroy19** [comment]
It depends on the m/c maintenance status. But since last year we changed it only two times.

**Comment by bhaskarroy19** [comment]
*Bump*
>>>update: I cleared all entries of beeswax_session but it didn't work.
Looking for a workaround.

**Comment by bhaskarroy19** [comment]
@romainr, Hi I need some info about how the hiver-server2 host gets discovered?, means when someone login to hue then what is the flow from there to hiveserver2 discovery for any user, where it looks for any user-specific profile/cache if any.

**Comment by rajeshksv** [comment]
For quick fix, update server_host in beeswax_queryhistory table for all rows to latest hive server ip and restart hue server.

**Comment by bhaskarroy19** [comment]
@romainr, Update: We found that hue cached the hive server for a user and try to query to the IP present in beeswax_queryhistory even if the hive server endpoint changed.
As at the time of report there was no solution in the latest hue also for this problem, we came to the below resolution and it is working fine:
1. We moved from IP to DNS hostname for the hive server.
2. Update all the entries of the beeswax_queryhistory to Hive DNS hostname.
3. Update Hue config to Hive DNS hostname.
4. Restart Hue servers.

So, in the case of new servers, do not touch the config, just update the /etc/hosts entries, the DNS mappings in hue will be automatically updated.  

So, the thread can be closed.

You can share the version if this issue has been resolved. Thanks.

**Comment by romainr** [comment]
:+1: 

Good to know. And the problem solution will come in the Hue 5 revamp which is using connectors instead.
