### ISSUE TITLE
No docker tag available for version 4.7.1

### ISSUE THREAD

**Issue by gps035** [cloudera/hue#1230]
It looks like the latest stable release of Hue is 4.7.1, but there is no docker tag for this version.  
Would it be possible to push this tag?

For now we are trying 4.7.0, but I'm not sure if the bug fixes in this patch release are significant.

P.S. Sorry for not following the issue template, but it didn't seem relevant to this one as it is not a bug.

**Comment by romainr** [comment]
It should be good now: https://hub.docker.com/layers/gethue/hue/4.7.1/images/sha256-7cd74a99e95488c2cb0be5df7d0cbd6c80197e0e8e753d9f2ec80d110a23f927?context=repo

**Comment by gps035** [comment]
Thanks for that.
