### ISSUE TITLE
found that python3 is not supported

### ISSUE THREAD

**Issue by archzi** [cloudera/hue#1236]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:

According to the latest documentation , I want to make hue and install to the server, but I found that python3 is not supported
Steps to reproduce it?

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
hue version: hue-4.7.1.tgz
system version: centos7

Here is the command I executed
```bash
yum install python3 python3-devel -y  

cd hue-4.7.1 && PREFIX=/usr/share make install
```
then i found the following error

```bash

"PYTHON_VER is python3.6."
"Python 3 module install via pip"
/home/huedev/hue-4.7.1/Makefile.vars:65: *** "Error: must have python development packages for python3.6. Could not find Python.h. Please install python3.6-devel".  Stop.

```

**Comment by George-zqq** [comment]
I have a same problem !!! When i dockerize hue in CentOS 7.6 , maybe makefile has a bug.

**Comment by romainr** [comment]
It fails because of the check here https://github.com/cloudera/hue/blob/master/Makefile.vars#L62 if Python is not in one of the expected path

**Comment by George-zqq** [comment]
@romainr Thank ! I found my path of Pthon.h , and rename the path , it works !!!  
That's what i do 
> set env: export PYTHON_VER=python3.6
> find / -name Python.h

[root@cfc6eedd2944 hue]# ls -al /usr/include/python3.6m/Python.h
-rw-r--r-- 1 root root 3221 Dec 24  2018 /usr/include/python3.6m/Python.h

>  cp -r /usr/include/python3.6m/ /usr/include/python3.6/
