### ISSUE TITLE
Impala and hive syntax parser fails for queries having subquery in from clause

### ISSUE THREAD

**Issue by SachinJanani** [cloudera/hue#1237]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:

Steps to reproduce it? : Try to parse the following query: **SELECT avg(t1.x), max(t1.y) FROM (SELECT x,y from a) AS t1;**

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

**Comment by SachinJanani** [comment]
Following is the stack trace seen for this query: 
`    TypeError: Cannot read property 'columns' of undefined

      3745 | 
      3746 |      var subQuery = parser.getSubQuery($$[$0]);
    > 3747 |      subQuery.columns.forEach(function (column) {
           |               ^
      3748 |        parser.expandIdentifierChain({ wrapper: column });
      3749 |        delete column.linked;
      3750 |      });

      at Object.apply (desktop/core/src/desktop/js/parse/sql/hive/hiveSyntaxParser.js:3747:15)
      at Object.parse (desktop/core/src/desktop/js/parse/sql/hive/hiveSyntaxParser.js:4972:40)
      at Parser.parseSyntax (desktop/core/src/desktop/js/parse/sql/sqlParseUtils.js:764:14)
`

**Comment by romainr** [comment]
Sounds like a legit bug. Would you be interested in working on the parser? https://docs.gethue.com/developer/parsers/

Also will check on the master branch which got a lot of improvements compared to 4.5 (4.8 is coming soon).

**Comment by sachinunravel** [comment]
Sure will try to fix this issue
