### ISSUE TITLE
Building a debian package with Python 3.7 deps

### ISSUE THREAD

**Issue by elukey** [cloudera/hue#1239]
Describe the bug:

Hi! This is more a request to figure out what is the best procedure to build Hue from source, and then package it (in my case, in a deb package). From the documentation I see that `make apps` is needed to populate the `build` directory, and I though that the Debian package needed only to copy that directory on the target system, but then I realized that the procedure is more complex.

I also tried with `PREFIX=/some/path PYTHON_VER=python3.7 make install` and ended up in:

```
  File "/home/vagrant/hue-release-4.7.1/desktop/core/ext-py/MySQL-python-1.2.5/setup_posix.py", line 2, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'
```

I checked the ext-py directories and some of them seem not ready for Python3, so I am wondering if I am doing the right steps.

If I follow https://github.com/cloudera/hue#building-from-source everything works fine (so the dev server comes up without any issue).

Steps to reproduce it?

Hue source version 4.7.1, then:

```
PYTHON_VER=python3.7 make apps
PYTHON_VER=python3.7 PREFIX=/some/local/path make install
```

Followed https://docs.gethue.com/administrator/installation/install/

Ideally what I want to achieve is something similar to the debian package that Cloudera releases with CDH, but built for python 3.7 and some other dependencies (like Mariadb dev instead of Mysql, etc..).

Any help would be really appreciated :)

**Comment by romainr** [comment]
Have you looked at Hue in Apache BigTop the and https://github.com/cloudera/hue/blob/master/tools/docker/hue/Dockerfile.py3 ?

**Comment by elukey** [comment]
@romainr Thanks a lot for the links, BigTop doesn't package anymore Hue but the Docker file was very helpful (especially https://github.com/cloudera/hue/blob/master/tools/docker/hue/Dockerfile.py3#L45 that solves the py2 build issues).

The remaining problem is that if I use something like `PREFIX=/tmp/hue-build` for make install (inside the debian build) it works fine (cannot use more priviledged dirs like /usr/lib in debian/rules IIUC), namely I am able to get a single `hue` directory with all the files that I need, but in some python egg files I get the wrong path. For example, this is the result of a egg-link file after I deploy the deb package:

```
cat /usr/lib/hue/build/env/lib/python3.7/site-packages/metadata.egg-link
/tmp/hue-build/hue/desktop/libs/metadata/src
```

In the above case, the debian packaging is correctly deploying the metadata.egg-link under /usr/lib/etc.., but its content is not right and hue fails to start. Is there anything that I am missing that could solve this problem? Or should I simply find a way to use `PREFIX=/usr/lib` during the debian build? Alternatively I can manually fix those egg-links, but it feels a bit hacky.

**Comment by elukey** [comment]
I also found another strange thing:

```
systemd[1]: Started Hue.
python3[2976]: Traceback (most recent call last):
python3[2976]:   File "/usr/lib/hue/build/env/bin/supervisor", line 33, in <module>
python3[2976]:     sys.exit(load_entry_point('desktop', 'console_scripts', 'supervisor')())
python3[2976]:   File "/usr/lib/hue/desktop/core/src/desktop/supervisor.py", line 336, in main
python3[2976]:     outfile = open_file(os.path.join(log_dir, 'supervisor.out'), 'a+', 0)
python3[2976]: ValueError: can't have unbuffered text I/O
systemd[1]: hue.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: hue.service: Failed with result 'exit-code'.
```

As far as I understand unbuffered I/O is only available in binary mode for python3.

**Comment by elukey** [comment]
Same thing in:

```
Traceback (most recent call last):
  File "/usr/lib/hue/desktop/core/src/desktop/supervisor.py", line 368, in main
    log_stdout = open_file(os.path.join(log_dir, name + '.out'), 'a+', 0)
ValueError: can't have unbuffered text I/O
```

And also:

```
  File "/usr/lib/hue/desktop/core/src/desktop/kt_renewer.py", line 95, in detect_conf_var
    f = file(CONF.CCACHE_PATH.get(), "rb")
```

IIUC `file` is not supported in python3, it needs open.

**Comment by romainr** [comment]
Indeed, looks like some components still miss a few relatively small Python 3 changes (missed as lack of test coverage and I use cherrpy/gunicorn in Python 3), but those should be very few.

Would you able to send a pull request for those to make it compatible both for Python 2/3? I can help on the review.

**Comment by elukey** [comment]
Of course! Will try to send one asap, there are some bits that are not clear to me, I'll try to propose something so we can discuss what's best in the pull request.

**Comment by elukey** [comment]
@romainr the bit of code that I am trying to port now is `wsgiserver.py`:

`_fileobject_uses_str_type = isinstance(socket._fileobject(None)._rbuf, basestring)`

The `_fileobject_uses_str_type` variable is then used afterwards to create a class, that I guess is meant to work with binary vs text? `socket._fileobject` is deprecated in python3, do you have any indication/suggestion about how to proceed?

**Comment by elukey** [comment]
Given the fact that the change to wsgiserver.py are big it might be better to just use gunicorn, do you have any examples about how do do it? I am using this config since I checked what was present inside CDH packages, so I am fine to use gunicorn as alternative.

**Comment by romainr** [comment]
In the hue.ini, you can look for:

```
  # Set to true to use CherryPy as the webserver, set to false
  # to use Gunicorn as the webserver. Defaults to CherryPy if
  # key is not specified.
  use_cherrypy_server=false

  # Gunicorn work class: gevent or evenlet, gthread or sync.
  gunicorn_work_class=sync
```

and https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/management/commands/rungunicornserver.py

It works pretty well for me, curious how it works for other people

**Comment by elukey** [comment]
@romainr I tried to give it a go, but I found some troubles that are almost surely my fault. I started from this systemd unit config:

```
[Unit]
Description=Hue

[Service]
User=hue
Group=hue
Environment=PYTHONPATH=/usr/lib/hue/desktop/libs/:/usr/lib/hue/desktop/core/src/:/usr/lib/hue/build/env/lib/python3.7/site-packages/
Environment=DJANGO_SETTINGS_MODULE=desktop.settings
WorkingDirectory=/usr/lib/hue
ExecStart=/usr/lib/hue/build/env/bin/python3 /usr/lib/hue/desktop/core/src/desktop/management/commands/rungunicornserver.py

[Install]
WantedBy=multi-user.target
```

I tried to find a way to specify /var/log/hue as logging dir, but I didn't find one, so I specified `WorkingDirectory=/usr/lib/hue` and the `logs` dir was created in there. Not ideal, but I am surely missing a config bit somewhere.

I also had to set `DJANGO_SETTINGS_MODULE` in there due to this error:

```
django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

That is strange since I see it configured in `rungunicornserver.py`. I then saw this error:

```
Aug 13 09:05:06 python3[15877]: Traceback (most recent call last):
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 168, in _add_installed_apps_translations
Aug 13 09:05:06 python3[15877]:     app_configs = reversed(list(apps.get_app_configs()))
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/apps/registry.py", line 138, in get_app_configs
Aug 13 09:05:06 python3[15877]:     self.check_apps_ready()
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/apps/registry.py", line 125, in check_apps_ready
Aug 13 09:05:06 python3[15877]:     raise AppRegistryNotReady("Apps aren't loaded yet.")
Aug 13 09:05:06 python3[15877]: django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
Aug 13 09:05:06 python3[15877]: During handling of the above exception, another exception occurred:
Aug 13 09:05:06 python3[15877]: Traceback (most recent call last):
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/desktop/core/src/desktop/management/commands/rungunicornserver.py", line 40, in <module>
Aug 13 09:05:06 python3[15877]:     class Command(BaseCommand):
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/desktop/core/src/desktop/management/commands/rungunicornserver.py", line 41, in Command
Aug 13 09:05:06 python3[15877]:     help = _("Gunicorn Web server for Hue.")
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/utils/translation/__init__.py", line 89, in ugettext
Aug 13 09:05:06 python3[15877]:     return _trans.ugettext(message)
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 338, in gettext
Aug 13 09:05:06 python3[15877]:     return do_translate(message, 'gettext')
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 321, in do_translate
Aug 13 09:05:06 python3[15877]:     _default = _default or translation(settings.LANGUAGE_CODE)
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 228, in translation
Aug 13 09:05:06 python3[15877]:     _translations[language] = DjangoTranslation(language)
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 129, in __init__
Aug 13 09:05:06 python3[15877]:     self._add_installed_apps_translations()
Aug 13 09:05:06 python3[15877]:   File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/utils/translation/trans_real.py", line 171, in _add_installed_apps_translations
Aug 13 09:05:06 python3[15877]:     "The translation infrastructure cannot be initialized before the "
Aug 13 09:05:06 python3[15877]: django.core.exceptions.AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.
``

If I comment the line `help = _("Gunicorn Web server for Hue.")` I don't see errors anymore, and I don't have to set `DJANGO_SETTINGS_MODULE` in the systemd unit either. It seems as if it was an early logging happening before initialization of all settings, but again I am not super familiar with the codebase.

Then another error that blocked me:

```
Aug 13 09:41:20 systemd[1]: Started Hue.
Aug 13 09:41:20 python3[19196]: Traceback (most recent call last):
Aug 13 09:41:20 python3[19196]:   File "/usr/lib/hue/desktop/core/src/desktop/management/commands/rungunicornserver.py", line 156, in <module>
Aug 13 09:41:20 python3[19196]:     rungunicornserver()
Aug 13 09:41:20 python3[19196]:   File "/usr/lib/hue/desktop/core/src/desktop/management/commands/rungunicornserver.py", line 90, in rungunicornserver
Aug 13 09:41:20 python3[19196]:     bind_addr = conf.HTTP_HOST.get() + ":" + str(conf.HTTP_PORT.get())
Aug 13 09:41:20 python3[19196]: AttributeError: 'Config' object has no attribute 'get'
```

I traced down `Config` up to desktop/lib/conf.py, and effectively there is no `get` available in the class. 

Thanks in advance for the help and sorry for the wall of debugging :)

**Comment by elukey** [comment]
@romainr any idea about the above error? I can't figure out from the code where one could have `get()` working.. But since you mentioned that it works very well for your use case, then I am a bit confused..

**Comment by romainr** [comment]
` AttributeError: 'Config' object has no attribute 'get'` errors often means either Hue is not fully compiles, some modules are not registered in app.reg or the booting/entrypoint somehow is not in dependency order.


Did you first make sure that your dev Hue work properly with Gunicorn?
```
./build/env/bin/hue rungunicornserver

[2020-08-19 00:56:52 -0700] [78133] [INFO] Starting gunicorn 19.9.0
[2020-08-19 00:56:52 -0700] [78133] [DEBUG] Arbiter booted
[2020-08-19 00:56:52 -0700] [78133] [INFO] Listening at: http://0.0.0.0:8001 (78133)
[2020-08-19 00:56:52 -0700] [78133] [INFO] Using worker: threads
/home/romain/projects/hue/build/env/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)

```

**Comment by elukey** [comment]
@romainr thanks a lot for the suggestion, sorry for the lag I was afk :) 

Very interesting: I tried `PYTHONPATH=/usr/lib/hue/desktop/libs/:/usr/lib/hue/desktop/core/src/:/usr/lib/hue/build/env/lib/python3.7/site-packages/ /usr/lib/hue/build/env/bin/python3 /usr/lib/hue/build/env/bin/hue rungunicornserver` and it works fine, but the same PYTHONPATH with `/usr/lib/hue/desktop/core/src/desktop/management/commands/rungunicornserver.py` leads to the Config error.

**Comment by romainr** [comment]
Weird, it works for me. I bet there is indeed something to fix somewhere

**Comment by elukey** [comment]
@romainr I am curious about how you run it - do you use a specific PYTHONPATH or something else? Is it possible to share some details about what is the shell command that you use? It would help me trying to figure out what's wrong :)

**Comment by romainr** [comment]
I really do nothing special, just type `./build/env/bin/hue rungunicornserver` and PYTHONPATH is empty. 

To try to debug it, you could try to print the paths you get when running the hue command maybe. The virtual env might be incomplete too or with wrong paths (build/env/lib/python3.8/site-packages/hue.pth ...)

**Comment by elukey** [comment]
> I really do nothing special, just type `./build/env/bin/hue rungunicornserver` and PYTHONPATH is empty.

In this case, it works for me as well without PYTHONPATH, but my understanding is that this is for the dev server (so I shouldn't use it for production).

> To try to debug it, you could try to print the paths you get when running the hue command maybe. The virtual env might be incomplete too or with wrong paths (build/env/lib/python3.8/site-packages/hue.pth ...)

Definitely, but what I was asking in the other comments is what you'd run for production use cases (assuming that what I wrote above about the dev server is right).

Thanks for the patience!

**Comment by elukey** [comment]
@romainr ping :)

**Comment by elukey** [comment]
Updating this issue after some discoveries (clear problem between keyboard and computer :)

The cloudera hue package (from which I was getting settings/etc..) makes a symlink in /usr/lib/hue/desktop/conf to /etc/hue/conf, where I have deployed my config. Running the supervisor without it was causing the defaults to be picked, and hence my confusion about running the dev server.

I was able to run  the supervisor with gunicorn (only flipping the setting in hue.ini), but I had to fix two little py2/py3 bugs in the kt_renewer (I'll send a pull request for these).

In hue.ini I am using mysql as datastore, with a schema already populated by 3.9's tables. I've ran the migration scripts to test the upgrade to 4.7.1 and everything went fine.

The current issue that I have is that my LDAP settings (in hue.ini under `[[ldap]]` and using `backend=desktop.auth.backend.LdapBackend`) seem not working anymore, namely I cannot log in into the Hue home page. I enabled debug logging and I can see something like:

```
[01/Sep/2020 11:43:15 +0000] backend      WARNING  Cannot configure LDAP with SSL and enable STARTTLS.
[01/Sep/2020 11:43:15 +0000] backend      DEBUG    Rejecting empty password for XXXXX
```

That is [this](https://github.com/cloudera/hue/blob/faebb36a7b1b3f56e1871189c45359f4d6ac4e02/desktop/core/ext-py/django-auth-ldap-1.3.0/django_auth_ldap/backend.py#L150) line IIUC. The XXXXX value is not the username though, but the password.. if I dump in a separate log username and password of that bit of code I see, in fact, the username with the value of the password and an empty password. I checked the hue.ini config and it should be compatible with 4.7.1, not sure what it is wrong, maybe some code change of the ldap backend caused this? 

Thanks again for the patience (I am slowly getting to know better Hue).

**Comment by elukey** [comment]
This is a follow up error, probably another py2 -> py3 leftover:

```
Traceback (most recent call last):
  File "/usr/lib/hue/desktop/core/src/desktop/auth/forms.py", line 216, in authenticate
    server=server)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/usr/lib/hue/build/env/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/metrics/registry.py", line 389, in wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/hue/desktop/core/src/desktop/auth/backend.py", line 578, in authenticate
    self.import_groups(server, user)
  File "/usr/lib/hue/desktop/core/src/desktop/auth/backend.py", line 620, in import_groups
    import_ldap_users(connection, user.username, sync_groups=True, import_by_dn=False, server=server)
  File "/usr/lib/hue/apps/useradmin/src/useradmin/views.py", line 796, in import_ldap_users
    connection, user_pattern, sync_groups=sync_groups, import_by_dn=import_by_dn, server=server, failed_users=failed_users
  File "/usr/lib/hue/apps/useradmin/src/useradmin/views.py", line 946, in _import_ldap_users
    return _import_ldap_users_info(connection, user_info, sync_groups, import_by_dn, server, failed_users=failed_users)
  File "/usr/lib/hue/apps/useradmin/src/useradmin/views.py", line 982, in _import_ldap_users_info
    validate_username(ldap_info['username'])
  File "/usr/lib/hue/apps/useradmin/src/useradmin/forms.py", line 58, in validate_username
    if not validator.match(username_pattern):
TypeError: cannot use a string pattern on a bytes-like object
[01/Sep/2020 13:59:45 +0000] forms        ERROR    LDAP auth error: cannot use a string pattern on a bytes-like object
```

**Comment by elukey** [comment]
@romainr I am able to use hue now, there are still some issues here and there but I should be able to sort them out and send a pull request if you are ok. You mentioned in a previous code review that code must be python2 compatible, is there any facilitation in the code to distinguish if python2 or 3 is used ? (like a var PY3 = True etc..). I am asking to figure out how to better add defensive coding for both 2 and 3.

**Comment by elukey** [comment]
I see that in some places there is a `sys.version_info[0]` guard.

**Comment by elukey** [comment]
@romainr finally the pull request builds, I left some comments on it about the LDAP module. When you have a moment, let me know what you think about those. I am currently running that patch with gunicorn and it looks good.

**Comment by romainr** [comment]
Glad to hear and thanks for all the details.

And yes, to keep both Python 2 and 3 compatibility we can use the sys
module. And feel free to send some PRs

**Comment by elukey** [comment]
@romainr I have updated https://github.com/cloudera/hue/pull/1244 with all the code that I had to change to make my env work with py3 (+ldap +kerberos), let me know your thoughts.. I had some troubles with python-ldap and its usage of binary strings, I found a solution that worked but it may require more inputs/guidance from you.

**Comment by romainr** [comment]
I see, thanks for the work and research, this looks great! Better to make it work gradually and keep the Py2 as-is like you did.

**Comment by elukey** [comment]
@romainr we may have to reopen sorry, I missed some use cases. I added a pull request for the first ones, and now I found this:

```
[10/Sep/2020 12:14:33 +0000] api2         ERROR    Error running <function logs at 0x7f862f932e18>
Traceback (most recent call last):
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 41, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/api2.py", line 125, in logs
    response['logs'] = get_api(request.user, interface, cluster=cluster).logs(app_id, app_type, log_name, json_logs)
  File "/usr/lib/hue/apps/jobbrowser/src/jobbrowser/apis/workflow_api.py", line 113, in logs
    data = get_oozie_job_log(request, job_id=appid)
  File "/usr/lib/hue/apps/oozie/src/oozie/views/dashboard.py", line 179, in decorate
    return view_func(request, *args, **kwargs)
  File "/usr/lib/hue/apps/oozie/src/oozie/views/dashboard.py", line 619, in get_oozie_job_log
    return JsonResponse(return_obj, encoder=JSONEncoderForHTML)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/django_util.py", line 497, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/json_utils.py", line 38, in encode
    return ''.join(chunks)
  File "/usr/lib/hue/desktop/core/src/desktop/lib/json_utils.py", line 44, in iterencode
    for chunk in chunks:
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

This happen when navigating to a page like `hue/jobbrowser/#!id=0094132-200720135922440-oozie-oozi-W`

**Comment by elukey** [comment]
Also this happens when I try to submit a hive query:

```
[10/Sep/2020 12:30:37 +0000] decorators   ERROR    Error running execute
Traceback (most recent call last):
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 299, in fields
    return [HiveServerTColumnValue2(field).val.pop(0) for field in self.cols]
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 299, in <listcomp>
    return [HiveServerTColumnValue2(field).val.pop(0) for field in self.cols]
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 395, in rows
    yield row.fields()
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 301, in fields
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/decorators.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 225, in execute
    response = _execute_notebook(request, notebook, snippet)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", line 153, in _execute_notebook
    response['handle'] = interpreter.execute(notebook, snippet)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 98, in decorator
    return func(*args, **kwargs)
  File "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py", line 301, in execute
    result = db.use(query.database, session=_session)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/dbms.py", line 895, in use
    return self.client.use(query, session=session)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1301, in use
    data = self._client.execute_query(query, session=session)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 937, in execute_query
    return self.execute_query_statement(statement=query.query['query'], max_rows=max_rows, configuration=configuration, session=session)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 944, in execute_query_statement
    results, schema, operation_handle, session = self.execute_statement(statement=statement, max_rows=max_rows, configuration=configuration, orientation=orientation, session=session)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 981, in execute_statement
    (res, session) = self.call(self._client.ExecuteStatement, req, session=session)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 717, in call
    return self.call_return_result_and_session(fn, req, status, session=session)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 754, in call_return_result_and_session
    session = self.open_session(self.user)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 708, in open_session
    configuration = self.get_configuration(session=session)
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1162, in get_configuration
    properties = [(row[0].split('=')[0], row[0].split('=')[1]) for row in results.rows() if '=' in row[0]]
  File "/usr/lib/hue/apps/beeswax/src/beeswax/server/hive_server2_lib.py", line 1162, in <listcomp>
    properties = [(row[0].split('=')[0], row[0].split('=')[1]) for row in results.rows() if '=' in row[0]]
RuntimeError: generator raised StopIteration
```
