### ISSUE TITLE
unable to use any sql parser as separate npm package

### ISSUE THREAD

**Issue by harikrishnakanchi** [cloudera/hue#1255]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug: I tried to use calcite sql parser from gethue npm package.

Steps to reproduce it?
clone [hue_dep](https://github.com/cloudera/hue/tree/master/tools/examples/api/hue_dep) example
remove "hue" dependency
run `npm install gethue`
modify import statement in app.js to
```js
import sqlAutocompleteParser from 'gethue/parse/sql/hive/hiveAutocompleteParser';
```
run the following command
`npm run webpack`

Actual behaviour:
throwing error

Expected behaviour:
should compile successfully

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

**Comment by yi-you** [comment]
throwing what error?
the gethue version should be "^4.7.10"

**Comment by harikrishnakanchi** [comment]
Hi @yi-you ,

I verified version number is `^4.7.10`.

This is the error I am seeing after following above reproduce steps.
```
ERROR in ./node_modules/gethue/parse/sql/hive/hiveAutocompleteParser.js
Module not found: Error: Can't resolve 'parse/sql/hive/sqlParseSupport' in '/path-to-hue/hue/tools/examples/api/hue_dep/node_modules/gethue/parse/sql/hive'
 @ ./node_modules/gethue/parse/sql/hive/hiveAutocompleteParser.js 89:0-61 5073:0-15
 @ ./src/app.js
 @ multi ./src/app.js
```

**Comment by romainr** [comment]
Indeed, currently only a local Hue repository should work. @sreenaths has a plan to make the imports work when using the `npm`.

**Comment by khtruong** [comment]
+1 I have the same issue and would love to use a sql parser via npm package.

**Comment by khtruong** [comment]
Hi @romainr and @sreenaths! Just wondering, is there a status or eta on this?

**Comment by smaspe** [comment]
I've been using 

```ts
import sqlAutocompleteParser from 'gethue/parsers/genericAutocompleteParser.js';
```

successfully so far (same for the hive parser, I assume)
