### ISSUE TITLE
504 Gateway Timeout For Presto SQLAlchemy

### ISSUE THREAD

**Issue by DRavikanth** [cloudera/hue#1265]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? No

Describe the bug: 
1. Configured Hue to query Presto and simple queries seem to be running fine.
2. However, when issuing long-running queries, Hue throws the following error exactly after 1 minute

`504 Gateway Time-out 504 Gateway Time-out openresty/1.15.8.1 `

There is no stack trace in the hue logs. It looks like there is some hardcoded timeout set for 60secs which might need some tweaking. But, I am unable to figure out the config. It's nowhere documented in SQLAlchemy. Is there any config that we can pass from Hue for this? TIA

Steps to reproduce it? Configure Hue to query Presto as mentioned in: https://docs.gethue.com/administrator/configuration/connectors/#presto and run a query that runs for more than a minute.

Hue version or source? gethue docker latest image

**Comment by romainr** [comment]
This is probably expected, long running queries should run asynchronously in a separate task. It will come with https://issues.cloudera.org/browse/HUE-8738

**Comment by DRavikanth** [comment]
Thanks, @romainr. Can you help address the following questions?

1. It looks like the code is shipped, so is it already available in latest docker image?
2. If not will it be available as part of 4.8 release?
3. Can I make code changes as mentioned in the JIRA to our local image and use it?

**Comment by DRavikanth** [comment]
@romainr, We upgraded hue to the latest version 4.8.0. It looks like https://issues.cloudera.org/browse/HUE-8738 is targeted for 4.8.0 but its still open. Any inputs here, please? When can I expect this to be fixed? This is a critical blocker for us.

TIA

**Comment by romainr** [comment]
SQLAlchemy is synchronous, while Impala/Hive are using the HiveServer2 API which is async, and so does not block until the end of the query execution.

I would recommend to turn on the task server https://docs.gethue.com/administrator/administration/reference/#task-server and help contributing back/report feedback on the feature.

**Comment by DRavikanth** [comment]
Hi @romainr, Thanks for the inputs. Let me try exploring that.

**Comment by DRavikanth** [comment]
The timeout in this particular case happened with the synchronous calls and the issue seems to happen in the NGINX configuration. The timeout at NGINX is configured at 60secs so observing this behaior. After increasing it to like 1 hour we resolved this problem. I will close this issue. I will explore Async feature and will create issue if found any.

nginx.ingress.kubernetes.io/proxy-connect-timeout: '900'
nginx.ingress.kubernetes.io/proxy-read-timeout: '900'
nginx.ingress.kubernetes.io/proxy-send-timeout: '900' 

Thanks

**Comment by romainr** [comment]
Thanks for the report! It might then depend on how many concurrent queries are executed via Hue, please send more feedback if you see issues. In the meantime, the Task Server is getting more and more robust.
