### ISSUE TITLE
Comment is not shown when view the table info from table browser first time

### ISSUE THREAD

**Issue by zhang-jc** [cloudera/hue#1277]
When I view the table info from table browser first time, comment is not shown. When I find the table from sources area and refresh, then comment is shown.

The related issue is [https://github.com/cloudera/hue/issues/1205](https://github.com/cloudera/hue/issues/1205)

Environment:

- hue version: open source 4.8.0
- OS: CentoOS 7.3
- Python2.7.5
- hive2.1.1

Here are my test steps:
step1: comment is not shown
![](https://user-images.githubusercontent.com/18087653/94122246-e63b3700-fe84-11ea-909a-8fd671abbb08.png)

step2: find the table from sources area, comment is not shown
![](https://user-images.githubusercontent.com/18087653/94122418-197dc600-fe85-11ea-811e-a6dd3b675b41.png)

step3: refresh, comment is shown
![](https://user-images.githubusercontent.com/18087653/94122456-239fc480-fe85-11ea-9477-3af26cb437fa.png)

step4: open metastore and view table info again, comment is show
![](https://user-images.githubusercontent.com/18087653/94122545-45994700-fe85-11ea-8f60-69041e3d2982.png)

[](https://github.com/cloudera/hue/issues/1205)

**Comment by Akhilsnaik** [comment]
created Patch : https://issues.cloudera.org/browse/HUE-9500 for this isssue.
