### ISSUE TITLE
A compatibility problem of chrome: The cursor position is not displayed correctly in hive editor.

### ISSUE THREAD

**Issue by zhang-jc** [cloudera/hue#1302]
### Environment
    hue version: open source 4.8.0
    OS: Ubuntu 18.04.5 LTS
    browser：Chrome 86.0.4240.75 (64 位)
### The problem is as follows.
![](https://user-images.githubusercontent.com/18087653/96091319-05fdd200-0efc-11eb-8785-c0e2a3d27091.png)

**Comment by romainr** [comment]
This is very weird, do you see it on https://demo.gethue.com/ too? (I guess it might be local depend: so you still have the issue if you temporally switch to English as the local in your browser?)

Note: the translations have not been performed in a while, hence maybe the conflicts

**Comment by zhang-jc** [comment]
This problem also appears on [https://demo.gethue.com/](https://demo.gethue.com/).
I test this problem with firefox/chrome on ubuntu/windows/mac. This problem only appears on ubuntu with chrom.
![](https://user-images.githubusercontent.com/18087653/96204145-1febf300-0f96-11eb-9b6c-28ba2fd90aee.png)
