### ISSUE TITLE
[notebook2] Show again credential modal on username/password connection string interpolation 

### ISSUE THREAD

**Issue by romainr** [cloudera/hue#1309]
Folllow-up on #1048

Indeed, e.g with 

`postgresql://hue:${PASSWORD}@localhost:5432/hue`

I tried with Editor 2, but are you with Editor 1? (execute button is the same as in above screenshot with a little triangle).

We could need to handle again the 401 status and trigger the modal asking for the credentials:

`handleAjaxError(data, callback)`

```    } else if (data.status === 401) {
      // Auth required
      this.status(STATUS.expired);
      $(document).trigger('showAuthModal', {
        type: this.dialect(),
        callback: this.execute,
        message: data.message
      });
```

![image](https://user-images.githubusercontent.com/17945/96327836-2314cc80-0ff2-11eb-9dde-0538312b7da0.png)

**Comment by jramineni** [comment]
Will you please provide the changes so I can build in my environment?

**Comment by romainr** [comment]
Need to override
def create_session(self, lang=None, properties=None):

in https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py#L120


and return the 401

**Comment by jramineni** [comment]
I did override def create_session(self, lang=None, properties=None):  in sql_alchemy.py
`
    props = super(SqlAlchemyApiSpliceDb, self).create_session(lang, properties)

    LOG.exception('In my create_session')
    properties = dict([(p['name'], p['value']) for p in properties]) if properties is not None else {}
    props['properties'] = {} # We don't store passwords


    if '${' in self.options['url']:  # URL parameters substitution
      if '${PASSWORD}' in self.options['url']:
        auth_provided = False

        if 'password' in properties:
          user = properties.get('user') or self.options.get('user')
          props['properties']['user']= user
          pwd = properties.get('password') or self.options.get('password')
          props['properties']['password'] = pwd
          auth_provided = True

      if not auth_provided:
        LOG.exception('Raise error')
        raise AuthenticationRequired(message='Mytest : Missing username and/or password')

    return props`

With this change Dialog to enter user/password is displayed.  I see the user/password in session properties, but there not logged into database, and on refrest to reload tables, it displays error "Missing username and/or password"

**Comment by romainr** [comment]
First, are you using Editor 1 or 2?

**Comment by jramineni** [comment]
Currently using Editor 1.  Had to switch back to Editor 1, since there were some errors with Editor 2

**Comment by romainr** [comment]
Could you push it to a branch? (would be easier to test)

`showAuthModal` has a callback, and it should call again create_session(), so that it auths with the inputed credentials.

Left assist does not support it like that yet IIRC, but Editor does so better to focus on Editor only first.
