### ISSUE TITLE
[fb] support for viewing serialized (gzip compressed) HDFS files

### ISSUE THREAD

**Issue by PAStheLoD** [cloudera/hue#131]
There was some hint for some kind of deserializer support in this [HDFS operations made easy announcement](http://gethue.com/file-browser-enhancements-hdfs-operations-made-easy/) on Oct 8, though that was disturbingly vague.

For example we have a lot of smaller text files which we can read using hdfs dfs -text <path> (or hadoop fs -text <path>), but hue can't properly show them.

They start like this:

```
EQ!org.apache.hadoop.io.LongWritableorg.apache.hadoop.io.Text*org.apache.hadoop.io.compress.DefaultCodec
```

**Comment by PAStheLoD** [comment]
Sorry for the long break, but it took a bit of time to get access to the source of the Camus job that makes the files :)

It's simply using an encoder (writer provider) that "ships with" Camus:

```
etl.record.writer.provider.class=com.linkedin.camus.etl.kafka.common.SequenceFileRecordWriterProvider
```

which lives [here](https://github.com/linkedin/camus/blob/master/camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/common/SequenceFileRecordWriterProvider.java).

**Comment by romainr** [comment]
Ha, we don't have any reader for this one!
