### ISSUE TITLE
while running the make apps command in hue 4.8.0 getting the below errors

### ISSUE THREAD

**Issue by balajivenka** [cloudera/hue#1321]
![npm -install --no-bin-links-error](https://user-images.githubusercontent.com/60769946/96589834-eb17cd00-1302-11eb-83ba-cc150d00c4d5.JPG)
![Uploading npm run webpack-error.JPG…]()

ERROR: After October 20ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

launchpadlib 1.10.13 requires testresources, which is not installed.
daphne 2.5.0 requires asgiref~=3.2, but you'll have asgiref 2.3.2 which is incompatible.
django-timezone-field 4.0 requires django>=2.2, but you'll have django 1.11.28 which is incompatible.
![error-message](https://user-images.githubusercontent.com/60769946/96586110-22d04600-12fe-11eb-90c8-95dea34ba340.JPG)

![error-deoptimise](https://user-images.githubusercontent.com/60769946/96586367-878ba080-12fe-11eb-8415-eb39eb7e5619.JPG)

error message:
npm ERR! Linux 3.10.0-1062.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "webpack"
npm ERR! node v6.17.1
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! gethue@4.8.0 webpack: `webpack --config webpack.config.js`
npm ERR! Exit status 2
npm ERR![^npm-debug.log]
npm ERR! Failed at the gethue@4.8.0 webpack script 'webpack --config webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gethue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! webpack --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs gethue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls gethue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /home/actian/Hue/hue/c
make[1]: *** [npm-install] Error 1
for the above error we have tried installing node.js as mentioned in the dependency and installed some packages like 
npm install 
sudo yum update 
sudo yum install epel-release 
sudo yum install nodejs
sudo yum install npm
yum -y install nodejs npm 

nothing has been worked out still throwing npm error find the attached error og
[Error-log.txt](https://github.com/cloudera/hue/files/5408708/Error-log.txt)
[npm-debug.log](https://github.com/cloudera/hue/files/5408712/npm-debug.log)

please find the below environment details
node-v 
v6.17.1
npm-v
3.10.10
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-1062.el7.x86_64
Architecture: x86-64

**Comment by romainr** [comment]
https://docs.gethue.com/administrator/installation/dependencies/#nodejs

**Comment by romainr** [comment]
node --version
v10.22.1

**Comment by balajivenka** [comment]
![image](https://user-images.githubusercontent.com/60769946/96610135-ec53f480-1318-11eb-800f-abc78d5578d1.png)
[root@UKSL-SSAHU-01 hue]# node -v
v6.17.1
[root@UKSL-SSAHU-01 hue]# npm -v
3.10.10

**Comment by balajivenka** [comment]
the below document is not provided how to install nodejs on centos https://docs.gethue.com/administrator/installation/dependencies/#nodejs

**Comment by balajivenka** [comment]
after running the make apps command in ubantu system we are getting the below message wheather this indicates make apps run sucessfully or not no confirmation messages?
![image](https://user-images.githubusercontent.com/60769946/96611483-58832800-131a-11eb-9971-1f34672821f8.png)
0 static files copied to '/home/actian/RP/hue/build/static', 1598 unmodified, 249 post-processed.
make[1]: Leaving directory '/home/actian/RP/hue'
