### ISSUE TITLE
Hue server dashboard error

### ISSUE THREAD

**Issue by balajivenka** [cloudera/hue#1340]
Getting the below error message while clicking the dashboard on hue server.

HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/admin/info/system?user.name=hue&doAs=admin&wt=json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff5d6088e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
![Dashboard Error](https://user-images.githubusercontent.com/60769946/97293947-587fac80-1873-11eb-93f3-a5c773fc4097.JPG)

**Comment by romainr** [comment]
Solr is down or Hue not pointing to it:
https://docs.gethue.com/administrator/configuration/connectors/#dashboards

**Comment by balajivenka** [comment]
solr is down

**Comment by balajivenka** [comment]
hue is not pointig to it
