### ISSUE TITLE
Solr server could not be contacted properly

### ISSUE THREAD

**Issue by balajivenka** [cloudera/hue#1351]
I followed the below link to set up the apapche solr setup its throwing the error not able to see the databases and dashboard part 
https://docs.gethue.com/administrator/configuration/connectors/#dashboards
please find the below steps
step1: hue folder 
./build/env/bin/pip install sqlalchemy-solr
step2: 
added the below code in the database section in pseudo-distributed.ini file but didn't workout
[[[solr]]]
   name = Solr SQL
   interface=sqlalchemy
   options='{"url": "solr://<username>:<password>@<host>:<port>/solr/<collection>[?use_ssl=true|false]"}'
Step3: in interpreter already the below code was defined and it was commented as well,so i uncommented and tried still facig the [issues.](url
![solr-error](https://user-images.githubusercontent.com/60769946/97579763-776b7380-1a18-11eb-9b43-24f66d9025e4.JPG)
)
Interpreter:
[[[solr]]]
  name = Solr SQL
  interface=solr
  ## Name of the collection handler
  # options='{"collection": "default"}'

getting  the below error while login to the hue server.

Solr server could not be contacted properly: HTTPConnectionPool(host='localhost', port=8983): Max retries exceeded with url: /solr/admin/info/system?user.name=hue&doAs=admin&wt=json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by balajivenka** [comment]
any update on this issue?

**Comment by Akhilsnaik** [comment]
can you try this way ?

https://gethue.com/solr-search-ui-only/

ie by adding : 
```
[search]
solr_url=https://mysolr.example.com:5001/solr
```
