### ISSUE TITLE
HUE 4.8.0 query Hive table with Flink in Notebook, result page is confusing. 

### ISSUE THREAD

**Issue by liuxx532** [cloudera/hue#1360]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
![image](https://user-images.githubusercontent.com/12507976/97962249-b110f580-1def-11eb-8257-f4020af00f17.png)

Steps to reproduce it?
1. select connector "Notebook" 
2. select "Flink" 
3. enter sql "use catalog myhive"        "select * from tbl"

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
Hue: 4.8.0
OS: Linux ambari.server 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Browser: chrome  86.0.4240.111  (x86_64)

**Comment by liuxx532** [comment]
I found this issue is caused by the flink-sql-gateway.
![image](https://user-images.githubusercontent.com/12507976/97967801-b0309180-1df8-11eb-93b3-174885ddac72.png)

**Comment by romainr** [comment]
What is confusing?

**Comment by romainr** [comment]
Do you have the same issue in the Editor? (Not notebook, there might be a
bug there)

**Comment by liuxx532** [comment]
Yep. 
![image](https://user-images.githubusercontent.com/12507976/98062870-ca668000-1e89-11eb-8198-ea6e6d936930.png)

**Comment by romainr** [comment]
This was probably fixed since 3.8, would you give a try with Hue master?
(there is no 3.9 release yet)

**Comment by liuxx532** [comment]
@romainr  3.8/3.9 or 4.8/4.9?

**Comment by romainr** [comment]
Sorry I mean 4.8 and 4.9 obviously :+1: 

As it works on https://demo.gethue.com/hue/editor/?type=flink which runs master.

**Comment by romainr** [comment]
And some more improvements just landed in master

**Comment by Akhilsnaik** [comment]
@liuxx532  look for anny exception in /var/log/hue/runcpserver.log and mitigate that to this thread.
might be some already fixed issue.
