### ISSUE TITLE
jobbrowser - pagination for oozie jobs doesn't work

### ISSUE THREAD

**Issue by elukey** [cloudera/hue#1373]
Describe the bug:

I noticed that when I tried to browse old oozie jobs from the jobbrowser panel the list doesn't get updated (or if it does, it takes tens of seconds).

I don't see logs from Hue related to a failure to fetch from oozie, and I see some JS errors only while fetching the page, not when hitting the >> button, so I am a bit confused about how to debug this further (JS is not my best skill). Suggestions?

![Screen Shot 2020-11-06 at 9 29 30 AM](https://user-images.githubusercontent.com/1536240/98343771-979bc380-2012-11eb-9385-748f348f819b.png)

Steps to reproduce it?

Check the status of an oozie coordinator (like `/hue/jobbrowser/#!id=0202753-200915132022208-oozie-oozi-C`) and try to move across pages.

![Screen Shot 2020-11-06 at 9 18 35 AM](https://user-images.githubusercontent.com/1536240/98342736-260f4580-2011-11eb-9743-186a25ac8223.png)

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

4.8.0, python 3.7

**Comment by elukey** [comment]
@romainr hi! Can you give me some suggestions in here? This makes the oozie browsing really unusable.. is it part of the old vs new codebase discussion?

**Comment by romainr** [comment]
To be clear, you are on the list of coordinators, not the list of coordinator actions of a coordinator? (I see schedule task)

Some thoughts: 

Either the button has no action (could add a little print debug to its click action to confirm) or if there are some running jobs, the page will update itself but it will reset the the pagination (which is a bug, IIRC this was or not fixed a while ago).

If you are on the later the pagination was not implemented.

504 error is a timeout which can happen when Hue asks Oozie the logs of a long running coordinator and it has a lot of them/is slow. It should not be related indeed but could make Hue hang/be slow while the call hangs.

**Comment by elukey** [comment]
Still need to be fixed :)

**Comment by elukey** [comment]
This is still a bug!

**Comment by elukey** [comment]
Still a bug :)
