### ISSUE TITLE
Why all oozie workflow stored in the desktop_document2 table ??

### ISSUE THREAD

**Issue by userxiaozhu** [cloudera/hue#1377]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:

I used the AWS EMR HUE to create oozie workflow , the HUE version is 4.7.1,I found all metadata was saved in the table desktop_document2, why not save in oozie_workflow.

Steps to reproduce it?

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

**Comment by romainr** [comment]
All the apps shared the save tables, it is generic this way and enable easy reuse and functionalities.

Could you detail more what is your worry?
