### ISSUE TITLE
Where can I get latest image? gethue/hue:latest or gethue/hue:4.8.0 not work 

### ISSUE THREAD

**Issue by xiashei** [cloudera/hue#1379]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:
Not the  same as https://demo.gethue.com/
Steps to reproduce it?

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
4.8.0.
I want to use some functions in https://demo.gethue.com/. after I run 2 presto sql, when I click each sql,the result will change. But it not work when  I run ```docker run -it gethue/hue:latest or 4.8.0``` .where can I get this function?
by the way,can i run many sql one time? when I type in ``` show tables;show schemas;```,it run successfully,but the result is only for ```show tables```,and when I click ```show shcemas```,the result is empty

**Comment by romainr** [comment]
latest --> master branch (but currently only updated every other week, will be fixed soon)
4.8.0 --> 4.8 release branch

In your case you might want a more recent work https://hub.docker.com/r/gethue/hue
