### ISSUE TITLE
Oozie's job browser incorrectly renders PNG data

### ISSUE THREAD

**Issue by elukey** [cloudera/hue#1386]
Describe the bug:
This is the continuation of #1262, in which the problem was firstly described. There are two problems:
1) If Hue can't render the Oozie job's graph from XML, it tries to fetch its PNG representation from Oozie and to render it instead. This ends up into a broken user experience since the PNG's binary data is dumped on the HTML's code without any `<img>` tag:
<img width="651" alt="Screen Shot 2020-11-14 at 9 51 05 AM" src="https://user-images.githubusercontent.com/1536240/99143594-f7235000-265e-11eb-9973-29bb99f96708.png">

2) As mentioned above, if Hue cannot handle the Oozie's job XML code it fallbacks to the PNG image. In our case, we have a workflow with extra `""` in some actions that cause the str representation of the XML to not be transformable in valid JSON (that is needed to then render the graph correctly in the UI).

The end result of both is this broken page:

<img width="1172" alt="Screen Shot 2020-11-14 at 9 55 18 AM" src="https://user-images.githubusercontent.com/1536240/99143656-8a5c8580-265f-11eb-8e16-a51defce4476.png">

Steps to reproduce it?
In a workflow.xml, it is sufficient to have a map-reduce action with a property like the following:
```
                <property>
                    <!--Quoted on purpose -->
                    <name>cassandra.output.keyspace</name>
                    <value>"${cassandra_keyspace}"</value>
                </property>
```
The double quoting in this case is needed (it is passed to a cassandra client that doesn't accept single quotes) but it makes the xml -> json conversion to fail:

```
[14/Nov/2020 09:03:32 +0000] dashboard    ERROR    Graph data could not be generated from Workflow 0015355-201103154415936-oozie-oozi-W: Expecting ',' delimiter: line 1 column 2511 (char 2510)
Traceback (most recent call last):
  File "/usr/lib/hue/apps/oozie/src/oozie/views/dashboard.py", line 363, in list_oozie_workflow
    workflow_data = Workflow.gen_workflow_data_from_xml(request.user, oozie_workflow)
  File "/usr/lib/hue/apps/oozie/src/oozie/models2.py", line 263, in gen_workflow_data_from_xml
    node_list = generate_v2_graph_nodes(oozie_workflow.definition)
  File "/usr/lib/hue/apps/oozie/src/oozie/importlib/workflows.py", line 748, in generate_v2_graph_nodes
    node_list = json.loads(node_list)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 2511 (char 2510)
```
The specific bit in `workflows.py` that causes the problem is:

```
  # Get XSLT
  parser = etree.XMLParser(resolve_entities=False)
  xslt = etree.parse(xslt_definition_fh, parser=parser)
  xslt_definition_fh.close()
  transform = etree.XSLT(xslt)

  # Transform XML using XSLT
  transformed_root = transform(workflow_definition_root)
  node_list = re.sub('[\s]', '', str(transformed_root))
  node_list = json.loads(node_list)
```

In theory there should be a way to escape properly some chars before the `json.loads`, but I didn't find a valid solution yet (suggestions welcome).

Hue version or source?
Hue 4.8.0

**Comment by elukey** [comment]
@romainr hi! Any idea how to debug this?

**Comment by romainr** [comment]
It feels like we either need to encode the binary properly so that it is json compatible, e.g. https://stackoverflow.com/questions/1443158/binary-data-in-json-string-something-better-than-base64 (and maybe add a new type field in the response saying that if it is regular workflow data or binray) 
or create a new API endpoint to get back the binary image directly.

**Comment by elukey** [comment]
@romainr so I see two problems:
1) the XML -> json conversion that doesn't work
2) the fact that, as a fallback, the image of the workflow is retrieved from oozie and displayed as is without any <img> tag or similar in the HTML code.

1) for some workflows may be acceptable, but the fallback should work in theory..

**Comment by romainr** [comment]
:+1:

**Comment by elukey** [comment]
@romainr the follow up in this case would be to see if we can add the <img> tag for the PNG binary stuff, but it is a little outside my realm, suggestions?

**Comment by romainr** [comment]
So the easiest is probably to add the <img> tag and fill it up when the API is called with format=svg?

**Comment by elukey** [comment]
Still need to be fixed :)

**Comment by elukey** [comment]
This is still a bug!

**Comment by elukey** [comment]
Still a bug :)
