### ISSUE TITLE
Error while compiling statement: FAILED: SemanticException [Error 10072]: Database does not exist: `dby_pro`

### ISSUE THREAD

**Issue by ximengyun** [cloudera/hue#1387]
![QQ截图20201114181602](https://user-images.githubusercontent.com/19189288/99144956-7d628500-26a5-11eb-986c-980fc27a699e.png)

version: hue4.8
problem：can't watch the table

**Comment by romainr** [comment]
Could you click on the little circle refresh icon? Seems like the DB does not exist.

**Comment by ximengyun** [comment]
the DB exist in hive，I can query by hue sql,I click on the little circle refresh icon，but no use

**Comment by ximengyun** [comment]
I found the problem,when I refresh the table,hue execute the commend "DESCRIBE FORMATTED `dby_dwd`.`dwd_customer_info_detail`" commond , I try to execute this commend by hive，also have the error "Database does not exist"，this is bug,may be delete the backquote，may be can solve the problem.

**Comment by ximengyun** [comment]
I found the problem,when I refresh the table,hue execute the commend "DESCRIBE FORMATTED dby_pro.pro_info_detail" commend , I try to execute this commend by hive client，also have the error "Database does not exist"，this is bug,may be delete the backquote, can solve the problem.

**Comment by romainr** [comment]
Is your hive-site.xml not allowing the backquotes?

`hive.support.quoted.identifiers = none`

Currently Hue expects them to be always there

https://docs.cloudera.com/HDPDocuments/HDP2/HDP-2.5.3/bk_data-access/content/hive-013-feature-quoted-identifiers.html
