### ISSUE TITLE
Add 'show tables' to autocomplete for Flink

### ISSUE THREAD

**Issue by romainr** [cloudera/hue#1399]

**Comment by romainr** [comment]
Best is probably to start with a simple `SHOW TABLES|VIEWS|DATABASES`, similarly to 'sql_show' in https://github.com/cloudera/hue/tree/master/desktop/core/src/desktop/js/parse/jison/sql/ksql and add it to the generic https://github.com/cloudera/hue/tree/master/desktop/core/src/desktop/js/parse/jison/sql/generic

Then import it in the structure.json. That way it would kickstart a basic reusable SHOW grammar, and then we can see for the dialect/Calcite specific as we go deeper.

- Flink 'SHOW' statement https://ci.apache.org/projects/flink/flink-docs-release-1.12/dev/table/sql/show.html
- ksql example https://github.com/cloudera/hue/commit/04ab447238e63ce5ee736e4fc0b2aba013a7c3f3#diff-f0a0b26331f281bf8942ef9ce306371934fc02988fdad643f73c94a1aac7b39b 
- Dask SQL https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/js/parse/jison/sql/dasksql/show/show.jison

**Comment by romainr** [comment]
docker-compose to easily boot a Flink DB https://gethue.com/blog/tutorial-query-live-data-stream-with-flink-sql/

**Comment by Akhilsnaik** [comment]
@romainr  assigning this to myself.
