### ISSUE TITLE
Hue configure with hive and hadoop occured some problem.

### ISSUE THREAD

**Issue by b1322457** [cloudera/hue#140]
![screenshot from 2015-01-01 16 01 08](https://cloud.githubusercontent.com/assets/7726415/5591866/83087846-91cf-11e4-9fc3-a46686d4d569.png)
   Only focus on the hadoop and hive ,I connect the remote pc that has  hadoop and hive but occured this problem.
   I  see the /tmp access are 777 in the remote pc . 
   I change the "8020" to "9000" it still didn't work.(Hive Editor),It maybe the permission problem.

**Comment by b1322457** [comment]
Maybe the "/tmp" is on the hdfs ,but i see  at the hdfs the permission  is also "777".

**Comment by romainr** [comment]
You need to have WebHdfs enabled: http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/cdh_ig_cdh_hue_configure.html#topic_15_4_1_unique_1
