### ISSUE TITLE
[beeswax]Table alias fail to execute auto complete while sql endwith semicolon";"

### ISSUE THREAD

**Issue by jasonliaoxiaoge** [cloudera/hue#141]
SQL example: select test.id from table test;

Currently i clear ";" in autocomplete.utils.js:
------------------------------------------------------------------------------------------------------------------------------
diff --git a/hue-2.5.0-cdh4.6.0/apps/beeswax/static/js/autocomplete.utils.js b/hue-2.5.0-cdh4.6.0/apps/beeswax/static/js/autocomplete.utils.js
index a2754cc..fee92c2 100644
--- a/hue-2.5.0-cdh4.6.0/apps/beeswax/static/js/autocomplete.utils.js
+++ b/hue-2.5.0-cdh4.6.0/apps/beeswax/static/js/autocomplete.utils.js
@@ -49,7 +49,8 @@
     }
     var _found = _val.substr(_from, _to).replace(/(\r\n|\n|\r)/gm, "").replace(/from/gi, "").replace(/join/gi, ",").split(",");
     for (var i = 0; i < _found.length; i++) {
-      var _tablealias = $.trim(_found[i]).split(" ");
+      _foundclean=_found[i].replace(";", "");
+      var _tablealias = $.trim(_foundclean).split(" ");
       if (_tablealias.length > 1) {
         _aliases[_tablealias[1]] = _tablealias[0];
       }

**Comment by jasonliaoxiaoge** [comment]
I create issue: https://issues.cloudera.org/browse/HUE-2517

**Comment by enricoberti** [comment]
Thanks but that's been solved on 3.6 (see https://issues.cloudera.org/browse/HUE-1977)
We won't backport it to 2.5 which is a very old version of Hue

**Comment by jasonliaoxiaoge** [comment]
cool, thanks a lot.
