### ISSUE TITLE
hannibal-hue application install problem!!!

### ISSUE THREAD

**Issue by shfhp** [cloudera/hue#142]
1. download hannibal-hue application: https://github.com/ymc/hannibal-hue/ 
2. unzip hannibal-hue-master.zip 
3. upload hannibal to /opt/cloudera/parcels/CDH/lib/hue 
4. ./build/env/bin/python tools/app_reg/app_reg.py --install hannibal --relative-paths
5. reboot hue
6. visit http://127.0.0.1:8888
Error:
ImproperlyConfigured: Error importing authentication backend desktop.auth.backend.AllowFirstUserDjangoBackend: "No module named useradmin.models

Fix：hue/tools/app_reg/common.py
line 28: APPS_ROOT = os.path.join(INSTALL_ROOT, 'apps')
modify to:
APPS_ROOT = INSTALL_ROOT

**Comment by romainr** [comment]
Thanks!

It could also be that you don't need the --relative-paths or should put it in 'apps' and do like https://github.com/danieltardon/kafka-hue#installation

**Comment by shfhp** [comment]
I read the "kafka-hue#install" webpage, and find the problem:
I should change to apps directory and run command:
# cd  /opt/cloudera/parcels/CDH/lib/hue/apps
move hannibal to apps directory
# ../build/env/bin/python tools/app_reg/app_reg.py --install hannibal --relative-paths
It's OK! Thanks for you help!!

**Comment by shfhp** [comment]
I read the "kafka-hue#install" webpage, and find the problem:
I should change to apps directory and run command:
# cd  /opt/cloudera/parcels/CDH/lib/hue/apps
move hannibal to apps directory
# ../build/env/bin/python tools/app_reg/app_reg.py --install hannibal --relative-paths
It's OK! Thanks for you help!!

**Comment by shfhp** [comment]
I read the "kafka-hue#install" webpage, and find the problem:
I should change to apps directory and run command:
1. cd /opt/cloudera/parcels/CDH/lib/hue/apps
2 move hannibal to apps directory
3. ../build/env/bin/python tools/app_reg/app_reg.py --install hannibal --relative-paths
It's OK! Thanks for you help!!

**Comment by shfhp** [comment]
1. cd /opt/cloudera/parcels/CDH/lib/hue
2. ./app.reg file in CDH 5.3  define:
{
    "path": "./apps/hbase", 
    "author": "Hue", 
    "version": "3.7.0", 
    "name": "hbase", 
    "desc": "Explore and edit HBase clusters, tables and rows"
  }, 
3. run app_reg.py command to install hannibal application :
./build/env/bin/python tools/app_reg/app_reg.py --install hannibal --relative-paths
4. check build/env/lib/python2.6/site-packages/hue.pth file:
..\..\..\..\..\apps\apps\hbase\src  <==  2 apps in directory paths
# app.reg configuration file has problem? 
# application position and --relative-paths should not a problem.

5. check tools/app_reg/app_reg.py file: 
def get_app_info(app_loc):
  """
  get_app_info(app_loc) -> (app_name, version, description) 
# this comment not correct, should return 4 fields, miss author in comment.

  Runs the app's setup.py to get the info. May raise ValueError and OSError.
  """
  return stdout.split('\n')[:4]
