### ISSUE TITLE
Api Error: Invalid method name: 'scannerOpenWithScan'

### ISSUE THREAD

**Issue by Areks** [cloudera/hue#143]
Hello, i use hbase 0.94.26 and latest hue. I can see tables on the server but when i try to search or open table i get error (see title). I tried to google, but without result.

**Comment by romainr** [comment]
Are you sure that you are using Thrift Server V1? (and not V2)

**Comment by M2shad0w** [comment]
now support Thrtft Server V2?

**Comment by romainr** [comment]
Still HBase Thrift Server v1
