### ISSUE TITLE
Support issues for 'clickhouse'

### ISSUE THREAD

**Issue by inkzuji** [cloudera/hue#1443]
1. ClickHouse in hue loads 1000 directly by default, it cannot be loaded by scroll like hive.
2. ClickHouse downloads up to 1000 pieces by default when downloading in hue. Even if "limit" is used, it still cannot download more than 1000 pieces of data.
3. ClickHouse cannot use "create temporary table" in hue.
4. There is a problem of timing failure in ClickHouse in hue

version is 4.8.0

**Comment by romainr** [comment]
Are you using the SqlAlchemy dialect? https://docs.gethue.com/administrator/configuration/connectors/#clickhouse

**Comment by inkzuji** [comment]
> Are you using the SqlAlchemy dialect? https://docs.gethue.com/administrator/configuration/connectors/#clickhouse

Yes, I using the SqlAlchemy dialect

**Comment by tianting12** [comment]
I use SqlAlchemy  not well, can you tell me your SqlAlchemy  version !! 
Thanks !!!

**Comment by inkzuji** [comment]
> I use SqlAlchemy not well, can you tell me your SqlAlchemy version !!
> Thanks !!!

SqlAlchemy version: 1.3.8

**Comment by tianting12** [comment]
What I use on hue is sqlalchemy-clickhouse and have some questions about version ，

**Comment by tianting12** [comment]
I have used several versions ，and now I wang to use jdbc .BUT I dont no have to docker build .

**Comment by tianting12** [comment]
Is SqlAlchemy OK?

**Comment by romainr** [comment]
1. and 2. feels like the JDBC connector is used and not SqlAlchmey interface (https://docs.gethue.com/administrator/configuration/connectors/#clickhouse), but would need to check why. It might be related to SqlAlchemy.
3. What is the error? It might be related to https://github.com/xzkostyan/clickhouse-sqlalchemy
4. What is the error message?

**Comment by tianting12** [comment]
Thank you very much.！ I got it through the Sqlalchemy Clickhouse. But there are requirements for the version

infi.clickhouse-orm==1.0.3  sqlalchemy-clickhouse==0.1.4.post0 and There is one more area that needs to be modified

in /usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py lines 230

`self.options['url'].startswith('phoenix://') or self.options['url'].startswith('presto://') or \
        self.interpreter.get('dialect_properties') and self.interpreter['dialect_properties']['trim_statement_semicolon']:
      statement = statement.strip().rstrip(';')

   #if self.interpreter.get('dialect_properties', {}).get('has_use_statement') and snippet.get('database'):
   #  connection.execute('USE ' + snippet['database'])

    result = connection.execute(statement)`
 
This is my DockerFile

`FROM gethue/hue:latest

RUN  /usr/share/hue/build/env/bin/python2.7 -m pip install --upgrade pip -i https://pypi.douban.com/simple && \
     ./build/env/bin/pip install infi.clickhouse-orm==1.0.3  sqlalchemy-clickhouse==0.1.4.post0  -i https://pypi.douban.com/simple
COPY sql_alchemy.py /usr/share/hue/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py
`

**Comment by romainr** [comment]
`latest` image should just work as is from right now

**Comment by tianting12** [comment]
Have you recompiled the packaged image。 Cool，thanks
