### ISSUE TITLE
gethue.com search showing results from other websites

### ISSUE THREAD

**Issue by DandyDev** [cloudera/hue#146]
**Problem**: When you do a search on the [Hue website](http://gethue.com/), it shows a non-styled result list with links to all kinds of external websites that have nothing to do with Hue
**How to reproduce**: 
- Go to the [Hue website](http://gethue.com/)
- Click on the search icon
- Type "OAuth" (this is what I was searching for)
- Press `Enter`
- Be amazed by lots of websites on how to write essays

See attached screenshot
![screen shot 2015-01-31 at 10 12 53](https://cloud.githubusercontent.com/assets/854991/5987554/d1042b52-a931-11e4-82db-9b8d7b1a83cf.png)
.

**Comment by romainr** [comment]
Weird, we are having a look, thanks!

**Comment by enricoberti** [comment]
Thank you so much for letting us know! The issue has been fixed!
