### ISSUE TITLE
Add a dask-sql parser and connector

### ISSUE THREAD

**Issue by romainr** [cloudera/hue#1480]
From Nils:

Thanks to @romain for his nice comment to this medium post on dask-sql, where he asks if it would be a good idea to add dask-sql as a parser and a connector to Hue. I would be very happy to collaborate on this! Thank you very much for proposing this.

Looking at the code (and your very nice documentation), I have the feeling that adding a new "dask-sql" component should be rather straightforward - whereas adding the SQL parser would probably be a bit more work.
I would probably start with the presto dialect and first remove everything that dask-sql does not implement (so far).

Creating a correct parser seems like a really large task to me and I would be happy if you have good suggestions on how to properly sync Hue with the SQL dask-sql understands and if you have any suggestions on how to speed up the development.

I would also be happy for any guidance on how to reasonably split this large task and if you think in general if this is a good idea.

Thanks!

**Comment by romainr** [comment]
Potential tasks:

1. 'dask-sql' Dialect
1. autocomplete

**Comment by romainr** [comment]
3. (could be done just after 1.)
In a follow-up commit feel free to add it above Clickhouse in the documentation too: https://docs.gethue.com/administrator/configuration/connectors/#clickhouse (edit button on the top right corner)

**Comment by romainr** [comment]
For 2., should be similar to https://github.com/cloudera/hue/commit/3d0d9ec1a3f0e0f27be676210cf527b511039cd6#diff-b25a8655b531acf6de9f727258ebe914ee6c156d3f29223757232bac13cd24bf (but now there is the new structure.json and more changes, so to tweak a bit)

**Comment by nils-braun** [comment]
Thanks for all the nice hints @romainr - really appreciated! 

I tried to do some first steps towards number 2.
* I generated some `json` in `desktop/core/src/desktop/js/parse/jison/dasksql` (I noticed that hyphen seem not to work properly) 
* and also let `generateParsers.js` generate the matching `js` files in `desktop/core/src/desktop/js/parse/sql/dasksql/`. 
* Then, I am running ` npm run dev-workers` and ` npm run dev` all the time.
* I have also changed the dialect in `types.py` to `dasksql`.

However, I do not think Hue is picking up the correct grammar in the autocomplete, as it is still showing all the (old) options. Probably I missed some important step...

**Comment by romainr** [comment]
Hum, I suppose this is the branch
https://github.com/nils-braun/hue/commit/5b4f56af260b77c44708d76369bc3e9d3f907ff9
on top the head, not sure yet about what is missing. @JohanAhlen 

Did you also update the name of the interpreter in the hue ini to be?
```[[[dasksql]]]```

Nit: adding the paths to `.eslintignore` will help later.

**Comment by romainr** [comment]
Also if you search in the repo with 'flink' or 'ksql' (other dialects), it will show-up all the other places (mostly for syntax highlighter and `webpack.config.npm.js`).

**Comment by JohanAhlen** [comment]
The connector/interpreter name needs to match, so if connector.dialect == 'dask-sql' it won't match with an autocompleter named 'dasksql'. You can check the how the available dialects are reported to the UI in the chrome console:

`window.huePubSub.publish('cluster.config.get.config', config => { console.log(config.app_config.editor.interpreters) });`

expand the array and check what the dialect attribute is set to.

For "... (I noticed that hyphen seem not to work properly)" I'll take a look ( #1498 )

**Comment by romainr** [comment]
@nils-braun, if you want you can send the PR here and I can play with it to check?

**Comment by nils-braun** [comment]
Hi @romainr - thanks for reminding me and sorry for the late update. I did manage to get the correct parser to work (the problem was: I was confused that e.g. the ALTER keyword was still shown, although I have removed it from the list, but it seems I needed to remove it "by hand" from the JavaScript).
Now I am in the process of adjusting and refining the SQL definition (and then adding tests). I can push a somewhat incomplete first draft today evening - but I hope I can finish it next weekend.

**Comment by romainr** [comment]
Great, was just making sure you were not stuck! And this looks like an awesome progress! (and feel free to send iterative PRs as you go or later, as you prefer!)

**Comment by romainr** [comment]
Wondering if expected (proposed by the autocomplete):

`docker run --rm -it -p 8080:8080 nbraun/dask-sql`

`SHOW TABLES`

`(pyhive.exc.DatabaseError) {'message': 'Can not parse the given SQL: Encountered "<EOF>" at line 1, column 11.\nWas expecting:\n "FROM" ...\n\nThe problem is probably somewhere here:\n\n\tSHOW TABLES\n\t ^', 'errorCode': 0, 'errorName': "<class 'dask_sql.utils.ParsingException'>", 'errorType': 'USER_ERROR', 'errorLocation': {'lineNumber': 1, 'columnNumber': 11}} [SQL: SHOW TABLES] (Background on this error at: http://sqlalche.me/e/4xp6)`

**Comment by romainr** [comment]
Ha: `SHOW TABLES from "schema"`

**Comment by romainr** [comment]
On demo.gethue.com: https://demo.gethue.com/hue/editor/?type=8

**Comment by nils-braun** [comment]
That is super great, @romainr! I have already tested it and it works!

**Comment by romainr** [comment]
The demo is simply Hue latest daily image on k8s: https://github.com/cloudera/hue/tree/master/tools/kubernetes
It is a long tradition: https://gethue.com/hadoop-tutorial-live-demo-hadoop-directly-from-your-browser/
The DBs engines are also installed via k8s or docker (like dask-sql) or docker-compose (https://github.com/romainr/query-demo)

There is still a continuous weekly ironing (next steps is more table/query samples) but it is getting there!
A lightweight version via components should also come-up in Q1 2021, similarly to https://docs.gethue.com/developer/components/parsers/

**Comment by romainr** [comment]
While playing with the Editor on https://demo.gethue.com/hue/editor/?type=10

Noticed that we don't autocomplete the columns for some reason. Might be useful to add (along the CREATE MODEL ;))

```SELECT | FROM "nyc-taxi"```

**Comment by nils-braun** [comment]
Oh, thanks for checking that!
That should be easy to add, I will try to look into that.
One thing I mentioned, is that the tooltip on the left bar that should normally show a sample of the column data is empty. Looking into it I realized that Hue is automatically creating a SELECT query in the background (which is cool), but using backticks ` for the identifiers (not quotes "). I think this also happens for presto (and does also not work there). Is there a way how I can change this?

**Comment by romainr** [comment]
IIRC it might be related to quoting the table name (as a table without - worked), but to check.

Ha weird for the samples, it should already use quotes cf. https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/lib/connectors/types.py#L412. Will check that

**Comment by nils-braun** [comment]
Hu, I am confused. It works on demo.gethue.com... 
Maybe that was a false alarm - sorry for that! I will need to check again...

**Comment by romainr** [comment]
demo.gethue is using the daily build, so it is the master code from yesterday (so very recent)
