### ISSUE TITLE
Update documentation for HDP installation guide

### ISSUE THREAD

**Issue by moandcompany** [cloudera/hue#149]
A new step-by-step writeup has been created as an update to my previous post on using HDP 3.7+ with HDP 2.2. (previously seen here: http://gethue.com/how-to-deploy-hue-on-hdp/)

The new step-by-step writeup should be on the www.gethue.com blog soon.

Cheers,
Andrew

**Comment by romainr** [comment]
Awesome!

The new version is here:
http://gethue.com/hadoop-hue-3-on-hdp-installation-tutorial/

Thanks a lot!
