### ISSUE TITLE
If I have many instances of mysql ,please tell me how to configure them

### ISSUE THREAD

**Issue by Level1Accelerator** [cloudera/hue#1491]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
in hue4.8
[[[mysql]]]
name=MySQL
interface=sqlalchemy
options='{"url": "mysql://root:root@localhost:3306/hue"}'

**Comment by romainr** [comment]
Currently it will need multiple sections, e.g. 

```
[[[mysql]]]
...
[[[mysql-2]]]
...
```

and you might lose the specific dialect autocomplete for the other ones but it won't matter in your case if you are using MySql as the default SQL dialect autocomplete is the same

or try the connectors:
https://github.com/cloudera/hue/commit/0519528f6106f7f3b386c6e227b2f2b86db28de0#diff-8fd150922f8c9228c6177b6f4a533d87a27c04424b2e3546b26344f000ac6b40R33
