### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by ainilife** [cloudera/hue#15]
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hue Maven Parent POM 2.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ hue-parent ---
[INFO] Installing /home/hadoop/hue/maven/pom.xml to /home/hadoop/.m2/repository/com/cloudera/hue/hue-parent/2.1.0-SNAPSHOT/hue-parent-2.1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.497s
[INFO] Finished at: Tue Oct 30 17:51:46 CST 2012
[INFO] Final Memory: 3M/117M
[INFO] ------------------------------------------------------------------------
make[1]: Entering directory `/home/hadoop/hue/desktop'
make -C core env-install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from hueversion import VERSION
  File "/home/hadoop/hue/desktop/core/hueversion.py", line 1
    ../../VERSION
    ^
SyntaxError: invalid syntax

**Comment by xiyoulaoyuanjia** [comment]
i also get the error from the release-3.11.0 tarball ,

**Comment by enricoberti** [comment]
Make sure you use Maven 3

**Comment by Faynman-Dragon** [comment]
i also get the error from the release-4.2.0

**Comment by BlueSkyyy** [comment]
Did you solved this problem? I also get the error. Version of Maven is 3.0.5. Version of Python is 2.7.6.

**Comment by Atrbear** [comment]
i get the error from the release-4.1.0

**Comment by CrystalRanita** [comment]
I get the same error with hue 4.7.1, Python 2.7.17 on Ubuntu18.04.
After replacing all hueversion.py files' VERSION as @ainilife mentioned make apps without VERSION error.
X => ../../../VERSION
O => VERSION="4.7.1"

Comment out original VERSION:
find . -name "hueversion.py" -exec sed -i "/VERSION/ s/^/#/" {} +

Add new line VERSION="4.7.1"
find . -name "hueversion.py" -exec sh -c 'echo VERSION=\"4.7.1\" | tee -a {}' \;

**Comment by wachoo** [comment]
I get the same error with hue 4.11.0, Python 3.8, ubuntu:20.04  built by Dockerfile. fix it by:

```sh
RUN cd /hue && \
    find . -name "hueversion.py" -exec sed -i "/VERSION/ s/^/#/" {} + && \
    find . -name "hueversion.py" -exec sh -c 'echo -e "\nVERSION=\"4.11.0\"" | tee -a {}' \;
```
