### ISSUE TITLE
404 error while creating index through the csv files.

### ISSUE THREAD

**Issue by balajivenka** [cloudera/hue#1517]
steps to create 
1)select index and then select the file option.
2) select the csv file from hdfs browser. 
Error message:
400 Client Error: Bad Request for url: http://localhost:8983/solr/admin/configs?user.name=hue&doAs=admin&action=LIST&wt=json { "responseHeader":{ "status":400, "QTime":1444}, "error":{ "metadata":[ "error-class","org.apache.solr.common.SolrException", "root-error-class","org.apache.solr.common.SolrException"], "msg":"Solr instance is not running in SolrCloud mode.", "code":400}} (error 400)

Could not create index. Check error logs for more info.please find the aatched error log.
Hue version 4.8.0
[error.log](https://github.com/cloudera/hue/files/5702659/error.log)

**Comment by romainr** [comment]
"Solr instance is not running in SolrCloud mode.", non Cloud might not be supported yet

**Comment by balajivenka** [comment]
while starting the solr in cloud mode getting the below error.

solr version 8.6.0 

root@usau-bvenka-01:/usr/src/solr-8.6.0# bin/solr -e cloud
*** [WARN] *** Your open file limit is currently 1024.
 It should be set to 65000 to avoid operational disruption.
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
*** [WARN] ***  Your Max Processes Limit is currently 1567.
 It should be set to 65000 to avoid operational disruption.
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh

Welcome to the SolrCloud example!

This interactive session will help you launch a SolrCloud cluster on your local workstation.
To begin, how many Solr nodes would you like to run in your local cluster? (specify 1-4 nodes) [2]:
2
Ok, let's start up 2 Solr nodes for your example SolrCloud cluster.
Please enter the port for node1 [8983]:
7574
Please enter the port for node2 [7574]:
7574
Solr home directory /usr/src/solr-8.6.0/example/cloud/node1/solr already exists.
/usr/src/solr-8.6.0/example/cloud/node2 already exists.

Starting up Solr on port 7574 using command:
"bin/solr" start -cloud -p 7574 -s "example/cloud/node1/solr"

*** [WARN] ***  Your Max Processes Limit is currently 1567.
 It should be set to 65000 to avoid operational disruption.
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
WARNING: Starting Solr as the root user is a security risk and not considered best practice. Exiting.
         Please consult the Reference Guide. To override this check, start with argument '-force'

ERROR: Failed to start Solr using command: "bin/solr" start -cloud -p 7574 -s "example/cloud/node1/solr" Exception : org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)

**Comment by balajivenka** [comment]
getting an error message while fetching the csv files on dashboard
A server error occurred.  Please contact the administrator.

**Comment by balajivenka** [comment]
any updates on this issue?

**Comment by balajivenka** [comment]
awaiting for the resolution
