### ISSUE TITLE
0 value show in the result is empty

### ISSUE THREAD

**Issue by penggongkui** [cloudera/hue#1547]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:
![image](https://user-images.githubusercontent.com/49138427/103124203-f2bc6f00-46c1-11eb-8507-428090b9a257.png)

Steps to reproduce it?
select 0;

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

docker version: gethue/hue

**Comment by romainr** [comment]
Indeed, this is a bad one.

Also `select false`

**Comment by penggongkui** [comment]
is hueUtils.deXSS issue?

**Comment by romainr** [comment]
Could be or actually https://github.com/cloudera/hue/commit/1a1fb6416606c4cc5fc05ad0d7dc7c5683337741

UI issue for sure.
{code}
{"status": 0, "result": {"has_more": true, "type": "table", "meta": [{"comment": null, "type": "BOOLEAN_TYPE", "name": "_c0"}], "data": [[false]], "isEscaped": true}}
{code}

**Comment by romainr** [comment]
Should be good after rebase!
https://github.com/cloudera/hue/pull/1549

Thanks a lot for the report and doing a pull request!
