### ISSUE TITLE
The Hue Team needs your help!

### ISSUE THREAD

**Issue by enricoberti** [cloudera/hue#155]
Hey former or present collaborators!

The Hue team would like you to stop having fun pushing up code to open source projects just for 5 minutes and review/sign this ICLA - Individual Contributor License Agreement: https://www.clahub.com/agreements/cloudera/hue (short version: this is just for saying that you agreed in lawyer terms to have your work contributed/included to Hue!). 

We know, building up stuff is much better, but sometimes we have to deal with legal things too... And the first one to sign will get a surprise!

@romainr @enricoberti @xizhao @newalex @gdgt @pslawski @suhassatish @subtleGradient @benbishop @dominikgehl @shuodiaoaws @shrijeetrf @thinker0 @wibou7 @l1x @lfrancke @papisz @ashu210890 @vybs @waywardmonkeys @cwalet @grundprinzip @t3hi3x @Ile2 @zhihaixu @bmwh @raphi @andreisavu @mrmrs @alheio @RuiPereira @ambreenkazi @nfo @dbeech @jkukul @xskk169x @annmcctw

**Comment by shrijeetrf** [comment]
So what is the surprise ;)

**Comment by enricoberti** [comment]
@shrijeetrf  please send us your postal address at team@gethue.com :)
