### ISSUE TITLE
Invalid datasource credentials cached when using SQLAlchemy connector

### ISSUE THREAD

**Issue by ebessah** [cloudera/hue#1573]
## Problem

We are trying to use SparkSQL with the SQLAlchemy connector like so:

```
[[[hive]]]
    name=Databricks
    interface=sqlalchemy
    options='{"url":"databricks+pyhive://token:${PASSWORD}@<host>:<port>/default","connect_args":{"cluster":"<cluster_name>"}}'
```

Users are prompted on the UI to enter their password the first time they try to execute a query. When a valid password is 
provided and `Connect` button on the modal/dialog is clicked, connection is successfully established, query is executed and a response is returned, which is good. However, when an invalid password is provided, the modal/dialog disappears on the click of `Connect` and an error appears with either a blank message or a message which reads "No error message, 
please check the logs". 

Subsequent query executions do not display the modal/dialog again but rather use the wrong credentials set in the `ENGINE` object in `desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py` to establish connection, which throws an exception when line `223` is executed:

```python
connection = engine.connect()
```

The way we have gone around the problem is to restart the service so that whatever is held in memory via the `ENGINE` 
object is removed for the modal to show again. This is not at all ideal for us since at any particular time, we have several users using the system. Our use-case is such that each user connects to the datasource using their own generated token (as password). Tokens could expire at anytime whiles users are using Hue, and would require that the modal is shown for the correct token (password) to be used when query executions are failing.

## Workaround

We extract line `223` into a function (which is called from anywhere it's needed within the script) and wrap a `try...except` block around it. In this case, if a connection error occurs and exception is thrown when executing a query from within `execute`, we remove the `ENGINE` object by its key and then raise an `AuthenticationRequired` exception. This triggers the modal to show on the UI again for the correct credentials to be provided.

```python
def _get_engine_key(self):
    return ENGINE_KEY % {
      'username': self.user.username,
      'connector_name': self.interpreter['name']
    }

...


def _create_connection(self, engine):
    connection = None
    try:
      connection = engine.connect()
    except Exception as e:
      engine_key = self._get_engine_key()
      del ENGINES[engine_key]
      raise AuthenticationRequired(message='Could not establish connection to datasource')

    return connection
```

Usage in `execute` and `explain`:

```python
engine = self._get_engine()
connection = self._create_connection(engine)
```

## System Information

Hue version: open source 4.8.0 via docker
Browser: Latest versions of Google Chrome or Firefox
OS: macOS Catalina version 10.15.7

**Comment by romainr** [comment]
Thanks, looks like a legit problem and a good fix!

Would you be able to just send a pull request?

**Comment by ebessah** [comment]
Sure -  I'll sort that and send one over
