### ISSUE TITLE
[presto] select result repeated 

### ISSUE THREAD

**Issue by penggongkui** [cloudera/hue#1576]
![image](https://user-images.githubusercontent.com/49138427/103499579-8f7dca00-4e83-11eb-9910-66e4d6605f37.png)

not everytime happen, but maybe 10 times will happen

version: in the demo.gethue.com

**Comment by romainr** [comment]
Due to the `polling` change?

To check the Ajax call in the Chrome console, to see if there is a duplicated `fetch_results` of the data returned in the `fetch_result` is wrong (probably the former is happening)

**Comment by penggongkui** [comment]
fetch_results is duplicated too

**Comment by penggongkui** [comment]
https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L341

**Comment by romainr** [comment]
With `parallel`?

I saw only one `fetch_results` but it had double rows:

`SELECT array[1, 2, 3]`

![image](https://user-images.githubusercontent.com/17945/103534622-14e18a00-4e44-11eb-94a1-c0ca73355e06.png)

**Comment by penggongkui** [comment]
both check_status && progress && fetch_result will call pyhive https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L319

**Comment by romainr** [comment]
Maybe we should disable poll before we get a cleaner solution.

And looking at https://github.com/dropbox/PyHive/blob/master/pyhive/presto.py#L303, should we do something similar to 
`response.pop('data', None)`
to avoid this if poll is supposed to only return the status and have no side effetcs?

**Comment by penggongkui** [comment]
feel OK to disable the feature, I have build my version fixed by this way.

**Comment by penggongkui** [comment]
Pyhive use the same nexturl both in poll and fetch result ,so it can't be fixed if not use lock, response is not the same object , get response from nexturl and update nexturl need atomic

**Comment by romainr** [comment]
Note about async queries:
https://github.com/cloudera/hue/issues/1681

About the double results:
We could still keep the presto specific for the progress but add the previously fetched results into the result.

About getting logs:
https://github.com/cloudera/hue/issues/1682

**Comment by romainr** [comment]
@penggongkui Isn't Presto blocking on https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py#L254 until the query is finished? (and so the execute_statement() call does not return right away)

**Comment by penggongkui** [comment]
No, it will return a something like cursor immediately, or the check status
will never work.

**Comment by penggongkui** [comment]
Maybe fetch_logs will block?

**Comment by romainr** [comment]
Ha good to know, thanks! Will check if same behavior with Hive too! Maybe it is using the async automatically under the cover which is nice.

I am currently looking at cleaning-up SqlAlchemy API. Will also check for the dup results.

**Comment by penggongkui** [comment]
@romainr is this issue finally resolved? Now I have another idea, if we don't use lock , we can deep copy the cursor for check progress, so the result will not duplicate.

**Comment by romainr** [comment]
The problem is still there. Would be awesome if you have another idea!

**Comment by penggongkui** [comment]
OK, I will try this idea

**Comment by vijayinani** [comment]
Is there a fix to this? We planned to use Hue with Trino in Production. Everything else works fine till now, but this duplicate thing will cause a bad user experience and the data cannot be trusted. What is the solution? Let me know if I need to do any code change at local level.

**Comment by zhuzhengjun01** [comment]
We found that data repeat in HUE console  while I used trino pyhive connection, is there any version has been fixed yet?

**Comment by fatihmete** [comment]
Still exists in trino
