### ISSUE TITLE
Cannot upload files bigger than 1MB in FileBrowser

### ISSUE THREAD

**Issue by JulianBlin** [cloudera/hue#1588]
I have deployed Hue using official docker image but I do have an issue when using the FileBrowser. 
The upload process works well if file is smaller than exactly 1MB, otherwise I get an error returned by Nginx : 413 Request Entity Too Large

No logs on Hue Server logs.
Am I the only one and how can I change this limit ?

Hue version 4.7.1 deployed on k8s.
![Capture d’écran 2021-01-06 à 14 37 44](https://user-images.githubusercontent.com/10685391/103774755-5c773a00-502d-11eb-8d60-0a727a004fa0.jpg)

Please note that I have no problem uploading big files using Ambari File view or CLI, which means that the error is linked to Hue only.

Thanks

**Comment by JulianBlin** [comment]
Could be related to Nginx limitation : https://www.tecmint.com/limit-file-upload-size-in-nginx/ 

I guess I am not the only one to have the issue ? Everyone using docker image should be concerned ?!

**Comment by romainr** [comment]
Could put 100MB or 0 for `client_max_body_size 100M;` in deed.

The nginx config for the Docker image is https://github.com/cloudera/hue/blob/master/tools/docker/nginx/nginx.conf#L10

Would you like to patch it, rebuild and confirm?

**Comment by JulianBlin** [comment]
Sorry for the late update but it was actually a bad configuration on Ingress side (hue was deployed on a Rancher cluster). Not a hue issue.
