### ISSUE TITLE
why Hue/SparkSQL on aws emr runs Tez and Hbase

### ISSUE THREAD

**Issue by oskotsky** [cloudera/hue#1620]
I had issue with running "count" sql statement in spark-sql with Hue. The error was coming from Tez about missing Token in Hbase.   
The same query runs just fine over spark-sql cli. Could you please explain or point to some resources which show why we see Tez/Hbase involved while running spark-sql over Hue? Or this is some miss configuration and needs to be fixed.

**Comment by romainr** [comment]
You might face some issues if not using the very latest Hue. Here is a very recent blog demoing a setup that works well: https://gethue.com/blog/querying-spark-sql-with-spark-thrift-server-and-hue-editor/

**Comment by oskotsky** [comment]
the latest AWS EMR 5.32 which I am running, installs Hue 4.8 (4 months old released). In hue.ini I see recommended configuration for spark-sql:

[[[sparksql]]]
      name = SparkSql
      interface = hiveserver2

This is misleading as hiveserver2 submits sql queries as a hive mapreduce job, not SparkSQL per se. This is why I see Tez in log files. Am I correct here? If so, how to configure Hue to work with SparkSQL sql engine, like over Spark thrift server or something like that?

**Comment by Akhilsnaik** [comment]
https://gethue.com/blog/querying-spark-sql-with-spark-thrift-server-and-hue-editor/

**Comment by oskotsky** [comment]
It seems like I am missing something here. Your configuration specifies hiveserver2 connector for sparksql. But hiveserver2 is not the same as spark thrift server (STS). This is why I see different execution over spark-sql and Hue spark sql. Please correct me if I got something wrong.

**Comment by oskotsky** [comment]
the answer to my question:

Spark thrift server on aws emr uses port 10001 by default. Thus setting "sql_server_port=10001" fixes the issue.

On the other hand, aws emr uses port 10000 for hive. That is why Hue's default documentation was bringing up Hive instead of SparkSQL.

**Comment by romainr** [comment]
:+1:
