### ISSUE TITLE
TUMBLE function autocomplete

### ISSUE THREAD

**Issue by romainr** [cloudera/hue#1629]
This is one of the major functions.

#1 Adding to the autocomplete
#2 Check if can add to the right assist Function panel (e.g. like with the Hive dialect)

TUMBLE
https://ci.apache.org/projects/flink/flink-docs-release-1.12/dev/table/sql/queries.html#group-windows

https://ci.apache.org/projects/flink/flink-docs-stable/dev/stream/operators/windows.html#tumbling-windows

https://docs.gethue.com/developer/parsers/#syntax-highlighting

**Comment by romainr** [comment]
Step .1 is done? Should we follow-up in another jira?

**Comment by Akhilsnaik** [comment]
Step-1 is done
Working on Step-2
