### ISSUE TITLE
cant't add sqoop job

### ISSUE THREAD

**Issue by fly3q** [cloudera/hue#163]
the chrome report like this
sqoop.js:216 Uncaught TypeError: undefined is not a function

/data/opt/cloudera/parcels/CDH-5.3.2-1.cdh5.3.2.p0.10/lib/hue/apps/sqoop/static/js/sqoop.js:

**Comment by romainr** [comment]
Yes, https://issues.cloudera.org/browse/HUE-2579 missed CDH5.3.3, it will be fixed in C5.3.4 and C5.4.0
