### ISSUE TITLE
Execute hive sql error

### ISSUE THREAD

**Issue by roywang1985** [cloudera/hue#165]
I have install hue3.7.0,and I can read database in Hive Editor.
But when I execute one sql in Query Editor,finally got error msg.

Fetching results ran into the following error(s):
'NoneType' object has no attribute 'values'

It seems something error in python?
I use Python2.6

**Comment by romainr** [comment]
Please use the mailing list for the problem of setups: http://groups.google.com/a/cloudera.org/group/hue-user
