### ISSUE TITLE
hue-4.8.0 how to switch to chinese

### ISSUE THREAD

**Issue by victorvli** [cloudera/hue#1667]
Although I finally switch hue to Chinese through many efforts, I still have some questions.

1. Is it nesessary to change the value of 'LANGUAGE_CODE' to 'zh-CN' in desktop/core/src/desktop/settings.py since I can change language preference in 'My Profile' page through web ui?
2. Is it nesessary to run "make locales"? If yes, does this operation have causal relationship with operation 1?
3. I've changed language preference to "simplified chinese" and update user. But if I open a private window or change another browser, the language preference is still "english" or even "german". Is the setting persisted?

**Comment by romainr** [comment]
As a user you should not need to do anything, Hue will follow your Browser language preferences. Some translations might be missing though, and the .po files would need to be translated and then compiled via `make locale`.

https://docs.gethue.com/administrator/configuration/server/#language

**Comment by victorvli** [comment]
After execute command "make locales", there're many .po files which have been modified. Should I commit all changes to my own project which is forked on hue?

**Comment by romainr** [comment]
Yes, just in case (even if most of them will only have headers re-generated, at least it will be in sync with the actual strings in the code)

**Comment by victorvli** [comment]
BTW, is there any api to add user and list all users?

**Comment by romainr** [comment]
Have you check the website? https://docs.gethue.com/developer/api/

**Comment by victorvli** [comment]
Yes, this doc contains how to make user admin, change user passoword and etc. But I'm looking for how to
**1. add single user
2. add batch users
3. list all users**
I don't find any of it in this doc. :(
