### ISSUE TITLE
Support async execute in SqlAlchemy API

### ISSUE THREAD

**Issue by romainr** [cloudera/hue#1681]
Looking at polling in pyhive https://github.com/dropbox/PyHive#db-api-asynchronous, seems like a clean way would be to submit execute() with async_=True and use poll().operationState.

**Comment by agl29** [comment]
What is the actual problem and i.e. what thing we want? 
And we need to integrate async_=Ture and poll().operationState here https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py#L232 ?

**Comment by romainr** [comment]
It would be simpler to start first with https://github.com/cloudera/hue/issues/1682

Yes, we want to add an `is_async` property to sqlalchemy dialects, so that we can chose to execute statements in non blocking mode.
