### ISSUE TITLE
Support get_logs in SqlAlchemy API

### ISSUE THREAD

**Issue by romainr** [cloudera/hue#1682]
Looking at polling in pyhive https://github.com/dropbox/PyHive#db-api-asynchronous, seems like a clean way would be to submit execute() with async_=True and use poll().operationState.

**Comment by agl29** [comment]
I think for the get_log we are talking about this https://docs.sqlalchemy.org/en/13/core/engines.html#dbengine-logging.
I was trying it but I was able to print on the shell (like create_engine("sqlite://", **echo=True**)  but not captured it.

**Comment by romainr** [comment]
Yes, it will obviously depend on the SQL dialect and connector. So would recommend to test with Hive.

**Comment by agl29** [comment]
I changed the interface for hive
`
    [[[hive]]]
      name=Hive
      interface=sqlalchemy
      options='{"url": "hive://localhost:10000/default"}'`
     
And change the create_engine line from `create_engine(URL,  **options)`  to `create_engine(url, echo=True, echo_pool='debug', **options)`

getting output in the shell 
<img width="1792" alt="Screenshot 2021-02-09 at 6 58 02 PM" src="https://user-images.githubusercontent.com/36241930/107370612-37cd2100-6b09-11eb-9f38-2195f417ed55.png">

but not able to capture in the get_log function.

**Comment by romainr** [comment]
Just call it?

Right now we don't do anything https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py#L396

Look at the get_log() call in the Chrome XHR, it will add the logs in the Log panel of the editor.

Best way it to manually call the cursor.fetch_logs() via the SqlAlchemy in a shell first like described in above link.

Then add a test https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy_tests.py

Then add the `cursor.fetch_logs()` to `fetch_logs()`
