### ISSUE TITLE
Describe Function autocomplete for flink

### ISSUE THREAD

**Issue by Akhilsnaik** [cloudera/hue#1683]
Describe the bug: Currently Describe Function is not autofilled in flink editor , This should be added to flink editor.
reference for Describe function 
Syntax : `DESCRIBE [catalog_name.][db_name.]table_name `
Reference for Describe : https://ci.apache.org/projects/flink/flink-docs-stable/dev/table/sql/describe.html#describe-statements

Steps to reproduce it? 
Issue is reproducable in the master branch

Hue version or source? 
Latest build from msater branch

**Comment by romainr** [comment]
It is probably a simple mess-up here https://github.com/cloudera/hue/blob/b682f4b5c6cccd4ca874cd1b88cb83ca23dfcdf9/desktop/libs/notebook/src/notebook/connectors/flink_sql.py#L291

**Comment by romainr** [comment]
Where we use the column names instead of the row values :)
