### ISSUE TITLE
Documentation changes: Maybe a typo and link not working

### ISSUE THREAD

**Issue by Harshg999** [cloudera/hue#1689]
Going through the development section of the docs,  Documentation link seems broken below [Blog & Website
](https://docs.gethue.com/developer/development/#blog--website)

Also, looks like [Sump-up](https://docs.gethue.com/developer/development/#sump-up) is a typo and the intended heading might be different. If not, then what does it mean?

**Comment by romainr** [comment]
Nice, could you just fix the anchor links?

e.g. `build it` --> #documentation-1


:+1: to fix the `Sump` typo too!
