### ISSUE TITLE
Move '?' Show Editor help to the '...' Menu

### ISSUE THREAD

**Issue by romainr** [cloudera/hue#1707]
![image](https://user-images.githubusercontent.com/17945/106153111-0c266000-6133-11eb-885a-26003d82696c.png)

e.g. Below 'Queries'

**Comment by romainr** [comment]
@Harshg999

**Comment by romainr** [comment]
Also in a follow-up PR --> Moving 'Database' text to a tooltip, e.g. 'Database hue'

**Comment by Harshg999** [comment]
> ![image](https://user-images.githubusercontent.com/17945/106153111-0c266000-6133-11eb-885a-26003d82696c.png)
> 
> e.g. Below 'Queries'

Should the new heading be 'Editor Help' ? Because '?' below 'Queries' might not look good.

**Comment by romainr** [comment]
:+1: for just 'Help' 
and by ? I meant the icon

**Comment by Harshg999** [comment]
Reopen #1710 for the follow-up PR

**Comment by Harshg999** [comment]
> Also in a follow-up PR --> Moving 'Database' text to a tooltip, e.g. 'Database hue'

This means that when hovering on 'hue', it should show 'Database hue' instead of just 'hue' right ?

**Comment by romainr** [comment]
:+1: 

The idea is to avoid any ambiguity subtly without polluting the interface when not needed/ in use.
