### ISSUE TITLE
Presto JDBC returns 1000 only rows  [1000 record limitation]

### ISSUE THREAD

**Issue by sivankumar86** [cloudera/hue#1726]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
https://gethue.com/custom-sql-query-editors/

Describe the bug:
    Would like to download entire results in csv or other format in presto-editor

Steps to reproduce it?
 1. Launch emr 5.30.1 or latest version (Hue 4.6.0) 
 2. Open presto-editor
 3. Run a select query which have more than 1000 rows 
 4. you can download only 1000 rows

Hue version or source? Hue 4.6.0

It is JDBC connector limitation , is there a plan to implement stream the entire results in Hue for JDBC ?

NOTE: JDBC interface 1000 record limitation

We are working on lifting this restriction in an upcoming release.

**Comment by michelle37** [comment]
Tested both Hue 4.4.0 and 4.6.0 they all have limitations to download more than 1000 record. Is this something we will see changes in the next release?

**Comment by sivankumar86** [comment]
adding further info. It works in Hue 4.4.0 but, broken in >4.6.0. I could see , download api has been reformatted after 4.4.0.

https://github.com/cloudera/hue/blob/release-4.4.0/desktop/libs/notebook/src/notebook/connectors/base.py#L433

**Comment by sivankumar86** [comment]
adding further info. It works in Hue 4.4.0 but, broken in >4.6.0. I could see , download api has been reformatted after 4.4.0.

https://github.com/cloudera/hue/blob/release-4.4.0/desktop/libs/notebook/src/notebook/connectors/base.py#L433

**Comment by lijc210** [comment]
I also encountered this bug in version 4.8

**Comment by dev-ops-hub** [comment]
Hi, i would like to find out if the issue solved? I also have the same issue when query using jdbc

**Comment by mrdominguez** [comment]
@romainr @adrianyavorskyy @bjornalm Folks, are there any plans to add pagination support to the JDBC interface?

Ref:
https://issues.cloudera.org/browse/HUE-3419

https://gethue.com/custom-sql-query-editors/
> NOTE: JDBC interface 1000 record limitation
>❗️ Currently the JDBC interface does not support pagination of results. As such, Hue limits the result sets from JDBC data sources to 1000 records. We are working on lifting this restriction in an upcoming release.

**Comment by bjornalm** [comment]
@JohanAhlen do you know anymore about this?
