### ISSUE TITLE
HTTPConnectionPool(host='localhost, port=8998): Max retries exceeded with url: /sessions (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))

### ISSUE THREAD

**Issue by kingvip** [cloudera/hue#1728]
浏览器打开服务的报错信息HTTPConnectionPool(host='localhost, port=8998): Max retries exceeded with url: /sessions (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by romainr** [comment]
https://docs.gethue.com/administrator/configuration/connectors/#apache-livy
