### ISSUE TITLE
Polish Presentation mode

### ISSUE THREAD

**Issue by Harshg999** [cloudera/hue#1729]
Describe the bug: 
Presentation Mode in demo.gethue.com is bugged.

Steps to reproduce it?
- Go to demo.gethue.com
- Run a query
- Open presentation mode
<img width="1542" alt="Screenshot 2021-02-03 at 6 38 22 PM" src="https://user-images.githubusercontent.com/42064744/106751305-00fd9380-664f-11eb-90e8-d94345e21919.png">

- Above is when we are in presentation mode and by clicking 'X', we exit presentation mode.
- We cant edit the query too like we used to do before in previous mode.

**Comment by romainr** [comment]
Thanks @Harshg999 !

This brings a good point if it should stay read only or not, or at least in v1. Concept: one and only one location where to edit to keeo simple.

For sure we need to update the styling a bit to feel cleaner/leaner (e.g. unify close button to be like expand, scroll back to top/left etc...), show on hover etc and noticing that empty titles are ugly 'Add -- comments...'.

@JohanAhlen

**Comment by romainr** [comment]
And probably:


Keep | Exec/stop all |  
-- | -- | --
  | Vars |  
  | 10 rows height |  
  | Download/Copy |  
  |   |  
  | Titles --> auto add -- <Tables> |  
  | Open as Preso? |  
  |   |  
Drop | Edit |  
  | Show/hide code? |
