### ISSUE TITLE
How to configure beeswax to use user and password to connect to hiveserver2?

### ISSUE THREAD

**Issue by mbanduk** [cloudera/hue#174]
How to aloow beeswax to connectto hiveserver2 having a PasswdAuthenticationProvider class and ``hive.server2.custom.authentication.class`` set in the hive-default.xml?

```
<property>
  <name>hive.server2.custom.authentication.class</name>
  <value>com.mycompany.hive.service.Authenticator</value>
</property>
```

**Comment by erickt** [comment]
Hello @mbanduk. Questions like this are more appropriate on the [hue-user](https://groups.google.com/a/cloudera.org/forum/#!forum/hue-user) mailing list. That said, I believe this is the [documentation](http://gethue.com/how-to-use-hue-with-hive-and-impala-configured-with-ldap-authentication-and-ssl/) you are looking for.
