### ISSUE TITLE
Un-expand Menu action full width clikable

### ISSUE THREAD

**Issue by romainr** [cloudera/hue#1750]
For some reason, only the right half is clickable. This prevent expanding, un-expanding without moving the mouse.

![image](https://user-images.githubusercontent.com/17945/107286229-24d92480-6a15-11eb-8634-88968d6bd8f6.png)

**Comment by Harshg999** [comment]
The space left which is not clickable to un-expand is a 'div' element for version number
https://github.com/cloudera/hue/blob/941ae313fa050286018253fe64bcc7672053babc/desktop/core/src/desktop/js/components/sidebar/Sidebar.vue#L78

Removing it and sending the PR.
