### ISSUE TITLE
Hue Access Encrypted S3 Bucket

### ISSUE THREAD

**Issue by alericmckearn** [cloudera/hue#1757]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:
Hue can't access a file that is protected by sse-kms

Steps to reproduce it?

S3 bucket with sse-kms encryption
add file to s3 bucket
Open file in S3 browser 

[Errno 22] Bad Request

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
Hue 4.7

**Comment by alericmckearn** [comment]
it looks like 4.9 is still using boto2.46 and i don't see a place to put the sse-kms headers in get_key

**Comment by romainr** [comment]
Indeed, 2 possible ways:

1. backport it to Hue (we kind of need to clone the boto2 repo anyway cf. https://github.com/cloudera/hue/issues/1756)
2. investigate porting to boto3 or AWS JS SDK (there is a plan to rewrite the File Browser UI with Vue.js in ~Q2 2021, might be a good timing to revisit the API as well

.1 is probably the shortest for now, maybe there is a pull request in the official boto repo already too

**Comment by alericmckearn** [comment]
would you be open to mixing boto3 and boto2?  i think i can rewrite this section of the aws api in boto3

**Comment by romainr** [comment]
:+1: This could be also a good way to start the transition.

I see boto 2 should not conflict with boto3 as they have 2 different names, so it seems doable to ship both and do what you said.

For the record where the modules are:

- https://github.com/cloudera/hue/tree/master/desktop/core/ext-py (Python2)
- https://github.com/cloudera/hue/blob/master/desktop/core/requirements.txt (Python3)

**Comment by alericmckearn** [comment]
and nevermind then since the namespaces are different

**Comment by alericmckearn** [comment]
okay, i'll throw a design together as there are a lot more options than there were and post it here.

**Comment by kauaygor** [comment]
NAO VAI DERRUBAR TAO FACIL BBB RUIM

Em ter, 9 de fev de 2021 15:27, jkm <notifications@github.com> escreveu:

**Comment by alericmckearn** [comment]
so it looks like the following will be changed:
- [client.py](https://github.com/cloudera/hue/blob/master/desktop/libs/aws/src/aws/client.py) - upgrade from boto to boto3 drop the concept of "connection" as most functions operate directly off of client
- conf.py - any new settings
- s3_file.py - shift to client.get_object_v2
- s3fs.py - directly use the client - leave notes about future UI changes for extra configs for things like create bucket
- s3stat.py - no changes
- upload.py - change to use the client

Out of scope Items - 
- cleaning up the file naming standards
- adding any extra options from the api into the UI

**Comment by alericmckearn** [comment]
@romainr need some help with a test.  i don't currently have any proxies set up so i can't test whether the botocore setup allows username:password in a proxy setup

`import boto3
from botocore.config import Config
region = "us-east-1"
proxy_list = {'http': '<username>:<password>@<hostname>:<port>'}

boto_config = Config(
    region_name = region,
    retries = {
        'max_attempts': 10,
        'mode': 'standard'
    },
    proxies = proxy_list
)

kwargs = {
   'config': boto_config
}
client = boto3.session.Session(profile_name="<local_profile>").client("s3", **kwargs)

foo = client.head_bucket(Bucket="<bucket_name>")
print(foo)`

this commit is pretty vague about what is allowed => https://github.com/timuralp/botocore/commit/9ca81fbc4e09687254693ac086d61a478e9f2db3

**Comment by romainr** [comment]
Thanks, the scope looks fair. About the proxy I don't have any handy and I am not sure how much it is used. For me for now we could add a note that this option was not tested in this first of the migration (I don't recall when the feature was added, might be visible in https://github.com/cloudera/hue/commits/master/desktop/libs/aws/src/aws/conf.py).

**Comment by romainr** [comment]
@ranade1 FYI
