### ISSUE TITLE
Docker Container Executor

### ISSUE THREAD

**Issue by emmanuelmathot** [cloudera/hue#176]
Is the integration of Docker Container Executor planned into Hue?

**Comment by romainr** [comment]
It is not planned for now, we recommend installing Hue like a regular webserver

**Comment by emmanuelmathot** [comment]
I think you misunderstood my request. I was talking about the executor: http://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/DockerContainerExecutor.html

I imagine it could be an action available in workflow editor.
Thank you for your prompt reply.

**Comment by romainr** [comment]
Ho I see!

This is the same as running a MapReduce (or Java) action indeed, so it should work out of the box!
