### ISSUE TITLE
Hive data warehouse has no response/ lost connection with the main server

### ISSUE THREAD

**Issue by ThuyenP** [cloudera/hue#1760]
I used the demo for Hive last Saturday and it still worked. But then it stops and disconnects with the main server since last Sunday. Can you fix it? Thank you.

**Comment by romainr** [comment]
Thanks for the report!
There is a lot of usage and the Hive server regularly blows up. It will now reboot everyday to avoid hanging/limbo for a week.

**Comment by ThuyenP** [comment]
Thank you so much for fixing it!
