### ISSUE TITLE
Release 3.8.0

### ISSUE THREAD

**Issue by oflebbe** [cloudera/hue#177]
Sorry i am confused ...

* The commit 5774b660d9d99613cbf865220d81b69c5d18ca59  is missing from the release-3.8.0 , so the pom.xml in apps/spark/java/*/pom.xml read 3.7.0-SNAPSHOT

* May I kindly ask which git entry corresponds to https://dl.dropboxusercontent.com/u/730827/hue/releases/3.8.0/hue-3.8.0.tgz (the announced tarball in the blog).
  At first sight commit 7289d4984c3ae55315e8f67c6ccc4d52275be397 (aka  HUE-2654) is missing.

Scratching my head which download I should use for Apache Bigtop ...

**Comment by romainr** [comment]
Sorry about this!

At first for item 1, I can see it: https://github.com/cloudera/hue/commits/branch-3.8

I would forget about the github tgz link, this link to the sources of the repo only, not the compiled release.

I created a new 3.8.0 tarball, and checked that it contained HUE-2654: https://www.dropbox.com/s/s7g4zoq52zgxxu4/hue-3.8.0.tgz?dl=0

Will replace the official tarball with this one.

**Comment by romainr** [comment]
Will also prepare a 3.8.1: https://github.com/cloudera/hue/issues/178

**Comment by oflebbe** [comment]
Is a dropbox link really suitable for delivering a release?

**Comment by romainr** [comment]
3.8.1 release is out https://github.com/cloudera/hue/tree/release-3.8.1 with a tarball link in http://gethue.com/hue-3-8-with-an-oozie-editor-revamp-better-performances-improved-spark-ui-is-out/

**Comment by oflebbe** [comment]
Thank you very much!! Bigtop patch is ready by now: BIGTOP-1850
