### ISSUE TITLE
Hue 3.8.0 - Map reduce job in workflow is not using the job properties

### ISSUE THREAD

**Issue by searchwizard** [cloudera/hue#179]
Mapreduce job as part of a workflow is not submitting the job properties to oozie/yarn. When I submit the following as part of a workflow, I am getting an exception about the output dir. Similar job in Job Designer is succeeding with out any issues.

```
Failing Oozie Launcher, Main class [org.apache.oozie.action.hadoop.MapReduceMain], main() threw exception, Output directory not set in JobConf.
  org.apache.hadoop.mapred.InvalidJobConfException: Output directory not set in JobConf.
  at org.apache.hadoop.mapred.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:118)
  at org.apache.hadoop.mapreduce.JobSubmitter.checkSpecs(JobSubmitter.java:460)
  at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:343)
  at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1285)
```

![image](https://cloud.githubusercontent.com/assets/6089654/7355678/73944ed0-ecf1-11e4-822a-f0282950267b.png)

On a side note, is there a way to export the oozie workflow xml ? I don't see it in 3.8.0, I have it in my existing 3.7.1 installation?

Also, the import feature is missing
![image](https://cloud.githubusercontent.com/assets/6089654/7355880/b1a2a5b8-ecf2-11e4-985c-3c3964ac2dee.png)

**Comment by romainr** [comment]
This should be independent of Hue if you see the correct properties in the XML of the workflow when submitting it? This is typical of a mix of new/old API, did you upgrade the Oozie Sharelib too?

Note that you can edit/re-submit it directly from File Browser: http://gethue.com/hadoop-tutorial-submit-any-oozie-jobs-directly-from/

About the export/import, a better solution is underway with
http://gethue.com/export-and-import-your-oozie-workflows/
https://issues.cloudera.org/browse/HUE-1660

**Comment by searchwizard** [comment]
XML of the workflow doesn't have the properties I specified in my action. 

```
<action name="mapreduce-2db4">
        <map-reduce>
            <job-tracker>${jobTracker}</job-tracker>
            <name-node>${nameNode}</name-node>
            <file>/user/skk/jars/coolhadoop.jar#coolhadoop.jar</file>
        </map-reduce>
        <ok to="End"/>
        <error to="Kill"/>
    </action>
```

If I just execute a M/R job from the job designer without going through the workflow editor, the definition looks like the following and my job is succeeding. 
```
<map-reduce>
    <job-tracker>${jobTracker}</job-tracker>
    <name-node>${nameNode}</name-node>
    <configuration>
        <property>
            <name>mapreduce.mapper.class</name>
            <value>cool.hadoop.TokenizerMapper</value>
        </property>
        <property>
            <name>mapreduce.reducer.class</name>
            <value>cool.hadoop.IntSumReducer</value>
        </property>
        <property>
            <name>mapred.input.dir</name>
            <value>/user/skk/data</value>
        </property>
        <property>
            <name>mapred.output.dir</name>
            <value>/user/skk/pig-out/${outdir}</value>
        </property>
    </configuration>
    <archive>/user/skk/jars/coolhadoop.jar#coolhadoop.jar</archive>
</map-reduce>
```

**Comment by searchwizard** [comment]
If I edit the Workflow xml saved in HDFS with the configuration and property entries and submit it, the workflow is succeeding.

**Comment by romainr** [comment]
This is indeed a bug, thanks a lot for the report!

A fix is on the way: https://review.cloudera.org/r/5179/

**Comment by romainr** [comment]
Fix is in 3.9 and upcoming 3.8.1: https://github.com/cloudera/hue/commit/4ebef116615510103e603e93e6a905217f8d9906

**Comment by searchwizard** [comment]
Thanks for the quick response. When are you releasing 3.8.1?

**Comment by romainr** [comment]
Let's do it at the end of this week!

**Comment by searchwizard** [comment]
Applied the patch in my system. It works great. Thanks

**Comment by fabricebrito** [comment]
will Cloudera update the quickstart VM with this patch?

**Comment by romainr** [comment]
When C5.4.1 is released (1-2 weeks), the VM is usually updated just after. 

Would you need help to patch it yourself?

**Comment by fabricebrito** [comment]
Hello! Thanks but it's really easy to patch :-)
If you'll be doing a new release, can you add the export/import oozie workflow functionality you have on gethue.com ?

**Comment by romainr** [comment]
The import/export is changing, see those post for more info:

http://gethue.com/new-apache-oozie-workflow-coordinator-bundle-editors/
http://gethue.com/export-and-import-your-oozie-workflows/

**Comment by sonupsp3** [comment]
Hi romainr,

I'm using CDH 5.4.0, Hue 3.7 and i'm facing the same issue. Can you please help me in applying patch.

Thanks,

**Comment by romainr** [comment]
Are you using CM?
If yes I would recommend to upgrade to the minor upgrades like 5.4.7. I can send you a text patch other wise but it might be tricky

**Comment by gangele397** [comment]
Same bug exist in java action i have create the java action and passing my properties like below
          <configuration>
                <property>
                    <name>hadoop.custom.configuration.file</name>
                    <value>/usr/hdp/current/spark-client/Merge_Json/conf/jsonmerger-dev.conf</value>
                </property>
                <property>
                    <name>yyyymmdd</name>
                    <value>20150921</value>
                </property>
still java program not able to find these properties, when I run from command line passing system property with -D its working fine.

looks like same issue.

**Comment by sonupsp3** [comment]
Hi, Thanks for the reply, 
Yes, I'm using CM but i can't upgrade because this is my pre-prod enviroment.

**Comment by sonupsp3** [comment]
Hi romainr,
If i try to run hue-oozie spark job, Getting the below error aftersubmitting. Can you please help me in adding credentials i didn't find any credentials for spark, Thanks
Failing Oozie Launcher, Main class [org.apache.oozie.action.hadoop.SparkMain], main() threw exception, Delegation Token can be issued only with kerberos or web authentication.

**Comment by romainr** [comment]
Please use another issue or follow-up on the thread you already started https://groups.google.com/a/cloudera.org/forum/#!topic/hue-user/HDv9UFfo11A
