### ISSUE TITLE
Results not visible in Notebook table format

### ISSUE THREAD

**Issue by joemonaghan-iw** [cloudera/hue#1792]
## Bug
Hue intermittently shows results in table format for a Notebook. It has shown to happen when the user executes a query in a Notebook (first time it works) then executes a query in the Hive editor and then returns to the Notebook. When they execute a query after returning to the Notebook the issue happens. The image below shows what happens when you first execute a query on the Notebook(results in table format as expected):

![Screenshot 2021-02-12 at 16 52 32](https://user-images.githubusercontent.com/51318825/108348157-543c1e00-71d9-11eb-8f9c-197d8faedebf.png)

However, after returning to the Notebook (as described above) and executing the same query (or any other query) the following happens:

![Screenshot 2021-02-12 at 16 47 37](https://user-images.githubusercontent.com/51318825/108348136-4dada680-71d9-11eb-8c3a-1cb4e77369db.png)

## Hue version: 4.8.0

No logs appear on the browser console or on the server logs for this issue.

**Comment by romainr** [comment]
Yes, those are old flaky issues like this in Editor 1. Editor 2 is coming this year without those.
It runs on beta at demo.gethue.com/

**Comment by joemonaghan-iw** [comment]
Hi, @romainr thanks for your response. Will update when Editor 2 is available.

**Comment by sumtumn** [comment]
Hi, I am using Hue 4.10.0, and I find this issue still exists, so Editor2 is not available in 4.10.0? And what about 4.11 ?

**Comment by bjornalm** [comment]
Hi @sumtumn, editor v2 is now (current master branch) available behind feature a flag called "enable_hue_5=true" in the file desktop/conf/pseudo-distributed.ini under section [desktop]. Previously the flag was called "enable_notebook_2" but I'm not sure if it was supported in 4.10, you can try and have a look. Just update the config and restart Hue.
