### ISSUE TITLE
Hue 3.8.0 - Number of jobs badge next to the job browser link is not showing up

### ISSUE THREAD

**Issue by searchwizard** [cloudera/hue#180]
In 3.7.1, After submitting a job, there is a badge that appears next to the "Job Browsers" link.

![image](https://cloud.githubusercontent.com/assets/6089654/7377282/69f0948e-edb3-11e4-8c33-f2901a8c9330.png)

The badge is not showing up in 3.8.0 after submitting new jobs:
![image](https://cloud.githubusercontent.com/assets/6089654/7377250/358e571c-edb3-11e4-9a16-1fd5277ed63e.png)

**Comment by enricoberti** [comment]
Fixed! https://github.com/cloudera/hue/commit/db4223f913e16116f527d8dde9a400340ddddc52

Thanks!

**Comment by romainr** [comment]
Fixed in 3.9 and 3.8.1

**Comment by searchwizard** [comment]
Applied the patch in my system. It works great. Thanks
