### ISSUE TITLE
Hue 3.8.0 - Not getting prompted for parameters when a Sqoop design is submitted

### ISSUE THREAD

**Issue by searchwizard** [cloudera/hue#182]
When I submit a sqoop design with a parameter, I am not getting a prompt for the parameter value. Job is getting submitted with the $PARAM as it is.

![image](https://cloud.githubusercontent.com/assets/6089654/7396392/95031abe-ee6e-11e4-878a-e18092bb5f58.png)

**Comment by searchwizard** [comment]
I just noticed that the prompt is coming up only if the parameter is part of the prepare step. If I add the following, it works

![image](https://cloud.githubusercontent.com/assets/6089654/7396714/5539d8de-ee71-11e4-803b-181d48d65098.png)

**Comment by searchwizard** [comment]
Does a workflow from the workflow editor supposed to prompt for the parameters? I have a simple workflow and its not prompting for parameters. Thanks.

**Comment by romainr** [comment]
Yes it should, cf. oozie examples and http://gethue.com/new-apache-oozie-workflow-coordinator-bundle-editors/

Where did you put the ${parameter}?

**Comment by searchwizard** [comment]
1. From Job Designer: My parameter is part of the sqoop command. In this case, I am only getting the prompt if the parameter is also part of the "Prepare" Step.
2. From Workflow Editor: My parameter is part of the sqoop command. I couldn't get this working at all.

Example sqoop command I am using:
```
import --as-avrodatafile --null-string "" --null-non-string "" --fields-terminated-by \001 --escaped-by \\ --compress --num-mappers 1 --connect jdbc:oracle:thin:@xxxxxx:xxxx/xxxx --username xxxxx --password xxxx --table ${Table} --target-dir /user/skk/sqoop/${Table}
```

**Comment by searchwizard** [comment]
I observed the following today:

For the same workflow - If I go to File browser, select the workflow xml and submit it, its prompting for the parameter value. But If I submit it from the workflow editor, it's not asking for parameter.

Thanks.

**Comment by romainr** [comment]
It works fine for me in the new editor, e.g. https://www.dropbox.com/s/gilgpoo8a0oh9sp/oozie-sqoop-demo.ogv?dl=0

**Comment by searchwizard** [comment]
Thanks for the screen cast. I saw your video and I tried the exact step and it didn't prompt me for the parameter. Any suggestions on how to debug this? Thanks.

**Comment by romainr** [comment]
I am using Hue master, I just tried 3.8 and indeed it is missing 78b8334b305662c88f22170aacce547e425a939a I just put it to 3.8.1 too

**Comment by searchwizard** [comment]
Awesome. This works great.
