### ISSUE TITLE
Hue 3.8.0 - Coordinator schedule is getting reset to "day 0:0" after saving

### ISSUE THREAD

**Issue by searchwizard** [cloudera/hue#183]
After saving a coordinator, the frequency is getting reset to "day 0:0"

I selected

![image](https://cloud.githubusercontent.com/assets/6089654/7399400/a8192e3a-ee83-11e4-86e0-62e138ad3d55.png)

After saving, it went back to:

![image](https://cloud.githubusercontent.com/assets/6089654/7399363/4e37f572-ee83-11e4-9f6b-553b877f0622.png)

**Comment by romainr** [comment]
This is https://issues.cloudera.org/browse/HUE-2717

**Comment by enricoberti** [comment]
And fixed!  https://github.com/cloudera/hue/commit/05e23ee235812e6e6c526d92fad547ad02fb7c23

**Comment by searchwizard** [comment]
Applied the patch on my side and it works great. Thanks.
