### ISSUE TITLE
urllib.unquote error exposed by Python 3 runtime when extracting zip file or compressing file in File Browser

### ISSUE THREAD

**Issue by rickb78** [cloudera/hue#1833]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? No

Describe the bug:

User attempts to extract a zip file in the File Browser, or attempts to compress a file in the File Browser.  User is presented with error:

"Exception occurred while extracting archive: module 'urllib' has no attribute 'unquote'"

Steps to reproduce it?

2 ways:

1)  Attempt to extract a zip file in the File Browser
2)  Attempt to compress a file in the File Browser

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

Hue 4.7+

**Comment by rickb78** [comment]
Added fix as part of PR for #1799 fix as well.  urllib.unquote needs to be converted to urllib_unquote in Filebrowser views.py.

https://github.com/cloudera/hue/pull/1810

**Comment by romainr** [comment]
Nice, thanks Rick! Just could we do it in a separate PR? (to avoid mix&matching apples and oranges ;))

**Comment by rickb78** [comment]
@romainr , fixed that here:

https://github.com/cloudera/hue/pull/1841

**Comment by romainr** [comment]
Excellent, thank you Rick!
