### ISSUE TITLE
[Hue3.7.1][filebrowser][change file permissions dialog]

### ISSUE THREAD

**Issue by yushaopeng** [cloudera/hue#184]
When I perform the changing file permission action on a file which permission is -rwxrwxrwx, I just do nothing except click the submit button, but the file's execution permission is missing(-rw-rw-rw-), It seems that the execute checkbox is set "disabled", when the form is submitted the execute checkbox's value is not submitted

**Comment by romainr** [comment]
HDFS files don't have the x permission (it does not make sense in HDFS), so this is normal
