### ISSUE TITLE
Filebrower fails to auto-decompress in Python 3 runtime

### ISSUE THREAD

**Issue by rickb78** [cloudera/hue#1851]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?  No

Describe the bug:

gz, bz2, avro and other compressed files are supposed to be auto-detected and automatically decompressed when the user tries to view them.  However, in Python 3 runtime, when a user tries to open these compressed files, they are presented with the binary representation of the file, not the decompressed file contents.

Steps to reproduce it?

Try to open a gz, bz2, or avro file from the File Browser when using a Python 3 runtime.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

Hue 4.7+

**Comment by rickb78** [comment]
The following PR fixes the detection of the file types, which is the first problem, as the strings need to be treated as bytes in Python 3 to be able to be compared against the file contents:

https://github.com/cloudera/hue/pull/1852

However, this doesn't fix this entirely.  Once the files are properly detected, decompression of the files fails for an as-yet unknown reason.

**Comment by rickb78** [comment]
Updated the PR to include a fix for auto-decompression of gz, bz2, and avro files in Python 3 runtime.  https://github.com/cloudera/hue/pull/1852/files

**Comment by romainr** [comment]
Thanks @rickb78 !
