### ISSUE TITLE
504 Gateway Time-out after 1min hue with presto

### ISSUE THREAD

**Issue by oskotsky** [cloudera/hue#1853]
I am running Hue/Presto queries on aws emr. query over presto-cli runs just fine. However, if query takes longer than 1 min, Hue interface throws error "504 Gateway Time-out 504 Gateway Time-out" and becomes unusable. 
Is there setting which sets timeout to such short time? How can I change it? 

Thank you

**Comment by Akhilsnaik** [comment]
@oskotsky ,
Can you check hue.ini config file and see whats the `query_max_run_time` configured, its default value is 1 min. 
you might need to fine tune the config as needed.
https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L1065
`   # # options='{"url": "presto://username:password@localhost:8080/tpch/default","connect_args":"{\"session_props\": {\"query_max_run_time\": \"1m\"}}"}'`

**Comment by romainr** [comment]
On EMR not sure if sqlalchemt, jdbc etc interfaces are used for the Hue.

Task Server + SqlAlchemy Async execute are active WIP and will solve this issue on blocking/long running queries with SqlAlchemy.

In your case on top of Akhil suggestion probably worth checking the timeout between the Load Balancer and Hue (best guess), and Hue to Presto.

**Comment by oskotsky** [comment]
Thank you so much! It was elb (elastic load balancer) timeout setting. Everything works now!

**Comment by romainr** [comment]
@agl29 just FYI
