### ISSUE TITLE
3.8.1 does not work on zookeeper.rest_url

### ISSUE THREAD

**Issue by so2boy** [cloudera/hue#187]
When we access url like http://localhost/zookeeper/tree/product//,  Django or Browser trims the last '/'. The url changed to http://localhost/zookeeper/tree/product/. The file apps/zookeeper/src/zookeeper/urls.py does not contain suitable urlpattern for that changed url. Because the urlpattern is url(r'tree/(?P<id>\w+)/(?P<path>.+)$', 'tree', name='tree').  The last '+' need to change to '*'. Then I need change some code in apps/zookeeper/src/zookeeper/views.py: def tree(request, id, path),  add '/' before the var path.

**Comment by romainr** [comment]
Thanks! Want to directly submit a pull request?
