### ISSUE TITLE
make[2]: *** [/var/www/hue/desktop/core/build/sasl-0.1.1/egg.stamp] Error 1

### ISSUE THREAD

**Issue by pleamon** [cloudera/hue#188]
I have the all depend

copying sasl/__init__.py -> build/lib.linux-x86_64-2.6/sasl
copying sasl/saslwrapper.py -> build/lib.linux-x86_64-2.6/sasl
running build_ext
building '_saslwrapper' extension
creating build/temp.linux-x86_64-2.6
creating build/temp.linux-x86_64-2.6/sasl
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isasl -I/usr/include/python2.6 -c sasl/saslwrapper.cpp -o build/temp.linux-x86_64-2.6/sasl/saslwrapper.o
gcc: sasl/saslwrapper.cpp：No such file or directory
gcc: No input file
error: command 'gcc' failed with exit status 1
make[2]: *** [/var/www/hue/desktop/core/build/sasl-0.1.1/egg.stamp] Error 1
make[2]: Leaving directory `/var/www/hue/desktop/core'
make[1]: *** [.recursive-install-bdist/core] Error 2
make[1]: Leaving directory `/var/www/hue/desktop'
make: *** [install-desktop] Error 2

**Comment by romainr** [comment]
"gcc: sasl/saslwrapper.cpp：No such file or directory" hum, are you sure all the sasl packages are there?
What is your OS?

**Comment by pacosoplas** [comment]
Hi: I have the same error from centos 7:

[root@xxx.xx.xx.xx hue-3.11.0]# sudo make install
--- Installing core source structure...
--- Installing Desktop core...
INSTALL_DIR=/usr/local/hue make -C desktop install
make[1]: se ingresa al directorio `/opt/hue-3.11.0/desktop'
INSTALL_DIR=/usr/local/hue/desktop/core \
        INSTALL_CONF_DIR=/usr/local/hue/desktop/conf \
        make -C core install-bdist
make[2]: se ingresa al directorio `/opt/hue-3.11.0/desktop/core'
--- Building egg for sasl-0.1.1
running bdist_egg
running egg_info
writing sasl.egg-info/PKG-INFO
writing top-level names to sasl.egg-info/top_level.txt
writing dependency_links to sasl.egg-info/dependency_links.txt
reading manifest file 'sasl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'sasl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building '_saslwrapper' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isasl -I/usr/include/python2.7 -c sasl/saslwrapper.cpp -o build/temp.linux-x86_64-2.7/sasl/saslwrapper.o
sasl/saslwrapper.cpp:21:23: error fatal: sasl/sasl.h: No existe el fichero o el directorio
 #include <sasl/sasl.h>
                       ^
compilación terminada.
error: command 'gcc' failed with exit status 1
make[2]: *** [/opt/hue-3.11.0/desktop/core/build/sasl-0.1.1/egg.stamp] Error 1
make[2]: se sale del directorio `/opt/hue-3.11.0/desktop/core'
make[1]: *** [.recursive-install-bdist/core] Error 2
make[1]: se sale del directorio `/opt/hue-3.11.0/desktop'
make: *** [install-desktop] Error 2

**Comment by pacosoplas** [comment]
I fixed it unistalling my actual lxml version and installing
yum install libxslt-devel libxml2-devel
sudo yum install libxml2 libxml2-devel libxml2-python libxslt libxslt-devel
