### ISSUE TITLE
about to start service

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#190]
Hi:

i want to ask that when i use "build/env/bin/supervisor" the command to start hue service, 
and if i want to stop hue service, i use ctrl+c to stop, it will display error like:

Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1517, in shutdown
    h.close()
  File "/usr/lib64/python2.6/logging/__init__.py", line 716, in close
    _releaseLock()
  File "/usr/lib64/python2.6/logging/__init__.py", line 208, in _releaseLock
    _lock.release()
  File "/usr/lib64/python2.6/threading.py", line 142, in release
    self.__block.release()
KeyboardInterrupt

and sometime it can not stop the service

so i want to ask that if there are other start command and stop command

thanks~~~

**Comment by romainr** [comment]
AFAIK there is no start/stop scripts, so just starting like you do and killing the process if no clean way to terminate. Packages script usually try to clean stop then -9 stop processes

**Comment by AddQuan** [comment]
I try to use kill -9 to stop supervisor, however I found that the supervisor will restart another thread after a while. In other word, I cannot use kill -9 to stop hue. And when I read hue manual, it said that we can use /etc/init.d/hue stop to stop. But I don't find hue under init.d directory.

**Comment by romainr** [comment]
You need to kill supervisor itself, not the Hue server (as supervisor makes sure the Hue process is always there).

Manual probably talks about the packaged version of Hue, will remove references to init.d
