### ISSUE TITLE
[slack] Unsecure usage of rewrite_user for MockRequest

### ISSUE THREAD

**Issue by Harshg999** [cloudera/hue#1917]
https://github.com/cloudera/hue/blob/435aa613c8259d0890257717916dd14e23c8524a/desktop/core/src/desktop/lib/botserver/views.py#L166-L168

Unsecure and need to fix 
ref. https://github.com/cloudera/hue/pull/1862#discussion_r594668310

**Comment by Harshg999** [comment]
Do we have to remove all the attributes set by rewrite_user which? Like taking back all the permissions to fix it?? @romainr

**Comment by romainr** [comment]
Please search in the current code base how we do
