### ISSUE TITLE
About log configuration

### ISSUE THREAD

**Issue by AddQuan** [cloudera/hue#193]
Dear Sir:

I already start supervisor successfully, and find the logs (supervisor.log, runcpserver.log ... etc) was located in {HIVE_HOME}/logs, and in the pseudo-distributed.ini I only find out how to config audit.log =>  'audit_event_log_dir='. So I want to know how can I config the location of other logs such as supervisor.log, runcpserver.log, error.log and so on. Thanks a lot.

**Comment by romainr** [comment]
The env variable DESKTOP_LOG_DIR should replace %LOG_DIR% in https://github.com/cloudera/hue/blob/master/desktop/conf.dist/log.conf

So try to export DESKTOP_LOG_DIR=/var/log/...
