### ISSUE TITLE
[docs]  intended word mismatch in Document section in User conecpt?

### ISSUE THREAD

**Issue by Harshg999** [cloudera/hue#1933]
Describe the bug:
Is the intended word here is `saved` or `shared` or maybe both??
https://docs.gethue.com/user/concept/#documents

Hue version or source? 
Source: Hue docs(docs.gethue.com)

**Comment by romainr** [comment]
+1

'can be saved.' --> ~ 'shared with other users or groups'.

Note: could also add a note about the 'Gist'/'Public' links https://gethue.com/blog/2020-03-04-datawarehouse-database-sql-collaboration-and-sharing-with-link-and-gist/

And could also prepare 'Beta' Slack sharing section
