### ISSUE TITLE
is there some tables recored the data users download or exported ? i can no find some table relate to the history, can U help me ?

### ISSUE THREAD

**Issue by joostshao** [cloudera/hue#194]
is there some tables recored the data users download or exported ?
i can no find some table relate to the history, can U help me ?

if no, how can i do to patch the export history to some tables?

**Comment by romainr** [comment]
No, you would have to look at the access logs, or enable the specific logger for audit logs https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L115
