### ISSUE TITLE
[editor] Error message shown in UI should sanitised to prevent Html injection

### ISSUE THREAD

**Issue by Akhilsnaik** [cloudera/hue#1942]
### Describe the bug:
 Error message shown in UI should sanitised to prevent Html injection, Currently when i type 
`http://127.0.0.1:8000/hue/editor/?type=impala%253cimg%20src%20onerror=alert(document.domain)`
its creating XSS issue.

### Steps to reproduce it?
Use Master/4.9 hue
In Browser set the url : http://hue-server:port/hue/editor/?type=impala%253cimg%20src%20onerror=alert(document.domain)
There will be below message in UI 

<img width="867" alt="Screenshot 2021-03-25 at 5 20 06 PM" src="https://user-images.githubusercontent.com/18462803/112468519-5a9c5780-8d8e-11eb-96eb-1722617af09f.png">

**Comment by Harshg999** [comment]
Looks like the patch has been merged and this issue can be closed? @Akhilsnaik

**Comment by Akhilsnaik** [comment]
issue merged to master.
