### ISSUE TITLE
Spark + Yarn + Livy Server - Not releasing or stopping the Application Master

### ISSUE THREAD

**Issue by searchwizard** [cloudera/hue#198]
Every time I go to the Spark Query Editor in Hue (even in the same session switch back and forth between Spark and some other application), its creating a new Application Master in Hadoop/Yarn and not releasing or cleaning them up after I execute my Spark/Scala code. This blocks resources in Hadoop cluster.

It would be nice to be able to:
1. Reuse the application master when switching between applications in Hue in the same session.
2. Be able to stop the Application Master from the Spark Query Editor.
3. Automatically stop the Application Master after some period of in-activity.

**Comment by romainr** [comment]
@erickt, I though we had # 3 already?

We are going to make # 2 more obvious (right now the user needs to go in Job Browser). Normally when you leave the notebook, it sends a call to close the notebook sessions.

**Comment by searchwizard** [comment]
> Normally when you leave the notebook, it sends a call to close the notebook sessions.

When you send a call to close the notebook session, does it suppose to terminate/kill the application master? If so, it's not doing it now (in Hue 3.8.1).

Thanks.

**Comment by romainr** [comment]
Yes it should, I see the ajax call going to close_notebook in Hue but need to check on the Yarn mode if then Hue send the close to Livy and Livy understands it

**Comment by searchwizard** [comment]
I tried to trace the network calls in my chrome and I don't see a call going to the server about stop/shutdown/destroy. Can you please tell me how the call looks like? Thanks.

**Comment by romainr** [comment]
I forgot about https://issues.cloudera.org/browse/HUE-2651!

Signal to close
https://github.com/cloudera/hue/blob/master/apps/spark/src/spark/api.py#L205

Sent to Spark but doing nothing :)
https://github.com/cloudera/hue/blob/master/apps/spark/src/spark/models.py#L411

We should call:
https://github.com/cloudera/hue/blob/master/apps/spark/src/spark/job_server_api.py#L89

**Comment by erickt** [comment]
* Reusing Application Masters would be awesome, but it'll be probably non-trivial to implement ([HUE-2833](https://issues.cloudera.org/browse/HUE-2833)).
* @spaztic1215 is currently working on (2) in https://review.cloudera.org/r/5423/.
* We do time out the spark sessions, but the timeout is an hour. This does need to be configurable ([HUE-2832](https://issues.cloudera.org/browse/HUE-2832)).

**Comment by Tagar** [comment]
Can Spark dynamic allocation be of help here? It wouldn't kill AM but at least will time out and remove executors.

**Comment by erickt** [comment]
FYI, [HUE-2832](https://issues.cloudera.org/browse/HUE-2832), which makes session timeout configurable, has landed. The default is still to shutdown idle sessions after an hour.

@Tagar: that would be an interesting idea to spin down executors if a session has gone temporarily idle. I've filed [HUE-2931](https://issues.cloudera.org/browse/HUE-2931) to track it.

**Comment by veseliy** [comment]
Hi, can i swich off, this function?
If i go away from notebook, session stil working.
