### ISSUE TITLE
Impala Query Editor + New Workflows = Sticky Bit Error Permissions

### ISSUE THREAD

**Issue by Carlos-91** [cloudera/hue#200]
Hi,

We are facing some troubles when trying to run a Hive2Script over an Oozie Workflow after making a query over Impala Query Editor:

Both of them (query and .hql script) do the same:

USE user1;
DROP TABLE IF EXISTS data;
CREATE TABLE data....

The problem is:
- First, Impala Query Editor creates the metadata (/user/hive/warehouse/user1.db/data) with user impala:hive
- Then, Hive2Script in Workflow tries to manage the same metadata (/user/hive/warehouse/user1.db/data) with the user logged in HUE, in this case, user1:hive

We think that this is an inconsistency. Obviously, we can remove the sticky bit, give 777 permissions and everybody happy but say bye to any security.

(Hive warehouse folder and all databases created under it have the 1775 default permission).

Any help would be appreciate. Thanks.

**Comment by romainr** [comment]
Could you use the mailing list for this type of end user discussion?
http://groups.google.com/a/cloudera.org/group/hue-user

I would recommend to enable Impala impersonations that way everything is done as the logged-in user: http://gethue.com/use-the-impala-app-with-sentry-for-real-security/
