### ISSUE TITLE
Error installing Hue 3.8.0 -- failed on install livy-core_2.10

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#201]
Hi :
 I attempt to build hue using 3.8.0 version
 I change the spark related pom.xml to version 3.8.0
 This error presents :

Building livy-core_2.10 3.8.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/eclipse/jetty/orbit/javax.mail.glassfish/1.4.1.v201005082020/javax.mail.glassfish-1.4.1.v201005082020.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] livy-main ......................................... SUCCESS [  2.316 s]
[INFO] livy-core_2.10 .................................... FAILURE [  0.903 s]
[INFO] livy-repl_2.10 .................................... SKIPPED
[INFO] livy-yarn_2.10 .................................... SKIPPED
[INFO] livy-server_2.10 .................................. SKIPPED
[INFO] Livy Project Assembly ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.661 s
[INFO] Finished at: 2015-07-02T15:47:22+08:00
[INFO] Final Memory: 16M/222M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project livy-core_2.10: Could not resolve dependencies for project com.cloudera.hue.livy:livy-core_2.10:jar:3.8.0-SNAPSHOT: Failed to collect dependencies at org.eclipse.jetty:jetty-plus:jar:8.1.14.v20131031 -> org.eclipse.jetty:jetty-jndi:jar:8.1.14.v20131031 -> org.eclipse.jetty.orbit:javax.mail.glassfish:jar:1.4.1.v201005082020: Failed to read artifact descriptor for org.eclipse.jetty.orbit:javax.mail.glassfish:jar:1.4.1.v201005082020: Could not transfer artifact org.eclipse.jetty.orbit:javax.mail.glassfish:pom:1.4.1.v201005082020 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/eclipse/jetty/orbit/javax.mail.glassfish/1.4.1.v201005082020/javax.mail.glassfish-1.4.1.v201005082020.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :livy-core_2.10
make[2]: *** [/home/test/hue_3.8/apps/spark/java-lib/livy-assembly.jar] Error 1
make[2]: Leaving directory `/home/test/hue_3.8/apps/spark'
make[1]: *** [.recursive-egg-info/spark] Error 2
make[1]: Leaving directory `/home/test/hue_3.8/apps'
make: *** [apps] Error 2

**Comment by romainr** [comment]
What did you change exactly?

We recommend to just pick Hue's 3.8 code directly from the release tag: https://github.com/cloudera/hue/tree/release-3.8.1

Or even better just from the master branch for now, and you should not need to change anything.

**Comment by polingsky** [comment]
I found it may be a network problems. 

but I encountered another problems.

when it installed to livy-core, the error is:

[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ livy-core_2.10 ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.3
[WARNING]  org.scalatra:scalatra-common_2.10:2.2.1 requires scala version: 2.10.0
[WARNING] Multiple versions of scala libraries detected!
[INFO] /opt/hue_381/apps/spark/java/livy-core/src/main/scala:-1: info: compiling
[INFO] Compiling 5 source files to /opt/hue_381/apps/spark/java/livy-core/target/classes at 1436234893037
[ERROR] error: error while loading <root>, error in opening zip file
[ERROR] error: scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:172)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredPackage(Mirrors.scala:175)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage$lzycompute(Definitions.scala:183)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage(Definitions.scala:183)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass$lzycompute(Definitions.scala:184)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass(Definitions.scala:184)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr$lzycompute(Definitions.scala:1024)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr(Definitions.scala:1023)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1153)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
[ERROR] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
[ERROR] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
[ERROR] 	at scala.tools.nsc.Main$.doCompile(Main.scala:79)
[ERROR] 	at scala.tools.nsc.Driver.process(Driver.scala:54)
[ERROR] 	at scala.tools.nsc.Driver.main(Driver.scala:67)
[ERROR] 	at scala.tools.nsc.Main.main(Main.scala)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:606)
[ERROR] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] 


but when i change ../apps/spark/java/pom.xml

<scala.version>2.10.3</scala.version>  to <scala.version>2.10.0</scala.version>

it disappear another problem:

[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ livy-core_2.10 ---
[INFO] /opt/hue_381/apps/spark/java/livy-core/src/main/scala:-1: info: compiling
[INFO] Compiling 5 source files to /opt/hue_381/apps/spark/java/livy-core/target/classes at 1436235264643
[INFO] java.lang.ClassNotFoundException 
[INFO]  - klass: 'java/lang/ClassNotFoundException'
[INFO] #
[ERROR] # A fatal error has been detected by the Java Runtime Environment:
[INFO] #
[ERROR] #  Internal Error (exceptions.cpp:424), pid=21175, tid=140165047781120
[ERROR] #  fatal error: ExceptionMark destructor expects no pending exceptions
[INFO] #
[INFO] # JRE version: Java(TM) SE Runtime Environment (7.0_60-b19) (build 1.7.0_60-b19)
[INFO] # Java VM: Java HotSpot(TM) 64-Bit Server VM (24.60-b09 mixed mode linux-amd64 compressed oops)
[INFO] # Core dump written. Default location: /opt/hue_381/apps/spark/java/core or core.21175

**Comment by erickt** [comment]
That seems... odd. Perhaps your maven repository got messed up? Perhaps moving ~/.m2/repository away and redownloading the dependencies will fix it.

What OS are you on? Do you have scala installed? If so, what version?

**Comment by polingsky** [comment]
thanks for erickt~
it's ok now.~~

**Comment by PedroMDuarte** [comment]
Also just ran into an issue with `livy-repl`.  I started from scratch, following the [install instructions](http://gethue.com/start-developing-hue-on-a-mac-in-a-few-minutes/).  I tried `make apps` and failed as follows:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] livy-main .......................................... SUCCESS [ 58.276 s]
[INFO] livy-core_2.10 ..................................... SUCCESS [01:11 min]
[INFO] livy-repl_2.10 ..................................... FAILURE [03:14 min]
[INFO] livy-yarn_2.10 ..................................... SKIPPED
[INFO] livy-spark_2.10 .................................... SKIPPED
[INFO] livy-server_2.10 ................................... SKIPPED
[INFO] livy-assembly_2.10 ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:24 min
[INFO] Finished at: 2016-07-04T11:09:27-07:00
[INFO] Final Memory: 29M/278M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project livy-repl_2.10: Could not resolve dependencies for project com.cloudera.hue.livy:livy-repl_2.10:jar:0.2.0-SNAPSHOT: Failed to collect dependencies at org.apache.spark:spark-repl_2.10:jar:1.5.0-cdh5.5.0-SNAPSHOT -> org.apache.spark:spark-core_2.10:jar:1.5.0-cdh5.5.0-SNAPSHOT -> org.apache.avro:avro-mapred:jar:hadoop2:1.7.6-cdh5.5.0-SNAPSHOT -> org.apache.avro:avro:jar:1.7.6-cdh5.5.0-SNAPSHOT -> org.codehaus.jackson:jackson-core-asl:jar:${cdh.jackson.version}: Failed to read artifact descriptor for org.codehaus.jackson:jackson-core-asl:jar:${cdh.jackson.version}: Could not transfer artifact org.codehaus.jackson:jackson-core-asl:pom:${cdh.jackson.version} from/to cdh.snapshots.repo (https://repository.cloudera.com/content/repositories/snapshots): Failed to transfer file: https://repository.cloudera.com/content/repositories/snapshots/org/codehaus/jackson/jackson-core-asl/$%7Bcdh.jackson.version%7D/jackson-core-asl-$%7Bcdh.jackson.version%7D.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]
```

I tried removing the m2 repository folder:

```
$ rm -r ~/.m2/repository/
```

and running `make apps` again resulted in the same error message.  Any help will be much appreciated.

**Comment by xfei6868** [comment]
i have some error as PedroMDuarte's error

on master and release-3.10.0

**Comment by PedroMDuarte** [comment]
Happy to report that the installation is now working for me.  I simply tried again without changing my local repo at all, so looks like this had something to do with maven after all.
