### ISSUE TITLE
Hue Table Browser create table leads to error page

### ISSUE THREAD

**Issue by rwu-wish** [cloudera/hue#2017]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:
When using the Hue Table Browser, clicking "New+" button to create table will result in 500 error page due to [this line](https://github.com/cloudera/hue/blob/release-4.8.0/desktop/libs/indexer/src/indexer/templates/importer.mako#L24) which is trying to import impala module. (The import will fail if Impala is not installed or is disabled app)

Steps to reproduce it?
Using Hue installation without impala
1) click on "Tables" on left hand side (Table Browser)
2) click on "New" to try to create new table. This will show an error page.

This was the error found in runcpserver.log
```
  File "/tmp/tmpyXIcyp/indexer/importer.mako.py", line 27, in <module>
    from impala import impala_flags
ImportError: No module named impala
```

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
Hue 4.8

**Comment by romainr** [comment]
Either you need to not blacklist the impala app or https://github.com/cloudera/hue/blob/master/desktop/libs/indexer/src/indexer/templates/importer.mako would need a fix similar to this below:


```
try:
    from impala import impala_flags
except Exception as e:
  LOG.debug('Impala application is not enabled')
  impala_flags = None
```

`'${ impala_flags and impala_flags.is_transactional() }
`...
