### ISSUE TITLE
Error trying make apps hue-3.8.1 in Mac Yosemati

### ISSUE THREAD

**Issue by abhishek-ch** [cloudera/hue#202]
I am trying to install hue-3.8.1 in Mac Yosemati and getting following error.
```
--- Creating virtual environment at /Volumes/work/bigdata/CHD5.4/hue-3.8.1/build/env
python2.7 /Volumes/work/bigdata/CHD5.4/hue-3.8.1/tools/virtual-bootstrap/virtual-bootstrap.py \
		-qq --no-site-packages /Volumes/work/bigdata/CHD5.4/hue-3.8.1/build/env
Traceback (most recent call last):
  File "/Volumes/work/bigdata/CHD5.4/hue-3.8.1/tools/virtual-bootstrap/virtual-bootstrap.py", line 2355, in <module>
    main()
  File "/Volumes/work/bigdata/CHD5.4/hue-3.8.1/tools/virtual-bootstrap/virtual-bootstrap.py", line 827, in main
    symlink=options.symlink)
  File "/Volumes/work/bigdata/CHD5.4/hue-3.8.1/tools/virtual-bootstrap/virtual-bootstrap.py", line 995, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Volumes/work/bigdata/CHD5.4/hue-3.8.1/tools/virtual-bootstrap/virtual-bootstrap.py", line 963, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Volumes/work/bigdata/CHD5.4/hue-3.8.1/tools/virtual-bootstrap/virtual-bootstrap.py", line 905, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Volumes/work/bigdat...ld/env/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
make: *** [/Volumes/work/bigdata/CHD5.4/hue-3.8.1/build/env/stamp] Error 1
```

Python Version - Python 2.7.10 |Anaconda 2.2.0 (x86_64)
Install Xcode , libxml2 , libxslt but no luck

Fails while triggering the following command
```
cmd = [
        py_executable, '-c',
        'import sys, pip; sys.exit(pip.main(["install", "--ignore-installed"] + sys.argv[1:]))',
    ] 
```

I already tried to install another pip version
```
 pip install virtualenv==1.10.1
```
No Luck

**Comment by romainr** [comment]
Did you follow exactly the guid? http://gethue.com/start-developing-hue-on-a-mac-in-a-few-minutes/

**Comment by abhishek-ch** [comment]
exactly in Step 4 it fails
```
Step 4: Compile and configure Hue
Now that we are all set with the requirements we can compile Hue by running

1
make apps
```

**Comment by romainr** [comment]
Any chance you could give a try with the master branch? We changed things in the virtual env recently and maybe it fixed something: 'git clone git@github.com:cloudera/hue.git'

@enricoberti

**Comment by enricoberti** [comment]
just tried both master and the tarball of 3.8.1 on a brand new installation of Yosemite (following the guide of gethue.com) and it works! https://www.dropbox.com/s/n2xencbp03iaw41/Screenshot%202015-07-09%2016.49.44.png?dl=0

@abhishek-ch i think it's probably some sort of configuration problem of your machine?

**Comment by NoraGithub** [comment]
how do you fix it ? @abhishek-ch

**Comment by wjn0918** [comment]
> how do you fix it ? @abhishek-ch

我也遇到同样的问题，应该是系统中没有安装pip（https://pip.pypa.io/en/stable/installing/），可以安装后再尝试
