### ISSUE TITLE
Missing 'name' and 'description' value in request header when creating gist

### ISSUE THREAD

**Issue by Harshg999** [cloudera/hue#2023]
Describe the bug:
- Name and description does not get added in request header for gist_create when user sets it for query and creating a gist

<img width="896" alt="Screenshot 2021-04-20 at 1 25 10 PM" src="https://user-images.githubusercontent.com/42064744/115359293-2b85d400-a1dc-11eb-9e61-f371883c80ee.png">

Steps to reproduce it?
- Give name and desc for a query
- Create a gist 
- Go to `Gist` folder and you'll see default name ( eg. MySQL Query )
- Check Networks tab to see request header for gist_create endpoint

Hue version or source? Latest master branch

**Comment by romainr** [comment]
:+1:
