### ISSUE TITLE
hive sequenceFile table with hdfs lzo

### ISSUE THREAD

**Issue by yuanxiaolong** [cloudera/hue#204]
I have a sequenceFile hive table  (lzo compress hdfs) , hive cli  select rows from table is fine。
when I run the same hive sql In HUE , I got this 

```
java.io.IOException: java.lang.RuntimeException: native-lzo library not available
```

after google the message , found the error is ```https://github.com/cloudera/hue/blob/master/apps/beeswax/src/beeswax/locale/zh_CN/LC_MESSAGES/django.po```

```
#: src/beeswax/templates/execute.mako:393
msgid "Fetching results ran into the following error(s):"
msgstr "正在提取遇到以下错误的结果："
```

How can I set the hue env , like spark ?   thanks ! thanks !

```
export SPARK_LIBRARY_PATH=:/usr/lib/hadoop/lib/native/
export SPARK_SUBMIT_LIBRARY_PATH=:/usr/lib/hadoop/lib/native/
export SPARK_CLASSPATH=:/usr/lib/hadoop/hadoop-lzo-0.4.20-SNAPSHOT.jar
```

**Comment by romainr** [comment]
By Hive CLI, do you mean with 'beeline'? Do you run 'beeline' from the same machine as Hue?

**Comment by yuanxiaolong** [comment]
Thanks for reply, Hive CLI  just  hive command  ```$HIVE_HOME/bin/hive```
I run hive command and query hive sql  On  "Hive Metastore Server" or "Hive gateway" (different machine) all fine.
"HUE" and "Hive Metastore Server" (same machine) ，but run hive sql with HUE UI , it doesn't work。

**Comment by romainr** [comment]
Hue uses the same as 'beeline' which uses HiveServer2 (so misconfiguration there, probably need to add the libs to  HiveServer2 path)

**Comment by yuanxiaolong** [comment]
Romainr, appreciate for your help, I set the env for HiveServer2, It works . thanks again! :+1: 
```
LD_LIBRARY_PATH=/usr/local/hadoop/lzo/lib
```

**Comment by romainr** [comment]
:)
