### ISSUE TITLE
replace gen_filenames() with iter_all_python_module_files() in runserver_plus

### ISSUE THREAD

**Issue by cyberyanka** [cloudera/hue#2041]
I cloned the repo (master branch), made all steps in the manual for Python3-based installation.

Tried to run runserver_plus and got an import error:

`ImportError: cannot import name 'gen_filenames' from 'django.utils.autoreload'`

Triggered by `build/env/lib/python3.7/site-packages/django_extensions/management/commands/runserver_plus.py`:

`from django.utils.autoreload import gen_filenames`

After searching for the same issue in vain I just went to the Django GitHub repo to see when and with what they replaced gen_filenames(). 

The commit when as I believe they deleted gen_filenames(): [link](https://github.com/django/django/commit/c8720e7696ca41f3262d5369365cc1bd72a216ca#diff-384a8302431bfb6168493fb02dca549e9294f02d52dcde766f5b1fb3983d68ba)

Then I replaced gen_filenames() with iter_all_python_module_files() like this:

```
from django.utils.autoreload import iter_all_python_module_files

if use_reloader and settings.USE_I18N:
    extra_files.extend(filter(lambda filename: filename.name.endswith('.mo'), iter_all_python_module_files()))
```

And runserver_plus worked just fine.
Maybe it will be useful for someone with the same problem.

**Comment by romainr** [comment]
Thanks for the report!

Would you mind sending a pull request for the fix so that you get the credits for it?

cc @agl29
