### ISSUE TITLE
import workflow to oozie edit in hue 3.8.0

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#210]
dear:

  I want to ask that if hue 3.8.1 remove import workflow action or not ??
   
  in hue 3.7.0, the edit oozie workflow page, there is an import button that we can import an existed workflow. but now in hue 3.8.1, I can not find this function...

  I have some workflows using in hue 3.7.0, but I upgrade hue to 3.8.1, and I want to re import these workflows to HUE 3.8.1. is it available??

  thanks

**Comment by romainr** [comment]
This feature is getting progressively replaced by a generic import/export that works all the time:
https://www.dropbox.com/s/kkonzrnco1lools/export-workflows.ogv?dl=0

If you are upgrading from 3.7 to 3.8 and keeping the same DB, backuping it, migrating the tables, and you are not going to lose anything. The Oozie editor is also revamped and only supports new workflows.

http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/cdh_ig_hue_database.htm...

In Hue 3.8 we recommend to dump the workflows like this http://gethue.com/export-and-import-your-oozie-workflows/

**Comment by polingsky** [comment]
dear:

https://www.dropbox.com/s/kkonzrnco1lools/export-workflows.ogv?dl=0
I would like to know the above example is which hue version??
it has import and export button in edit page.

so in hue 3.8.1, there is no way to import workflow in UI?

thanks

**Comment by romainr** [comment]
This is in master or will be in Hue 3.9 (to be release in about 1 month)
