### ISSUE TITLE
Could hue support spark 1.4 or 1.5, thanks?

### ISSUE THREAD

**Issue by vanjor** [cloudera/hue#212]
I was using spark 1.4
I was not able to build hue with set config spark 1.4 or 1.5, and though building success with config spark 1.3 in pom.xml
hue viewing spark job went into error:
AttributeError at /jobbrowser/jobs/application_1435834774266_6980
'SparkJob' object has no attribute 'preemptedResourceVCores'

detail see:http://stackoverflow.com/questions/31331282/cloudera-hue-can-not-view-spark-job-history

**Comment by romainr** [comment]
Yes, 1.4 and 1.5 are not supported yet: https://issues.cloudera.org/browse/HUE-2853

**Comment by vanjor** [comment]
thanks, is there a road map for supporting this? We'v great expecting this:)

**Comment by romainr** [comment]
There is no roadmap, it should be pushed today :)

https://review.cloudera.org/r/5664/

**Comment by vanjor** [comment]
thanks @romainr , I saw the CR is still not shipped , cause 3 issues left,  with good luck ,and shipped it soon:)

**Comment by romainr** [comment]
pushed!
