### ISSUE TITLE
Generated gist link should not be changable

### ISSUE THREAD

**Issue by Harshg999** [cloudera/hue#2143]
Describe the bug:
- Gist link can be edited in the input field of the modal
- With Slack share from editor now being active, the SQL Assistant will send the edited link which can be a potential problem
- Its better to remove the input field and something similar to the Query Link of saved queries

Gist Modal
<img width="631" alt="Screenshot 2021-05-21 at 7 48 06 PM" src="https://user-images.githubusercontent.com/42064744/119151932-7873f900-ba6d-11eb-9b43-cb6332133a32.png">

SQL Assistant message when directly sharing to Slack
<img width="378" alt="Screenshot 2021-05-21 at 7 48 36 PM" src="https://user-images.githubusercontent.com/42064744/119152020-8c1f5f80-ba6d-11eb-948e-df31641e7169.png">

**Comment by romainr** [comment]
+1 to just disable or readonly the input!
