### ISSUE TITLE
Autocomplete doesn't work when starting a quoted column name

### ISSUE THREAD

**Issue by jkillian** [cloudera/hue#2146]
_Describe the bug:_
  Autocomplete doesn't work after starting a quoted column name. This is unfortunate, because sometimes column names must be quoted depending on what they are.
 
  
  This seems to be a bug in the autocomplete parser, if I log the output of the genericAutocompleteParser, I get something like this:
  
<img width="361" alt="image" src="https://user-images.githubusercontent.com/1400151/119180048-be18cd80-ba3d-11eb-999a-f7a9641678bd.png">

  For context, I've been trying out some of your autocomplete parsers in a project I'm working on, and they've been really great to work with! Ran into this problem though when working with an example of mixed case column names.

_Steps to reproduce it?_

1) Type `SELECT  FROM wherever;`
2) Trigger autocomplete between `SELECT` and `FROM`. Column names show up!
3) Type a backtick, to begin a quoted column name, and trigger autocomplete. Nothing shows up.

_Demo:_
![2021-05-21 14 01 04](https://user-images.githubusercontent.com/1400151/119179652-2e731f00-ba3d-11eb-929b-88a9a422787f.gif)

_Hue version or source?_ Latest version of [the demo editor](https://demo.gethue.com/hue/editor).

**Comment by JohanAhlen** [comment]
This might not be trivial to fix. If I recall correctly the parser enters a different lexer state when between quotes. In this case it's open as there's no end quote present, so in short I don't believe it can detect the FROM token and wouldn't know what to suggest (the column could actually be named ` FROM ...`). 
 
I'll see what I can do when checking #2147.

**Comment by jkillian** [comment]
Amazing, thank you! I will try this out either today or Monday hopefully and will let you know if I encounter any issues!

**Comment by jkillian** [comment]
Tried stuff out today and looked to be working great, thanks again for the fixes so rapidly - makes working with quoted names way nicer.

I am very curious on this front about the amount of effort it would take to fix #2148 in order to get an autocompletion parser up and running that supports double-quotes in a first-class way, since [a lot of different databases use them and they are what the ANSI spec specifies](https://dba.stackexchange.com/a/29922). I know this might be a very non-trivial thing though 😅
