### ISSUE TITLE
Autocomplete doesn't close identifier quotes

### ISSUE THREAD

**Issue by jkillian** [cloudera/hue#2147]
_Describe the bug:_

Whereas #2146 talked about a lack of autocomplete for quoted column names, autocomplete does work when starting a quoted name after a `FROM` keyword. However, it inserts a `.` without closing the quotes, which makes the identifier invalid.

_Steps to reproduce it?_

1. Type `SELECT * FROM `.
2. Type a backtick and then trigger autocomplete. Select a database/schema.
3. The schema name will be autocompleted with a dot after it, but without a closing quote before the dot.

_Demo:_
![2021-05-21 14 18 48](https://user-images.githubusercontent.com/1400151/119181495-ad695700-ba3f-11eb-9307-7fa33aaa3226.gif)

_Hue version or source?_ Latest version of https://demo.gethue.com/hue/editor/

**Comment by JohanAhlen** [comment]
Thanks for reporting this one! At first glance it should be easy to fix as the parser knows about the backticks, I'll take a look next week.

**Comment by jkillian** [comment]
Amazing, thanks! I know the parser returns an `appendDot` field under its `suggestDatabases` results, perhaps adding a new`appendClosingQuote` or `appendQuote` field would be an appropriate fix? (Which depending on the dialect, the actual character the editor appends might vary).

Library is really nifty btw, having a great time trying it out so far!
