### ISSUE TITLE
Phoenix only autocompletes for wrong quote type

### ISSUE THREAD

**Issue by jkillian** [cloudera/hue#2148]
_Describe the bug:_

Somewhat related to #2146 and #2147, when autocompleting for Phoenix, which uses double-quotes to quote identifiers such as schema or table names, the autocomplete returns results after a backtick (which isn't valid) but does not return results after a double-quote (which is valid).

Context: I'm hoping that one of your pre-existing parsers will work well for Postgres SQL for a project I'm working on 😄 . I thought the Phoenix one would be a good fit and ran into this issue when trying it out.

_Steps to reproduce it?_
1. Type `SELECT * FROM ` in an editor for the phoenix dialect.
2. Type a backtick and trigger autocomplete - schema and table names show up even though they shouldn't.
3. Instead, type a double-quote and trigger autocomplete - nothing shows up even though it should.

_Demo_
![2021-05-21 14 31 40](https://user-images.githubusercontent.com/1400151/119182944-67ad8e00-ba41-11eb-878e-1b186a47d1c1.gif)

_Hue version or source?_ Latest version of https://demo.gethue.com/hue/editor/?type=2

**Comment by JohanAhlen** [comment]
It's a rather big change as the editor was originally built with only taking backtick quotes into account for identifiers. Over time we've added some support for different quote types but not throughout. There are for instance still utils that help with deciding whether to backtick a value or not that'd need to be adjusted.

On the parser side of it... A parser for a specific dialect is normally built with a mix of grammar "modules" from other dialects and I don't think it'd be wise to make a split there. An option to explore would be to accept any type of quotes for identifiers for all parsers, and move the decision to use a specific quote up to the consumer of the parse result. Alternatively, we could pick the quote type to use per dialect if we move to a dedicated lexer per parser, semantically that might make more sense.

I agree that this should be fixed as we're now supporting more and more dialects for the editor, however, it's difficult to say when we can see some improvements here at this point of time.

**Comment by jkillian** [comment]
Thanks for the summary, makes sense. I [saw this PR which seems to add some support for double-quotes in the grammars](https://github.com/cloudera/hue/pull/1655/files), and that [the `backtickIfNecessary` logic has some support for different quote types](https://github.com/cloudera/hue/blob/eb7a46dc76f9eded7aa0a479e834771cf6465933/desktop/core/src/desktop/js/sql/sqlUtils.ts#L274), but also found [some hardcoded things](https://github.com/cloudera/hue/blob/eb7a46dc76f9eded7aa0a479e834771cf6465933/desktop/core/src/desktop/js/parse/sql/sqlParseUtils.js#L578) like you alluded to.

I don't think I'm well informed enough to say which of your ideas makes the most sense, but appreciate the informative response!
