### ISSUE TITLE
Livy notebook session properties dialog has UI errors, and doesn't apply settings with multiple session recreates

### ISSUE THREAD

**Issue by rickb78** [cloudera/hue#2149]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?  No

Describe the bug:

Somewhere between Hue 4.7 and 4.9 there has been a regression in the Notebook Session properties dialog settings for Livy sessions.  If you create a new PySpark or Scala session, then go to edit the session properties, there are 2 distinct problems:

1.  Session properties dialog shows "Spark Conf" kvp option without even selecting it, and more kvp's can't be added.
2.  The first use of any other properties are applied to the Livy session, but the second time you try and recreate a session with some different properties, they aren't applied.

Steps to reproduce it?

For UI issue with properties dialog:
1.  Open new Notebook and add a Livy-based snippet, like Pyspark or Scala
2.  Let the snippet create the new Livy session with the default properties.
3.  Open the Session Properties dialog for the Notebook.
4.  The dialog will show "Spark Conf" kvp option and it shouldn't be shown yet without the user first selecting it. (See attached screenshot).  User also can't add additional Spark Conf kvp's.

For Livy session properties issue:
1.  Open new Notebook and add a Livy-based snippet, like Pyspark or Scala
2. Let the snippet create the new Livy session with the default properties.
3. Open the Session Properties dialog for the Notebook.
4. Add a new property, like "Queue" (or any other).  Change the value to something other than the default.
5. Recreate the session.  The changed properties are correctly applied.
6. Re-do steps 3 through 5, using a different value for the property this time.  The changed properties are not correctly applied... it is still using the property values from the first time the value was changed.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

Hue 4.9, Python 3.7.

<img width="1107" alt="Session_properties" src="https://user-images.githubusercontent.com/79486406/119192191-56668080-ba45-11eb-9cc4-3ceeb396b778.png">

**Comment by romainr** [comment]
There is probably some js error with ko.js saying the json data it needs to convert to the Conf input boxes does not match

**Comment by sheldon1iu** [comment]
> There is probably some js error with ko.js saying the json data it needs to convert to the Conf input boxes does not match

Why I have no the bottom of the add a prop.
![image](https://user-images.githubusercontent.com/39169452/119291692-73879300-bc81-11eb-86ed-d24b6948020d.png)
