### ISSUE TITLE
Can't retrieve log in oozie workflow

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#215]
dear:

when i start hue for a long time, sometimes in oozie workflow page, if to submit a job, 
I can't see logs.
It will show   "Failed to retrieve log:None" 

but when I restart hue server, the log will display.
does anyone encounter this problem??

thanks

**Comment by romainr** [comment]
This looks like https://github.com/cloudera/hue/commit/8da9e9a54f0b612dc1327c154a7eb4d45932122a which is in master, C5.4.3

**Comment by polingsky** [comment]
okok, I try it.
Thanks~~
