### ISSUE TITLE
make hue3.8.1 error

### ISSUE THREAD

**Issue by endymecy** [cloudera/hue#216]
My os is centos7 ,python is 2.7.5
when i make apps ,the following errors occur

Installed /home/spark-home/hue/hue/desktopbsbzookeeper/src
make[2]: Leaving directory `/home/spark-home/hue/hue/desktopbsbzookeeper'
make ipdb ipython nose coverage nosetty werkzeug windmill
make[2]: Entering directory `/home/spark-home/hue/hue/desktop'
--- Installing development tool: ipdb
/home/spark-home/hue/hueild/env/bin/python2.7 /home/spark-home/hue/hueild/env/bin/easy_install -f http://archive.cloudera.com/desktop-sdk-python-packages/ \
   -H archive.cloudera.com -qq ipdb
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'ipdb (0.1dev-r1716)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'lvm (2.02.115-2-RHEL7.-2015-01-28-)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'targetcli-fb (2.1.fb37)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'django (debug-toolbar-0.8.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'django-debug (toolbar-0.8.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'ipdb-0.1dev (r1716)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'logilab (astng-0.20.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'logilab (common-0.51.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
error: None
make[2]: *** [ipdb] Error 1
make[2]: Leaving directory `/home/spark-home/hue/hue/desktop'
make[1]: *** [/home/spark-home/hue/hueild/.devtools] Error 2
make[1]: Leaving directory `/home/spark-home/hue/hue/desktop'
make: *** [desktop] Error 2

**Comment by romainr** [comment]
Not sure we tested with Centos 7 yet, what happens if you remove ipdb from https://github.com/cloudera/hue/blob/master/desktop/devtools.mk#L22 ?

**Comment by endymecy** [comment]
now the error is : 

--- Installing development tool: ipython
/home/spark-home/hue/hueild/env/bin/python2.7 /home/spark-home/hue/hueild/env/bin/easy_install -f http://archive.cloudera.com/desktop-sdk-python-packages/ \
   -H archive.cloudera.com -qq ipython
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'lvm (2.02.115-2-RHEL7.-2015-01-28-)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'targetcli-fb (2.1.fb37)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'django (debug-toolbar-0.8.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'django-debug (toolbar-0.8.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'ipdb (0.1dev-r1716)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'ipdb-0.1dev (r1716)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'logilab (astng-0.20.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/home/spark-home/hue/hueild/envb/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'logilab (common-0.51.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
error: None
make[2]: *** [ipython] Error 1
make[2]: Leaving directory `/home/spark-home/hue/hue/desktop'
make[1]: *** [/home/spark-home/hue/hueild/.devtools] Error 2
make[1]: Leaving directory `/home/spark-home/hue/hue/desktop'
make: *** [desktop] Error 2


maybe some of my software install error

**Comment by YaaMe** [comment]
I got the same problem.....Did u solve it?

**Comment by romainr** [comment]
Are you on the same OS?

**Comment by YaaMe** [comment]
>mvn -v

 shows me:

    OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"
what's more,

    Apache Maven 3.3.3
    Java version: 1.8.0_51
    gmp-6.0.0a
    mysql-5.6.25

Did i do anything wrong?

**Comment by romainr** [comment]
Are you sure it is the same error as it is not the same OS as RHEL7 based.

Could you copy paste the steps you did? If you are using the tarball release you should do 'make install' like detailed in the README

**Comment by YaaMe** [comment]
I'm on mac.

The step is make apps like that:
>[hue-master] make apps                                                                                                                                                                                                                                  13:05:42  ☁  master ☂ ✭
cd /Users/yaame/workspace/hue-master/maven && mvn install
[INFO] Scanning for projects...

=======a lot of log========

>Installed /Users/yaame/workspace/hue-master/desktop/libs/libzookeeper/src
/Library/Developer/CommandLineTools/usr/bin/make ipdb ipython nose coverage nosetty werkzeug windmill
--- Installing development tool: ipdb
/Users/yaame/workspace/hue-master/build/env/bin/python2.7 /Users/yaame/workspace/hue-master/build/env/bin/easy_install -f http://archive.cloudera.com/desktop-sdk-python-packages/ \
	   -H archive.cloudera.com -qq ipdb
/Users/yaame/workspace/hue-master/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'ipdb (0.1dev-r1716)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/Users/yaame/workspace/hue-master/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'django (debug-toolbar-0.8.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/Users/yaame/workspace/hue-master/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'django-debug (toolbar-0.8.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/Users/yaame/workspace/hue-master/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'ipdb-0.1dev (r1716)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/Users/yaame/workspace/hue-master/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'logilab (astng-0.20.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/Users/yaame/workspace/hue-master/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'logilab (common-0.51.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
error: None
make[2]: *** [ipdb] Error 1
make[1]: *** [/Users/yaame/workspace/hue-master/build/.devtools] Error 2
make: *** [desktop] Error 2

If i `runserver`
>Validating models...

>0 errors found
August 06, 2015 - 22:30:07
Django version 1.6.10, using settings 'desktop.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

but it tell me
>ImportError at /accounts/login/
No module named useradmin.models

I keep searching the problem now..>_<

**Comment by endymecy** [comment]
tar should run  "make install"

**Comment by clevertension** [comment]
PEP440Warning  is just a warning, not a fatal error, If you are chinese, please make sure your VPN is powerful to defeat the GFW

**Comment by kevin7R** [comment]
I got the same problem! do you solve it?

**Comment by wjqin** [comment]
I got the same problem! 

/u01/hue-release-3.11.0/build/env/bin/python2.7 /u01/hue-release-3.11.0/build/env/bin/easy_install -f http://archive.cloudera.com/desktop-sdk-python-packages/ \
   -H pypi.python.org,archive.cloudera.com -qq ipdb==0.1dev-r1716
/u01/hue-release-3.11.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'pytz (2012d)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/u01/hue-release-3.11.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'targetcli-fb (2.1.fb37)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/u01/hue-release-3.11.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'django (debug-toolbar-0.8.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/u01/hue-release-3.11.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'django-debug (toolbar-0.8.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/u01/hue-release-3.11.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'ipdb (0.1dev-r1716)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/u01/hue-release-3.11.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'ipdb-0.1dev (r1716)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/u01/hue-release-3.11.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'logilab (astng-0.20.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/u01/hue-release-3.11.0/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'logilab (common-0.51.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
error: None
make[2]: *** [ipdb[0.1dev-r1716]] Error 1
make[2]: Leaving directory `/u01/hue-release-3.11.0/desktop'
make[1]: *** [/u01/hue-release-3.11.0/build/.devtools] Error 2
make[1]: Leaving directory `/u01/hue-release-3.11.0/desktop'
make: *** [desktop] Error 2

**Comment by 24king** [comment]
I got the same problem!
我也碰到了这个问题, 比较头疼, 不同环境产生的效果不太一样

**Comment by linbaicome** [comment]
...migrate to PEP 440 compatible versions.
  PEP440Warning,
error: None
make[2]: *** [ipdb[0.1dev-r1716]] Error 1
make[2]: Leaving directory `/data/soft/test/hue-release-4.1.0/desktop'
make[1]: *** [/data/soft/test/hue-release-4.1.0/build/.devtools] Error 2
make[1]: Leaving directory `/data/soft/test/hue-release-4.1.0/desktop'
make: *** [desktop] Error 2

**Comment by romainr** [comment]
Please move to Hue 4.6 https://gethue.com/hue-4-6-and-its-improvements-are-out/
