### ISSUE TITLE
Hue / Filebrowser file upload/download API?

### ISSUE THREAD

**Issue by ajck** [cloudera/hue#2168]
I need to upload and download files to and from HDFS, from an AngularJS note running in Zeppelin. I see from the bottom of this Hue blog entry: https://gethue.com/blog/rest-api-execute-sql-queries-browse-files/ that there's a File API but is there a public or private API endpoint for file upload and download please? I am in real need of this for a particular user requirement!
Users of this note would already be logged in to both Zeppelin and Hue if that makes a difference.

My alternative was to wonder if I could use the same endpoints the Hue Filebrowser does, e.g. for file upload I can see it does a POST to https://[Hue URL]/filebrowser/upload/file?dest=[HDFS destination folder] and specifies a CSRF header - is there any way I could use this as an alternative? I've seen there's an equivalent URL for file download too.

I understand WebHDFS allows upload/download but I can't use it in the environment I'm writing for as the port is not open for security reasons.

Thanks.

**Comment by romainr** [comment]
There is a new REST API much simpler where there is no CSRF/cookie and just a JWT token:
https://docs.gethue.com/developer/api/rest/#authentication

Just the upload is not ported yet:
https://docs.gethue.com/developer/api/rest/#file-browsing

But should not be too difficult to do, i.e. similarly to the new Query API:
https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/api_public.py
https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/api_public_urls.py

**Comment by romainr** [comment]
There is a new Public API for upload/download: https://docs.gethue.com/developer/api/rest/#upload
