### ISSUE TITLE
cloudera Hue can not view spark job history

### ISSUE THREAD

**Issue by vanjor** [cloudera/hue#219]
as I have post on SO: http://stackoverflow.com/questions/31331282/cloudera-hue-can-not-view-spark-job-history
find the relate issue have been resolved:https://issues.cloudera.org/browse/HUE-2853
I have check the latest code and build, still would not able to view spark history

the job detail page runs into error :
AttributeError at /jobbrowser/jobs/application_1435834774266_6980
'SparkJob' object has no attribute 'preemptedResourceVCores'

![1](https://cloud.githubusercontent.com/assets/864664/9055389/58708a82-3abd-11e5-9cd9-f2e738f485c4.png)

**Comment by spaztic1215** [comment]
Fixed with commit: https://github.com/cloudera/hue/commit/5bd1b676e72ac862cf1bdb4f909ba80d1c41d78c
