### ISSUE TITLE
Feature Request: display "application Type" in Hue job list

### ISSUE THREAD

**Issue by vanjor** [cloudera/hue#220]
In hadoop yarn job page, there list application Type for each job. in order to keep consistent and convenient  for viewing jobs' overview:)
![2](https://cloud.githubusercontent.com/assets/864664/9102898/bc98c3f8-3c2a-11e5-80a1-4687b22c77df.png)
![3](https://cloud.githubusercontent.com/assets/864664/9102900/be57400c-3c2a-11e5-9812-101e8df69bd0.png)

**Comment by romainr** [comment]
We could in YARN mode:
- merge Maps/Reduce columns into Progress
- add the Type column

**Comment by spaztic1215** [comment]
Application Type now appears in the Job Browser for both MR1 and YARN jobs as of https://github.com/cloudera/hue/commit/93f1cb7b9741021d3efb5b133d5e8c24d4e553f2
