### ISSUE TITLE
I met an error about submiting an oozie coordinator from HUE UI.

### ISSUE THREAD

**Issue by phoenixhadoop** [cloudera/hue#222]
Hi friends:

submit Coordinator cron-testoozieshell-ssh-cnsh231375 - hue  error

E1003: Invalid coordinator application attributes, parameter [start] = [2015-08-14T06:30Z] must be Date in GMT+08:00 format (yyyy-MM-dd'T'HH:mm+0800). Parsing error java.text.ParseException: Could not parse [2015-08-14T06:30Z] using [yyyy-MM-dd'T'HH:mm+0800] mask

I have selected the timezone America/Los_Angeles.

Please.

**Comment by romainr** [comment]
Can you provide the date for the 'start' attribute with a forma similar to yyyy-MM-dd'T'HH:mm+0800?
What does your Coordinator config look like?

**Comment by romainr** [comment]
Very probably the same issue as https://github.com/cloudera/hue/issues/227
