### ISSUE TITLE
lily-server SessionManager doesn't collectGarbage for BatchSessions

### ISSUE THREAD

**Issue by jmelching** [cloudera/hue#223]
The session manager doesn't remove sessions that are BatchSession's from the  _sessions Map.  This will become a memory leak over time.

**Comment by erickt** [comment]
Thanks! I got a fix for this lined up that should land later on today or tomorrow.

**Comment by jmelching** [comment]
Did this fix make it into the source?  i don't see it working as expected.

**Comment by erickt** [comment]
@jmelching: yep, it hasn't landed yet.

**Comment by erickt** [comment]
Submitted it for review in https://review.cloudera.org/r/6072/.
