### ISSUE TITLE
LDAP auth error: can't decode byte 0xc3

### ISSUE THREAD

**Issue by milletnis** [cloudera/hue#2250]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No, at least I couldn't find it

Describe the bug:
Since HUE 4.8.0 some LDAP users are not able to login anymore.
Same users and same LDAP backend with Hue 4.4.0 works fine for us.
```
[14/Jun/2021 08:46:34 +0000] backend      INFO     Augmenting users with class: <class 'desktop.auth.backend.DefaultUserAugmentor'>
[14/Jun/2021 08:46:34 +0000] forms        ERROR    LDAP auth error: 'ascii' codec can't decode byte 0xc3 in position 18: ordinal not in range(128)
```
This blocks migration to 4.8 and higher if connected to LDAP

Steps to reproduce it?
Connect to LDAP directory with users containing special characters in their names (ü ö ä ...)

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
open source 4.8 , open source 4.9, open source 4.10 - OS: Windows 10; Browsers: Firefox and Chrome.

**Comment by arturbrandysonwelo** [comment]
Yes I have the exact same problem with Hue 4.10 also with special characters in the user names (some polish letters: ł ó ś ą ...). This users cannot to logon using LDAP. Users without this special characters can logon normally.
