### ISSUE TITLE
ldap error:  AXES: AxesProxyHandler.update_request can not set request attributes to a None request

### ISSUE THREAD

**Issue by andrewzah** [cloudera/hue#2251]
*Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?*

I don't believe so.

*Describe the bug:*

When attempting to sign in via LDAP, the console shows these errors:
```
[14/Jun/2021 11:07:22 -0700] proxy        ERROR    AXES: AxesProxyHandler.update_request can not set request attributes to a None request
[14/Jun/2021 11:07:22 -0700] database     ERROR    AXES: AxesDatabaseHandler.user_login_failed does not function without a request.
```

*Steps to reproduce it?*
Configure hue.ini for ldap:
```
[[custom]]
[[auth]]
backend=desktop.auth.backend.LdapBackend

[[ldap]]
ldap_url = "ldap://ldap.example.com:389"
search_bind_authentication = true
use_start_tls = false
create_users_on_login = true
base_dn = "cn=users,cn=accounts,dc=cluster,dc=local"
bind_dn = "<bind dn>"
bind_password = "<bind pw>"
#ldap_cert=

[[[users]]]
user_filter="objectclass=user"
user_name_attr="uid"

[[[groups]]]
group_filter="objectclass=group"
group_name_attr="cn"
group_member_attr="member"
```

*Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).*

Version: built from master branch, latest commit.
browser: firefox 78.8.0.

**Comment by romainr** [comment]
Sounds like a legit bug when using the `LdapBackend` backend. Does it fail also with succesful logins?

It might be interesting to check what is different in the LDAP backend https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/auth/backend.py#L455 that inherits from `from django_auth_ldap.backend import LDAPBackend`
