### ISSUE TITLE
Could Hue oozie job submit not to force the time zone as UTC+0000?

### ISSUE THREAD

**Issue by vanjor** [cloudera/hue#227]
Hue oozie force set default time zone as UTC+0000.
while oozie now support other timezone, could Hue maintain a config setting of personal time zone?
by benefit of it, we would not need to manual change the timezone for each job submit?
 
![11](https://cloud.githubusercontent.com/assets/864664/9491445/97a741f8-4c21-11e5-92fa-bf4d5329a701.png)

**Comment by vanjor** [comment]
As I ready config oozie time zone as GMT+08:00, by hue oozie default time zone submit, it run into error.
![111](https://cloud.githubusercontent.com/assets/864664/9491510/45e606b4-4c22-11e5-909d-e180f7115e33.png)

now, we have to manual change the timezone before submit,e.g. change 2015-08-03T11:20Z to 2015-08-03T11:20+0800

ps.. we do not want to using UTC+0000 timezone, we want using local customerized timezone, together with all job time display.

**Comment by romainr** [comment]
Yes, currently Hue is hardcoded to use UTC

We should support https://issues.cloudera.org/browse/HUE-1910

We could pickup the timezone:
- from the hue server configuration, and provide a way to override it in the liboozie section of the hue.ini.
- from the browser of the client

Side question, how come do you have a '1' in the first screenshot next to the 'Do a dryrun...'?

**Comment by vanjor** [comment]
Thanks for quick response:)
"Side question, how come do you have a '1' in the first screenshot next to the 'Do a dryrun...'?"
I add it into src code just debugging to find the template for this page.

And I added following code into the file apps/oozie/src/oozie/templates/editor2/submit_job_popup.mako
for temperately use, which I did not need to change anything before commit job for most usage cases.

```javascript
 <script type="text/javascript">
   if($("#id_form-3-value").length<=0){
       $("#id_form-1-value").val(moment().format("YYYY-MM-DD[T]HH:mm") + '+0800');
       $("#id_form-2-value").val(moment('2020-01-01',"YYYY-MM-DD").format("YYYY-MM-DD[T]HH:mm") + '+0800');
    }else{
       $("#id_form-1-value").val(moment().format("YYYY-MM-DD[T]HH:mm") + '+0800');
       $("#id_form-2-value").val(moment().format("YYYY-MM-DD[T]HH:mm") + '+0800');
       $("#id_form-3-value").val(moment('2020-01-01',"YYYY-MM-DD").format("YYYY-MM-DD[T]HH:mm") + '+0800');
    }
</script>
```

**Comment by lonely7345** [comment]
vote for this  issue.  I 'am also using hue in china.

**Comment by romainr** [comment]
https://issues.cloudera.org/browse/HUE-1910 was done by @sai-krish
