### ISSUE TITLE
unable to integrate hue with MINIO

### ISSUE THREAD

**Issue by novneet** [cloudera/hue#2287]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
no

Describe the bug:
I am trying to integrate hue with minio , I have hosted minio in a aws instance and provided the  credentials like access key and secret key and region , in the  hue/desktop/conf.dist/hue.ini. I have updated it under [aws] but while accessing it in hue it says "Failed to retrieve buckets: local variable 'region_name' referenced before assignment"
Steps to reproduce it?
host a minio server in aws cloud , generate a access key 
edit hue/desktop/conf.dist/hue.ini , go to [aws] and fill those credentials and try to access via hue's webUI
Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

**Comment by romainr** [comment]
Could you should provide the full trace from the Hue logs?
