### ISSUE TITLE
Add doucumentation for Security app

### ISSUE THREAD

**Issue by dylan8902** [cloudera/hue#229]
Please can there be some documentation on the Sentry web app: https://github.com/cloudera/hue/blob/master/apps/security/src/security/static/security/help/index.html

**Comment by romainr** [comment]
You can see http://gethue.com/apache-sentry-made-easy-with-the-new-hue-security-app/

And a big revamp of the doc is planned for Hue 4: 
https://issues.cloudera.org/browse/HUE-2890

**Comment by romainr** [comment]
Until then, the Sentry blog posts detail the App http://gethue.com/category/security-2/
