### ISSUE TITLE
Feature Request: Hue oozie workflow support one click copy function

### ISSUE THREAD

**Issue by vanjor** [cloudera/hue#230]
Hue oozie workflow is really cool, especially the virtualised workflow editor. 
The is one issue. for many cases, we need copy an exist workflow, while current does not support. 
There is the use case for this feature request:
1. someone create a demo workflow, other's just need to copy it and change the copied one to quickly setup another workflow
2. someone need to setup and try a new version of the current workflow, he/she do not want to change the current online workflow, because the workflow does not support revert and virtualised  version function.
3. someone need to temperately run partial of current workflow,   he/she do not want to edit and recover the workflow, that's to fuzzy and easy to make mistake. this is a similar which run partial workflow when workflow run into error.

I am gonna to recommend  our teams to migrate the cronjob into hue oozie job system. And this feature will helps a lot.

![1111](https://cloud.githubusercontent.com/assets/864664/9578387/0e2cdc0e-501c-11e5-8c0f-0657a6407295.png)

**Comment by romainr** [comment]
There is a 'copy' button on the list of workflows page but you would rather have even after opening an existing workflow? (in the menu bar you highlighted)

**Comment by vanjor** [comment]
Thanks, Found the copy function in list page. please resolve it:)

![aaa](https://cloud.githubusercontent.com/assets/864664/9594644/19df0468-5090-11e5-941a-8f46abd1676d.png)

**Comment by romainr** [comment]
Glad to hear :)
