### ISSUE TITLE
SQL scratchpad problem

### ISSUE THREAD

**Issue by gjldwz** [cloudera/hue#2307]
hi：
I am based on：https://docs.gethue.com/developer/components/scratchpad/
phenomenon:
![image](https://user-images.githubusercontent.com/10614646/124785909-da36e680-df79-11eb-9af4-7459431ae875.png)
warn：Failed loading the Hue config!

Can you tell me what may be the cause of this?

thank you！

**Comment by romainr** [comment]
Should be fixed now
