### ISSUE TITLE
How to trigger Yarn file cache force update ?

### ISSUE THREAD

**Issue by sadofwind** [cloudera/hue#231]
I have a issue that the workflow use old jar in yarn while I already update the jar file on hdfs.
So I wonder How can I make the new jar file which the workflow used update on every node of yarn.

I think I can delete it on every datanode of yarn. But it's not a gorgeous way.

**Comment by romainr** [comment]
If the jars are on HDFS in the workspace of the workflow, restarting the workflow will use the new jar.

For usage question and non bug, we recommend to use the user list instead: http://groups.google.com/a/cloudera.org/group/hue-user

**Comment by sadofwind** [comment]
The old jar file can run on hue workflow.
My new jar file can run when I submit mission to yarn by shell.
When I use the new jar file, the new mission run submit by hue tell me can not find the main class.
So I wonder if the jar file is correctly update on yarn when I run the workflow.
I am not sure if I use hue in a wrong way or there is something wrong in hue. It's difficult to find the wrong place.

**Comment by sadofwind** [comment]
I know the reason.
I use Java workflow to submit a mapreduce  job. I add jar file path in "Jar name" and "Files". 
In this way the java job run error with class not find.
Then I remove the jar file path in "Files" and Left jar file path in "Jar name".The job can run correctly.
I think I must use the workflow wrong.
