### ISSUE TITLE
Can't load plugin: sqlalchemy.dialects:impala error on demo.gethue.com

### ISSUE THREAD

**Issue by Harshg999** [cloudera/hue#2313]
Describe the bug:
- `Can't load plugin: sqlalchemy.dialects:impala` error coming when trying to query Impala dialect

Steps to reproduce it?
- Open demo.gethue.com
- Try switching to Impala editor
- Check console logs e.g.

<img width="1267" alt="Screenshot 2021-07-08 at 9 57 06 PM" src="https://user-images.githubusercontent.com/42064744/124958141-73780280-e037-11eb-923e-60070c6ecfb2.png">

<img width="1555" alt="Screenshot 2021-07-08 at 9 56 18 PM" src="https://user-images.githubusercontent.com/42064744/124958022-55aa9d80-e037-11eb-9cc3-442021c0201f.png">

Hue version or source? 
- Latest master branch

**Comment by romainr** [comment]
Expected still if you use the sqlalchemy interface and don't install the
dialect. Check the docs for the pip install

**Comment by Harshg999** [comment]
For demo.gethue.com? @romainr

**Comment by romainr** [comment]
Look at the Docker image it is the same used for demo
