### ISSUE TITLE
installing Quickstart Examples Solr Search 

### ISSUE THREAD

**Issue by MiniPlayer** [cloudera/hue#233]
I cloned master, launched hue and an instance of Solr 5.3 .
Hue is launched in development mode and I do not have hdfs so i got some errors about that. 
But I noticed that the schema generated in the collection "twitter_demo" is builded by putting all field of the file to index to "required true" as it is indicated by default in "desktop/libs/indexer/src/indexer/utils.py". Which should hinder hue to import the data anyways as all field are not filled in the index.csv file.

Furthermore, The elevate.xml in "apps/search/examples/collections/solr_configs_twitter_demo/conf" used as template is wrong as well if we look at "apps/search/examples/collections/solr_configs_twitter_demo/index_data.csv" as there is no id of type String in the field which as for consequences to put the id field as tlong type anyway. 

That is why I changed the elevate xml by replacing any string by an int and the utils.py files to put "required false" by default then successfully imported the data manually.

If I am doing something wrong please tell me.

**Comment by romainr** [comment]
We are looking at Solr 5.x and revamping the indexer (https://issues.cloudera.org/browse/HUE-2961) now and just did basic testing and it does not work out of the box yet.

This is great feedback, maybe upstream Solr 5 requires this little changes to work.

**Comment by MiniPlayer** [comment]
I am pleased it helps you. I forgot to mention that I changed the schema.xml template , putting "TrieIntField" instead of "IntField" for all primitive types as IntField does not exist anymore in Solr 5.x.

**Comment by romainr** [comment]
And https://issues.cloudera.org/browse/HUE-3348
