### ISSUE TITLE
I want to integerate MS SQL Server with Hue

### ISSUE THREAD

**Issue by asif-khalil** [cloudera/hue#2335]
I am new into hue. I need help about MS SQL Server integration with hue to populate data. 
I have started application using docker and created a admin user. There is no default database into hue UI.
Unable to update hue.ini file password not accepted. Please help me or share the guideline that is help me to populate data into hue app.
![image](https://user-images.githubusercontent.com/64101506/125471914-c9d8508f-814f-4dda-a775-239ce5527ad5.png)

Only gethue/hue docker image i can use to integrate with my local database mysql. 
or other cloudera other products need to configure for use of hue web UI application.
If anyone reply that is helpfull for me.

**Comment by romainr** [comment]
https://docs.gethue.com/administrator/configuration/connectors/
