### ISSUE TITLE
No module named 'impala.sqlalchemy'

### ISSUE THREAD

**Issue by Harshg999** [cloudera/hue#2336]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? 
- Relates to #2313 

Describe the bug:
- `No module named 'impala.sqlalchemy'` error on demo.gethue.com

Steps to reproduce it?
- Go to demo.gethue.com
- Try to open Impala dialect

<img width="1538" alt="Screenshot 2021-07-14 at 12 18 30 AM" src="https://user-images.githubusercontent.com/42064744/125508364-a6be5813-9d14-4d5d-bece-72facbdcb373.png">

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
Latest master branch

**Comment by romainr** [comment]
module was added but currently the Docker build is broken, so not refreshed

https://hub.docker.com/repository/docker/gethue/hue/builds
