### ISSUE TITLE
There is a problem with hive SQL parsing：'show DATABASES;' report errors

### ISSUE THREAD

**Issue by zhoushengmufc** [cloudera/hue#2338]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:

Steps to reproduce it?

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

**Comment by zhoushengmufc** [comment]
‘show DATABASES;’  is a legal statement，but "Like" is required for error reporting

**Comment by Harshg999** [comment]
Hi @zhoushengmufc, can you give more context on the error? Like where it occured and steps to reproduce? 

Thanks!
