### ISSUE TITLE
On Edit hue.ini file Password prompted

### ISSUE THREAD

**Issue by asif-khalil** [cloudera/hue#2339]
I am trying to edit the hue.ini file of docker deployed application but password prompted. where i get the password of hue user. 

![jue](https://user-images.githubusercontent.com/64101506/125679825-a4ffff20-a488-423e-be31-2d180d40cffa.png)

**Comment by Harshg999** [comment]
Hi @asif-khalil, thank you for your question!

Can this be of any help? https://github.com/cloudera/hue/tree/master/tools/docker/hue
c.f.  `conf/z-hue-overrides.ini`

Hope this helps. Let me know if you have any further questions!

**Comment by asif-khalil** [comment]
I am not able to modify above mentioned conf/z-hue-overrides.ini file, docker image deploy into Docker Desktop application, 
A password prompted, I am not able to find default password of hue user. Please share.

Or any other way to update conf files of gethue/hue.

**Comment by asif-khalil** [comment]
I am not able to modify above mentioned conf/z-hue-overrides.ini file, docker image deploy into Docker Desktop application,
A password prompted, I am not able to find default password of hue user. Please share.

Or any other way to update conf files of gethue/hue.

**Comment by StSahana** [comment]
I solved the problem via "docker run -it -u 0 -p 8888:8888 gethue/hue:latest /bin/bash"
