### ISSUE TITLE
beeswax_server

### ISSUE THREAD

**Issue by yoer** [cloudera/hue#234]
i follow step from 'http://cloudera.github.io/hue/docs-3.7.0/sdk/sdk.html#fast-guide-to-creating-a-new-hue-application' to install a new hue application

when i execute 
'$ build/env/bin/hue beeswax_server'
hue says ' Unknown command:'beeswax_server' '

i have check by this command :
' $ ./tools/app_reg/app_reg.py --list '

and the result is:
Name               Version Author          Path
------------------ ------- --------------- -----------------------------------
about              3.9.0   Hue             about
beeswax            3.9.0   Hue             beeswax
filebrowser        3.9.0   Hue             filebrowser
hbase              3.9.0   Hue             hbase
help               3.9.0   Hue             help
impala             3.9.0   Hue             impala
jobbrowser         3.9.0   Hue             jobbrowser
jobsub             3.9.0   Hue             jobsub
metastore          3.9.0   Hue             metastore
oozie              3.9.0   Hue             oozie
pig                3.9.0   Hue             pig
proxy              3.9.0   Hue             proxy
rdbms              3.9.0   Hue             rdbms
search             3.9.0   Hue             search
security           3.9.0   Hue             security
spark              3.9.0   Hue             spark
sqoop              3.9.0   Hue             sqoop
useradmin          3.9.0   Hue             useradmin
zookeeper          3.9.0   Hue             zookeeper

**Comment by romainr** [comment]
beeswax_server command does not exist anymore since Hue 3.0 as Hue relies on HiveServer2 instead.

Note that the doc was fixed in 3.8: http://cloudera.github.io/hue/docs-3.8.0/sdk/sdk.html#fast-guide-to-creating-a-new-hue-application

**Comment by yoer** [comment]
thanks :), but i open the page from hue home page, which link is  'http://cloudera.github.io/hue/docs-3.7.0/sdk/sdk.html#fast-guide-to-creating-a-new-hue-application' . so may be you could change the link of the Learn/Documentation?

**Comment by romainr** [comment]
No problem :)

**Comment by yoer** [comment]
thanks a lot.
