### ISSUE TITLE
Not knowing killed spark context

### ISSUE THREAD

**Issue by SeongUk-Han** [cloudera/hue#235]
Livy Spark REST server does not check whether the spark context is alive or not.
Once a spark context was created (and not closed), livy assumed it is alive. 
So, running statements on the killed spark context (session) will remains running status forever.
I think livy may need to check spark contexts' status on every related requests.

**Comment by erickt** [comment]
Thanks! What circumstance were you able to hit this problem? One possibility I can think of is if you cause the interpreter to kill itself:

```
% curl -i -XPOST -H 'Content-Type: application/json' localhost:8998/sessions -d '{"kind": "pyspark"}'
% curl -XPOST -H 'Content-Type: application/json' localhost:8998/sessions/0/statements -d '{"code": "import os; os._exit(1)"}'
% curl -XPOST -H 'Content-Type: application/json' localhost:8998/sessions/0/statements -d '{"code": "1+"}' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154    0   140  100    14   7885    788 --:--:-- --:--:-- --:--:--  8235
{
    "id": 19,
    "output": {
        "ename": "Error",
        "evalue": "Interpreter died:\n",
        "execution_count": 19,
        "status": "error",
        "traceback": {}
    },
    "state": "available"
}
```

Currently the session doesn't transition into the "error" state because the livy-repl that manages the interpreter is still responding. If this is the case you are describing, I'm currently fixing it to properly transition into an errored state. :)

**Comment by erickt** [comment]
I've submitted https://review.cloudera.org/r/5967/ for review, which makes sure to transition sessions to the error state if the interpreter has erred out.

**Comment by SeongUk-Han** [comment]
@erickt 
I tested on CentOS 6.6, spark 1.4.1, hue 596dd8ead2ca610f6dbbc0fe2635e7a63c8c0395. And, I killed the spark context in the spark web UI.
Your commit seems to solve this issue. Thank you.

**Comment by SeongUk-Han** [comment]
@erickt 
Unfortunately, it was not fixed. 

This is how I tested.
1. create a session (kind = spark)

2. kill the spark context named as "Livy Spark shell" via the spark web UI
Log:
15/09/23 16:38:36 ERROR SparkDeploySchedulerBackend: Application has been killed. Reason: Master removed our application: KILLED
15/09/23 16:38:37 INFO SparkUI: Stopped Spark web UI at http://172.17.243.40:4040
15/09/23 16:38:37 INFO DAGScheduler: Stopping DAGScheduler
15/09/23 16:38:37 INFO SparkDeploySchedulerBackend: Shutting down all executors
15/09/23 16:38:37 INFO SparkDeploySchedulerBackend: Asking each executor to shut down
15/09/23 16:38:37 WARN ReliableDeliverySupervisor: Association with remote system [akka.tcp://sparkExecutor@172.17.240.110:37860] has failed, address is now gated for [5000] ms. Reason is: [Disassociated].

3. run any statement with the session
Response:
{"id":0,"state":"running","output":null}
Log:
172.26.108.92 - - - 23/Sep/2015:16:39:14 +0900 "POST /sessions/0/statements HTTP/1.1" 201 40
172.17.243.40 - - - 23/Sep/2015:16:39:15 +0900 "POST /execute HTTP/1.1" 200 2630
172.17.243.40 - - - 23/Sep/2015:16:39:15 +0900 "GET / HTTP/1.1" 200 16
15/09/23 16:40:37 INFO AppClient: Stop request to Master timed out; it may already be shut down.
15/09/23 16:40:37 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
15/09/23 16:40:37 INFO Utils: path = /tmp/spark-4028416f-d261-4260-95f4-4c11bb326a44/blockmgr-f199fa84-d9aa-4f43-bb6e-a9889cce9536, already present as root for deletion.
15/09/23 16:40:37 INFO MemoryStore: MemoryStore cleared
15/09/23 16:40:37 INFO BlockManager: BlockManager stopped
15/09/23 16:40:37 INFO BlockManagerMaster: BlockManagerMaster stopped
15/09/23 16:40:37 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
15/09/23 16:40:37 INFO SparkContext: Successfully stopped SparkContext
15/09/23 16:40:37 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
15/09/23 16:40:37 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
15/09/23 16:40:37 INFO RemoteActorRefProvider$RemotingTerminator: Remoting shut down.

4. get statements status
Response:
{"total_statements":1,"statements":[{"id":0,"state":"running","output":null}]}
Log:
172.26.108.92 - - - 23/Sep/2015:16:41:39 +0900 "GET /sessions/0/statements HTTP/1.1" 200 78

**Comment by SeongUk-Han** [comment]
@erickt 

Also, once the context killed, I need to restart livy server to create a new session.

**Comment by romainr** [comment]
Livy was moved to this repository: https://github.com/cloudera/livy
