### ISSUE TITLE
400 of "Install SDK Application"

### ISSUE THREAD

**Issue by yoer** [cloudera/hue#236]
when i request localhost:8000
and click calculator app, i could not see the icon of app, and have some log like that:
* "GET /static/calculator/art/icon_calculator_48.png HTTP/1.1" 404 32705
* "GET /jobbrowser/?format=json&state=running&user=yoer HTTP/1.1" 500 445

**Comment by yoer** [comment]
first, i need make folder in hue_root/build/calculator.
second, i need to move followed folder to hue_root/build/calculator
* hue_root/build/static/css 
* hue_root/build/js 
* hue_root/build/art

now hue can find the png.
is this problem a bug? or i need do something i do not do? 

ps, hue version is 3.8.1

**Comment by romainr** [comment]
Yes, this was indeed a bug fixed recently: https://github.com/cloudera/hue/commit/3d9ba9a952239872d28eba2b60d304d7738ece48

You did the good thing, and if doing a fresh clone you will get the fix automatically
