### ISSUE TITLE
Feature Request: Hue Oozie workflow UI enhancement 

### ISSUE THREAD

**Issue by vanjor** [cloudera/hue#237]
Hue Oozie is so nice , as we would like to make it better:_

Feature 1: In Hue Oozie editor. the input box is narrow and not auto scrolled, is hard to view/edit the command directly
two suggest:
1. the input box support auto scroll to fix parent box width
2. the input box support scroll into multi lines

![11](https://cloud.githubusercontent.com/assets/864664/10154661/dd13566a-669c-11e5-9722-d0dbc9a94bf5.png)

Feature 2: Hue  Oozie coordinator detail list a new column with  elapsed  time, we would like to glance the elapsed  time for coordinator' history runs  to diagnose the performance changes.
would it add an column elapse time  in snapshot 1 or snapshot 2?
BTW: what does the comment means/usage in snapshot 1
![11](https://cloud.githubusercontent.com/assets/864664/10154749/e6805080-669d-11e5-93af-6cf97d1e5f34.png)
![12](https://cloud.githubusercontent.com/assets/864664/10154753/e97cf2c0-669d-11e5-8d88-31d5aaab749a.png)

**Comment by romainr** [comment]
About the comment: you usually can get some messages like 'The dependency path /a/b/c is missing so the action cannot start'

**Comment by vanjor** [comment]
Got it , thanks @romainr , sounds like "warning message"? label "comment" is not easy to understand.

**Comment by romainr** [comment]
Agreed!

**Comment by enricoberti** [comment]
@vanjor thanks for the feedback!!
we landed several commits to address the issues:
https://github.com/cloudera/hue/commit/a757e216ab72a7239ac18b5da1a46e38efa51eac
https://github.com/cloudera/hue/commit/b36e73962d47abd4bece21d0a333b39d5e8fbf1b
https://github.com/cloudera/hue/commit/b011d14c2cc079ed32b4389111a8b74913d44b95
https://github.com/cloudera/hue/commit/c6f27edb9a577f1524075bb27a276d9258b09633

thanks again!
