### ISSUE TITLE
"POST /calculator/ HTTP/1.1" 403

### ISSUE THREAD

**Issue by yoer** [cloudera/hue#238]
i have install the **calculator** app , but when i  try the calculator, click the calculate button, and got this log: 

* 127.0.0.1 - - [29/Sep/2015 00:38:25] "POST /calculator/ HTTP/1.1" 403 -
* 127.0.0.1 - - [29/Sep/2015 00:38:26] "GET /jobbrowser/?format=json&state=running&user=yoer HTTP/1.1" 500 

i can't figure out how to fix this problem
help me please, thanks a lot :)

**Comment by yoer** [comment]
i find the solution, the moko had lost  csrf token, it would be ok after append csrf_token in moko file.

* Edit calculator/src/calculator/templates/index.mako
```Python
**${ csrf_token(request) | n,unicode }**
```

* run command 
```shell
./build/env/bin/python ./tools/app_reg/app_reg.py --sync
```

**Comment by yoer** [comment]
but still have this error
```shell
127.0.0.1 - - [29/Sep/2015 00:38:26] "GET /jobbrowser/?format=json&state=running&user=yoer HTTP/1.1" 500 
```

**Comment by enricoberti** [comment]
Awesome to hear you figured out the CSRF token bit :)
The HTTP 500 is because you probably didn't configure Hue to talk to your Hadoop installation? 
What does it say on the "Check configuration" tab on the /about/ page?

**Comment by romainr** [comment]
Nice! And about the 'csrf_token' token, do you want us to fix it or could you just do a pull request?

**Comment by yoer** [comment]
@enricoberti 
thanks.

 "Check configuration" show :
```
Potential misconfiguration detected. Fix and restart Hue.

hadoop.hdfs_clusters.default.webhdfs_url 	Current value: http://localhost:50070/webhdfs/v1
Failed to access filesystem root 
```

do i must need hadoop configuration in hue? or i can just have configure **beeswax** and use hive with hadoop in other machine?

**Comment by yoer** [comment]
@romainr 

is bug in [hue docs](
http://cloudera.github.io/hue/docs-3.9.0/sdk/sdk.html#install-sdk-application)?

i want to do a pull request :laughing: ,  but could not find **cloudera.github.io** project in github..

**Comment by enricoberti** [comment]
Where Hive is running you should have an HDFS running too, correct? 
You can read about the Hue configuration here: http://gethue.com/how-to-configure-hue-in-your-hadoop-cluster/

And for the pull request, this is the SDK doc file: https://github.com/cloudera/hue/blob/master/docs/sdk/sdk.md 

:)
thanks!

**Comment by romainr** [comment]
Fixed in https://github.com/cloudera/hue/pull/239, thanks!
