### ISSUE TITLE
Editor dialects throwing errors on demo.gethue.com

### ISSUE THREAD

**Issue by Harshg999** [cloudera/hue#2387]
Describe the bug:
- On demo.gethue.com, only `Pheonix` dialect is available for querying.
- Rest other dialects ( e.g. `MySql`, `Hive` etc.) are showing error and cannot load databases

Mysql
<img width="511" alt="Screenshot 2021-07-27 at 5 25 53 PM" src="https://user-images.githubusercontent.com/42064744/127149469-6f031e25-7b60-49ed-85b4-6fe2467588cc.png">

Hive
<img width="485" alt="Screenshot 2021-07-27 at 5 26 22 PM" src="https://user-images.githubusercontent.com/42064744/127149536-e59547b5-3078-4740-872a-05280763c591.png">

Steps to reproduce it?
- Open demo.gethue.com
- Try quering different dialects

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
- Latest master

**Comment by romainr** [comment]
Hive, MySql looks good, maybe you tried during the daily reboot of the demo DBs?

**Comment by Harshg999** [comment]
I think that might be the case. Closing this issue.
