### ISSUE TITLE
Hue Web Components

### ISSUE THREAD

**Issue by sirinath** [cloudera/hue#240]
Release Hue as Webcomponets also we can use parts of it for own web development.

**Comment by enricoberti** [comment]
That's a nice idea but an enormous effort. What would you need and where?

**Comment by sirinath** [comment]
Looking to embed some charts produced in the own UI.

**Comment by enricoberti** [comment]
Yes, for that in the future the dashboards will be shareable / embeddable but we cannot promise when yet. Do you feel like contributing to the project to make it happen faster? :)
