### ISSUE TITLE
Broken eventlet version with gunicorn

### ISSUE THREAD

**Issue by byungnam** [cloudera/hue#2425]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
https://github.com/cloudera/hue/commit/39e46cd57114ea0da78c30243b5bad48d2c1e121

Above commit has raised Eventlet version to 0.31.0 but this version not compatible with gunicorn 19.9.0. Need to downgrade eventlet to 0.30.0.
ref: https://github.com/eventlet/eventlet/issues/702

Steps to reproduce it?

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
opensource 4.10.0

**Comment by byungnam** [comment]
Oh. I found it has already been fixed by [commit](https://github.com/cloudera/hue/commit/d8e436dc08408af9c593d1e62a5dad8ffcffc4ca) but not included in the latest (4.10) release.

**Comment by romainr** [comment]
Indeed, and 4.11 should come by end of August: https://github.com/cloudera/hue/milestone/4
