### ISSUE TITLE
hue.suffix confusion

### ISSUE THREAD

**Issue by sirtristancomtedeartois** [cloudera/hue#243]
hello, I follow the install guide to set the hadoop.tmp.dir as /mnt/hadoop-${user.name}-${hue.suffix}, and change a line in the hadoop-env.sh as: export HADOOP_OPTS="-Dhue.suffix= $HADOOP_OPTS -Djava.net.preferIPv4Stack=true".

Thus, as a result of the settings change in hadoop-env.sh.
When I firstly start the dfs, a directory /mnt/hadoop-root- was created instead of /mnt/hadoop-root-${hue.suffix}, this is correct and matches my expection.

However when I run the example hive query shipped with hue. I noticed that a new directory /mnt/hadoop-root-${hue.suffix} is created for the job submitted, but, shouldn't the "hue.suffix" be replaced by some value set by hue internally? Or I must set some "hue.suffix" enviroment variable myself? if the value is to be set manually, then what's the value to be set? where and when this can be set?

And as the document said "...doing so as the `hue`
user if they're using Hue and via their own user account on the command line.
This leads to some contention on the directory specified by `hadoop.tmp.dir`..."
When and how this contention could happen? If this problem chould be expained a bit more in detail in the document, for example, briefy give a simple case of a contention scenario. I think it will be great and leads a less confusion documentation on this problem for any new users.

**Comment by romainr** [comment]
This is a very old part of the doc. AFAIK this is not used, it probably dates when use impersonation was not common in Hadoop, so it can be disgarded. I will see for removing it from the docs.

https://groups.google.com/a/cloudera.org/forum/#!topic/hue-user/wHHbAga-NiM

**Comment by sirtristancomtedeartois** [comment]
Hi Romainr, Thanks for the quick response, so does it mean that I I dont have to change hadoop.tmp.dir to /mnt/hadoop-${user.name}-${hue.suffix}, even if I just leave the settings as /mnt/hadoop-${user.name}, there will be no contention?

**Comment by romainr** [comment]
Yes, just forget about it :)

And the section will be removed at the next doc refresh.
