### ISSUE TITLE
[Livy] Spark submit paramaters - HDP

### ISSUE THREAD

**Issue by syepes** [cloudera/hue#244]
Hello,

I am trying to use Hue (7fc1bb4ed0) Spark Notebooks feature in our HDP environment, but the Livy server can not submit Spark jobs correctly to YARN as in HDP we need to pass the parameter java option "hdp.version".

Does there exist anyway to configure the Livy server so that is passes the options "spark.*.extraJavaOptions" when submitting a job?

These settings work with other tools like Zeppelin and Spark-shell:

spark-defaults.conf
```
spark.driver.extraJavaOptions                -Dhdp.version=2.3.2.0-2950
spark.executor.extraJavaOptions              -Dhdp.version=2.3.2.0-2950
spark.yarn.am.extraJavaOptions               -Dhdp.version=2.3.2.0-2950
```
export HADOOP_CONF_DIR=/etc/hadoop/conf
export SPARK_HOME=/opt/spark

Best regards,
Sebastian

**Comment by romainr** [comment]
We are going to have a look but Livy submits with the Spark submit command so it should pick up automatically the local spark options if Spark is setup in the environment.

**Comment by erickt** [comment]
You should be able to set these options in the `conf/spark-defaults.conf` file according to the [documentation](https://spark.apache.org/docs/latest/configuration.html#available-properties). Does it not work for you?

**Comment by syepes** [comment]
@erickt I already have these options and more in the conf/spark-defaults.conf file, that's actually the issue when Livy submits a jobs it looks like it does not read or take into consideration these options.

**Comment by erickt** [comment]
Is your `SPARK_HOME` pointing at Spark's `libexec` directory, where `$SPARK_HOME/conf` exists? For example, I use this on my mac: `SPARK_HOME=/usr/local/Cellar/apache-spark/1.5.0/libexec`.

**Comment by romainr** [comment]
Just checking but is the conf/spark-defaults.conf on the YARN nodes synced too? Livy is going to start the remote shell there (one way to test it is to see if you get a running Livy session at least or not) and you will need the properties there too.

BTW a quick way to debug it is to run the spark submit command submitted by Livy, cf the logs:

16:03:19.832 [ForkJoinPool-1-worker-1] INFO  c.c.h.l.s.SparkSubmitProcessBuilder - Running /usr/lib/spark/bin/spark-submit --master yarn-cluster --name Livy --class com.cloudera.hue.livy.repl.Main --conf spark.yarn.isPython=true --driver-java-options -Dlivy.repl.callback-url=http://localhost:8998/sessions/0/callback -Dlivy.repl.port=0 --proxy-user romain /home/romain/projects/hue/apps/spark/java-lib/livy-assembly.jar pyspark

(note: you might need to remove '-Dlivy.repl.port=0')

**Comment by syepes** [comment]
Yes everything is in sync and working correctly on the Spark and HDP side.

When running Spark shell it reads all the correct parameter from the spark-defaults.conf
```
spark-shell --master yarn-client --proxy-user syepes
scala> sv.version
res0: String = 1.5.1
```

Is I run Livy adding the option "hdp.version" to the command line it seams to work, but when lunched through HUE it does not.

```
/opt/apps/spark/bin/spark-submit --master yarn-cluster --name Livy --class com.cloudera.hue.livy.repl.Main --driver-java-options "-Dhdp.version=2.3.2.0-2950 -Dlivy.repl.callback-url=http://fr-s-cour-edg1.alidaho.com:4080/sessions/0/callback" --proxy-user syepes /usr/local/hue/apps/spark/java-lib/livy-assembly.jar spark
```

**Comment by erickt** [comment]
I know what's going on. The problem is both the livy and spark config file filter out all options that either start with `livy.` or `spark.`. Since this `hdp.version` doesn't start with either, it's not getting passed along. Livy does have some mechanisms to set this though. You could try running:

```
env LIVY_REPL_JAVA_OPTS="-Dhdp.version=2.3.2.0-2950" ./bin/livy-server
```

Which should set the `--driver-java-options` for you. That should tide you over until we get a proper config value for this situation.

**Comment by fnerdwq** [comment]
Unfortunately this workaround - exporting `LIVY_REPL_JAVA_OPTS="-Dhdp.version=2.3.0.0-2557"` for HDP 2.3.0.0 does not work.

Only if I patch the scala code and recomplie, I get it working - workaroudwise... 

In `apps/spark/java/livy-server/src/main/scala/com/cloudera/hue/livy/server/interactive/InteractiveSessionYarn.scala`:
```scala
builder.driverJavaOptions(f"-Dlivy.repl.callback-url=$url -Dlivy.repl.port=0 -Dhdp.version=2.3.0.0-2557")
```

**Comment by romainr** [comment]
Created https://issues.cloudera.org/browse/HUE-3041

**Comment by erickt** [comment]
@syepes / @fnerdwq: I fixed `LIVY_REPL_JAVA_OPTS` in https://github.com/cloudera/hue/commit/7289799f5c314aeae1b636bc32b0bcdf67def7f3. Want to update your Livy and try again?

**Comment by fnerdwq** [comment]
Perfect, seems to be working, even without setting `LIVY_REPL_JAVA_OPTS` explicitly.
The parameters set in spark-defaults (`spark.driver.extraJavaOptions` and `spark.yarn.am.extraJavaOptions`) seem to be passed correctly down into the livy server.

Now I'm just stuck with another SparkException, but that migt be unrelated 
```
Traceback (most recent call last): Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe. :
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 6.0 failed 4 times, most recent failure: Lost task 0.3 in stage 6.0 (TID 53, …):
org.apache.spark.SparkException: Error from python worker: /usr/bin/python: No module named pyspark PYTHONPATH was: /…/spark-assembly-1.4.1.2.3.2.0-2950-hadoop2.7.1.2.3.2.0-2950.jar java.io.EOFException at java.io.DataInputStream.readInt(DataInputStream. …
```

Thanks!

**Comment by syepes** [comment]
@erickt Thanks its now working. Now the only issue is that once the session is started, if I change any  settings like "Executor Cores" and click on "Recreate" the session is not restarted.

**Comment by romainr** [comment]
Are you on master? I just tried and it worked for me.

PS: follow-up in another issue? We are also currently revamping the session page as its UX it not good.
