### ISSUE TITLE
hue-plugins mvn build

### ISSUE THREAD

**Issue by maggie-lagos** [cloudera/hue#246]
make install-ing failed, ending at

![image](https://cloud.githubusercontent.com/assets/9218071/10527965/67687edc-7361-11e5-991c-77ac33c499dd.png)

After trying the link, I found the problem occurred because the dependency was no longer at the cloudera repository. I was able to download the jar and manually install it and successfully continue with the make. 

Please update hue-plugin's pom.xml to pull the jackson-mapper jar from an existing location.

**Comment by romainr** [comment]
Yes, it is unfortunate but the repo has some hiccups from time to time, usually retrying a bit afterwards should work (we have hourly build that checks that).
