### ISSUE TITLE
hue throws NoClassDefFoundError even list jars command show the jars are actually in classpath

### ISSUE THREAD

**Issue by sirtristancomtedeartois** [cloudera/hue#248]
Hello

After I used "add jar xxx.jar" to add jars to be used by hive-hbase integration. I run a "list jars" command, in hue results tab, it reads:
 	resource
0	/mnt/hbase-0.98.15-hadoop2/lib/high-scale-lib-1.1.1.jar
1	/mnt/hbase-0.98.15-hadoop2/lib/hbase-common-0.98.15-hadoop2.jar
2	/mnt/hbase-0.98.15-hadoop2/lib/metrics-core-2.2.0.jar
3	/mnt/hbase-0.98.15-hadoop2/lib/hbase-client-0.98.15-hadoop2.jar
4	/mnt/hbase-0.98.15-hadoop2/lib/hbase-server-0.98.15-hadoop2.jar
5	/mnt/hbase-0.98.15-hadoop2/lib/hbase-hadoop2-compat-0.98.15-hadoop2.jar
6	/mnt/hbase-0.98.15-hadoop2/lib/hbase-protocol-0.98.15-hadoop2.jar
7	/mnt/hbase-0.98.15-hadoop2/lib/hbase-hadoop-compat-0.98.15-hadoop2.jar
8	/mnt/hbase-0.98.15-hadoop2/lib/htrace-core-2.04.jar
9	/mnt/apache-hive-1.2.1-bin/lib/hive-hbase-handler-1.2.1.jar
10	/mnt/apache-hive-1.2.1-bin/lib/guava-14.0.1.jar
11	/mnt/apache-hive-1.2.1-bin/lib/zookeeper-3.4.6.jar
so I suppose the jars ARE correctly included in classpath.

However, when I then run (hbase_table_3 is a table mapped to a hbase table)
insert overwrite table hbase_table_3 values (123, '123');
It just fire "java.lang.NoClassDefFoundError: org/apache/hadoop/hbase/HBaseConfiguration" error.
BUT per the results of "list jars", this should not happen since it looks like "hbase-common-0.98.15-hadoop2.jar" IS in classpath.

**Comment by sirtristancomtedeartois** [comment]
The same error occurs even when I run the basic create table statement

CREATE TABLE hbase_table_6(key int, value string) 
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,cf1:val")
TBLPROPERTIES ("hbase.table.name" = "xyz-6");

**Comment by romainr** [comment]
Did you add the jars in the lib directory of HiveServer2 too?
