### ISSUE TITLE
Setting HADOOP_CONF_DIR

### ISSUE THREAD

**Issue by secsubs** [cloudera/hue#249]
I followed the run instructions from the Readme and had to add:
export HADOOP_CONF_DIR=/etc/hadoop/conf (using CDH 5.4.7 from parcels)

**Comment by romainr** [comment]
Thanks, will be fixed in https://review.cloudera.org/r/6225/diff/#

**Comment by romainr** [comment]
Fixed: https://github.com/cloudera/hue/commit/930713cf6b8868146f748fdd08ecaf1776605f9b
