### ISSUE TITLE
Yarn mode should be configurable

### ISSUE THREAD

**Issue by secsubs** [cloudera/hue#250]
On CDH 5.4.7 (Spark 1.3), "yarn-cluster" isn't supported but looks like the code has "yarn-cluster" hardcoded. The yarn master mode should be configurable via livy-defaults.conf?

**Comment by romainr** [comment]
Did you see?
https://github.com/cloudera/hue/blob/master/apps/spark/java/README.rst#livy-configuration

There is the default client mode and then yarn-client mode. It will apply to all the jobs submitted after restarting Livy
