### ISSUE TITLE
Question: Does Hue support multiple account system

### ISSUE THREAD

**Issue by vanjor** [cloudera/hue#252]
Does hue support both hue self-register user and ldap user at the same time?
Current I found if enable ldap user, then hue self-register user is not effect.
I have no idea whether  it due to my mis-configure.

**Comment by romainr** [comment]
On the latest Hue, you can specify multiple backends:

e.g.

    [desktop]
    [[auth]]
    backend=desktop.auth.backend.AllowFirstUserDjangoBackend,desktop.auth.backend.LdapBackend

https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L228
