### ISSUE TITLE
hue to presto jdbc error

### ISSUE THREAD

**Issue by VSMDD** [cloudera/hue#2521]
Hue in cdh5.16 reports an error through the JDBC link presto,The following is the configuration and error reporting，I don't know how to solve it

![image](https://user-images.githubusercontent.com/31095506/131821065-76d0005c-335f-49b5-af3f-bc8b0cc56947.png)
![image](https://user-images.githubusercontent.com/31095506/131821217-22c4fe12-ef79-4777-9e23-f34b33725d9a.png)

**Comment by romainr** [comment]
This is a super old version, now we recommend the SqlAlchemy interface for Presto: https://docs.gethue.com/administrator/configuration/connectors/#presto

**Comment by VSMDD** [comment]
> This is a super old version, now we recommend the SqlAlchemy interface for Presto: https://docs.gethue.com/administrator/configuration/connectors/#presto

This is configured according to the official website, but there will be problems，
![image](https://user-images.githubusercontent.com/31095506/131835446-55fcb692-0c7e-42ac-bc78-28e29c57c048.png)
![image](https://user-images.githubusercontent.com/31095506/131835372-8ece4af1-720c-40ab-9010-9ab1f1db225d.png)

**Comment by VSMDD** [comment]
version hue 3.9.0+cdh5.16.2+8463，Should the interface be JDBC？
