### ISSUE TITLE
Duplicate results with Trino

### ISSUE THREAD

**Issue by jojodaser** [cloudera/hue#2530]
Describe the bug: Duplicate results occur when connecting Trino with hue. But Using sqlalchemy and trino client does not.

Steps to reproduce it:  Sometimes it happens and not have relevant logs.

Hue version: hue-4.9 or hue-4.10, use docker image from docker-hub, run on k8s

**Comment by romainr** [comment]
This sounds like https://github.com/cloudera/hue/pull/1580

**Comment by sbbagal13** [comment]
@jojodaser @romainr I am facing same issue with Trino ? Is there any resolution for this ?

**Comment by sbbagal13** [comment]
@Harshg999 any thoughts on this , looks like its critical bug

**Comment by agl29** [comment]
Hi @sbbagal13, @jojodaser 
We've made some change to the Hue code to better support Trino. Could you please try the latest version of Hue and let us know if you encounter the same issue? Your feedback is valuable. Thank you for reporting the issue.
