### ISSUE TITLE
Livy server with Kerberos

### ISSUE THREAD

**Issue by searchwizard** [cloudera/hue#254]
I have configured Hue 3.9.0 and ran the Livy Server. My Hadoop/Yarn are Kerberos enabled and when I try to create a scala notebook, I get the following error.

```
at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:111) at 
org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala) Caused by: 
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): 
SIMPLE authentication is not enabled. Available:[TOKEN, KERBEROS] at 
org.apache.hadoop.ipc.Client.call(Client.java:1410) at 
org.apache.hadoop.ipc.Client.call(Client.java:1363) at 
org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206) at 
com.sun.proxy.$Proxy7.getClusterMetrics(Unknown Source) at 
org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getClusterMetrics(Ap
plicationClientProtocolPBClientImpl.java:178) ... 30 more 15/11/09 13:02:07 INFO util.Utils: Shutdown hook called
```

**Comment by romainr** [comment]
This is https://issues.cloudera.org/browse/HUE-2658

**Comment by searchwizard** [comment]
I see HUE-2658 is open. Any idea when that is going to be released? Thanks.

**Comment by romainr** [comment]
We do not know currently

**Comment by searchwizard** [comment]
Thank you. Any workarounds (or recommendations) for running spark notebooks in a secure (Kerberos enabled) Hadoop cluster?

**Comment by romainr** [comment]
Talking to Livy would work without security, just when Livy submits the remote shell wit hthe spark-submit command, there should happen the required kerb auth. We never tried yet, would recommend to try to run a spark-submit command as the Livy user on the Livy machine and see if this one already works.

**Comment by romainr** [comment]
Livy was moved to this repository: https://github.com/cloudera/livy

**Comment by brucenelson6655** [comment]
I have tried Livy with using a kerberos ticket grated to the Livy user and it works as expected - it works but totally useless as far as securing the session.  The larger issue is two fold, on its own SPNEGO could do the trick as par as passing the current principal - with hue it gets more complicated - unlike hive on spark where the spark-submit under yarn is owned by hive, Livy could pick up the user // princ from hue but we would run into a the complication of impersonation.
