### ISSUE TITLE
Expand the CLI with addition Query/Storage operations

### ISSUE THREAD

**Issue by romainr** [cloudera/hue#2545]
https://docs.gethue.com/developer/api/cli/

TODO:
- Auth: 
  - On auth, auto select SQL and storage connectors if only one, or select from the list
  - Remember last value used: e.g. dialect/connector, propose last api URL/login as default when relogin..
- Query: select dialect, execute a custom statement reusing Notebook Python lib
- Storage: download, upload

**Comment by pixpack** [comment]
Hey, I would like to work on this. The original repository for the CLI at https://github.com/gethue/compose seems to be missing though. I also can't seem to find the CLI code in this repository. Could you give me some guidance about this?

**Comment by bjornalm** [comment]
This feature has been dropped in Hue for now. 

@pixpack I apologise that your offer to contribute was left unanswered for so long. We are working on getting our community processes back on track. Are you still interested in contributing, if so any preferences for backend or frontend work?
