### ISSUE TITLE
How to connect livy-spark with standalone spark cluster ?

### ISSUE THREAD

**Issue by andrimirandi** [cloudera/hue#255]
Hi, 

Can you help to point some tutorials or explain which configuration that I have to change to connect livy-spark with running spark standalone cluster, 
- whether it is possible right now ?
- or do I have to create livy-spark cluster ?

I have try the following and its not working : 
- POST the session creation with the following data {"kind": "spark", "master" : "spark://localhost:7077" }
- Start the livy-server with master parameters : ./bin/livy-server --master spark://localhost:7077

havent got any other idea, and I cannot find any reference to set master in the configuration

Thanks

**Comment by romainr** [comment]
You should configure you Spark as Standalone, then Livy will pick up automatically your Spark options if Spark if configured property. Then if you run Livy in local mode (the default), it should work.

**Comment by andrimirandi** [comment]
that work @romainr , thanks
sorry for the late reply

**Comment by shamsmali** [comment]
@andrimirandi could you please explain me how you got that working. For me it doesn't work at all and also even tried with YARN too

**Comment by alivcor** [comment]
@shamsmali (and to anyone else who faces this issue):

1. Navigate to `livy-0.5.0-incubating-bin/conf`
2. `cp livy.conf.template livy.conf`
3. `vi livy conf`

and uncomment the line:

`livy.spark.master = spark://your-spark-standalone-cluster-url:7077`

(Without quotes).
