### ISSUE TITLE
Build Failure Error

### ISSUE THREAD

**Issue by JMetai** [cloudera/hue#256]
Hi,

I am getting following error when I try to "make apps" after cloning this repo. I installed all dependencies. Please advise.
Here is the error:

$ cd hue
$ make apps
cd /home/ec2-user/hue/maven && mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hue Maven Parent POM 3.9.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/1.0/maven-enforcer-plugin-1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:03.440s
[INFO] Finished at: Thu Nov 19 17:00:32 EST 2015
[INFO] Final Memory: 4M/117M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-enforcer-plugin:1.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.mav]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
make: *** [parent-pom] Error 1

**Comment by romainr** [comment]
You probably have a connectivity problem on your EC2, or you tried to compiled at a bad timing when the apache maven repo was not available.

**Comment by JMetai** [comment]
Thank you for your response. I am able to download other packages with out any issue on EC2 instance, I verified and don't see any issue with proxy. I included proxy username, proxy password, proxy port, proxy server name in Maven's settings.xml file as well. I tried to compile several times during the day and I tried few minutes ago too, still no luck, I don't think maven repo is down. Do you know any other issue preventing from compiling? or Do I have to setup proxy in any other file with maven? 
Also I downloaded maven enforcer plugin manually and moved over to following folder 
/usr/share/maven2/poms/maven-enforcer-plugin-1.0.pom
and I tried to run "mvn compile" from /usr/share/maven2/poms folder but still didn't work for me. Following error I get when I try to execute "mvn compile"

$ cd /usr/share/maven2/poms
$ pwd
/usr/share/maven2/poms
$ mvn compile
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.107s
[INFO] Finished at: Thu Nov 19 21:36:31 EST 2015
[INFO] Final Memory: 3M/117M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/ec2-user/hue). Please verify you invoked Maven from the corre]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by romainr** [comment]
I tried again to rebuild it yesterday and it worked, I installed maven2 from the binary release.

**Comment by vskc23** [comment]
Sir,
I have built the maven properly and verified,
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-25T01:19:05+05:30)
Maven home: /home/chaitanya/maven
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-39-generic", arch: "amd64", family: "unix"



But when i'm building using make apps,
I'm getting the same error,
please help me out
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.cloudera.hue:hue-parent >---------------------
[INFO] Building Hue Maven Parent POM 4.2.0-SNAPSHOT
[INFO] --------------------------------[ pom ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/1.0/maven-enforcer-plugin-1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.565 s
[INFO] Finished at: 2018-04-28T13:44:24+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-enforcer-plugin:1.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-enforcer-plugin:jar:1.0: Could not transfer artifact org.apache.maven.plugins:maven-enforcer-plugin:pom:1.0 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Temporary failure in name resolution: Unknown host repo.maven.apache.org: Temporary failure in name resolution -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Makefile:122: recipe for target 'parent-pom' failed
make: *** [parent-pom] Error 1
Thanks and Regards,
Krishna

**Comment by romainr** [comment]
This is because is seems like the Maven website was done or you did not have Internet
