### ISSUE TITLE
CDH 5.5 Hue 

### ISSUE THREAD

**Issue by heenameena** [cloudera/hue#257]
I have installed CDH 5.5 and has Hue. So what is the difference between Hue that came along with CDH and Hue in this repo?

**Comment by romainr** [comment]
You can compare the commit difference if you want https://github.com/cloudera/hue/tree/cdh5.5.0-release

Generally Hue in CDH is more integrated with CDH and is lagging by ~1 or 2 months on master http://gethue.com/hue-3-9-with-all-its-improvements-is-out/
