### ISSUE TITLE
LDAP auth error: can't decode byte 0xc3

### ISSUE THREAD

**Issue by arturbrandysonwelo** [cloudera/hue#2570]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
Yes but it is closed (#2250).

Describe the bug:
In HUE 4.10.0 some LDAP users are not able to login anymore.

[14/Jun/2021 08:46:34 +0000] backend      INFO     Augmenting users with class: <class 'desktop.auth.backend.DefaultUserAugmentor'>
[14/Jun/2021 08:46:34 +0000] forms        ERROR    LDAP auth error: 'ascii' codec can't decode byte 0xc3 in position 18: ordinal not in range(128)

This blocks migration to 4.10 if connected to LDAP

Steps to reproduce it?
Connect to LDAP directory with users containing special characters in their names (some polish letters: ł ó ą ...)

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
open source 4.10 - OS: Windows 10; Browsers: Firefox

Connected with issue: #2250

**Comment by gzhukov** [comment]
Hi, simple patch for this issue is here: https://github.com/cloudera/hue/pull/2622

**Comment by gzhukov** [comment]
Also looks like sometimes we gets binary string in "[username_pattern](https://github.com/cloudera/hue/blob/3d13bc132bdcfd623525353fee7303e8f8c3ecce/apps/useradmin/src/useradmin/ldap_access.py#L354)":
Pushed fix to the same branch.

Also if you use gethue docker image with non-ascii locale, you should rebuild gethue image with additional steps:
`
FROM myhue:4.10.0
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales && apt-get clean
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

`
It prevents logger errors for non-ascii symbols.
