### ISSUE TITLE
[Search] search can not show detail of a doc while search with a id field

### ISSUE THREAD

**Issue by yushaopeng** [cloudera/hue#258]
Hello, I found that when I do search with a id field, such as "id:553573403", hue returns a doc with id field highlight, and then i click for the doc detail, the browser send a POST request to "/search/get_document" with a form param id in "id[]:<em>553579908</em>", hue response with "{"status": 1, "message": "This document does not have any index id."}". I find that the solr actually response id field with highlight. can hue side so some special handle while search with id field?

**Comment by yushaopeng** [comment]
the POST form param id is : " id[]:&lt;em&gt;553579908&lt;/em&gt;"

**Comment by romainr** [comment]
On which Hue version are you?

**Comment by yushaopeng** [comment]
3.7.1

**Comment by romainr** [comment]
Ok I get it! Will have a look, obviously if we have the <em> tags in the id it won't work.

**Comment by romainr** [comment]
https://review.cloudera.org/r/6408/

**Comment by romainr** [comment]
https://github.com/cloudera/hue/commit/ccc1f907d4bda68a0581db38237a0cef60eee371
