### ISSUE TITLE
How to use SQL SCRATCHPAD of another website？

### ISSUE THREAD

**Issue by jianwei2** [cloudera/hue#2591]
hi all
       I want use my UI 、my  "Execute" button, and save sql by my interface 。 How I fetch sql change.   When the sql changes, I want to get it, because I want to save it in my database . so, how I get it in my website.

**Comment by Harshg999** [comment]
Hi @jianwei2, maybe this discussion can help you!
https://github.com/cloudera/hue/discussions/2224

**Comment by jianwei2** [comment]
> Hi @jianwei2, maybe this discussion can help you! #2224
Thank you 。  Is SQL SCRATCHPAD open source ?  How can I get the source code ?
