### ISSUE TITLE
Unsupported syntax in python 3

### ISSUE THREAD

**Issue by InvalidPointer** [cloudera/hue#2597]
This syntax causes SyntaxError when running in python 3 environment. https://www.python.org/dev/peps/pep-3109/#grammar-changes

https://github.com/cloudera/hue/blob/c01df1ce5bc1145e42937f911a9eb09d2d61eec3/desktop/libs/notebook/src/notebook/connectors/rdbms.py#L43

**Comment by SbloodyS** [comment]
I'm also facing the same problem.Have you solved it?

**Comment by InvalidPointer** [comment]
I've replaced it with `raise QueryError(message).with_traceback(sys.exc_info()[2])`.
Also you need to fix the same problem in `jdbc.py`.

**Comment by InvalidPointer** [comment]
Any news?

**Comment by InvalidPointer** [comment]
☹️

**Comment by Harshg999** [comment]
Thank you @InvalidPointer for reporting the issue! This has been fixed recently in the PR https://github.com/cloudera/hue/pull/3045.
Closing the issue.
