### ISSUE TITLE
_make_url fails when called from navigator_client search_entities

### ISSUE THREAD

**Issue by InvalidPointer** [cloudera/hue#2599]
Because instead of dict tuple of key-value tuples is provided.

https://github.com/cloudera/hue/blob/c01df1ce5bc1145e42937f911a9eb09d2d61eec3/desktop/libs/metadata/src/metadata/catalog/navigator_client.py#L351

https://github.com/cloudera/hue/blob/c01df1ce5bc1145e42937f911a9eb09d2d61eec3/desktop/core/src/desktop/lib/rest/http_client.py#L251

**Comment by Harshg999** [comment]
Thank you @InvalidPointer for reporting this bug!
This has been fixed in https://github.com/cloudera/hue/pull/2647.
