### ISSUE TITLE
Zookeeper browser doesn't work with Zookeeper 3.4.6 REST server

### ISSUE THREAD

**Issue by shobull** [cloudera/hue#260]
REST API in Zookeeper 3.4.6 doesn't respond with JSON by default (It returns empty string). Script *apps/zookeeper/src/zookeeper/rest.py* requests without header "Accept: application/json" so that it fails. Using header "Accept: application/json" everything works.

**Comment by romainr** [comment]
In follow-up of http://gethue.com/new-zookeeper-browser-app/#comment-60688, would you send a pull request?

**Comment by shobull** [comment]
There it is https://github.com/cloudera/hue/pull/263

**Comment by romainr** [comment]
Thanks!
