### ISSUE TITLE
'ascii' codec can't encode characters in position 92-94: ordinal not in range(128)

### ISSUE THREAD

**Issue by q127981** [cloudera/hue#2606]
Steps to reproduce it?

**Error when SQL contains Chinese characters.**

![image](https://user-images.githubusercontent.com/31874319/137311988-298fcd95-8c5c-4e34-957f-75c74976774f.png)

![image](https://user-images.githubusercontent.com/31874319/137311914-0df894ce-8210-46fb-91b3-cc51febf82cf.png)

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

HUE 4.10

**Comment by yixinGod** [comment]
How to solve this problem？

**Comment by Harshg999** [comment]
Thanks @szsuyuji for pointing out the fix!
The issue is resolved in the latest 4.11.0 release.
