### ISSUE TITLE
The Spark session could not be created in the cluster

### ISSUE THREAD

**Issue by junseokpark** [cloudera/hue#261]
I upgrade CDH 5.4 to CDH 5.5.
I built livy server for using spark on Hue 3.9.0.
Then, I added
[desktop]
  app_blacklist=
to hue configuration. (Hue Service Advanced Configuration Snippet (Safety Valve) for hue_safety_valve.ini)

However, I cannot run pyspark on Hue 3.9.0.

It says:
The Spark session could not be created in the cluster: SLF4J: Class path contains multiple SLF4J bindings. SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/jars/avro-tools-1.7.6-cdh5.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class] SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation. 15/12/02 21:55:57 INFO RMProxy: Connecting to ResourceManager at chrome011/10.0.2.211:8032 15/12/02 21:55:57 WARN UserGroupInformation: PriviledgedActionException as:junseokpark (auth:PROXY) via root (auth:SIMPLE) cause:org.apache.hadoop.security.authorize.AuthorizationException: User: root is not allowed to impersonate junseokpark ERROR: org.apache.hadoop.security.authorize.AuthorizationException: User: root is not allowed to impersonate junseokpark

In addition, I think that WARN message is related to LDAP setting.

Thanks.

**Comment by romainr** [comment]
Livy is not supported in CDH yet but in your error case, you need to specify root as a proxy user, replace hue by root in the core-site.xml, e.g. http://www.cloudera.com/content/www/en-us/documentation/enterprise/latest/topics/cdh_ig_cdh_hue_configure.html?scroll=topic_15_4#topic_15_4_1_unique_1

http://gethue.com/spark/
