### ISSUE TITLE
[File Browser] Allow TAB in File Editor

### ISSUE THREAD

**Issue by guignol** [cloudera/hue#262]
The behavior of the TAB key in Hue default when editing file (meaning moving to the next HTML anchor). When editing file TAB should be consider as a character as it might be the value separator. Maybe a check box to enable or disable the tab behavior can be set + some javascript to handle tab when focus is in the textbox

**Comment by romainr** [comment]
How about http://superuser.com/questions/67934/typing-the-tab-character-in-browser-text-boxes ?
