### ISSUE TITLE
Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE

### ISSUE THREAD

**Issue by 932397261com** [cloudera/hue#2635]
Describe the bug:
![image](https://user-images.githubusercontent.com/45875741/141044682-431353ee-0ebe-44c7-8fb1-5183e2ac9f68.png)
Submitting a large SQL task will report this error, is there any way to solve it?

Hue version or source? 
CDH6.3.2

**Comment by Akhilsnaik** [comment]
Its in here : https://github.com/cloudera/hue/blob/8aa24a89648ab7c079cbce7369481fefbc05efc7/desktop/core/ext-py/Django-1.11.29/django/conf/global_settings.py#L301 

Changing this has to help.

```
$ cp /opt/cloudera/parcels/CDHlib/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/conf/global_settings.py <Backup to desired folder>

3) Edit the file
$ vim /opt/cloudera/parcels/CDH/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11.20-py2.7.egg/django/conf/global_settings.py

DATA_UPLOAD_MAX_MEMORY_SIZE = None
```

**Comment by 932397261com** [comment]
it works well,thanks!
