### ISSUE TITLE
[Question]: Usage of aggregate fields in Search Dashboards

### ISSUE THREAD

**Issue by asulis** [cloudera/hue#264]
Dear Hue team, 
in your presentation slides "Interactive Big Data Analysis with Solr, Spark and Hue" (http://www.slideshare.net/gethue/hadoop-summit-interactive-big-data-analysis-with-solr-spark-and-hue), in slides from 18 to 22 you talk about aggregate fields definition and their usage inside the Search Dashboards. The slides show two very interesting features, as single aggregate field value (average bytes_I) in slide 19, and the timeline with a target field aggregated choosing a custom metric instead of the sum metric only (as shown in slide 22). The issue is that I am not able to figure out how to draw these very useful dashboards in my own hue instance. I am using the 3.9.0 version. Have these features been included in the last release yet? Could you give me some suggestions about how to use them?

**Comment by romainr** [comment]
This is still a beta for now, you can enable it by setting it to true
https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L982

**Comment by asulis** [comment]
Thank you very much Romain. I'll try it. When are you planning to include that in a stable release?

**Comment by romainr** [comment]
Current plan is for Hue 4, which is for sometime during the second part of 2016

**Comment by tarekabouzeid** [comment]
hi @romainr can you please tell me which configuration exactly to set to true to enable the metric "X2" in the hue dashboards ? thanks so much in advance

**Comment by romainr** [comment]
This is
https://github.com/cloudera/hue/blob/master/desktop/conf/pseudo-distributed.ini.tmpl#L1129
(still in development yet)
