### ISSUE TITLE
[fields] an endless loop if the context has only one ' " '

### ISSUE THREAD

**Issue by jaluo** [cloudera/hue#266]
Hello, I Found that when I post a file, if the first line has a ’ " ‘, and dosn't has the other one in the context, field_values_from_separated_file() will has an endless loop:
while content:
    last_newline = content.rfind('\n')
    if last_newline > -1:
      # If new line is quoted, skip this iteration and try again.
      if content[:last_newline].count('"') % 2 != 0:
        content += fh.read()
        continue

**Comment by sai-krish** [comment]
@jaluo  Can you give me some more context on what the above code does. Are you referring to a specific app in hue? Also, what do you mean by post a file ?

**Comment by romainr** [comment]
Sai, I guess he is talking about the create table wizard in metastore app. If the sample line as an even number of " seems like we could infinite loop

**Comment by sai-krish** [comment]
@jaluo  I am not able to reproduce the issue locally with even or odd quotes in a single line. Can you provide a sample that's failing for you.

Thanks.

**Comment by jaluo** [comment]
I found this issue on http://ip:port/indexer/#create/wizard/fields when I create a indexer. With the file:
id	"title	name
1	hello	hello

**Comment by sai-krish** [comment]
Looks genuine. Created https://issues.cloudera.org/browse/HUE-3085 to track this.

**Comment by romainr** [comment]
How are we on this one?

**Comment by sai-krish** [comment]
Fixed for 3.10 
https://github.com/cloudera/hue/commit/d8aa0f649d96f2278def266beab4a288f17de7a2
