### ISSUE TITLE
Is there a way to use static tables schemas for sql-scratchpad autocomplete?

### ISSUE THREAD

**Issue by Branyer** [cloudera/hue#2690]
In my use case I would only need to use this editor, to save sql queries in my react app.

I have the schema of the tables in a javascript obejct.

Is there a way to make sql-scratchpad autocomplete recognize this schemas and work offline?

**Comment by Harshg999** [comment]
Hi @Branyer! Thank you for your question.
`/autocomplete` endpoints retrieves schema info from the connected/plugged-in databases so it cannot recognise the static table schema in javascript object.

But Hue is open source ;) so I think you can try tweaking the sql-scratchpad UI calls to go via a method which works the same way /autocomplete does in the backend but it retries schema info from your javascript object.

Hope it helps!

**Comment by Harshg999** [comment]
Closing this issue since this was answered!
