### ISSUE TITLE
Kerberos Tickets shall not be assumed to be renewable *by default*

### ISSUE THREAD

**Issue by markus289** [cloudera/hue#2695]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
I could not find the issue at the above mentioned locations.

Describe the bug:
When setting up a Cloudera instance, I decided to use the [FreeIPA provided playbook](https://github.com/freeipa/ansible-freeipa) to setup authentication, including Kerberos. The default [`krb5.conf`](https://github.com/freeipa/ansible-freeipa/blob/b0252fb57a86ccf3a0a077c052f3b0d0256bc061/roles/ipaclient/action_plugins/ipaclient_get_otp.py#L94) that is created by this playbook allows tickets to be renewable, but that is not the default. In other words, `renew_lifetime` is not set.

Unfortunately, Hue assumes that the default is that all tickets are renewable _by default_. This seems to stem from the fact that Cloudera's default `krb5.conf` includes `renew_lifetime = 7d`.

Here is the relevant part of `/var/log/hue/kt_renewer.log` that is shown when Hue starts without `renew_lifetime` set in `krb5.conf`:

> [24/Nov/2021 17:18:44 ] settings     INFO     Welcome to Hue 4.6.0
> [24/Nov/2021 08:18:47 -0800] decorators   INFO     AXES: BEGIN LOG
> [24/Nov/2021 08:18:47 -0800] decorators   INFO     Using django-axes 2.2.0
> [24/Nov/2021 08:18:47 -0800] hiveserver2  WARNING  Job Browser app is not enabled
> [24/Nov/2021 08:18:48 -0800] api          WARNING  Oozie application is not enabled: Model class oozie.models.Job doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
> [24/Nov/2021 08:18:48 -0800] __init__     INFO     Couldn't import snappy. Support for snappy compression disabled.
> [24/Nov/2021 08:18:48 -0800] kt_renewer   INFO     Reinitting kerberos retry attempt 0 from keytab /usr/bin/kinit -k -t /var/run/cloudera-scm-agent/process/28-hue-KT_RENEWER/hue.keytab -c /var/run/hue/hue_krb5_ccache hue/worker.lab.some.domain@LAB.SOME.DOMAIN
> [24/Nov/2021 08:18:50 -0800] kt_renewer   INFO     Renewing kerberos ticket to work around kerberos 1.8.1: /usr/bin/kinit -R -c /var/run/hue/hue_krb5_ccache
> [24/Nov/2021 08:18:50 -0800] kt_renewer   ERROR    Couldn't renew kerberos ticket in order to work around Kerberos 1.8.1 issue. Please check that the ticket for 'hue/worker.lab.some.domain@LAB.SOME.DOMAIN' is still renewable:
>   $ klist -f -c /var/run/hue/hue_krb5_ccache
> If the 'renew until' date is the same as the 'valid starting' date, the ticket cannot be renewed. Please check your KDC configuration, and the ticket renewal policy (maxrenewlife) for the 'hue/worker.lab.some.domain@LAB.SOME.DOMAIN' and `krbtgt' principals.

Ignore the date, I had filing this bug on my to do list for quite some time now...

Recreating the steps that Hue takes to create a ticket results in a non-renewable ticket.

```
$ /usr/bin/kinit -k -t /var/run/cloudera-scm-agent/process/28-hue-KT_RENEWER/hue.keytab -c /var/run/hue/hue_krb5_ccache hue/worker.lab.some.domain@LAB.SOME.DOMAIN
$ /usr/bin/kinit -R -c /var/run/hue/hue_krb5_ccache
kinit: KDC can't fulfill requested option while renewing credentials
$ klist -c /var/run/hue/hue_krb5_ccache -f
Ticket cache: FILE:/var/run/hue/hue_krb5_ccache
Default principal: hue/worker.lab.some.domain@LAB.SOME.DOMAIN

Valid starting       Expires              Service principal
11/24/2021 17:43:11  11/25/2021 17:43:11  krbtgt/LAB.SOME.DOMAIN@LAB.SOME.DOMAIN
        Flags: FIA

$ man klist
	F    Forwardable
	I    Initial
	A    preAuthenticated

NOTE: missing from list
	R    Renewable
```

The "official" solution may be to let Cloudera manage `krb5.conf`. Another solution may be to edit the file that is generated by FreeIPA's playbook manually. A third solution, which we currently use, is to write this in `/etc/krb5.conf.d/renew_lifetime` (as this is the easiest to automate using Ansible):

```
[libdefaults]
  renew_lifetime = 7d
```

**Proposed solution:**
But I would like to propose the following solution: in [`kt_renewer.py`](https://github.com/cloudera/hue/blob/56cc4878397538673854421e6af295d3d67cfb97/desktop/core/src/desktop/kt_renewer.py#L31) add `-r 7d` to the list of options to `kinit`. This would remove the (unwritten) assumption that tickets are renewable by default.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
Above log comes from CDH 7.1.7.0 (CDH-7.1.7-1.cdh7.1.7.p0.15945976), but this is applicable for current versions of Hue.

**Comment by quadoss** [comment]
Please check HUE-9521 which is specifically for this scenario where if renew_lifetime is set to 0, add in a property under kerberos krb5_renewlifetime_enabled to false.

https://github.com/cloudera/hue/commit/0af5e238db207f9cf8affbdb67bbb45175767005

**Comment by markus289** [comment]
Thank you for this hint.
