### ISSUE TITLE
How to configurate Postgresql, so that I can access Postgresql database on HUE?

### ISSUE THREAD

**Issue by WeiningZheng** [cloudera/hue#2710]
dear all, I'v got a problem during connect my postgresql in Centos 7. 
I have a few databases on  me@10.10.19.113: 5432, namely db1, db2, db3, db4.......dbN. 
I am trying to build it on hue with db1, it works with the following code

[Notebook]
[[interpreters]]
[[[postgresql]]]
      name = postgresql
      interface=sqlalchemy
      options='{"url": "postgresql://postgres:[me@10.10.19.113:5432/db1]"}'

[librdbms]
[[databases]]
[[[postgresql]]]
      nice_name="My pgsql1"
      name=db1
      engine=postgresql
      host=10.10.19.113
      port=5432
      user=me
      password=pws
      #options={"init_command":"SET NAMES 'utf8'"}

But How can I connect all the databses (db1, .....,dbN)?  
Thanks and I am looking forward to get your feedback soon. 

PS. It is sucessfully connecting to all databases of MySQL, however it doesn't work for Postgresql.

**Comment by WANGXiao0622** [comment]
Same question, i've tried to config multiple postgresql databases in the 
```
[librdbms]
[[databases]]
[[[postgresql]]]
[[[postgresql2]]]
[[[postgresql3]]]...
```
but it didn't work out. Neither did I config the `"name=" `as null or mark as` "#name="`

i'm using postgresql version 9.2.21 and Hue version 4.10.0

I would be grateful if you have any suggestions.
Thanks
