### ISSUE TITLE
Support to set cache-control in Hue response header

### ISSUE THREAD

**Issue by yuexinmao** [cloudera/hue#2835]
ICurrently it seems not possible to configure cache-control header on Hue HTTP response. While capturing the HTTP response, we find that Hue always sets cache-control header to "no-cache" only which does not remove the cache. Cache-control needs to be able to be configured to other values such as "no-cache, no-store" for enhanced data security. 

There are other HTTP response headers that can be controlled via hue.ini such as secure_content_security_policy, secure_browser_xss_filter, secure_content_type_nosniff etc. However, there is no such setting available for cache-control header.

Raising this issue to file this requirement as a feature request.

**Comment by Harshg999** [comment]
Hey @yuexinmao, thanks for flagging this issue!
Recently @athithyaaselvam has been working on a related issue and the PR is up for review: https://github.com/cloudera/hue/pull/3296

I feel the PR also solves this issue and now we are introducing a config to disable cache and adding headers to restrict caching. (There can be performance issues in Hue if enabled)

It will be available in the master soon and in a subsequent release in the near future.
