### ISSUE TITLE
Apache Impala query with `LIMIT` 0

### ISSUE THREAD

**Issue by Montana** [cloudera/hue#2845]
Hey all, 

I've searched and have found some queries submitted to Impala with `LIMIT 0`,  in which the logical case is `null rows`. My question is why would someone want to limit this to `0`? 

One thought I had was to check the query, or connection, or if say, you were limit fetching a lot of rows from a huge table or a data set every time you run a `SQL` query. 

My understanding is the argument to the `LIMIT` clause must evaluate to a constant value. I guess some questions I have are as follows:

How are query fragments distributed among the impala executors, and is there a way to load balance the query load among executors in case when we have dedicated executor and co-ordinator?

Is this currently the best solution? https://docs.cloudera.com/documentation/enterprise/latest/topics/impala_admission.html#admission_control

Thanks so much,
Montana Mendy

**Comment by milletnis** [comment]
This is propably related to a Impala JDBC driver flag called "**PreparedMetadataLimitZero**"

Please also see here:
https://www.cloudera.com/documentation/other/connectors/impala-jdbc/latest/Cloudera-JDBC-Driver-for-Impala-Install-Guide.pdf
https://community.cloudera.com/t5/Support-Questions/Impala-adding-a-LIMIT-0-clause-when-issuing-query-from/td-p/88803
https://community.cloudera.com/t5/Support-Questions/Impala-query-with-limit-0/m-p/331366
