### ISSUE TITLE
create new APP error

### ISSUE THREAD

**Issue by endymecy** [cloudera/hue#288]
I use command “./build/env/bin/hue create_desktop_app calculator” create a new app and use command "./build/env/bin/python tools/app_reg/app_reg.py --install calculator --relative-paths" to reg it , then i found an issue that all static files were copied to "build/static" dir instead of "build/static/calculator" dir. my app can't show app images,because it can't find it in right path.

**Comment by romainr** [comment]
Did you try on hue master or an older Hue?

**Comment by endymecy** [comment]
my version is 3.9.0

**Comment by romainr** [comment]
Yes, this is a bug fixed by https://github.com/cloudera/hue/commit/3d9ba9a952239872d28eba2b60d304d7738ece48 which will be in the future Hue 3.10
