### ISSUE TITLE
dependency about akka in livy-server/livy-croe

### ISSUE THREAD

**Issue by airokey** [cloudera/hue#291]
The original question is when refreshing page in notebook, an existing session in livy-server won't be killed, even close the page, and this happened in firefox e.t.c(exclude chrome).
I have just fixed this bug with heartbeat mechanism, while merging my code, i found this:
        <dependency>
            <groupId>org.scalatra</groupId>
            <artifactId>scalatra_${scala.binary.version}</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.typesafe.akka</groupId>
                    <artifactId>akka-actor_${scala.binary.version}</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
Actually, i used akka, so the true question is if i can't use akka?

**Comment by airokey** [comment]
Oh, there's something wrong in xml code. The code is in livy-core/pom.xml line 59~68

**Comment by romainr** [comment]
Livy was moved to https://github.com/cloudera/livy
