### ISSUE TITLE
Latest docker image is not working

### ISSUE THREAD

**Issue by elferherrera** [cloudera/hue#2925]
Running HUE with the latest docker image (20220712-140101) gets an `Internal Server Error` in the browser.

The command used was
```
docker run -it -p 8888:8888 gethue/hue:latest
```

The error in the logs is
```
ValueError: Missing staticfiles manifest entry for 'desktop/js/bundles/hue/defaultVendors~hue-cdd60c62-bundle-1f13ec821594913a93cd.js'
```

**Comment by vivostar** [comment]
+1, I come across this problem, too.

**Comment by kailanyue** [comment]
+1, I come across this problem, too.

**Comment by steelcolosus** [comment]
+1 same here

**Comment by Overcrash86** [comment]
+1 same here, too

**Comment by Harshg999** [comment]
Hi everyone, this issue should be fixed now with the latest docker image.
