### ISSUE TITLE
Helm Chart doesn't support enable_all_interpreters flag 

### ISSUE THREAD

**Issue by preetsindhal** [cloudera/hue#2929]
Describe the bug:

Current helm chart only includes the [[interpreters]]  under the [notebook] section thus all other flags under [notebook] are set to default and can't be changed for example 'enable_all_interpreters' and not allowing to enable only the selected editors from the whitelisted apps.

Steps to reproduce it?

Deploy Helm chart and try to set 'enable_all_interpreters' flag to false under [notebook] section

**Comment by Harshg999** [comment]
This feature was recently reverted from the master branch: https://github.com/cloudera/hue/commit/b2bab308e08895b118b7f6a84c0a776a897d39bb
