### ISSUE TITLE
make apps ERROR

### ISSUE THREAD

**Issue by 1356469429** [cloudera/hue#293]
Failed to parse plugin descriptor for org.apache.maven.plugins:maven-enforcer-plugin:1.0 (/root/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.0/maven-enforcer-plugin-1.0.jar): error in opening zip file -> [Help 1]

**Comment by 1356469429** [comment]
--- Creating virtual environment at /home/hadoop/hue-release-3.7.1/build/env
python2.6 /home/hadoop/hue-release-3.7.1/tools/virtual-bootstrap/virtual-bootstrap.py \
		-qq --no-site-packages /home/hadoop/hue-release-3.7.1/build/env
--- /home/hadoop/hue-release-3.7.1/build/env ready
cd /home/hadoop/hue-release-3.7.1/maven && mvn install 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Hue Maven Parent POM 3.7.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.apache.maven.plugins:maven-enforcer-plugin:jar:1.0 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.238s
[INFO] Finished at: Tue Jan 12 22:11:31 PST 2016
[INFO] Final Memory: 4M/43M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to parse plugin descriptor for org.apache.maven.plugins:maven-enforcer-plugin:1.0 (/root/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.0/maven-enforcer-plugin-1.0.jar): error in opening zip file -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginDescriptorParsingException
make: *** [parent-pom] Error 1

**Comment by enricoberti** [comment]
Which system are you building it on? Which maven version do you have?

**Comment by enricoberti** [comment]
Actually, make sure you are running Maven 3+ with an Oracle JDK, not OpenJDK

**Comment by tdevendra** [comment]
Install Maven 3 and above with bin not source and set below variables
export M2_HOME=/usr/local/apache-maven/apache-maven-3.2.1
export M2=$M2_HOME/bin
export PATH=$M2:$PATH
