### ISSUE TITLE
Autocomplete does not work with fully qualified names involving catalogs/datasources

### ISSUE THREAD

**Issue by manojmit11** [cloudera/hue#2937]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
**No**

Describe the bug:
With Trino/Presto it's a widespread/everyday use case to write queries across catalogs/data sources. 

A simple example could be joining a tables in MySQL and hive.

_SELECT *
FROM mysql.mydb.mytable a JOIN hive.mydb.mytable b
ON a.id = b.id;_

So there are 3 levels of autocomplete `catalog`.`database`.`table`  . The autocomplete included in hue only supports 2 levels `database`.`table`

Steps to reproduce it?
Across all browsers and versions.

**Comment by manojmit11** [comment]
Hi @JohanAhlen : Can you confirm if hue autocomplete supports the above use case?

**Comment by divincode** [comment]
Hi @manojmit11 have gone through code or know from where the autcomplete feature works,I will also try to look into it.
