### ISSUE TITLE
make apps errors about guppy

### ISSUE THREAD

**Issue by billbargens** [cloudera/hue#294]
The error messages are as follows:

--- Building egg for guppy-0.1.10
running bdist_egg
running egg_info
writing guppy.egg-info/PKG-INFO
writing top-level names to guppy.egg-info/top_level.txt
writing dependency_links to guppy.egg-info/dependency_links.txt
reading manifest file 'guppy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'guppy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'guppy.sets.setsc' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/hue/hue-release-3.9.0/build/env/include/python2.7 -c src/sets/sets.c -o build/temp.linux-x86_64-2.7/src/sets/sets.o
gcc: ./specs: Is a directory
error: command 'gcc' failed with exit status 1
make[2]: *** [/soft/hue/hue-release-3.9.0/desktop/core/build/guppy-0.1.10/egg.stamp] Error 1
make[2]: Leaving directory `/soft/hue/hue-release-3.9.0/desktop/core'
make[1]: *** [.recursive-env-install/core] Error 2
make[1]: Leaving directory `/soft/hue/hue-release-3.9.0/desktop'
make: *** [desktop] Error 2

**Comment by enricoberti** [comment]
hi!
on which system are you trying to build it? have you tried building master to see if you have the same problem?

**Comment by billbargens** [comment]
I download the package from: https://github.com/cloudera/hue/releases/tag/release-3.9.0.
The working system is CentOS release 6.6.

**Comment by 1356469429** [comment]
try 
yum install gcc

**Comment by billbargens** [comment]
GCC had been installed, and the version is 4.4.7 20120313.

**Comment by 1356469429** [comment]
I met this problem before
error: command 'gcc' failed with exit status 1
I reinstall the development packages

**Comment by billbargens** [comment]
Could you please show me more details about your steps?

**Comment by 1356469429** [comment]
you can try to reinstall the development packages

**Comment by billbargens** [comment]
You means all of this listed in https://github.com/cloudera/hue#development-prerequisites:
Oracle's JDK (read more here)
ant
asciidoc
cyrus-sasl-devel
cyrus-sasl-gssapi
gcc
gcc-c++
krb5-devel
libtidy (for unit tests only)
libxml2-devel
libxslt-devel
make
mvn (from apache-maven package or maven3 tarball)
mysql
mysql-devel
openldap-devel
python-devel
sqlite-devel
openssl-devel (for version 7+)
gmp-devel

**Comment by 1356469429** [comment]
I have forgot which one 
python 2.6
gcc 4.4.7
maven 3.0

**Comment by billbargens** [comment]
Still not work!
Can anyone give some helps?
My system enviroments:
centos 6.6
python2.7.9
gcc4.4.7
maven 3.0.3
hue-3.9.0  https://github.com/cloudera/hue/releases/tag/release-3.9.0.

**Comment by 1356469429** [comment]
I'm not through compilation on centos6.5 before
Put the system into centos6.7 is useful

**Comment by enricoberti** [comment]
i tried on a freshly installed Centos 6.6 and it goes through without problems.
I think there's something wrong with your GCC actually, are you sure you don't have a specific GCC related configuration on your system? (ie. setting a GCC_EXEC_PREFIX in your env)

**Comment by billbargens** [comment]
Finally solved with root privilege.
