### ISSUE TITLE
Error accessing the database: Snippet type custom is not configured

### ISSUE THREAD

**Issue by divincode** [cloudera/hue#2951]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
When we use importer.And follow the steps to reproduce it, and we encounter the following error. Error accessing the database: Snippet type custom is not configured

Steps to reproduce it?

1. Log in to the Hue Web UI, and click the "Importer" on the left bar.

2. Choose "External Database" in "Type", and enter the connection info.

3. Click the "Test Connection".

4. The error message appears in the upper right corner of the page.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
4.10.0
<img width="1440" alt="Screenshot 2022-08-08 at 11 40 15 AM" src="https://user-images.githubusercontent.com/35135348/183350966-ee45bf46-3cb4-43d3-a544-450604bcd1d9.png">

**Comment by divincode** [comment]
Related issue - https://github.com/cloudera/hue/issues/966

**Comment by divincode** [comment]
Any suggestions @Harshg999 @wing2fly

**Comment by divincode** [comment]
@romainr can u comment?

**Comment by divincode** [comment]
I have done the rca for this error.
This error is caused by incorrect post body sent by this following api call - 
/indexer/api/indexer/indexers/get_db_component

This call calls a fxn get_db_component() which in turn calls a fxn api = _get_api(request)
note the post body has only field - source 
file_format = json.loads(request.POST.get('source', request.POST.get('fileFormat', '{}')))
The fxn fails at this line where it requires a value file_format from the postbody but not present.

**Comment by Harshg999** [comment]
This has not been updated from a long time and need to take a second look.
@agl29 - Are you familiar with this?
