### ISSUE TITLE
Querying via Trino/Presto on table created with Hive shows encoded data for complex types

### ISSUE THREAD

**Issue by divincode** [cloudera/hue#2958]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
When we create a hive table with complex data types such as map.And then use the presto engine on hue to query it back encoded data as shown below.Which is not seen by presto and trino cli. 

Steps to reproduce it?
1. Create a hive table through hue with complex data type such as map.
2. Then use presto and trino to query it with hue.
3. Use hive to query it with hue.
You can observer difference in results as shown below.

trino result - "{u'status': u'NOT_ENTITLED', u'mode': u'ONLINE'}"
hive result - {"status": "NOT_ENTITLED", "mode": "ONLINE"}"

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
4.10 Linux

**Comment by divincode** [comment]
RCA -  the code is written most of the queries from various connectors are executed through the following api call - (notebook/api/execute/{dialect}
Dialect - Hive for hive
               Trino for trino
Depending on the dialect different connector class is used (which you can see different interfaces in ini file) -
Hive - notebook.connectors.hiveserver2.HS2Api Class
Trino/Presto - notebook.connectors.jdbc.JdbcApi  Class

Both classes use different in built packages/functions which comes from different files - 
Hive - From beeswax/Execute  from /usr/lib/hue/desktop/libs/notebook/src/notebook/connectorshiveserver2.py
Trino/Presto - From Jdbc/Execute from /usr/lib/hue/desktop/libs/notebook/src/notebook/connectorsjdbc.py

So maybe thats why.

**Comment by divincode** [comment]
Went deep into the code of notebook/src/notebook/connectors/jdbc.py calls fxns from other file desktop/libs/librdbms/src/librdbms 

uses this:
from py4j.java_gateway import JavaGateway, JavaObject 
it uses this package as a bridge between java and python .
When we use only jdbc with java it shows right result - {"status": "NOT_ENTITLED", "mode": "ONLINE"}"
But with this py4j wrapper some encoding happens - {"status": "NOT_ENTITLED", "mode": "ONLINE"}"

Is this expected or a bug ? Any suggestions to fix this.

**Comment by Harshg999** [comment]
Hi @divincode, this encoding issue could be the case for py2.7.
Check here by logging `data` if it has unicode value.
https://github.com/cloudera/hue/blob/a4df9c89bc460a86f40c7d7b1122715a3b69a4e0/desktop/libs/notebook/src/notebook/connectors/jdbc.py#L98
Then convert those to string for py2.7 (you can use `sys.version_info[0] > 2` for distinguishing b/w py3 and py2) and possibly send a quick PR? :)

**Comment by divincode** [comment]
i have logged those values there it comes in this format "{u'status': u'NOT_ENTITLED', u'mode': u'ONLINE'}"
You are saying it the version is python then we should like modify the output
the data is a string so
the only thing possible is replacing
data, description = query_and_fetch(self.db, snippet['statement'], 1000)
    has_result_set = data is not None
    non_unicode_data = data
    for row in range(0,len(non_unicode_data)):
      for col in range(0,len(non_unicode_data[row])):
          temp = non_unicode_data[row][col]
          temp = temp.replace("u'","\"")
          temp = temp.replace("\'", "\"")
          non_unicode_data[row][col] = temp
    data = non_unicode_data
 this is the parser I had written but there are questions on data integrity.

**Comment by divincode** [comment]
I understand wat u are saying but data is 2d array of strings and each item is string
"{u'status': u'NOT_ENTITLED', u'mode': u'ONLINE'}"
so not feasible
like converting unicode to normal
like i googled no such solution
you cannot convert this to this {"status": "NOT_ENTITLED", "mode": "ONLINE"}"
json loads etc does not work
