### ISSUE TITLE
Cannot see edit spark conf properties on PySpark notebook session

### ISSUE THREAD

**Issue by aporwal3** [cloudera/hue#2964]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
Yes

Describe the bug:
We are not able to see edit spark conf properties on PySpark notebook session

![image](https://user-images.githubusercontent.com/13012295/186632849-230f2212-75d1-4f3b-9793-f1185f8210f4.png)

Steps to reproduce it?
Go to Notebook
Create a PySpark session

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
Hue 4

**Comment by Nuno09** [comment]
Hi,

I have the same issue.

And this seems to be supported for a long time:
http://cloudera.github.io/hue/latest/releases/release-notes-3.9.0/
https://issues.cloudera.org/browse/HUE-2727

Not sure why this is an issue now...

I am running latest Hue 4.10
