### ISSUE TITLE
If coordinator workflow calendar display count has limit??

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#297]
Hi:
  
  I have a coordinator workflow to run every day, 
  In coordinator workflow page, I only can see 1000 count execute result
  But the workflow is still running, the new result does not display on the page
  I can not see the log from the page
  Does there is any solutions for me?
  See the following image.

  thanks.
  
![workflow](https://cloud.githubusercontent.com/assets/7900367/12347167/6955d01e-bb96-11e5-9a99-e5e51c20a106.png)

**Comment by sai-krish** [comment]
Hi,
   What version of Hue are you using ? Hue 3.9 has coordinator dashboard
pagination that allows you to view all possible data. Earlier versions had
some limitations.

**Comment by polingsky** [comment]
version is 3.7 
But i found the link
https://github.com/cloudera/hue/commit/28be8c8bb7c3440526cf25ddbcb0f990cc3dc801

it seems fixed!!
I try to update the code first.

thanks!!
