### ISSUE TITLE
Unable to increase the executor memory in Hue config

### ISSUE THREAD

**Issue by Nagesh-impetus** [cloudera/hue#2971]
Not able to increase spark executor memory on Hue, it is creating a kubernetes executor pod with the default configuration as 1 core cpu and 1 GB of memory. Can you please point us where this default configuration for spark executor pod on Hue.

**Comment by aporwal3** [comment]
All, we are not able to increase spark executor memory on hue. Even if we do it using a query it is taking a default configuration of 1 core of CPU and 1 GB of memory.

Both spark and hue are hosted on kubernetes environment. We use livy as spark client to submit queries.

Please do let us know if more information is required on the same.
