### ISSUE TITLE
suggestKeywords list omits `DELETE`

### ISSUE THREAD

**Issue by gjsjohnmurray** [cloudera/hue#2983]
https://github.com/cloudera/hue/blob/d5634ef1fa42b2832413e30b4962a975fa3af3c8/desktop/core/src/desktop/js/parse/sql/generic/sqlParseSupport.js#L1004-L1020

I'm surprised not to see `DELETE` in this list.

**Comment by JohanAhlen** [comment]
@gjsjohnmurray, this one is used for the generic SQL autocomplete, it's the default one used for when there's no dedicated autocomplete parser for a dialect in Hue. The generic parser doesn't support DELETE so that's why it's not part of this list.

Out of curiosity, which dialect are you querying?

**Comment by gjsjohnmurray** [comment]
The SQLTools extension for Visual Studio Code is using the generic one, as follows:
```ts
import sqlAutocompleteParser from 'gethue/parsers/genericAutocompleteParser.js';
```

https://github.com/mtxr/vscode-sqltools/blob/17de7a5c8047a1df7013228d2aad96cbea4aa9a0/packages/plugins/intellisense/language-server.ts#L8

and then
```ts
const hueAst = sqlAutocompleteParser.parseSql(text.substring(0, currentOffset), text.substring(currentOffset));
```

https://github.com/mtxr/vscode-sqltools/blob/17de7a5c8047a1df7013228d2aad96cbea4aa9a0/packages/plugins/intellisense/language-server.ts#L125

Is there any prospect of the generic parser supporting DELETE in the future?

**Comment by bjornalm** [comment]
Hi @gjsjohnmurray, sorry for the late reply. Adding DELETE to the generic parser parser is not on our roadmap, but we do not oppose it and we very much appreciate contributions. So if you would like to create a PR for it we could definitely add it  :-)

**Comment by gjsjohnmurray** [comment]
@bjornalm thanks for responding. I have submitted PR #3061 but its CI appears to have stalled.

**Comment by JohanAhlen** [comment]
Not sure why the CI stalled. I closed and re-opened the PR and it seems to be running now.

**Comment by gjsjohnmurray** [comment]
@bjornalm thanks for merging my PR. Any ETA on when a new NPM package will be published?

**Comment by bjornalm** [comment]
@gjsjohnmurray There is no fixed date yet but we are gonna try to get a new version of Hue out the coming weeks which should include a new version of gethue on npm.
