### ISSUE TITLE
Failure to Submit Spark SQL with Livy Batch Mode

### ISSUE THREAD

**Issue by divincode** [cloudera/hue#2987]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
Cant run multiple queries through livy batch mode.

Here is the configuration -
 [[[sparksql]]]
      name = SparkSql
      interface = livy-batch

Steps to reproduce it?
Running sample queries -
show tables;
create table mytable (name string, id string);
insert into mytable (id,name) values('1','liming');
select * from mytable;

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
4.10.0

**Comment by divincode** [comment]
Went more into the code , the execute fxn of livy-batch interface 

  def execute(self, notebook, snippet):
    api = get_spark_api(self.user)
    if snippet['type'] == 'jar':
        properties = {
            'file': snippet['properties'].get('app_jar'),
            'className': snippet['properties'].get('class'),
            'args': snippet['properties'].get('arguments'),
        }
    elif snippet['type'] == 'py':
        properties = {
            'file': snippet['properties'].get('py_file'),
            'args': snippet['properties'].get('argument', []),
        }
    else:
        properties = {
            'file': snippet['properties'].get('app_jar'),
            'className': snippet['properties'].get('class'),
            'args': snippet['properties'].get('arguments'),
            'pyFiles': snippet['properties'].get('py_file'),
            'files': snippet['properties'].get('files'),
            # driverMemory
            # driverCores
            # executorMemory
            # executorCores
            # archives
        }
    response = api.submit_batch(properties)
    return {
        'id': response['id'],
        'has_result_set': True,
        'properties': []
    }

It does not support queries .

**Comment by divincode** [comment]
The error from this fxn - 

  def close_statement(self, notebook, snippet):
    api = get_spark_api(self.user)

    session_id = snippet['result']['handle']['id']
    if session_id is not None:
      api.close_batch(session_id)
      return {
        'session': session_id,
        'status': 0
      }
    else:
      return {'status': -1}  # skipped

**Comment by divincode** [comment]
The fix for it -

  def close_statement(self, notebook, snippet):
    api = get_spark_api(self.user)

    try:
      session_id = snippet['result']['handle']['id']
      if session_id is not None:
        api.close_batch(session_id)
        return {
          'session': session_id,
          'status': 0
        }
    except:
      return {'status': -1}  # skipped

For 0 session id is not present, hence it is error .
Here is the fix .

**Comment by bjornalm** [comment]
@divincode Thanks for reporting the bug and also sharing the solution. I apologize for the late reply.
@nidhibhatg Can you have a look at this?
