### ISSUE TITLE
Job History Unavailable In Hue

### ISSUE THREAD

**Issue by billbargens** [cloudera/hue#299]
We're setting up Hue for the first time with v3.9.0.
I'm unable to view the older jobs in the Job Browser. 
I can see the current running jobs as well as the recently finished jobs just fine, but if the resource 
manager is restarted, the Hue Job Browser will be empty until any new jobs are run. 
The setup in the hue.ini file is as follows (rm is running on host1; our job history server is host2):
  # Configuration for YARN (MR2)
  # ------------------------------------------------------------------------
  [[yarn_clusters]]
    [[[default]]]
      resourcemanager_host=host1
      resourcemanager_port=8032
      submit_to=True
      resourcemanager_api_url=http://host1:8088
      proxy_api_url=http://host1:8088
      history_server_api_url=http://host2:19888
  # Configuration for MapReduce (MR1)
  # ------------------------------------------------------------------------
  [[mapred_clusters]]
    [[[default]]]
      submit_to=False

I can view the job history directly at the job history URL:http://host2:19888.
I assume we should be able to see our job history from within Hue, due to the history_server_api_url" setting.
Any help would be much appreciated.

**Comment by sai-krish** [comment]
Hi,
   Unfortunately Hue doesn't support this functionality yet. We are
tracking it on - https://issues.cloudera.org/browse/HUE-2558

   Hue currently talks to the RM to display the Job list and hence when you
restart it, the list is refreshed.

Thanks.

**Comment by billbargens** [comment]
So currently the 'history_server_api_url' in hue.ini is of no use?

**Comment by romainr** [comment]
Yes, this one is currently not used (as the full URLs get returned).

At some point Hue will directly contact the JHS to get the expired jobs that are no in listed in the RM anymore.

**Comment by romainr** [comment]
Good to close?

**Comment by spaztic1215** [comment]
The logs URL was fixed with https://github.com/cloudera/hue/commit/b1866eb1acc2047cd93885840fae7d6f1f66613d

But full fix for checking RM, JHS and Spark HS is tracked in https://issues.cloudera.org/browse/HUE-3079 and probably won't be targeted until Hue 4.
