### ISSUE TITLE
Failure to run multiple queries in an notebook/interface

### ISSUE THREAD

**Issue by divincode** [cloudera/hue#3017]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?

Describe the bug:
Its more of a feature request we should run multiple queries in hue at once ,when we click run button.

Steps to reproduce it?

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).

**Comment by bjornalm** [comment]
@divincode Thanks for engaging :-) Not sure if this is what you are asking, but we are working on multi statement execution for the next version of our editor. The editor can contain multiple sql statements that can be executed individually and the cursor/caret will determine which statement to show the result for. If you are asking something else, can you elaborate a bit further?

**Comment by divincode** [comment]
hi @bjornalm  what i understood, is that even though we have multiple statements.
like this
1. statement1 ; statement 2;
2.  statement 3 ;

we can only execute one statement like statement 1 or 2 or 3, in the current versions .
Wat I imagine or want develope with open source is that if we hit run button all statements(1,2,3 ) get executed  andwe get output display for the one which we want.

**Comment by bjornalm** [comment]
I see. I theory I guess we could use the new multi statement execution editor but also include an option to execute all the statements automatically instead of manually. I'll discuss this with the team. Is this something you would be interested in developing and opening a PR for in that case?
