### ISSUE TITLE
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block

### ISSUE THREAD

**Issue by FrantiChow** [cloudera/hue#3035]
Hello,we encountered atomic problem in using hue4.10 and hue4.7. When can we fix this problem？

error message: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block
os info:RHEL 7.4

**Comment by Harshg999** [comment]
Hey @FrantiChow, can you provide more context? 
Like where are you getting this? What operation/steps are you performing? Maybe some logs to debug further?

**Comment by FrantiChow** [comment]
> Hey @FrantiChow, can you provide more context? Like where are you getting this? What operation/steps are you performing? Maybe some logs to debug further?
 Thanks for reply！We have two Editor in hue, hive and impala.The error messages occures on execute query by impala Editor.The problem is not inevitable,but sporadic,and only occure in impala Editor.
Besides the Hue DB we use is MYSQL 5.7.31 .

**Comment by FrantiChow** [comment]
@Harshg999 
Thanks for reply！We have two Editor in hue, hive and impala.The error messages occures on execute query by impala Editor.The problem is not inevitable,but sporadic,and only occure in impala Editor.
Besides the Hue DB we use is MYSQL 5.7.31 .

**Comment by Harshg999** [comment]
Maybe these links can help you?
- https://community.cloudera.com/t5/Support-Questions/You-can-t-execute-queries-until-the-end-of-the-atomic-block/m-p/93773
- https://community.cloudera.com/t5/Support-Questions/Error-while-querying-HIve-tables-from-HUE/td-p/295069
- https://community.cloudera.com/t5/Support-Questions/Hue-4-7-Can-t-login-using-LDAP/td-p/299076

Hope it helps!

**Comment by FrantiChow** [comment]
Thanks for help! 
Let me have a try for it.
