### ISSUE TITLE
filebrowser: upload dir for uploading large archives

### ISSUE THREAD

**Issue by fnerdwq** [cloudera/hue#304]
In Hue 3.9.0 we are facing the problem that on the upload of a large archives (eg. zip files) over the filebrowser (_Upload -> Zip/Tgz/Bz2 file_)  `/tmp/` is filling up before the complete file is actyally uploaded (the unpacking did not start yet).

The prolbem apparently is:
- The upload of a > 2.5Mb archive uses the Django `TemporyFileUploadHander` which is storing the temporary upload in `/tmp` as default
- only then the exitings  parameter `[filebrowser] archive_upload_tempdir` is used to actually unpack this archive in to this location,

It would be essential to be able to also redirect the initial zip upload to a different folder location. I would suggest that the `archive_upload_tempdir` parameter sets _both_ directories: For initial upload _and_ for the unpacking of the archive.

Or do I miss a configuration option?

Thanks for any help.
Frederik

**Comment by romainr** [comment]
Yes, it would make more sense to unify archive_upload_tempdir to also set the path of TemporyFileUploadHander for this archive case.

Note that the archive upload is currently more designed for small files, like 100MB max. Hue's server still does all the work, and we would need at some point the equivalent of a task queuing system to offload this task of the HTTP server.

**Comment by fnerdwq** [comment]
Sure, there are better ways of data ingestion. But since it is possible for the users to actually try to upload large archives, they potentially do it and fill up /tmp (unluckily, if the upload fails due to space problemm, the file ``/tmp/<random>.upload`` is not deleted.
