### ISSUE TITLE
filebrowser: download of files with spaces not working

### ISSUE THREAD

**Issue by fnerdwq** [cloudera/hue#305]
The Filebrowser Hue 3.9.0 has the bug, that clicking on files with spaces in the filename, does not start the download, but gives a page not found
```
Page not found http://huehost.com:8888/filebrowser/download/user/someuser/6licenses%20flat.pdf?disposition=inline
```

The URL in the browsers address filed shows:
```
URL http://huehost.com:8888/filebrowser/download/user/someuser/6licenses%2520flat.pdf?disposition=inline
```

Changing the URL manually to, i.e. replacing `%2520` by `%20`
```
http://huehost.com:8888/filebrowser/download/user/someuser/6licenses%20flat.pdf?disposition=inline
```
makes the download actually happen.

So there is an errouneous URL encoding step in the code.

Thanks
Frederik

**Comment by enricoberti** [comment]
Thanks!
That was recently fixed with https://github.com/cloudera/hue/commit/bb5dfc6fe865200151d88fa7a359eb037dfc2324
and it's gonna be in Hue 3.10

**Comment by fnerdwq** [comment]
cool, thanks. Is there a schedule for 3.10?

**Comment by romainr** [comment]
Current target is in about 2 weeks
