### ISSUE TITLE
Queries with date variable brokes UI

### ISSUE THREAD

**Issue by akaAPal** [cloudera/hue#3051]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
After reloading page with date query or load that query from query history all variable editboxes are shown and query history became hidden

Steps to reproduce it?
1. create table with date type -  create table t2.dtest (i int,tdate DATE)
2.  add some values in the table - INSERT into t2.dtest values (3, '1990-01-02'), (4, '2025-01-01')
3. run query with date variable - select * from t2.dtest where tdate = "${datestr}"
4. refresh page by clicking Refresh button in browser or pressing F5

Hue version or source?
CDH 6.3.4
![uibug](https://user-images.githubusercontent.com/116652095/197787309-433c9277-36ef-404f-a925-038bbdf87bc2.png)

**Comment by bjornalm** [comment]
@akaAPal thanks for reporting :-) I can't reproduce this in our nightly builds. Which version of Hue are you using and which browser?

**Comment by Akhilsnaik** [comment]
@bjornalm  This issue was there on only CDH-6.3.4 hue ( hue-3.9) this has been fixed already now.

**Comment by akaAPal** [comment]
Hue™ 4.4.0 - cdh6.3.4
In which version that was fixed?

**Comment by bjornalm** [comment]
@Akhilsnaik ^
