### ISSUE TITLE
Gethue Demo not in last version

### ISSUE THREAD

**Issue by javier-dideco** [cloudera/hue#3058]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com? No

Describe the bug: Demo version of GetHue is not working well. There are lots of errors when trying to do almost anything. I'll describe just one of them, but you can't create new databases nor tables nor importing any files.

Steps to reproduce it?
Login into https://demo.gethue.com/hue/accounts/login?next=/hue/
In Hive's default database, try to create a table pressing "+" button. Yo get 500 Server Error. With an "You are accesing an older version of Hue" message.:
![image](https://user-images.githubusercontent.com/102544895/198898393-514b3722-a931-4aa6-ae9e-9867fe4abc2a.png)

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...). Demo version

**Comment by Harshg999** [comment]
Hi @javier-dideco, thanks for reporting this issue.

It looks like the Importer has regressed on demo.gethue.com
@agl29  - Can you take a quick look?

**Comment by Harshg999** [comment]
This seems related to this issue: https://github.com/cloudera/hue/issues/3059

**Comment by javier-dideco** [comment]
Hi @Harshg999 , thanks for checking it and following up. As far as I understand I can't help more and just wait for you to update the gethue deployed in demo (https://demo.gethue.com/hue/accounts/login?next=/hue/)
Is that correct?

**Comment by Harshg999** [comment]
Yes, once the Hue docker image is fixed, it will reflect on demo.gethue.com as well.

**Comment by Harshg999** [comment]
Hi @javier-dideco, thanks for flagging this issue!
Importer is fixed in `demo.gethue.com` now.

**Comment by javier-dideco** [comment]
Thanks a lot Harsh!! Now works fine.

I see that now "Charts" are not working but I guess I better report it 
in a new issue

-- 

Logo PiperLab
	

*Javier Di Deco Sampedro*
Co-fundador
piperlab.es <https://piperlab.es>
