### ISSUE TITLE
filebrowser: download of file behind reverse proxy not working

### ISSUE THREAD

**Issue by fnerdwq** [cloudera/hue#306]
As follow up on #305:
I just realised that having hue 3.9.0 behind a apache reverse proxy I have another bug on the 
filebrowser download, when clicking on a file.

Using a URL `https://huehost.com/filebrowser/`  (`https://huehost.com` ssl terminating and reverse proxying to `http://localhost:8888`) and clicking on a filebrowser file to download, tries to download from the proxy destination instead of the original URL. The result is a download forom
`http://localhost:8888/filebrowser/view/user/someuser/6licenses%20flat.pdf`

This is probably a problem in the Javascript handling this?

Thanks
Frederik

**Comment by fnerdwq** [comment]
Hi again,
apparently this line is the prolblem:
https://github.com/cloudera/hue/blob/master/apps/filebrowser/src/filebrowser/templates/listdir_components.mako#L1079
`file.url` resolves to the URL where Hue is listening on, not to the URL on the reverse Proxy.

I don't know how this line should look exactly, but quite sure, here's the problem.

**Comment by enricoberti** [comment]
Hi Frederik!
If you are on master, do you mind trying to change that line to 
`location.href = '${url('filebrowser.views.view', path='')}' + file.path;`
to see if it works for you?

Thanks,
e.

**Comment by fnerdwq** [comment]
Hi Enrico,
that doesn't seem to be valid code (ServeError).
But reusing the to lines from the `if` branch
https://github.com/cloudera/hue/blob/master/apps/filebrowser/src/filebrowser/templates/listdir_components.mako#L1076-L1077
seem to "not change the URL. Meaning, that my test instance is not behind a reverse Proxy, but the URL is th correct one, when I reuse these lines. The the "changed
 directory" from the `if` branch works in the reverse proxy, I would be confident, that this would work to. Could only test it in a downtime windows tomorrow.

BTW: I don't realy see why there is a conditional anyway, handling dirs and files differently.

**Comment by enricoberti** [comment]
It's because directory browsing doesn't trigger a page change but the file viewer/download is actually another page.

We haven't had this problem before, and it works for us on the demo too behind a reverse proxy (ie. http://demo.gethue.com/filebrowser/view=/solr/collection2/core_node1/data/index#/solr/yelp_demo/core_node1/data/tlog  and click on the tlog file)

**Comment by fnerdwq** [comment]
Hi,
this is weird, do you think it's an issue in the proxy configuration? It's quite (apache) standard:
```
ProxyPass / http://localhost:8888/
ProxyPassReverse / http://localhost:8888/
ProxyRequests Off
SetEnv proxy-nokeepalive 1
 ```
on Port 443, and a rewrite from port 80. That's all.

**Comment by fnerdwq** [comment]
Hi, I found the solution:
The non default Option `ProxyPreserverHost On` was missing.

Thanks anyway!
