### ISSUE TITLE
Importing project in Intellij or eclipse.

### ISSUE THREAD

**Issue by jamalahmedmaaz** [cloudera/hue#308]
Hi all,

Can anyone point me to the documentation on importing this project into any IDE. I am looking to debug the source code from the beginning.

Right now in my current project i am using Spark JobServer and the  UI is build by us.

I am thinking of integrating this into our current system. Will need some confidence on the code and how it works.

**Comment by romainr** [comment]
If you are using Livy, you should look at https://github.com/cloudera/livy

If you are working on the Hue UI, generally people just create an existing project based on the root, or just other text editors
