### ISSUE TITLE
Config error when adding multiple subsections to notebook --> interpreters

### ISSUE THREAD

**Issue by jv1522** [cloudera/hue#3086]
The below is my .ini content, wherein I am trying to expose two different bigquery datasets, I am getting a config error.
[ notebook ]
enable_notebook_2=true

[[ interpreters ]]

[[[ bigquery ]]]
name = dataset1
interface=sqlalchemy
options='{"url": "bigquery://project-name/dataset1", "use_query_cache": "true"}'

[[[ bigquery ]]]
name = dataset2
interface=sqlalchemy
options='{"url": "bigquery://project-name/dataset2", "use_query_cache": "true"}'

**Comment by bjornalm** [comment]
@jv1522 thanks for reporting and I apologize for the late response. Hue is open source and our aim is to have the community contribute with answers and fixes so you could also get help by posting a question at https://github.com/cloudera/hue/discussions or https://discourse.gethue.com/  

@amitsrivastava can you have a quick look?

**Comment by bjornalm** [comment]
@amitsrivastava Have you had a change to look at this?

**Comment by sbbagal13** [comment]
Hi All, Do we have any update on this?
I am also trying to similar configuration to add multiple Trino catalogs /clusters  but its not working

**Comment by amitsrivastava** [comment]
@jv1522 @sbbagal13 can you try adding `-1` and `-2` as suffixes in the names of the interpreters? This would create an array of bigquery interpreters. Something like the following might work.

```
[[ interpreters ]]

[[[ bigquery-1 ]]]
name = dataset1
interface=sqlalchemy
options='{"url": "bigquery://project-name/dataset1", "use_query_cache": "true"}'

[[[ bigquery-2 ]]]
name = dataset2
interface=sqlalchemy
options='{"url": "bigquery://project-name/dataset2", "use_query_cache": "true"}'
```
