### ISSUE TITLE
Post-processing 'desktop/ext/css/jquery.mCustomScrollbar.min.css' failed!

### ISSUE THREAD

**Issue by alecinvan** [cloudera/hue#309]
Hi, All

I am building the hue in Ubuntu 15.10, by executing 
>make apps

It went good until 

Running '/usr/local/hue/build/env/bin/hue migrate --merge' with None
Running migrations for django_extensions:
- Nothing to migrate.
 - Loading initial data for django_extensions.
Installed 0 object(s) from 0 fixture(s)
Running migrations for desktop:
- Nothing to migrate.
 - Loading initial data for desktop.
Installed 0 object(s) from 0 fixture(s)
Running migrations for beeswax:
- Nothing to migrate.
 - Loading initial data for beeswax.
Installed 0 object(s) from 0 fixture(s)
Running migrations for hbase:
- Nothing to migrate.
 - Loading initial data for hbase.
Installed 0 object(s) from 0 fixture(s)
Running migrations for jobsub:
- Nothing to migrate.
 - Loading initial data for jobsub.
Installed 0 object(s) from 0 fixture(s)
Running migrations for oozie:
- Nothing to migrate.
 - Loading initial data for oozie.
Installed 0 object(s) from 0 fixture(s)
Running migrations for pig:
- Nothing to migrate.
 - Loading initial data for pig.
Installed 0 object(s) from 0 fixture(s)
Running migrations for search:
- Nothing to migrate.
 - Loading initial data for search.
Installed 0 object(s) from 0 fixture(s)
? You have no migrations for the 'security' app. You might want some.
Running migrations for spark:
- Nothing to migrate.
 - Loading initial data for spark.
Installed 0 object(s) from 0 fixture(s)
Running migrations for sqoop:
- Nothing to migrate.
 - Loading initial data for sqoop.
Installed 0 object(s) from 0 fixture(s)
Running migrations for useradmin:
- Nothing to migrate.
 - Loading initial data for useradmin.
Installed 0 object(s) from 0 fixture(s)
Running migrations for notebook:
- Nothing to migrate.
 - Loading initial data for notebook.
Installed 0 object(s) from 0 fixture(s)
Running '/usr/local/hue/build/env/bin/hue collectstatic --noinput' with None
Post-processed 'desktop/ext/js/jasmine-2.3.4/jasmine.css' as 'desktop/ext/js/jasmine-2.3.4/jasmine.55eee6cfbbea.css'
Post-processed 'desktop/ext/chosen/chosen.min.css' as 'desktop/ext/chosen/chosen.min.9ed7949517ef.css'
Post-processed 'desktop/ext/css/bootstrap-fileupload.css' as 'desktop/ext/css/bootstrap-fileupload.d32f07ebc666.css'
Post-processed 'desktop/ext/css/font-awesome.min.css' as 'desktop/ext/css/font-awesome.min.4fbd15cb6047.css'
Post-processed 'desktop/ext/css/leaflet.markercluster.css' as 'desktop/ext/css/leaflet.markercluster.2121bb8ca1b3.css'
**Post-processing 'desktop/ext/css/jquery.mCustomScrollbar.min.css' failed!**

Traceback (most recent call last):
  File "/usr/local/hue/build/env/bin/hue", line 9, in <module>
    load_entry_point('desktop==3.9.0', 'console_scripts', 'hue')()
  File "/usr/local/hue/desktop/core/src/desktop/manage_entry.py", line 57, in entry
    execute_from_command_line(sys.argv)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle_noargs
    collected = self.collect()
  File "/usr/local/hue/build/env/local/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/staticfiles/management/commands/collectstatic.py", line 125, in collect
    raise processed
ValueError: The file 'desktop/ext/css/mCSB_buttons.png' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x7f6fea9d8690>.
make[1]: Leaving directory '/usr/local/hue/apps'

It shows one error: **Post-processing 'desktop/ext/css/jquery.mCustomScrollbar.min.css' failed!**, I have no idea how to fix it, and ignore it. Then I run

hadoopuser@rooster:/usr/local/hue/build/env/bin$ ./hue runserver
Validating models...

0 errors found
February 03, 2016 - 16:30:56
Django version 1.6.10, using settings 'desktop.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Seems the server starts, the host IP is 192.168.168.0, but can't open the page: 192.168.168.0:8000
I was trying to re-config the 
./desktop/conf/pseudo-distributed.ini

It didn't work either, any solutions for this?

thanks

AL

**Comment by romainr** [comment]
Did you do a fresh clone of master? I could not reproduce it on Ubuntu 14.04 (we don't test on 15.04 as it is not a LTS).

If you want to access it not by opening http://127.0.0.1:8000/

have a try to start Hue with:

./hue runserver 0.0.0.0:8000

**Comment by alecinvan** [comment]
@romainr Thanks a lot, it works : )
