### ISSUE TITLE
Certain kubernetes security standard not compatible with current HUE deployment.

### ISSUE THREAD

**Issue by y2s82** [cloudera/hue#3101]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No
Describe the bug:
Certain kubernetes security standard includes deploying with random user with `root` GID. In such scheme, UID, technically, can only be known after the container is deployed in the pod. I was able to bypass this issue by making configuration change as a part of the entrypoint to detect and assign UID to HUE deployment before HUE is ran.  This became impossible in recent change that took away write permission to `desktop/conf` folder/files.  Now HUE runs with default for its UID and fails.  Setting `server_user` to an empty string also fails.  To meet the kubernetes standard, there should be a way to have UID setting be optional and rely on GID for necessary permission, or `desktop/conf` folder should be writeable to add overriding configurations.

Steps to reproduce it?
(without having a kubernetes cluster with the same security setting, the following is likely the closest and simplest way to test it)
1. Create a sample ini file:
```ini
[desktop]
server_user=
server_group=root
```
2. Run `hue:latest` with the above file mounted to `desktop/conf`

Conversely, if we choose to explicitly set UID, then we would need the configuration file to be writable during runtime of the container:
1. Run `hue:latest` with `-it --entrypoint bash` arguments
2. Run `touch desktop/conf/test`

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
`latest` on Dockerhub

**Comment by Harshg999** [comment]
@ranade1 Can you take a quick look?
