### ISSUE TITLE
How do I connect Spark workers to livy-spark master?

### ISSUE THREAD

**Issue by koujalgi-amith** [cloudera/hue#312]
I have a livy-server setup in the same box as Spark master. I am running only livy-server and creating a spark session from the REST interface (I'm not starting the Spark process. I see a Spark process being created for each spark session created from livy). Now, I'd like to add one or more worker nodes to the master (assuming livy-server has the master Spark running). The worker nodes are in different boxes and I'm trying to connect to the master by this command:
`./sbin/start-slave.sh spark://<livy-box-ip>:7077`
Now, I know that the master isn't listening on port 7077. And also I see different Spark processes spawned for each session.
How would I make the master to listen on a port and connect a worker to the livy-spark master?

**Comment by romainr** [comment]
Hey, the Livy project moved to https://github.com/cloudera/livy, I would recommend to ask the question there

**Comment by amithkoujalgirzt** [comment]
Hello. Thanks for your reply. I'm using Livy and not Hue. I asked the question here since I couldn't see the issues section [there](https://github.com/cloudera/livy).
