### ISSUE TITLE
Gethue Demo not showing any Charts after a Hive query

### ISSUE THREAD

**Issue by javier-dideco** [cloudera/hue#3125]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
No

Describe the bug:
After executing a Hive query to any table (with OK Results) the "Chart" tab doesn't show anything

Steps to reproduce it?
1) Log in into https://demo.gethue.com/hue/accounts/login?next=/
2) Select Hive Editor (https://demo.gethue.com/hue/editor/?type=6)
3) Execute a query from any table. For example, when I'm reporting this, one of the tables is district_wise_rainfall_normal_csv. Query: "SELECT * FROM district_wise_rainfall_normal_csv"
4) Check that the Results are correct. In this case:
![image](https://user-images.githubusercontent.com/102544895/207817786-3c0349f4-3f37-4938-aea8-4d77e6faaf7f.png)
5) Go to "Chart" tab
6) Nothing is shown for any of the chart types. And neither the "Setting" button works.
![image](https://user-images.githubusercontent.com/102544895/207818051-9c8d7f95-0a64-43bb-a6ab-7c6dec9fd5ed.png)

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
The version deployed as Demo in https://demo.gethue.com/hue/accounts/login?next=/

**Comment by bjornalm** [comment]
@javier-dideco Thanks for reporting. I will have a look.

**Comment by bjornalm** [comment]
This is a new bug in the experimental version 2 of the sql editor. We have created an internal Jira for this and will follow up.

**Comment by javier-dideco** [comment]
Thanks for the quick response!

Hope you can fix it soon.

Best regards,

-- 

Logo PiperLab
	

*Javier Di Deco Sampedro*
Co-fundador
piperlab.es <https://piperlab.es>

**Comment by bjornalm** [comment]
PR available here https://github.com/cloudera/hue/pull/3143

**Comment by Harshg999** [comment]
@bjornalm - Good to close?
