### ISSUE TITLE
How to connect livy-spark with standalone spark cluster - exception while starting server

### ISSUE THREAD

**Issue by shamsmali** [cloudera/hue#313]
It would be nicer if some document can be shared on setting up livy with spark standalone. We tried our best to set it up, but we always get issue while running livy server. 

./bin/livy-server --master spark://10.0.0.30:7077   -- this is how i am starting livy server

We get "Unsuported Operation" and below is the code from SparkManager
 def clientManager: SessionManager[ClientSession, CreateClientRequest] = {
    throw new UnsupportedOperationException
  }

**Comment by romainr** [comment]
FYI Livy moved to its own project repo https://github.com/cloudera/livy
