### ISSUE TITLE
Accumulo integration?

### ISSUE THREAD

**Issue by pauljacksonrodgers** [cloudera/hue#315]
I'm curious if Cloudera has considered an Accumulo integration for Hue that would work much like the existing HBase integration.

What would be the best way to create such a thing? Maybe writing some kind of adapter so that Accumulo could respond to requests to the HBase API? Or would I actually want to implement it natively?

**Comment by romainr** [comment]
The core of the app is based on the HBase Thrift v1 API https://github.com/cloudera/hue/blob/master/apps/hbase/thrift/Hbase.thrift

What are Accumulo APIs? They might have a very similar one as it is very close to HBase.

Quick search found that there is a Thrift Server 
https://issues.apache.org/jira/browse/ACCUMULO-482
https://github.com/accumulo/pyaccumulo
