### ISSUE TITLE
Hive HA support

### ISSUE THREAD

**Issue by fnerdwq** [cloudera/hue#316]
Hello,

is there a way to configure hue 3.9/3.10 to support Hive HA, i.e. configuring the hive service discovery over the zookeeper ensemble?

Thanks
Frederik

**Comment by romainr** [comment]
Yes, this is plan for within 2 months (Hue 3.10) normally, high priority: https://issues.cloudera.org/browse/HUE-2738

**Comment by fnerdwq** [comment]
ok, thanks

**Comment by fabian-tibor** [comment]
Well we have 2019 now and the ticket is still open.
Any plans to implement that in the near future?

**Comment by romainr** [comment]
Hue is open source and the feature was recently contributed: https://issues.cloudera.org/browse/HUE-8887

**Comment by romainr** [comment]
FYI @alericmckearn
