### ISSUE TITLE
importer: SemanticException [Error 10035]: Column repeated in partitioning columns when adding partition columns

### ISSUE THREAD

**Issue by sumtumn** [cloudera/hue#3201]
Is the issue already present in https://github.com/cloudera/hue/issues or discussed in the forum https://discourse.gethue.com?
not found

Describe the bug:
import remote file to tabel, add partition column, can't remove columns and  click save, error happens：
> Error while compiling statement: FAILED: SemanticException [Error 10035]: Column repeated in partitioning columns

Steps to reproduce it?
1. upload file
[exam_event_df11.csv](https://github.com/cloudera/hue/files/10790840/exam_event_df11.csv)

2. add partition:  data & hour
3. click save， error happens: 
Error while compiling statement: FAILED: SemanticException [Error 10035]: Column repeated in partitioning columns

Error log shows in hive, data and hour column exist in columns and partition columns of creating table sql simultaneously.
So I realized that maybe I should remove date and hour columns. So I click the button on the left side of FIELDS section, and change 
`exam_id,student_id,exam_grade_id,exam_subject_id,exam_time,exam_score,date,hour`
to
`exam_id,student_id,exam_grade_id,exam_subject_id,exam_time,exam_score`
then click "Change filed names", and I find that date and hour are still in FIELDS section. Click Save button, same error happens.

If I don't add partition columns, the import process succeed.

Hue version or source? (e.g. open source 4.5, CDH 5.16, CDP 1.0...). System info (e.g. OS, Browser...).
4.11.0

**Comment by bjornalm** [comment]
Hi @sumtumn, thanks for reporting. @sreenaths can you take a look?
