### ISSUE TITLE
Vue3 webcomponentwrapper does not wrap

### ISSUE THREAD

**Issue by gijsbertpieterbrouwer** [cloudera/hue#3217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, I have some trouble getting the wrapper to work. Could you point me in the right direction?

My main.ts looks like

```
import { createPinia } from "pinia";
import piniaPersist from 'pinia-plugin-persist';
import { createApp, CreateAppFunction, h } from 'vue';

import wrapper from "vue3-webcomponent-wrapper";
import TickChatWidget from "./components/molecules/widget/TickChatWidget.vue";

const pinia = createPinia();
pinia.use(piniaPersist);

const createAppWrapper: CreateAppFunction<Element> = (component) => {
  return createApp(component)
    .use(pinia)
}

// eslint-disable-next-line no-debugger
debugger;

const tickChatWidgetComponent = wrapper(TickChatWidget, createAppWrapper, h);
window.customElements.define("tick-chatwidget", tickChatWidgetComponent);
```

![image](https://user-images.githubusercontent.com/76774141/223048137-330daa07-6b71-4305-9eb1-aa962f040dd6.png)

### Steps To Reproduce

1. Create a wrapper
2. Open in brower
3. Get an error 

### Hue version

wrapper

**Comment by bjornalm** [comment]
Hi @gijsbertpieterbrouwer, thanks for reporting. What is the error that you are getting saying?
