### ISSUE TITLE
livy batch post request

### ISSUE THREAD

**Issue by nvijayap** [cloudera/hue#322]
Hello,

I am trying to get this livy batch request working and facing issues ...

`$ curl -X POST -d '{ "file": "target/scala-2.10/livy_2.10-0.1-SNAPSHOT.jar" }' localhost:8998/batches; echo`

Output of above is ...

`No usable value for file`
`Did not find value which can be converted into java.lang.String`

I tried this as well ...

`curl -X POST localhost:8998/batches?file=target/scala-2.10/livy_2.10-0.1-SNAPSHOT.jar localhost:8998/batches; echo`

Output of above is ...

`java.lang.NullPointerExceptionjava.lang.NullPointerException`

**Comment by romainr** [comment]
Livy moved to https://github.com/cloudera/livy, could you open the issues there?

**Comment by nvijayap** [comment]
Hi Romain, 

I went to https://github.com/cloudera/livy to open the issue, but I don't see "Issues" tab there, so how do open a issue there?  May be you or the admin need to enable the Issues tab there?

Thanks
Naga

**Comment by romainr** [comment]
I thnik the Livy project prefers to see first a discussion on their list:
https://groups.google.com/a/cloudera.org/group/livy-user

https://github.com/cloudera/livy/wiki/Contributing-to-Livy
