### ISSUE TITLE
where is the exceptions_renderable function? 

### ISSUE THREAD

**Issue by xyniceboy** [cloudera/hue#325]
hue/apps/filebrowser/src/filebrowser/views.py
`54 from desktop.lib.exceptions_renderable import PopupException`
where is the exceptions_renderable function?

**Comment by romainr** [comment]
Is is there: https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/lib/exceptions_renderable.py#L31

**Comment by xyniceboy** [comment]
ok, thanks.
