### ISSUE TITLE
sql mode multiline comment lead to more than one sql string split error

### ISSUE THREAD

**Issue by hiliny** [cloudera/hue#3254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

what i expect is where i use sql mode, multiline comment dont cause multi sql string split failed  

### Steps To Reproduce

copy this sql below to demo.gethue.com editor and you will get the error

/**
1. some1
2. some2
**/
-- selet *

SELECT * FROM employee1;

-- some else
SELECT * FROM employee_txt;

### Hue version

open source current master

**Comment by hiliny** [comment]
I mean the current highlight rows is not right! ;  I doubt the multiline comment end double * cause this  problem。

**Comment by bjornalm** [comment]
@hiliny thanks for reporting. I can reproduce that multi line comments are no working as expected.
@JohanAhlen, do you know if multiline comments should be supported?

**Comment by JohanAhlen** [comment]
@hiliny it indeed can't parse the statements with the example you provided.

The issue appears when you use two '*' in the multi line comment delimiters, if you change it to:

```
/*

some1
some2
*/
-- selet *
SELECT * FROM employee1;

-- some else
SELECT * FROM employee_txt;
```

It works.

I'll see if we can adjust the parsers to also accept `/**` and `**/`.
