### ISSUE TITLE
[FileBrowser] Is it possible to run FileBrowser separately?

### ISSUE THREAD

**Issue by earthquakesan** [cloudera/hue#326]
I only need to run FileBrowser from the Hue suite. Was wondering if there is a functionality exist to run it separately.

**Comment by romainr** [comment]
How about http://gethue.com/how-to-manage-permissions-in-hue/?

And any reason not to use the Job Browser and SQL editors?

**Comment by earthquakesan** [comment]
@romainr will not do. I want part of functionality which enable uploading/downloading files from the browser. Packing it in the docker with configurable params and having exposed on port 7777 (for example). I don't want to run the whole suite.

I suppose, that it is not possible then? As I could see FileBrowser is a separate Django component, which heavily depends on hadoop and desktop components. There should be a way to run it separately (at least for testing?)

**Comment by romainr** [comment]
Not sure why it won't do? cf. above post it is exactly how doing that, disabling any apps you don't want.

You can also blacklist at the code level the apps, e.g. in the hue.ini

    [desktop]
    app_blacklist=search,security,oozie,jobbrowser,pig,beeswax,search,zookeeper,impala,rdbms,spark,metastore,hbase,sqoop,jobsub

**Comment by earthquakesan** [comment]
@romainr I want a lightweight solution. Also, sorry, but using user access control to disable components sounds like a crutch to me.

Blacklist may do the trick. If I blacklist other components can I remove the code for them from the repo?
