### ISSUE TITLE
Running real-time queries over Livy

### ISSUE THREAD

**Issue by aanastasov** [cloudera/hue#327]
Our setup involves using spark-jobserver with a single context, and running queries that work in the matter of seconds against that context. Our problem is that we don't want to create a separate context with every Spark job, but rather reuse the same one, because it is a big overhead to create it every time.

Does Livy supports this setup?

**Comment by romainr** [comment]
That's exactly one of the goal of Livy, to keep long running contexts/shell than can be accessed by REST.

Livy moved to https://github.com/cloudera/livy, could you ask there or on https://groups.google.com/a/cloudera.org/group/livy-user ?
