### ISSUE TITLE
Can not edit the submitted workflow in oozie editor

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#330]
HI:
 
  I use HUE 3.9, 
  I create a workflow in oozie editor. and then submit the job.
  But when I want to edit the submitted workflow in oozie editor, the workflow can not edit.
  like the following image:

  
![image](https://cloud.githubusercontent.com/assets/7900367/13910094/e1ad6686-ef57-11e5-8d37-ec4aca432e97.png)

It only display the action menu and workflow name, can not edit the job content.

I checked the browser debug, it shows the error:

![image](https://cloud.githubusercontent.com/assets/7900367/13910122/3aa4a506-ef58-11e5-9b89-fdb7601a41ad.png)

Some workflows I only get the workflow name in editor mode.
![image](https://cloud.githubusercontent.com/assets/7900367/13911818/73367490-ef70-11e5-8703-28ebb1b8bb25.png)

before the workflow submitted, the workflow can edit.

I find the issue:
https://issues.cloudera.org/browse/HUE-2972
They say the error in hue3.7, but I use HUE3.8.1, does not discover the questions.
In hue 3.9, I encounter the error.

does anyone know the issue?
thanks.

**Comment by romainr** [comment]
This is https://issues.cloudera.org/browse/HUE-3435 which is in master and Hue 3.10
