### ISSUE TITLE
Please help me!  HUE+MYSQL

### ISSUE THREAD

**Issue by Liuyanzhi** [cloudera/hue#332]
I want to know hue wheather could as a mysql web ui to using. Don't use the other any big data tools.
Only use hue with mysql. The way is right or wrong.Thanks for answer.
我想知道hue是否可以作为mysql数据查询的web ui使用。不搭配任何大数据软件只是mysql+hue.
这么用是否可行.感谢回答!

**Comment by romainr** [comment]
Yes, have a look at http://www.cloudera.com/documentation/enterprise/latest/topics/cdh_ig_hue_database.html#concept_id1_wkj_zj_unique_1
