### ISSUE TITLE
Import  related hdfs-site.xml or core-site.xml when run oozie workflow

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#333]
Hi:
 
   Every time I create a oozie workflow to run job, like:
 
   if I run a java action, I have to import hdfs-site.xml, core-site.xml or yarn-site.xml
   or 
   if I run hive action, I have to import hive-site.xml
   or 
   if I run hbase related job, I have to import hbase-site.xml

   So I want to ask,  in HUE config, I already set the HADOOP_CONF=/etc/hadoop/conf
   hive_conf_dir=/etc/hive/conf
   hbase_conf_dir=/etc/hbase/conf
   
   why I run the job still to import those files, the job could run ?
   Does other config to set?

   I use hue3.9. and cluster with kerberos.
   thanks.

**Comment by romainr** [comment]
@sai-krish what do we recommend?
Usually there is putting those directly in the sharelib, maybe https://issues.cloudera.org/browse/HUE-2960

**Comment by romainr** [comment]
Any update?

**Comment by polingsky** [comment]
I found the following issue:
http://stackoverflow.com/questions/33101771/oozie-java-action-does-not-include-core-site-xml

and in yarn-site.xml
the value "yarn.application.classpath"  also defined $HADOOP_CONF_DIR
so we have to set environment for $HADOOP_CONF_DIR
and restart yarn and oozie service 

then the oozie java action could not import these configs. the java action can run successfully in security cluster.

**Comment by sai-krish** [comment]
Hi polingsky,
   Passing the above xmls by default for every action would be incorrect as you can create non hadoop jobs using these actions as well.
  The correct way to do this would be to set the parameter `oozie.service.HadoopAccessorService.action.configurations` in  oozie-default.xml for every action you need.

You can read more about this here - http://github.mtv.cloudera.com/CDH/oozie/blob/cdh5-4.1.0/core/src/main/resources/oozie-default.xml#L1891
