### ISSUE TITLE
Number precision loss in HUE ad-hoc query web result

### ISSUE THREAD

**Issue by xq262144** [cloudera/hue#335]
#### Problem
First, it is a common javascript case, not actually a HUE bug.
HUE has a ```/notebook/api/fetch_result_data``` api to get data for Ad-Hoc queries.
The response format of this api is ```application/json```.
On the client side, we simply call the browser api ```JSON.parse``` to transform the json text response to a JSON object.
If there is number (bigint/double) result in the json response and this number is out of the javascript safe integer range, the result would become inaccurate.
We could simply test this in browser console:
```javascript
JSON.parse('196643078539894907')
```
The result would be ```196643078539894900``` instead of expected ```196643078539894907```.

MDN Javascript Number MAX_SAFE_INTEGER page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

#### Solution
1. Perhaps we could convert all the data in json to string to keep number precision.
2. We use another JSON parser instead of browser default ```JSON.parse``` and convert number out of safe integer range to string.

**Comment by romainr** [comment]
@enricoberti, this was done in the older editor I think?

**Comment by romainr** [comment]
And tracking in https://issues.cloudera.org/browse/HUE-3472, will be there for the upcoming 3.10 release!

**Comment by enricoberti** [comment]
And resolved! Thanks @xq262144!

**Comment by xq262144** [comment]
Thanks a lot! @enricoberti

**Comment by xq262144** [comment]
@romainr I found another precision loss case in rdbms app, and here is my PR https://github.com/cloudera/hue/pull/343
