### ISSUE TITLE
hue content

### ISSUE THREAD

**Issue by JMetai** [cloudera/hue#336]
Where does all the dashboards created with HUE widgets are stored on Cloudera Manager version of HUE ?

Let's say I want to develop dashboards using HUE widgets in development and I'd like to deploy it to Production. Are these dashboards created as files somewhere on HUE instance so that I can take 
them and deploy it to Production?

With dashboard development, would it be possible to use version control tool such as Git ?

Thanks

**Comment by romainr** [comment]
All the data is saved in the Hue database.

If you want to export a few dashboards to another Hue, you can use the export/import:
http://gethue.com/exporting-and-importing-oozie-workflows/
http://gethue.com/export-and-import-your-search-dashboards/

**Comment by JMetai** [comment]
Thank you!
