### ISSUE TITLE
Saved Notebooks no longer allow user to add snippets, also show Hive Editor history

### ISSUE THREAD

**Issue by sumtumn** [cloudera/hue#3367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Described as in https://issues.cloudera.org/browse/HUE-9602

### Steps To Reproduce

I found this was introduced by https://github.com/cloudera/hue/commit/d7209ad85ebf8a0331a00f9890e59f8404ee6cb6, 
  desktop/libs/notebook/src/notebook/api.py
```def _save_notebook(notebook, user):
  if notebook['snippets'][0].get('connector') and notebook['snippets'][0]['connector'].get('dialect'):  # TODO Connector unification
    notebook_type = 'query-%(dialect)s' % notebook['snippets'][0]['connector']
    if notebook['snippets'][0] and notebook['snippets'][0].get('executor'):
      notebook['snippets'][0]['executor']['executables'] = []
  else:
    notebook_type = notebook.get('type', 'notebook')
```
If I change to the following code, it fixed.
```
def _save_notebook(notebook, user):
  if notebook['snippets'][0].get('connector') and notebook['snippets'][0]['connector'].get('dialect'):  # TODO Connector unification
    if notebook['snippets'][0] and notebook['snippets'][0].get('executor'):
      notebook['snippets'][0]['executor']['executables'] = []
  notebook_type = notebook.get('type', 'notebook')
```
But I don't have the context of releated commits, any suggesstions?

### Hue version

Open source release 4.10

**Comment by bjornalm** [comment]
Hi @sumtumn, thanks for reporting this bug. Since Hue is open source we do highly appreciate all contributions. To help us along, do you want to submit a pull request with the suggested code changes and we will have someone from the core team review it properly?

**Comment by bjornalm** [comment]
@sumtumn Check out https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md

**Comment by sumtumn** [comment]
Ok, I will create a PR when I am available.

**Comment by bjornalm** [comment]
> Ok, I will create a PR when I am available.

Awesome!
