### ISSUE TITLE
How to programmatically set permissions to a group?

### ISSUE THREAD

**Issue by tomiko20** [cloudera/hue#3369]
Are there any updates from your team regarding CLI functions to manage HUE users? This remains an issue.

### Discussed in https://github.com/cloudera/hue/discussions/1924

<div type='discussions-op-text'>

<sup>Originally posted by **oskotsky** December 15, 2020</sup>
After upgrading to Hue 4.7 we have to (1) create a group, (2) explicitly assign a non-admin user to a group, and (3) set group permissions (was not the case with Hue 4.4). Some of this can be done programmatically:
1. assign a user to the Linux group 
2. use useradmin_sync_with_unix to create hue user with the correct group assigned

However, I can't find a way to do (3): programmatically set permissions to a group. What is a programmatic way to do this? This can be done over GUI but we are running Hue on the cloud (fluid cluster) and everything has to be automated. Please advise.  </div>

**Comment by Harshg999** [comment]
@nidhibhatg - Can you take a look?
