### ISSUE TITLE
Integrate kyuubi with hue , use scala language , how to skip auto send "use default"

### ISSUE THREAD

**Issue by MyqueWooMiddo** [cloudera/hue#3377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I can use kyuubi (spark engine) with hue , just submit SQL , quite good feature .

When I send "set kyuubi.operation.language=scala;" in beeline console , the console transforms to 'spark-shell' , then I can send scala scripts in the beeline console , and I get correct results. 

When I send "set kyuubi.operation.language=scala;" in hue window,  it works , 
but I send other following scala scripts , it does not work . The error log shows that hue automatically sends "use default" to backend database server.

So, I just want a switch config to disable automaticall send "user default" in hue.

### Steps To Reproduce

I can use kyuubi (spark engine) with hue , just submit SQL , quite good feature .

When I send "set kyuubi.operation.language=scala;" in beeline console , the console transforms to 'spark-shell' , then I can send scala scripts in the beeline console , and I get correct results. 

When I send "set kyuubi.operation.language=scala;" in hue window,  it works , 
but I send other following scala scripts , it does not work . The error log shows that hue automatically sends "use default" to backend database server.

So, I just want a switch config to disable automaticall send "user default" in hue.

### Hue version

Open source release 4.11.0

**Comment by bjornalm** [comment]
Hi @MyqueWooMiddo and thank you for reaching out. Perhaps @sreenaths can help you with this?
