### ISSUE TITLE
Hue behind proxy

### ISSUE THREAD

**Issue by butterhc** [cloudera/hue#339]
I am working in a system where the preference is to have a single virtual host, and route application traffic to the appropriate instance via context routes.  Is there a way that hue can support this?

**Comment by romainr** [comment]
Have you looked at?
http://gethue.com/mini-task-configure-hue-with-a-proxy/
http://gethue.com/i-put-a-proxy-on-hue/
http://gethue.com/using-nginx-to-speed-up-hue-3-8-0/

**Comment by butterhc** [comment]
Thanks, I have. The closest thing to what I'm looking for is on the http://gethue.com/i-put-a-proxy-on-hue/ page.  However in that example hue consumes the "/" root context which is not desire-able.

I would rather have all hue traffic identified by the context root "hue". Is there a way to define the context path of the hue servlet?

For instance tomcat has the ability to load a context.xml with the app to do something similar to my request.
http://tomcat.apache.org/tomcat-7.0-doc/config/context.html

I think this is a fairly common enterprise setup to have one VIP for all traffic entering the site, then the different app traffic be routed by their context strings.

**Comment by Bengreen** [comment]
Has anyone managed to find a solution to this as this is quite a pain having to reserve a virtualhost for hue

**Comment by enricoberti** [comment]
Maybe experimenting a bit with mod_rewrite could do that

**Comment by Akhena** [comment]
We are currently running into this issue, which is now unfortunately closed without any leads to a solution.
As anyone managed to find a solution to host Hue behind a proxy with a context path different of "/" ?

**Comment by khusantt** [comment]
Up question. Maybe as anyone managed to find a solution
