### ISSUE TITLE
 <add title>Frequent login attempts

### ISSUE THREAD

**Issue by sqxinquan** [cloudera/hue#3396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Your session expired and your current action requires to reload this page

### Steps To Reproduce

Your session expired and your current action requires to reload this page

### Logs

Your session expired and your current action requires to reload this page

### Hue version

CDH6.1.1

**Comment by bjornalm** [comment]
Hi @sqxinquan, can you try to explain in more words what the bug is about, including steps to reproduce?

**Comment by sqxinquan** [comment]
I have been receiving error messages about reload all the time. I currently have 110 hub users, and in the middle, I have created a domain name resolution using nginx resolution
<img width="411" alt="image" src="https://github.com/cloudera/hue/assets/76837695/2e2c8f92-f4b9-44d5-94d1-1c2e5ff39ba2">

**Comment by bjornalm** [comment]
@sqxinquan thanks, can you share some more info please, like the config files and log files etc?

@tabraiz12 once we have more info, can you have a quick look at this one when you have some time to spare?

**Comment by wachoo** [comment]
I have also encountered the same problem, which is that there is a timeout parameter on nginx needs to be modified and fixed.
`proxy_connect_timeout 3600s;
proxy_send_timeout 3600s;
proxy_read_timeout 3600s;
send_timeout 3600s;`
