### ISSUE TITLE
Critical vulnerabilities in the image

### ISSUE THREAD

**Issue by Eanhain** [cloudera/hue#3411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello, was wondering if there are any plans to remove critical vulnerabilities in the hue image? In particular, I'm interested in the notebook library, which cannot be updated manually, as I understand it is modified for the needs of hue. 

![image](https://github.com/cloudera/hue/assets/42633367/c16f466d-39eb-41e4-8ef1-b7a0f18caa04)

### Steps To Reproduce

1. Make docker pull image hue
2. Run a vulnerability scan

### Hue version

release-4.11

**Comment by Harshg999** [comment]
Hey @Eanhain, thanks for reporting these vulnerabilities. `notebook` package is actually a false positive showing up because Hue as an app named "notebook" which the scan might be thinking of some other package.

For other vulnerabilities, can you share the package/CVEs list?

**Comment by Eanhain** [comment]
Critical vulnerabilities are in packages:
django 3.2.16
execa 0.7.0

There are high vulnerabilities in packages:
ubuntu/linux 5.4.0-153.170
cryptography 36.0.1
wheel 0.34.2
setuptools 45.2.0
kerberos 1.3.0
flower 0.9.7
celery 4.4.7

**Comment by Harshg999** [comment]
@ranade1 @wing2fly @athithyaaselvam - Can you please take a look?
