### ISSUE TITLE
Unable to add Hive DB 

### ISSUE THREAD

**Issue by pratik4891** [cloudera/hue#3416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hue is currently running on k8 and now trying to configure hive details in the config map section of the pods 

Provided below details 

[hive]
server_host=hostnam
server_port=10000
server_username=user
server_password=user

In UI only postgres DB is showing and not hive , please advise what setting changes need to be done

### Steps To Reproduce

Ran the helm commands 

helm repo add hue https://helm.gethue.com
helm install my-hue hue/hue --version 1.0.3

Opened the config map of the pod to add the hive details in below format 

[hive]
server_host=hostnam
server_port=10000
server_username=user
server_password=user

Refreshed the UI and no hive DBs were showing up

### Hue version

latest

**Comment by Harshg999** [comment]
Hey @pratik4891, IIRC the config section is `[beeswax]` instead of `[hive]`.
Can you once give that a try and see if that helps?
