### ISSUE TITLE
Npm install for version 6 does not work.

### ISSUE THREAD

**Issue by eonkleynhans** [cloudera/hue#3419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When attempting to install hue in a local svelte project the following error occurs.

### Steps To Reproduce

Run npm i gethue

### Logs

npm WARN tarball tarball data for cuix@file:desktop\core\src\desktop\static\desktop\ext\cuix\cuix-13.0.4.tgz (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for @cloudera/cuix-core@file:desktop\core\src\desktop\static\desktop\ext\cuix\cloudera-cuix-core-1.0.6.tgz (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for cuix@file:desktop\core\src\desktop\static\desktop\ext\cuix\cuix-13.0.4.tgz (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for @cloudera/cuix-core@file:desktop\core\src\desktop\static\desktop\ext\cuix\cloudera-cuix-core-1.0.6.tgz (null) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path ..\node_modules\gethue\desktop\core\src\desktop\static\desktop\ext\cuix\cloudera-cuix-core-1.0.6.tgz
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open '..\node_modules\gethue\desktop\core\src\desktop\static\desktop\ext\cuix\cloudera-cuix-core-1.0.6.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: ..\AppData\Local\npm-cache\_logs\2023-07-28T08_13_16_651Z-debug-0.log

### Hue version

Open source release 6

**Comment by Harshg999** [comment]
@JohanAhlen Any idea?

**Comment by rgrohitg** [comment]
+1 as there are few references in package.json which are ferred from the publishers local mahcine like cloudera-cuix-core-1.0.6.tgz'

**Comment by bjornalm** [comment]
@eonkleynhans Thanks for reporting. 
We have updated Hue to use new UI libraries from Cloudera. These are included as files in the open source repo and building the entire project works fine, but we forgot to update the gethue npm package to handle this change. I will try to get a fix ready next week.

Hue is open source and if you want to you can speed up the process and submit your own PR to fix this and we will publish the new package.

**Comment by bjornalm** [comment]
@rgrohitg @eonkleynhans We have updated and published a new version of the npm package. It should work now. I apologise for the delay.

**Comment by eonkleynhans** [comment]
Hi @bjornalm,
Apologies my delay in response as I haven't had time to look at it myself.
Thank you very much for looking into this!
