### ISSUE TITLE
hue stops polling for results abruptly after 5 min leading to network error in case of large file csv downloads 

### ISSUE THREAD

**Issue by satvik1992** [cloudera/hue#3435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are getting an error while downloading the presto query result from Hue UI. We are using hue 4.7.1 to execute queries on Presto, after executing the query we use download the query result as CSV option in Hue UI. The download progresses for sometime but then it fails (We get this error in the browser: Failed - Network error). We do not find any error logs on the hue pods though 

We observe this issue for large file csv downloads with the root cause that **hue stops polling for results abruptly after 5 min.** This happens 4 out of 5 times and hence the download fails with network error . **Is there any configuration/ time-out parameter that can be configured on the hue end that can fix this issue ?**

![NetworkErrorCsv](https://github.com/cloudera/hue/assets/66056033/5eeed2bd-0eb6-40f1-800a-64660e1d8aa6)

### Steps To Reproduce

1. Run a query that contains at least 5 columns  and 10 million rows.
2. Click on the option to download as a csv 
3. Observe that the download fails with message as network error 

### Hue version

4.7.1

**Comment by bjornalm** [comment]
@ranade1 I know this is for an old release, but do you know anything about this, can it be configured?

**Comment by ranade1** [comment]
Could you please provide more details on the following?

-     Which version of Hue are you using?
-     Is Hue running on a CDH On-Prem setup?
-     What is the size of the data file you are trying to download?
-     Can you share the configuration specifics of the Hue server?
