### ISSUE TITLE
 Error hive-server:10000 

### ISSUE THREAD

**Issue by Chinaskidev** [cloudera/hue#3442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello, I am having an error connecting to Hue. I am new to using these technologies and I would like to know if you could help me resolve this error.

"Could not connect to hive-server:10000 (code THRIFTTRANSPORT): TTransportException(u'Could not connect to hive-server:10000' "

I've seen in the terminal that there are two errors:
hive-metastore:9083"
    ports:
      - "10000:10000

ERROR    172.19.0.1 instructor - "POST /desktop/log_js_error HTTP/1.1" --- JS ERROR: {"msg":"Uncaught SyntaxError: Unexpected token ':'","url":"http://localhost:8888/hue/editor/?type=hive","line":2,"column":10,"stack":"SyntaxError: Unexpected token ':'\n    at DOMEval (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:152:12)\n    at Function.globalEval (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:386:3)\n    at text script (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:9905:11)\n    at ajaxConvert (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:9041:19)\n    at done (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:9511:15)\n    at XMLHttpRequest.<anonymous> (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:9813:9)"}

Thanks for the help!
![hue1](https://github.com/cloudera/hue/assets/108908392/30fa16d2-4b0d-4962-b24b-ad7d0081085d)

### Steps To Reproduce

ERROR    172.19.0.1 instructor - "POST /desktop/log_js_error HTTP/1.1" --- JS ERROR: {"msg":"Uncaught SyntaxError: Unexpected token ':'","url":"http://localhost:8888/hue/editor/?type=hive","line":2,"column":10,"stack":"SyntaxError: Unexpected token ':'\n    at DOMEval (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:152:12)\n    at Function.globalEval (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:386:3)\n    at text script (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:9905:11)\n    at ajaxConvert (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:9041:19)\n    at done (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:9511:15)\n    at XMLHttpRequest.<anonymous> (http://localhost:8888/static/desktop/js/bundles/hue/vendors~hue~notebook~tableBrowser-chunk-b7b41b4a7714b3f0eda6.23325c471e41.js:9813:9)"}

### Hue version

4.11

**Comment by bjornalm** [comment]
Hi @Chinaskidev and thanks for reaching out. Can you share your configuration data with us so that we can verify that your setup looks ok?

**Comment by Chinaskidev** [comment]
good day!! I appreciate you getting back to me.
I am sharing the file yml


`version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
    
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop-hive.env

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088"
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    ports:
      - "5432:5432"

  huedb:
    image: postgres:12.1-alpine
    volumes:
      - pg_data:/var/lib/postgresl/data/
    ports:
      - "5432"
    env_file:
      - ./hadoop-hive.env
    environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088 hive-metastore:9083"
  
  hue:
    image: gethue/hue:4.6.0
    environment:
        SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088 hive-metastore:9083 huedb:5000"
    ports:
      - "8888:8888"
    volumes:
      - ./hue-overrides.ini:/usr/share/hue/desktop/conf/hue-overrides.ini
    links:
      - huedb

volumes:
  namenode:
  datanode:
  pg_data:

`

**Comment by Chinaskidev** [comment]
i think the error is in the port 50070  but i dont know how i can fixing

**Comment by bjornalm** [comment]
@agl29 Any clue as to what is going on?

**Comment by Chinaskidev** [comment]
no, nothing!!! jeje well its ok thanks!
