### ISSUE TITLE
 LDAP auth error: 'ascii' codec can't decode byte 0xc5 in position 12: ordinal not in range(128)

### ISSUE THREAD

**Issue by discoteka** [cloudera/hue#3448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I wanted to integrate 4.10.0 version of Hue with LDAP. I've setup all the details under hue.ini and finally receive an error:
 LDAP auth error: 'ascii' codec can't decode byte 0xc5 in position 12: ordinal not in range(128)
Users in LDAP has non-English characters:
config       DEBUG    search_s('DC=XYZ', 2, '(&(sAMAccountName=%(user)s)(objectclass=*))') returned 1 objects: cn=john dœe,ou=company_xyz,ou=zewnêtrzna,dc=XYZ
Btw. I changed in hue.ini to utf-8, but without any specific results.

Any suggestions, or workaround? 

### Steps To Reproduce

1. Edit hue.ini and provide details for LDAP integration.
2. Restart service.
3. Go to WebUI and choose LDAP, provide user details. 
4. Check systemctl details or access.log

### Hue version

4.10.0

**Comment by discoteka** [comment]
I took a look at changes in ldap_access.py, but there is no improvement in my case.

**Comment by bjornalm** [comment]
Hi @discoteka and thanks for reporting. @ranade1 Can you have a look?

**Comment by discoteka** [comment]
Hi @bjornalm  thanks for assigning the task, I've edited ldap_access.py based on that issue https://github.com/cloudera/hue/commit/2290ee680b

**Comment by discoteka** [comment]
Hi @ranade1 any update on that?
