### ISSUE TITLE
The table "desktop_document2" is too large. Are there any safe methods to clean it up?

### ISSUE THREAD

**Issue by yogaliving** [cloudera/hue#3450]
### Description

The "desktop_document2" table has become excessively large and is associated with numerous foreign keys. I need to find a safe and appropriate way to clean up this table.

**Comment by twoyang0917** [comment]
![image](https://github.com/cloudera/hue/assets/3362750/ec94c68d-b1d9-4914-8007-eb797ac3000f)
I saw this at about page. It seems the following command will solve your problem.
```hue desktop_document_cleanup --cm-managed```
version is 4.11.0.
not verified. so please backup your database before you try it.
