### ISSUE TITLE
DB creation issue in HUE

### ISSUE THREAD

**Issue by natraj-956** [cloudera/hue#3476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to connecting my DB in HUE type as external database in custom mode but its getting error will connecting to it the error message is Connection Failed: Error accessing the database: invalid syntax (rdbms.py, line 
![Screenshot_1](https://github.com/cloudera/hue/assets/128578655/0f5380c4-4ec1-4e18-8ba4-4be040d7d77f)

### Steps To Reproduce

Docker installation with the image gethue/hue:latest

### Hue version

3.11

**Comment by bjornalm** [comment]
Hi @natraj-956 thanks for reporting. Sounds like a configuration issue, I'm gonna leave this open too see if anyone fro the community can help you out.
