### ISSUE TITLE
Hue - 403 - CSRF error body

### ISSUE THREAD

**Issue by yousafsafdar1** [cloudera/hue#3480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hue UI does not display anything when accessed from `localhost:8888` and shows an error related to **Hue - 403 - CSRF error body**. 

![Screenshot 2023-09-28 at 23 39 18](https://github.com/cloudera/hue/assets/97444419/b72708dc-08b9-4613-ba05-8ad3f6bfb1af)

The below settings are for connecting to Hadoop clusters, specifying a default file system, and configuring the database connection (MySQL). Additionally, it defines interpreters for MySQL and Trino, specifying their connection details on mEKS environment. Below are the configurations:

```
data:
  hue-ini: |
    [hadoop]
    [[hdfs_clusters]]
    [[[default]]]
    fs_defaultfs=
    [desktop]

    [[database]]
    engine=mysql
    host=hue-eks-test
    port=3306
    user=test
    password_script=/var/lib/hue/hue_passwords.sh
    name=hue_db

    [notebook]
    [[interpreters]]
      [[[mysql]]]
      name = mysql
      interface=sqlalchemy
      options='{"url": "mysql://test:xxxx@hue-eks-test:3306/hue_db"}'
      [[[trino]]]
      name = Trino
      interface=sqlalchemy
      options='{\"url\": \"trino://trino-svc:8080/tpch/default\"}'
```

We encountered the same issue on both Firefox and Chrome browsers while attempting to use versions 4.11 and 4.10 of Hue.

### Steps To Reproduce

1. Deploy all manifest files on mEKS
2. Run `kubectl port-forward service/hue 8888:8888`
3. Access using `http://localhost:8888`

### Logs

**Here is a summarized version of the lengthy error displayed on the Hue UI for your convenience:**

Hue - 403 - CSRF error body { display: none; visibility: hidden; padding-top: 120px; } .banner { height: 30px; width: 100%; padding: 0; position: fixed; top: 0; background-color: #F9F9F9; z-index: 1033; } .main-content { top: 106px!important; } .navigator { top: 30px!important; } .hue-title-bar { top: 58px!important; } if (document.documentMode && document.documentMode // check if it's a Firefox -1) { location.href = "/boohoo"; } } // check for IE document modes if (document.documentMode && document.documentMode 1 || suggestions.loading() --> 1 --> Type: Default: . Partition key Primary key Size User Group Permissions Date Popular join Popular join condition Popular aggregate - 31 --> Value Popular group by Popular group by Popular order by Popular order by Popular filter (function () { var aceUtil = ace.require('ace/autocomplete/util'); var HashHandler = ace.require('ace/keyboard/hash_handler').HashHandler; ko.bindingHandlers.matchedText = { init: function (element, valueAccessor) { var options = valueAccessor(); var $element = $(element); var refresh = function () { $element.empty(); var suggestion = options.suggestion; var value = options.isComment ? suggestion.details.comment : suggestion.value; if (options.filter() && suggestion.matchIndex > -1 && ((!options.isComment && !suggestion.matchComment) || (options.isComment && suggestion.matchComment))) { var before = value.substring(0, suggestion.matchIndex); var match = value.substring(suggestion.matchIndex, suggestion.matchIndex + suggestion.matchLength); var after = value.substring(suggestion.matchIndex + suggestion.matchLength); $element.append(document.createTextNode(before)); $('').text(match).appendTo($element); $element.append(document.createTextNode(after)); } else { $element.text(value); } }; refresh(); // matchIndex and matchLength are not observable, hence the pubsub to update var updatePubSub = huePubSub.subscribe('hue.ace.autocompleter.match.updated', refresh);

### Hue version

4.11

**Comment by bjornalm** [comment]
Hi @yousafsafdar1 and thanks for reporting. @amitsrivastava can you have quick look at this configuration and see what is wrong?

**Comment by yousafsafdar1** [comment]
Thank you @bjornalm for the response.

I tried to debug this issue more and found out that CSRF Token is Included in the form and sent correctly with the request after checking from the browser's (Chrome and Firefox) developer tools to inspect the network request which is causing the error.

`<input type="hidden" name="csrfmiddlewaretoken" value="...">`

See screenshots below from Chrome browser for your reference that might help your core team in resolving the issue.

<img width="1439" alt="CSRF-token1" src="https://github.com/cloudera/hue/assets/97444419/ea8a41f6-2e82-4ab4-91aa-9d67fdd3efc9">

<img width="1438" alt="CSRF-token2" src="https://github.com/cloudera/hue/assets/97444419/76ba933c-5923-4c7b-b8c3-21406eceba0f">

<img width="1435" alt="CSRF-token3" src="https://github.com/cloudera/hue/assets/97444419/d244fe06-abe8-41f4-8f74-2c02b26cc110">

**Comment by flash8627** [comment]
I also have the same problem 
Just like the landlord

**Comment by flash8627** [comment]
@yousafsafdar1  Has the problem been resolved?

**Comment by agl29** [comment]
Hello @yousafsafdar1 @flash8627,
Apologies for the delayed response. We've been occupied with implementing Trino-related features in Hue. It seems there might be an issue with the Trino configurations you provided. Please ensure that the correct format is used, like:
options='{"url": "http://localhost:8080/tpch"}'
Avoid using backslash around the url. And I hope this information proves helpful to you.
