### ISSUE TITLE
Results are not shown in new Notebooks

### ISSUE THREAD

**Issue by idzikovsky** [cloudera/hue#3491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It's not very clear what all the conditions are.
But now when I create new notebook, I'm unable to see output for some snippet types like Scala or Spark SQL (but I'm able to see output for sqlalchemy/MySQL snippet).

![Screenshot from 2023-10-06 16-02-02](https://github.com/cloudera/hue/assets/23353239/ed59383e-629a-4293-91ec-36ab07227811)

When notebook got saved I'm able to see output for Scala notes, but than things become weird.
For 2nd SparkSQL note I see an output from 1st note, and output for MySQL snippet now are not show.

![Screenshot from 2023-10-06 16-03-05](https://github.com/cloudera/hue/assets/23353239/01e2c036-9d9e-4f59-b84e-b0707cae8d23)

It seems like the issue appeared after [this fix](https://github.com/cloudera/hue/pull/2777).

Also, it explains why for the 2nd snippet I see output from the 1st snippet: it always takes a first snippet of the notebook:
```python
    snippet = notebook['snippets'][0]
````

I don't know how to fix this properly, but for me reverting that fix resolved the issue (however, it might brought back the problem which those fix has been made for) .

### Steps To Reproduce

Create new notebook, add some Spark or Spark SQL snippet and try to execute something there before saving that notebook.

### Hue version

4.11, master

**Comment by bjornalm** [comment]
@agl29 Could you have a look?

**Comment by idzikovsky** [comment]
For me reverting the fix for #2777 did the trick, however I think that the problem from #2777 came back.
I haven't dig a lot into the problem from #2777, so I haven't checked.
