### ISSUE TITLE
Hive 2.0 support?

### ISSUE THREAD

**Issue by cycyyy** [cloudera/hue#350]
The hive 2.0 has been released now.
But the beeswax is using hive 0.13 thrift
I want to use hbase1.x so that i have to update my hive to 2.0.
But hue does't support this.
Is that any plan about supporting hive 2.0?
Thanks a lot : )

**Comment by romainr** [comment]
Plan for Hive 2.0 is around Q3-Q4 this year (Hue is currently tested with 1.2). 

But isn't Thrift  backward compatible, even with 2.0?
