### ISSUE TITLE
Wrong database are selected by default in notebook Snippets

### ISSUE THREAD

**Issue by idzikovsky** [cloudera/hue#3505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When adding different kind of snippets in Notebook UI, selected database in right top side of the snippet always will be `default`.

![image](https://github.com/cloudera/hue/assets/23353239/6f00c3e5-7d17-40a9-b2f7-1a2f80d70613)
(I've added an empty Hive and than MySQL snippet.)

It appeared to be an issue after the following PR got merged:
https://github.com/cloudera/hue/pull/2897

### Steps To Reproduce

1. Create new Notebook.
2. Add snippets of different SQL types

### Hue version

4.11, master

**Comment by bjornalm** [comment]
@tabraiz12 Can you take a look?

**Comment by idzikovsky** [comment]
For me reverting the fix for #2897 did the trick, however I think that the problem from #2897 came back.
