### ISSUE TITLE
[beeswax] Hive Results Expired Immediately

### ISSUE THREAD

**Issue by sky4star** [cloudera/hue#352]
I am using Hue built from trunk branch, and i am using Hue with hiveserver2. I noticed my hive results expired very soon, not in days but in minutes. It seems as soon as i close the page it clean up the scratch folder.

I did some research, especially followed this document but no clue yet. http://gethue.com/hadoop-tutorial-hive-and-impala-queries-life-cycle/
All my configuration mentioned in the document is default value:

close_queries=false;
hive.server2.session.check.interval=0ms
hive.server2.idle.session.timeout=0ms
hive.server2.idle.operation.timeout=0ms

And i didn't found anything valuable in logs of namenode and hiveserver2.

**Comment by romainr** [comment]
I created https://issues.cloudera.org/browse/HUE-3709 to verify, and indeed we send a 'CloseSession' when we leave the page even if the close flag is off, going to fix it

**Comment by sky4star** [comment]
Thanks romain, again:)

**Comment by romainr** [comment]
https://github.com/cloudera/hue/commit/be4961692015880513d6392ff6c2299047fbe1c1
