### ISSUE TITLE
[trino][url][error]__init__() got an unexpected keyword argument 'SSL'

### ISSUE THREAD

**Issue by ElapsedSoul** [cloudera/hue#3527]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

I connected my trino with jdbc url like 'jdbc:trino://${ip}:${port}/hive?SSL=true&SSLVerification=NONE' correctly.

But in hue.ini
I set options='{"url": "trino://username:password@${ip}:${port}/hive?SSL=true&Verification=NONE","connect_args":"{\"protocol\": \"https\"}"}'

It seems '?SSL=true&Verification=NONE' not work as jdbc

### Steps To Reproduce

1. Setting options='{"url": "trino://username:password@${ip}:${port}/hive?SSL=true&Verification=NONE","connect_args":"{\"protocol\": \"https\"}"}'

2. Restart

### Hue version

4.10

**Comment by bjornalm** [comment]
@ElapsedSoul Thanks for reporting. @Harshg999 another Trino relate issue? Can you or @agl29 have a look?

**Comment by bjornalm** [comment]
@ElapsedSoul Glad you fid a fix :-) We would love a PR if you feel up to the task of making this a config.
