### ISSUE TITLE
presto 'user' and 'password' can not change in UI

### ISSUE THREAD

**Issue by ITRS1991** [cloudera/hue#3529]
### Description

I omitted 'user' and 'password' in presto config, they will be prompted in the UI. Hue not validating user credentials and just caching . Need to restart hue service to again prompt for login prompt if wrong credentials entered.

Other similar issue：
https://issues.cloudera.org/browse/HUE-7623

presto config：
    [[[presto]]]
      name=Presto
      interface=presto
      # ## Specific options for connecting to the Presto server.
      # ## The JDBC driver presto-jdbc.jar need to be in the CLASSPATH environment variable.
      # ## If 'user' and 'password' are omitted, they will be prompted in the UI.

      # ## LDAPS enabled over HTTPS.
      options='{"url": "jdbc:presto://<ip>:<port>/hive/default", "driver": "com.facebook.presto.jdbc.PrestoDriver"}'

**Comment by ElapsedSoul** [comment]
The same requirement. +1

**Comment by chengduhaha** [comment]
I believe this is a typical JDBC issue because I encountered it with other JDBC interfaces.

**Comment by 2416210017** [comment]
Is there a solution to this problem?

**Comment by ElapsedSoul** [comment]
Adding `${USER}:${PASSWORD}@` before `<ip>` in 
```options='{"url": "jdbc:presto://<ip>:<port>/hive/default",``` ,

like this ```options='{"url": "jdbc:presto://${USER}:${PASSWORD}@<ip>:<port>/hive/default",``` 

The web will prompt you to enter a username and password upon your initial access to the datasource.

@2416210017
