### ISSUE TITLE
HUE Job Designer mantain obsolet jar in oozie application workspace  lib folder

### ISSUE THREAD

**Issue by dscarlat** [cloudera/hue#353]
1. create a mapreduce action in Hue Job Designer. Point in "jar path" to your .jar file with the mapreduce code.
2. run it.
3. update the Job "jar path" to a new jar with your changes in the code.
4. run it.
5. look at oozie.wf.application.path lib folder and you'll see copies of both .jars... the new and the previous one
6. what is worst.... each map will run a differen .jar...

**Comment by romainr** [comment]
You would need to delete the old jar from the workspace folder? (below the cover, Oozie picks up everything in the lib dir of the workspace)

**Comment by dscarlat** [comment]
Yes this workaround works, but you can't see the workspace folder till you run the Job... I think HUE should take care of having in the workspace the right files...
