### ISSUE TITLE
Hue Docker image does not work on Graviton ec2 instance with aarch64

### ISSUE THREAD

**Issue by hafizmujadidKhalid** [cloudera/hue#3533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello!
I have an EKS cluster configured with AWS Graviton 64-bit ARM-based instances. I tried to deploy hue using helm but it did not work and gave the following error:
`exec ./startup.sh: exec format error`

Then I build the docker image using docker buildx and platforms: linux/amd64,linux/arm64. After that, it worked fine. Let us build a Hue docker image with multiple platforms to support Graviton instances. 

### Steps To Reproduce

1. Spin up an EC2 instance or EKS with AWS Graviton 64-bit ARM-based architecture.
2. Deploy hue using helm
3. Check pod logs, it will give an error

### Logs

Logs only contain one line:
**exec ./startup.sh: exec format error**

### Hue version

gethue/hue:latest

**Comment by bjornalm** [comment]
Hi @hafizmujadidKhalid and thanks for reporting. @agl29 Do you know if this this something that we are planning on supporting?
