### ISSUE TITLE
OIDC Auth causes ModuleNotFoundError: No module named 'mozilla_django_oidc'

### ISSUE THREAD

**Issue by David-N-Perkins** [cloudera/hue#3534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm using the latest Docker image and configuring auth to use OIDC. This causes a fatal exception about `mozilla_django_oidc` missing.

### Steps To Reproduce

1. Run the latest Docker image `gethue/hue:latest`. (I also tried several older tags on DockerHub)
2. Configure OIDCBackend for authentication. Here's a minimal hue.ini
```
[desktop]

# Webserver listens on this address and port
http_host=0.0.0.0
http_port=8888

[[auth]]
backend=desktop.auth.backend.OIDCBackend
```
3. Run the image. I'm running this on Kubernetes and got everything working using the default authentication. When I tried switching to OIDC, it won't start.

### Logs

[hue-54dc4d8c4d-kthjj-hue.log](https://github.com/cloudera/hue/files/13269847/hue-54dc4d8c4d-kthjj-hue.log)

### Hue version

gethue/hue:latest

**Comment by bjornalm** [comment]
Hi @David-N-Perkins and thanks for reporting. I'll leave this one open to see if anyone in the open source community has any ideas. Nor sure if it is a configuration issue or an actual bug. Did you have a look at the OIDC related discussions at our [discussion forum](https://discourse.gethue.com/search?q=OIDC)? If there is no progress then circle back and I'll assign this to someone from the core team to have a look when they have a moment to spare.

**Comment by David-N-Perkins** [comment]
Thanks for the link to the discussions forum. Found [OIDC Fails with Helm](https://discourse.gethue.com/t/oidc-fails-with-helm/430), from a while ago. It states `mozilla_django_oidc` is not included in the Docker image and has to be installed, which seems strange to me. Is there some kind of dependency conflict? It's also not recorded in the documentation anywhere I could find.

**Comment by David-N-Perkins** [comment]
I was able to get around the issue by extending the DockerHub Hue image. Here's the Dockerfile
```
FROM gethue/hue:20230822-140101
RUN ./build/env/bin/pip install --no-cache-dir mozilla_django_oidc
```
It would be nice to know if this is expected (in which case it needs to be added to the docs), or it will be fixed.

**Comment by bjornalm** [comment]
@David-N-Perkins glad to hear that you managed to get it working.
@ranade1 Do you know if this is by design or if we forgot it?
