### ISSUE TITLE
presto select result is repeated

### ISSUE THREAD

**Issue by fytz282117** [cloudera/hue#3562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

hue config presto connector, when I execute sql, the result is always wrong.
like this：
![1](https://github.com/cloudera/hue/assets/149564239/c051dbd9-f2d0-41e9-bdf9-5c22eb9afc74)
![2](https://github.com/cloudera/hue/assets/149564239/8522a140-fbf4-4836-9291-e2c9209bee93)

The correct result should be 49 pieces of data, when I dowload the result to excel or select count(*), the result is right.
![3](https://github.com/cloudera/hue/assets/149564239/615bd4f9-2992-4fb7-9404-0cc619b1b629)

Why?

### hue.ini
[desktop]
app_blacklist=hbase,importer
use_cherrypy_server=false
gunicorn_work_class=sync
[notebook]
[[interpreters]]
[[[hive]]]
name=Hive
interface=hiveserver2
[[[presto]]]
name=Presto
interface=sqlalchemy
options='{"url": "**********"}'

### docker-compose.yaml
version: '3.7'
services:
  hue:
      image: gethue/hue:latest
      hostname: hue
      container_name: hue
      ports:
      - "8889:8888"
      volumes:
        - /home/hue/conf/:/usr/share/hue/desktop/conf
      deploy:
        resources:
            limits:
              memory: 4G
            reservations:
              memory: 200M

### Hue version

gethue/hue:latest

**Comment by bjornalm** [comment]
Hi @fytz282117 and thanks for reporting. Is this happening for a specific query and dataset or is it always the case when you user presto?

**Comment by fytz282117** [comment]
> Hi @fytz282117 and thanks for reporting. Is this happening for a specific query and dataset or is it always the case when you user presto?

when I query a small dataset, it's ok，when I query a large dataset, it's repeated.

**Comment by fytz282117** [comment]
#1576 
#1580 
reasons may be pyhive?
when I try JDBC, raise exceptions, invalid syntax (jdbc.py, line 48:undefined).

**Comment by bjornalm** [comment]
@agl29 can you take a look?
