### ISSUE TITLE
HDP2.2 integrate hue failed.

### ISSUE THREAD

**Issue by henryon** [cloudera/hue#357]
I tried install Hue 3.9 on HDP2.2 and when hue installed. login found below errors:
Failed to access Hive warehouse: /user/hive/warehouse

I have hive directory is /apps/hive/warehouse  not /user/hive/warehouse.

Anyone can help on this? Thanks.

**Comment by romainr** [comment]
You would need to have a up to date hive-site.xml on the Hue machine, that way Hue will pick it up and know that you are not using the default HDFS path for the warehouse.

**Comment by henryon** [comment]
ok，thanks
