### ISSUE TITLE
failed % mvn -DskipTests -Dspark.version=1.4.1 clean package

### ISSUE THREAD

**Issue by xinwu246810** [cloudera/hue#358]
my spark version is 1.4.1. But when i do command " % mvn -DskipTests -Dspark.version=1.4.1 clean package", return 409. The error is:
[ERROR] Failed to execute goal on project livy-repl_2.10: Could not resolve dependencies for project com.cloudera.hue.livy:livy-repl_2.10:jar:3.9.0-SNAPSHOT: Failed to collect dependencies for [com.cloudera.hue.livy:livy-core_2.10:jar:3.9.0-SNAPSHOT (compile), org.scalatra:scalatra-scalatest_2.10:jar:2.3.0 (test), org.apache.httpcomponents:httpclient:jar:4.5 (test), org.apache.httpcomponents:httpcore:jar:4.4.1 (test), org.apache.spark:spark-assembly_2.10:jar:1.4.1 (test), org.apache.spark:spark-core_2.10:jar:1.4.1 (provided), org.xerial.snappy:snappy-java:jar:1.1.1.6 (test), org.apache.spark:spark-repl_2.10:jar:1.4.1 (provided), org.json4s:json4s-jackson_2.10:jar:3.2.5 (compile), net.sf.py4j:py4j:jar:0.8.2.1 (provided), net.databinder.dispatch:dispatch-core_2.10:jar:0.11.2 (compile), net.databinder.dispatch:dispatch-json4s-jackson_2.10:jar:0.11.2 (compile)]: Failed to read artifact descriptor for org.apache.spark:spark-assembly_2.10:jar:1.4.1: Could not transfer artifact org.apache.spark:spark-assembly_2.10:pom:1.4.1 from/to cloudera.snapshots.repo (https://repository.cloudera.com/content/repositories/snapshots): Failed to transfer file: https://repository.cloudera.com/content/repositories/snapshots/org/apache/spark/spark-assembly_2.10/1.4.1/spark-assembly_2.10-1.4.1.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]

Anyone can help on this? Thanks.

**Comment by xinwu246810** [comment]
failed `./hue livy_server`.The outputs are:
`[root@master bin]# ./hue livy_server
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/hdp/2.3.2.0-2950/hue/apps/spark/java-lib/livy-assembly.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/hdp/2.3.2.0-2950/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Failed to run spark-submit executable: java.io.IOException: Unable to determing spark-submit version [1]:
`
But using  `spark-submit --version` command. The outputs are:
`[root@master bin]# spark-submit --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.4.1
      /_/
                        
Type --help for more information.
`
When my spark version is `1.5.0`. The outputs are same! Could you help me ? Thanks. @romainr

**Comment by xinwu246810** [comment]
failed `./hue livy_server`.The outputs are:
```
[root@master bin]# ./hue livy_server 
SLF4J: Class path contains multiple SLF4J bindings. 
SLF4J: Found binding in [jar:file:/usr/hdp/2.3.2.0-2950/hue/apps/spark/java-lib/livy-assembly.jar!/org/slf4j/impl/StaticLoggerBinder.class] 
SLF4J: Found binding in [jar:file:/usr/hdp/2.3.2.0-2950/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class] 
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation. 
Failed to run spark-submit executable: java.io.IOException: Unable to determing spark-submit version [1]: 
```
But using `spark-submit --version` command. The outputs are:
```
[root@master bin]# spark-submit --version 
Welcome to 
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.4.1
      /_/
                        
Type --help for more information.
```
 When my spark version is `1.5.0`. The outputs are almost! The outputs are:
```
[root@slave2 bin]# ./hue livy_server
Failed to run spark-submit executable: java.io.IOException: Unable to determing spark-submit version [0]:

[root@slave2 bin]# spark-submit --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.5.0
      /_/
                        
Type --help for more information.
[root@slave2 bin]# 
```

Could you help me ? Thanks. @romainr

**Comment by romainr** [comment]
The livy version in Hue might block when it does not know the Spark version. This check was removed in the Livy project https://github.com/cloudera/livy
