### ISSUE TITLE
[Enhancement] Add support for Kyuubi JDBC connector

### ISSUE THREAD

**Issue by chengduhaha** [cloudera/hue#3587]
### Description

there is no a Kyuubi jdbc connector to query spark sql on hue, the kyuubi is as popular as livy.
here is my feature pl, please assign to me.
https://github.com/cloudera/hue/pull/3586

**Comment by Harshg999** [comment]
Thanks for working on the Kyuubi jdbc connector @chengduhaha, assigning the issue and PR to you.
