### ISSUE TITLE
Impala - Getting No available Impalad to send queries to.

### ISSUE THREAD

**Issue by FK7** [cloudera/hue#360]
I am trying to install Hue  on Amazon EMR(Hive, Impala installed in it) but getting No available Impalad to send queries to on UI.

And also I am able to hit the queries for Hive.

Is there anything am I missing here ?
Kindly anyone let me know how can I successfully installed the same on Amazon Linux AMI.

**Comment by romainr** [comment]
You need to tell Hue to which Impalads it can talk too by configuring the [impala] section in the hue.ini http://gethue.com/how-to-configure-hue-in-your-hadoop-cluster/

**Comment by FK7** [comment]
Thanks for the reply.
I am configuring the values in `pseudo-distributed.ini `and also specified the Impalad in the same but it does not work.

**Comment by FK7** [comment]
Hi 
Can anyone help me on this ?

**Comment by romainr** [comment]
If you open the /desktop/dump_config page in Hue, do you see the correct values in the Impala section?

**Comment by FK7** [comment]
yes @romainr things got resolved thanks for your assistance.
