### ISSUE TITLE
spark_opts not displayed on page reload

### ISSUE THREAD

**Issue by jjanyan** [cloudera/hue#361]
If you save a spark action with "Options list"  (spark_opts), then reload the page, the options are no longer displayed.

In [models2.py](https://github.com/cloudera/hue/blob/4616ba64913b9f6caa3d8585f0885bfc2620f5cc/apps/oozie/src/oozie/models2.py#L1972) there should probably be something like:

```
data['workflow']['properties']['spark_opts'] = old_wf.spark_opts
```

As a quick hack, I threw a try/except around it. It seemed unlikely that spark_opts is defined for every workflow. Works well enough.

Thanks

**Comment by spaztic1215** [comment]
@jjanyan which lines in models2.py did you add the above block to copy the old spark_opts?

**Comment by jjanyan** [comment]
here's a snippet. the last few lines are what i added. the try/except might not be necessary. i didn't spend time learning the code, so i took a defensive shortcut.
```
  # Workflow
  data['workflow']['uuid'] = str(uuid.uuid4())
  data['workflow']['name'] = old_wf.name
  data['workflow']['properties']['properties'] = json.loads(old_wf.job_properties)
  data['workflow']['properties']['job_xml'] = old_wf.job_xml
  data['workflow']['properties']['description'] = old_wf.description
  data['workflow']['properties']['schema_version'] = old_wf.schema_version
  data['workflow']['properties']['deployment_dir'] = old_wf.deployment_dir
  data['workflow']['properties']['parameters'] = json.loads(old_wf.parameters)
  data['workflow']['properties']['description'] = old_wf.description
  data['workflow']['properties']['sla'] = old_wf.sla
  data['workflow']['properties']['sla_enabled'] = old_wf.sla_enabled
  data['workflow']['properties']['imported'] = True
  data['workflow']['properties']['wf1_id'] = old_wf.id
  try:
    data['workflow']['properties']['spark_opts'] = old_wf.spark_opts
  except:
    pass
```
