### ISSUE TITLE
Issue while generating new parser

### ISSUE THREAD

**Issue by hiteshbaliyan** [cloudera/hue#3614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

While following https://docs.gethue.com/developer/development/#tutorial-creating-a-parser for the creation of new parser from the generic one like in example suggested `node generateParsers.js -new generic postgresql` encountering error as followed.

Environment versions are as followed:
Node v20.11.0
Npm 10.2.4
Python 3.9

``` bash
> node generateParsers.js -new generic postgresql

Identifying parsers...
Error: Could not find parser definitions for '-new, 'postgresql'
    at findParsersToGenerateFromArgs (file:///hue/tools/jison/generateParsers.js:49:11)
    at file:///hue/tools/jison/generateParsers.js:101:33
```

### Steps To Reproduce

cd tools/jison
npm install
node generateParsers.js -new generic postgresql

### Logs

Identifying parsers...
Error: Could not find parser definitions for '-new, 'postgresql'
    at findParsersToGenerateFromArgs (file:///hue/tools/jison/generateParsers.js:49:11)
    at file:///hue/tools/jison/generateParsers.js:101:33

### Hue version

release 4.11

**Comment by bjornalm** [comment]
Hi @hiteshbaliyan and thanks for reporting. I'll take look in the coming days.

**Comment by bjornalm** [comment]
Hi, sorry the long delay. It looks like new parser bootstrap tool was broken and removed some time ago since it was hardly ever used. I'll file a ticket to update the docs. Thanks for your patiance.
