### ISSUE TITLE
Same rdbms instance in HUE

### ISSUE THREAD

**Issue by rainysia** [cloudera/hue#363]
Hi there,
I use hue for mysql instance query, I have some mysql server and each server have serveral databases and tables,
E.G.:
HOST:PORT_____________________ Database_______Table
test-uat-0.domain.org:3308_______hive_test_______user, info,l og
test-uat-0.domain.org:3308_______hdp_test_______tbl_1, tbl_2
test-uat-2.domain.org:3308_______hive_test_______user, info, log     

Is there a simple way to configurate the `pseudo-distributed.ini` and let the HUE can **display different databases for one host**? 

Now i have to add the below content,

    [[[mysql0]]]
      nice_name="test 1"
      name=hive_test
      engine=mysql
      host=test-uat-0.domain.org
      port=3308
      user=read_user
      password=1234567
      options={"init_command":"SET NAMES 'utf8'"}
    [[[mysql1]]]
      nice_name="test 1"
      name=hdp_test
      engine=mysql
      host=test-uat-0.domain.org
      port=3308
      user=read_user
      password=1234567
      options={"init_command":"SET NAMES 'utf8'"}
    [[[mysql2]]]
      nice_name="test 1"
      name=hive_test
      engine=mysql
      host=test-uat-2.domain.org
      port=3308
      user=read_user
      password=1234567
      options={"init_command":"SET NAMES 'utf8'"}

Is hue can support a simple rdbms way like the below?

    [[[mysql0]]]
      nice_name="test 1"
      name=hive_test,hdp_test
      engine=mysql
      host=test-uat-0.domain.org
      port=3308
      user=read_user
      password=1234567
      options={"init_command":"SET NAMES 'utf8'"}
    [[[mysql2]]]
      nice_name="test 1"
      name=hive_test
      engine=mysql
      host=test-uat-2.domain.org
      port=3308
      user=read_user
      password=1234567
      options={"init_command":"SET NAMES 'utf8'"}

Thanks.

**Comment by romainr** [comment]
Yes, in the new editor http://gethue.com/custom-sql-query-editors/

**Comment by rainysia** [comment]
Hi Romanir, 
Thanks for you reply, 
I think we make a misunderstanding here,  I just want to use 
two database name for one DB instance.

So HUE can display a drop up in database name selectbox. Now there is only one `DATABASE`  list in the selectbox. How can we use it for multiple database name?
![1](https://cloud.githubusercontent.com/assets/1259324/15066367/23a7e888-139b-11e6-9160-ee07c865bd69.png)

**Comment by enricoberti** [comment]
Unfortunately that's not possible with the DB Query app at the moment

**Comment by romainr** [comment]
You would need to prefix the tables with the other databases and alternate. Are you looking at listing the tables of severals databases for joining them?

**Comment by rainysia** [comment]
Thanks, i will try, if can't, i will do some patch about this.

**Comment by YiwenWu** [comment]
@rainysia 请问这个问题你解决了吗？如何将一个连接中的指定不同数据库实例，能够放在同一个下拉框里，求教！！

**Comment by sudcha** [comment]
hi, did we get any patch for this? i am using Hue™ 3.12.0

Thanks.
