### ISSUE TITLE
1

### ISSUE THREAD

**Issue by fzxa** [cloudera/hue#3639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![企业微信截图_efd76c70-d9a5-4ca3-ae08-7b1ea4acc55f](https://github.com/cloudera/hue/assets/1428607/ae66c601-c28f-45af-87a0-2b71ebe872af)
![企业微信截图_25b1b634-43e6-45d3-9336-3ea07ea2d1db](https://github.com/cloudera/hue/assets/1428607/eac2b268-02f4-4959-a9ab-23afcd977e37)
![企业微信截图_3cf8a65f-dee6-464c-9865-f06e688ac294](https://github.com/cloudera/hue/assets/1428607/bae86311-4e7c-42ab-840d-e8c8ba54671d)
<img width="416" alt="企业微信截图_97b28424-a5e4-4f98-921e-078d45d2f1ac" src="https://github.com/cloudera/hue/assets/1428607/a33ed487-dfd7-4210-b5ec-52e030de9ce5">

### Steps To Reproduce

1.Kill this task:kyuubi_USER_SPARK_SQL_hadoop_default_xxxx
2.New task execution failed

### Logs

Error operating ExecuteStatement: org.apache.thrift.transport.TTransportException: java.net.SocketException: 断开的管道 (Write failed) at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:161) at org.apache.thrift.transport.TSaslTransport.flush(TSaslTransport.java:501) at org.apache.thrift.transport.TSaslClientTransport.flush(TSaslClientTransport.java:37) at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73) at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62) at org.apache.hive.service.rpc.thrift.TCLIService$Client.send_ExecuteStatement(TCLIService.java:239) at org.apache.hive.service.rpc.thrift.TCLIService$Client.ExecuteStatement(TCLIService.java:231) at org.apache.kyuubi.client.KyuubiSyncThriftClient.$anonfun$executeStatement$1(KyuubiSyncThriftClient.scala:252) at org.apache.kyuubi.client.KyuubiSyncThriftClient.$anonfun$withLockAcquiredAsyncRequest$2(KyuubiSyncThriftClient.scala:151) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750) Caused by: java.net.SocketException: 断开的管道 (Write failed) at java.net.SocketOutputStream.socketWrite0(Native Method) at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) at java.net.SocketOutputStream.write(SocketOutputStream.java:155) at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:159) ... 14 more

### Hue version

4.10

**Comment by fzxa** [comment]
1

**Comment by HYBG-1126** [comment]
请问，您解决这个问题了吗
