### ISSUE TITLE
How can I remove the help tips

### ISSUE THREAD

**Issue by zhuzhengjun01** [cloudera/hue#3647]
### Description

![image](https://github.com/cloudera/hue/assets/75296820/e8e17842-c4e3-4447-9569-1866d6cbb8c1)
I wanna remove the help tip in my case, but I can not find the switch in hue.ini

**Comment by bjornalm** [comment]
Hi, @zhuzhengjun01 and thanks for reaching out. Any special reason why you wanna remove the help section? It doesn't take up much space when collapsed. :-)

**Comment by zhuzhengjun01** [comment]
Thanks for your reply. We believe that this help section will affect non-professional users who may ask that this help does not give us internal tips but official usage

**Comment by zhuzhengjun01** [comment]
Therefore, we believe that the fewer sections in the interface, the less impact on users

**Comment by bjornalm** [comment]
I see. Well there is currently no setting that disables this, but if you want to you can add such a config and condition in a new PR and wI can review and merge it for you. We welcome open source contribution and I think that this one will have to be solved by the community.
