### ISSUE TITLE
Hue 3.10

### ISSUE THREAD

**Issue by JMetai** [cloudera/hue#366]
Hi Romain,

Any idea when Hue 3.10 will be releasing ?

Do you know following issue resolutions will be included in Hue 3.10 ?

https://issues.cloudera.org/browse/LIVY-49

https://github.com/cloudera/hue/commit/18a114fb3aff5399ba509e130d1159375700306b

Thanks,
Janga

**Comment by romainr** [comment]
We are targeting next week for 3.10.

Above jira is SPARK and commits above will be in 3.10
