### ISSUE TITLE
Hue demo page not working

### ISSUE THREAD

**Issue by TarynNicole** [cloudera/hue#3667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I navigate to https://demo.gethue.com/hue,

it provides the following error:

![image](https://github.com/cloudera/hue/assets/70257895/d46d5637-f42a-4745-92de-7690935a24aa)

### Steps To Reproduce

Logged on to https://demo.gethue.com/hue

### Hue version

gethue/hue:latest

**Comment by JohanAhlen** [comment]
Fix on the way with https://github.com/cloudera/hue/pull/3668
