### ISSUE TITLE
Demo site not working

### ISSUE THREAD

**Issue by wysisoft** [cloudera/hue#3684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am trying to browse different databases on the left pane on the demo site, and SparkSQL says "Could not connect to any of [('172.31.6.77', 10001)]". All the different db types seem to throw some kind of error.

### Steps To Reproduce

I am trying to browse different databases on the left pane on the demo site, and SparkSQL says "Could not connect to any of [('172.31.6.77', 10001)]". All the different db types seem to throw some kind of error.

### Hue version

current

**Comment by bjornalm** [comment]
Hi @wysisoft and thanks for reporting. @agl29 is this still the case and if so are we looking into it?

**Comment by agl29** [comment]
Hi @bjornalm 
I just checked, some of the dialects are working fine but still some are giving error.
