### ISSUE TITLE
the hue.ini config pr

### ISSUE THREAD

**Issue by pengcong90** [cloudera/hue#373]

**Comment by pengcong90** [comment]
where i ./build/env/bin/hue runserver the hue,it shows Starting development server at http://127.0.0.1:8000/,but i edited the hue.ini port 8888,then restart the hue,but it also show http://127.0.0.1:8000,who can give me some heip

**Comment by romainr** [comment]
If you run Hue with runserver, you need to edit desktop/conf/pseudo-distributed.ini instead. hue.ini is when you run with runcpserver command
