### ISSUE TITLE
Autocomplete duplicates table names when using Spark SQL and Hive

### ISSUE THREAD

**Issue by gustavofoa** [cloudera/hue#3746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using SQLAlchemy with Spark SQL and Hive autocomplate duplicates the table names.

The root cause seem to be that autocomplete calls ‘get_table_names’ and ‘get_view_names’ as we [can see here](https://github.com/cloudera/hue/blob/b3021149943c54f22f32d183f16113b9f3ae640a/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py#L461C23-L461C37). 

But in SQLAlchemy for Hive `get_view_names` calls `get_table_names` as we [can see here](https://github.com/dropbox/PyHive/blob/v0.6.1/pyhive/sqlalchemy_hive.py#L267_L270).

This causes duplicated table names as we can see in the printscreen bellow.

![image](https://github.com/cloudera/hue/assets/3338496/d263de9e-9b95-4511-92ab-181d7e43ef99)

### Steps To Reproduce

Connect Hue to SparkSQL with this config in `hue.ini`:

```
[[[sparksql]]]
  name = Spark Sql
  interface=sqlalchemy
  options='{"url": "hive://host.docker.internal:10000/bios"}'
```

### Hue version

gethue/hue:latest

**Comment by bjornalm** [comment]
Hi @gustavofoa and thanks for reporting. @Harshg999 can you take a look at this one or reassign if needed?
