### ISSUE TITLE
Permission denied /usr/share/hue/desktop/conf

### ISSUE THREAD

**Issue by vmtuan12** [cloudera/hue#3748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am deploying hue on k8s using this helm chart, and the pods keep having status CrashLoopBackOff. The image below illustrates the logs of the pod. How can I fix this?
![image](https://github.com/cloudera/hue/assets/100104530/b002e432-4866-4298-9da2-969d645dd762)

### Steps To Reproduce

I just use `helm install hue <repo>`

### Hue version

latest

**Comment by bjornalm** [comment]
Hi @vmtuan12 and thanks for reporting. @wing2fly Do you know why this is happening?
