### ISSUE TITLE
spark support with security not working

### ISSUE THREAD

**Issue by vishk123** [cloudera/hue#375]
I am trying to connect to setup a connection with hue + livy + spark + secure hadoop cluster. i am not able to connect secure but can connect to no-secure cluster though. Direct connection to hdfs/yarn is working fine. spark can also start a job on yarn but hue gives following error. I am using hue 3.9. Is this supported scenario.  could not fin much information here on this type of settings.

Could not start SASL: Error in sasl_client_start (-4) SASL(-4): no mechanism available: No worthy mechs found

after submit python script on notebook, it does not show anything not even error. Please suggest

**Comment by romainr** [comment]
Security support is coming in Livy 0.2 which is not released yet
