### ISSUE TITLE
erro No Module named Future

### ISSUE THREAD

**Issue by AbelLopezRuiz** [cloudera/hue#3757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello, I'm trying install the hue: latest version, hue-master, but, when the installation is running, then, it appears a error, about the module named future not found.

During installation, I've a redlines, about double path about ../${ROOT}/hue/desktop.... requeriments_base.txt

I've been trying to solve this issues for days, but I've got it!!

saludos. 

### Steps To Reproduce

--- Installing /home/hadoop/hadoop/hue/desktop/core/requirements.txt into virtual-env via /home/hadoop/hadoop/hue/build/env/bin/python3.8 /home/hadoop/hadoop/hue/build/env/bin/pip

ERROR: Could not open requirements file: [Errno 2] No existe el fichero o el directorio: '/home/hadoop/hadoop/hue/desktop/core/${ROOT}/desktop/core/base_requirements.txt'

--- Finished /home/hadoop/hadoop/hue/desktop/core/requirements.txt into virtual-env

Processing ./desktop/core/wheels/navoptapi-1.0.0-py3-none-any.whl

To address all issues (including breaking changes), run:

  npm audit fix --force

    from desktop.lib.thread_util import dump_traceback

  File "/home/hadoop/hadoop/hue/desktop/core/src/desktop/lib/thread_util.py", line 19, in <module>

    from future import standard_library

ModuleNotFoundError: No module named 'future'

make[1]: *** [Makefile:257: create-static] Error 1

make[1]: se sale del directorio '/home/hadoop/hadoop/hue'

make: *** [Makefile:237: install-env] Error 2

[hadoop@localhost hue-master]$

### Hue version

hue-master

**Comment by ranade1** [comment]
Set the ROOT environment variable to point out to your hue directory.
