### ISSUE TITLE
workflow sqoop about job xml  propertites 

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#376]
Hi 

   I want to use sqoop to import data from database to hbase using workflow
   But when I set credentials to hbase, it has a tips 'Requires hbase-site.xml in job path'
   In propertites tab, I can not find a JOB XML column for me to include hbase-site.xml?

![image](https://cloud.githubusercontent.com/assets/7900367/15355249/2afe7484-1d24-11e6-9a1e-ead58d496322.png)

    I try to include hbase-site.xml in files, but it doesn't work.

   If I use pig to insert data to hbase. In pig propertites, there is a JOB XML for me to include hbase-site.xml. so my pig job will succeed.

![image](https://cloud.githubusercontent.com/assets/7900367/15355302/71327fb8-1d24-11e6-8a48-2d4770355ee4.png)

   why sqoop workflow is no JOB XML?

   thanks.

**Comment by sai-krish** [comment]
What version of Hue is this ? I see it in Hue 3.9

**Comment by polingsky** [comment]
yes, 3.9

**Comment by sai-krish** [comment]
Like I said above, I see it in Hue 3.9. 

![sqoop-job-xml](https://cloud.githubusercontent.com/assets/9685943/15485822/5b7a3a64-20f6-11e6-9fa6-b2551597190c.png)


Are you seeing any Javascript errors ?

**Comment by polingsky** [comment]
!!!!!!!!!!!!
like the image.
![sqoop](https://cloud.githubusercontent.com/assets/7900367/15488768/4bf1c3dc-218c-11e6-93c8-1fdf3aa3a0f4.png)

only this error.

**Comment by sai-krish** [comment]
@polingsky any progress? Did you try re-deploying the static files by running
"./build/env/bin/hue collectstatic"

**Comment by polingsky** [comment]
Run "./build/env/bin/hue collectstatic" command, it still no JOB XML propertites
strange....

but If no other suggestions, 
it's ok, I find I  can use global settings to set the propertites.

Thanks.
