### ISSUE TITLE
Couldn't able to use hive in hue getting below error

### ISSUE THREAD

**Issue by ahamed08091990** [cloudera/hue#3765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Error
TSocket read 0 bytes (code THRIFTTRANSPORT): TTransportException('TSocket read 0 bytes')

Couldnt able to query or create any object in hive

### Steps To Reproduce

create database testhive;
TSocket read 0 bytes (code THRIFTTRANSPORT): TTransportException('TSocket read 0 bytes')

### Logs

Error
TSocket read 0 bytes (code THRIFTTRANSPORT): TTransportException('TSocket read 0 bytes')

### Hue version

unsure abt hue version of hue demo site

**Comment by sekhars-github** [comment]
I'm also getting same error, please someone can help me out on this issue.

Thanks in advance and appreciate your quick resolution .

**Comment by bjornalm** [comment]
Hi @ahamed08091990 and @sekhars-github

Thanks for reporting this, @Harshg999 can you take a look?

**Comment by Harshg999** [comment]
@ahamed08091990 @sekhars-github Can you check out the following links?
- https://github.com/cloudera/hue/discussions/2536
- https://github.com/cloudera/hue/discussions/2126

**Comment by ahamed08091990** [comment]
Hi Harsha,

I am using hue demo site for practicing.

I don't have any servers for setting this up.

Please let me know how to set the value mentioned in hue demo site for hive.

Thanks and Regards,
Syed

**Comment by ahamed08091990** [comment]
Does this issue got resolved?There is no update from my last mail.

**Comment by Harshg999** [comment]
Hey @ahamed08091990, Hive editor on demo.gethue.com is working fine now. Sometimes the demo playground requires a bit of cleanup from time to time.
