### ISSUE TITLE
RDBMS Results can't display any XML result in row.

### ISSUE THREAD

**Issue by rainysia** [cloudera/hue#377]
Hi Team,

Again, I have one mysql field and the value is 

`<doc>blablabla..</doc>`

The HUE will display nothing in there but i can use  browser F12 inspect the filed and find the HTML source code have the value.

So i guess we should add htmlencode or <pre>result</pre>in there ?

**Comment by rainysia** [comment]
https://github.com/cloudera/hue/pull/378

**Comment by romainr** [comment]
Thanks for the report and PR!
