### ISSUE TITLE
The results of the notebook interface cannot be displayed properly because its results interface is white

### ISSUE THREAD

**Issue by zhuzhengjun01** [cloudera/hue#3791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The results of the notebook interface cannot be displayed properly because its results interface is white
just like this 
![image](https://github.com/user-attachments/assets/3f8831fc-6687-4a42-8038-28bfd6d41760)

### Steps To Reproduce

I use this version of hue : gethue/hue:20240715-140101 
almost the latest version 

### Hue version

4.11.0 lastest

**Comment by zhuzhengjun01** [comment]
@Harshg999 hello，this problem also The problem is the same on the demo site

![image](https://github.com/user-attachments/assets/2903f143-eae3-42dd-80aa-6228b4abe065)

Can this problem be fixed？

**Comment by Harshg999** [comment]
Hey @zhuzhengjun01, thanks for reporting this. Any specific dialect you want to query where you are seeing this issue? Like does this happen for Hive editor also for you?

**Comment by zhuzhengjun01** [comment]
> Hey @zhuzhengjun01, thanks for reporting this. Any specific dialect you want to query where you are seeing this issue? Like does this happen for Hive editor also for you?

This should have nothing to do with the editor, it should have to do with opening the Notebook, and when the two snippets switch between them, the page rendering will not perform properly, so the result will be returned but not displayed

**Comment by zhuzhengjun01** [comment]
I fix it by this way, kind of hard code 
![image](https://github.com/user-attachments/assets/1020dba2-b906-4775-9fb1-00fb8f70c1aa)

**Comment by bjornalm** [comment]
Hi @zhuzhengjun01 and thanks for reporting. I can can reproduce when loading an existing notebook with multiple snippets and then executing one of them. 

I don't think the solution should be modifying the huePubSub.ts but probably how and when the `editor.render.data` event is published and managed. 

@ramprasadagarwal Could you take a look?

**Comment by zhuzhengjun01** [comment]
> Hi @zhuzhengjun01 and thanks for reporting. I can can reproduce when loading an existing notebook with multiple snippets and then executing one of them.
> 
> I don't think the solution should be modifying the huePubSub.ts but probably how and when the `editor.render.data` event is published and managed.
> 
> @ramprasadagarwal Could you take a look?

yes, this is not a good solution, just for using the notebook function temporary

**Comment by ramprasadagarwal** [comment]
Hi @zhuzhengjun01, I am unable to reproduce this bug at [demo.gethue.com](https://demo.gethue.com/). Can you please help me with the steps to reproduce it?

**Comment by zhuzhengjun01** [comment]
> Hi @zhuzhengjun01, I am unable to reproduce this bug at [demo.gethue.com](https://demo.gethue.com/). Can you please help me with the steps to reproduce it?

you can try switch  the snippet between any of the connectors and notebook, click the execute button then result will not rendering

**Comment by ramprasadagarwal** [comment]
> > Hi @zhuzhengjun01, I am unable to reproduce this bug at [demo.gethue.com](https://demo.gethue.com/). Can you please help me with the steps to reproduce it?
> 
> you can try switch the snippet between any of the connectors and notebook, click the execute button then result will not rendering

Thanks @zhuzhengjun01 

I am able to re-produce the bug both on [demo site](https://demo.gethue.com/hue) and on local, here are the detailed steps

1. Login to application (Logout and re-login if already logged in)
2. Navigate to any notebook and run the queries.
3. Navigate to any other notebook and run the queries. (White text will appear in table)
4. Refresh the page, the application works normal.
5. Logout and re-login, repeat step 2 and 3. Bug can be re-produced.

Attaching the screen recording for the reference.

**Workaround**: Refresh the page and re-run the query.

**Fix**: I will have deeper look on the root cause, in meanwhile please refer to workaround.

cc: @bjornalm 

https://github.com/user-attachments/assets/9a093510-010a-457a-b96a-55cbeb681c99

**Comment by zhuzhengjun01** [comment]
@ramprasadagarwal  this problem is still on the demo site,  i wanna know when this problem will be fixed?
