### ISSUE TITLE
 Hue launches multiple livy interactive sessions for the same user

### ISSUE THREAD

**Issue by rangareddy** [cloudera/hue#3801]
### Description

**Problem Statement:** Hue is launching the multiple livy interactive sessions for the same user. 

![HueSpark_SQL_afterMultipleRefreshes](https://github.com/user-attachments/assets/c8781b72-1c45-413d-bcb4-2f37152b49b9)

This is occurred due to end user **refresh the browser** or if the **browser session expires** and **refresh after expire** is **launching new applications**. Old Livy sessions stay until it reaches **livy.server.session.timeout** value. 

**Improvement:**

Either **use the existing livy session** or **create a new session by terminating old session**.

**Comment by Harshg999** [comment]
Hey @rangareddy, thanks for reporting this issue. 
I remember these duplicate Livy sessions gets cleaned up automatically if users are using the SparkSQL editor. Is this not the case for you after running some SparkSQL queries?
