### ISSUE TITLE
timeline error

### ISSUE THREAD

**Issue by hofst** [cloudera/hue#383]
I just stumbled across a problem. Until now, timelines worked without a problem with all my solr indices (CHD 5.7). But with a newly created index (only 10 documents, about 50 fields), the timeline stopped working with a javascript error:

The Firefox console shows:
![asd](https://cloud.githubusercontent.com/assets/2535762/15611580/4431210a-242b-11e6-9ae2-79b9667c5a12.PNG)

And the timeline dashboards never finishes:
![capture](https://cloud.githubusercontent.com/assets/2535762/15611562/22bdb826-242b-11e6-926d-ee4dd3959a61.PNG)

**Comment by hofst** [comment]
workaround:
it's working again after recreating from scratch in a new dashboard. My suspicion is that Hue got confused over the scheme over time (solr schemalessTemplate)

**Comment by romainr** [comment]
It is not oral though, if it happens again feel free to send a way to repro.

Coincidentally, we are currently improving the schemaless support https://github.com/cloudera/hue/commit/509733ea3b0dee47a4e5d83b523a341f67baa582, so far we mostly did for defied schemas

**Comment by hofst** [comment]
Just reproduced the issue (still cloudera 5.7):

- Create new schemaless index in solr
- create empty dashboard on this schema in hue
- ingress data
- create timeline (will never finish)

**Comment by hofst** [comment]
@romainr 

This issue keeps reoccuring in multiple dashboards and I would be really happy, if we could find a workaround other than recreating the whole dashboards. I attached an exported (corrupted) dashboard that shows the errorenous behaviour.


[test_hue.txt](https://github.com/cloudera/hue/files/318035/test_hue.txt)

**Comment by romainr** [comment]
So at dashboard creation there was a time_tdt field, but not it is gone?

I can see for adding a check to reset the time filter instead of bugging

**Comment by hofst** [comment]
> So at dashboard creation there was a time_tdt field, but not it is gone?

That's true for some cases. More general, the timefilter field appears to be selected automatically at dashbaord creation time. If there is no time field present at that time (e.g., a completely dynamic index is initially empty) or the time field temporarily disappears (e.g., a completely dynamic index temporarily becomes empty), then the dashboard gets corrupted, because the timefilter field is removed with no way to reset it manually.

I think the solution is to copy the behavior of elasticsearch/kibana: Give the user the option to set the timefilter field at index creation time and let him modify the field manually later. This also has the advantage that the user can correct an incorrectly guessed field later.
