### ISSUE TITLE
CORS cannot be disabled

### ISSUE THREAD

**Issue by yhvicey** [cloudera/hue#3839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

CORS cannot be disabled even with below configuration:
```ini
[desktop]
app_blacklist=corsheaders
cors_enabled=false
cors_allow_credentials=false
cors_allowed_origins=https://illegal-url/with/path
```
If CORS app/middleware is added the illegal url will trigger `SystemCheckError`, but after setting these configurations the error will not show up. However, even with this configuration, the CORS error will still show up.

### Steps To Reproduce

1. Spain up hue using helm chart
2. Update chart's value `hue.hue.ini` with above config
3. Try access it using ingress

### Hue version

Open source release 4.11

**Comment by Harshg999** [comment]
Hey @yhvicey, thanks for reporting this issue. Can you try your use-case with latest master?
