### ISSUE TITLE
Please support folder workflow editor list

### ISSUE THREAD

**Issue by linflytang** [cloudera/hue#384]
Now the workflow list in editor is not convenient to manage  when the workflow is more than 100+. How hard  it is to implement folder group manage(like the attach picture shows)?Left is folder tree, right is workflow list under the folder.
![unnamed qq screenshot20160530142316](https://cloud.githubusercontent.com/assets/13484409/15641363/f2fcd65e-2672-11e6-955b-ca0ec753967a.png)

**Comment by romainr** [comment]
Directories are available since Hue 3.10: http://gethue.com/hue-3-10-with-its-new-sql-editor-is-out/
