### ISSUE TITLE
 <jb> The task log reports SSL: CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by rayliu0** [cloudera/hue#3844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The stdout and stderr logs of the Hive task report the following error:
Failed to retrieve log: HTTPSConnectionPool(host='1a.5bcdewww.qq.comopqrtuvwxy-z', port=5009): Max retries exceeded with url: /node/containerlogs/container_e04_1726212362258_0249_01_000001/hadoop/stdout?start=-1000000&doAs=hadoop (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))

### Steps To Reproduce

1. yarn url https:// prefix
2. kerberos env: security_enabled=true
3. No CA is used： ssl_cert_ca_verify=false

### Logs

Failed to retrieve log: HTTPSConnectionPool(host='1a.5bcdewww.qq.comopqrtuvwxy-z', port=5009): Max retries exceeded with url: /node/containerlogs/container_e04_1726212362258_0249_01_000001/hadoop/stdout?start=-1000000&doAs=hadoop (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))

### Hue version

4.11.0

**Comment by rayliu0** [comment]
https://github.com/rayliu0/hue/commit/2271a4543e3afd317c635055a410c5c06b8c1312

**Comment by rayliu0** [comment]
https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests

**Comment by bjornalm** [comment]
Hi, @rayliu0 and thanks for reporting. 
@athithyaaselvam can you take a look?
