### ISSUE TITLE
fatal error:        'openssl/e_os2.h' file not found

### ISSUE THREAD

**Issue by dbl001** [cloudera/hue#386]
I'm trying to build 'hue' on OS X Yosemite: 10.11.5 with Xcode 7.3.1

There are similar incidents reported:

http://stackoverflow.com/questions/36443436/fatal-error-openssl-e-os2-h-file-not-found

http://blog.cloudera.com/blog/2015/04/how-to-install-hue-on-a-mac/

Any ideas?

**Comment by spaztic1215** [comment]
Were you able to successfully run `brew install openssl`?  You may need to export the headers, which for El Capitan can be done by setting the environment variables:

`export LDFLAGS=-L/usr/local/opt/openssl/lib && export CPPFLAGS=-I/usr/local/opt/openssl/include`

But in Yosemite the location of openssl may be different (i.e. - in Cellar), so you may need to symlink the path using `ln -s /usr/local/Cellar/openssl/1.0.2c/include/openssl /usr/local/include/openssl` or whatever, to symlink to your openssl location.  This thread should be helpful: https://github.com/phusion/passenger/issues/1630

**Comment by dbl001** [comment]
Sorry .. using Macports (not Home brew):

$ sudo port install openssl
Password:
Warning: port definitions are more than two weeks old, consider updating them by running 'port selfupdate'.
--->  Computing dependencies for openssl
--->  Deactivating openssl @1.0.2h_1+universal
--->  Cleaning openssl
--->  Activating openssl @1.0.2h_1
--->  Cleaning openssl
--->  Scanning binaries for linking errors
--->  Found 4 broken file(s), matching files to ports    
--->  Found 1 broken port(s), determining rebuild order
--->  Rebuilding in order
     python27 @2.7.11 +universal
--->  Computing dependencies for python27
--->  Dependencies to be installed: openssl
--->  Deactivating openssl @1.0.2h_1
--->  Cleaning openssl
--->  Activating openssl @1.0.2h_1+universal
--->  Cleaning openssl
--->  Cleaning python27
--->  Scanning binaries for linking errors
--->  No broken files found.

$ find /opt -name openssl -ls
263446412     2296 -rwxr-xr-x    1 root             admin             1174292 May 16 17:13 /opt/local/bin/openssl
60615166        0 drwxr-xr-x    5 root             admin                 170 Jun  1 10:55 /opt/local/etc/openssl
263446416        0 drwxr-xr-x   77 root             admin                2618 Jun  1 10:55 /opt/local/include/openssl
251500494        0 drwxr-xr-x   12 root             admin                 408 Apr 14 19:18 /opt/local/lib/ruby/1.8/openssl

I got past the include problems exporting 
export CPPFLAGS=-I/opt/local/include
                             
Now, I get a linker error:

ld: warning: directory not found for option '-L/opt/local/bin/openssl/lib'

It doesn’t seem to have an /opt/local/lib/openssl!

and also this:

ld: illegal text-relocation to '___gmp_binvert_limb_table' in /usr/local/lib/libgmp.a(mp_minv_tab.o) from '___gmpn_divexact_1' in /usr/local/lib/libgmp.a(dive_1.o) for architecture x86_64

**Comment by spaztic1215** [comment]
Hmm, not sure about what the flags should be set to for macports, but this is from cryptography's documentation: https://cryptography.io/en/latest/installation/#building-cryptography-on-os-x

**Comment by dbl001** [comment]
I installed and built ‘openssl’ and ‘gmp’ from github.
Hue built.

**Comment by riching** [comment]
ln -s /usr/local/opt/openssl/include/openssl /usr/local/include/openssl

**Comment by bsullins** [comment]
This is creeping back up on Sierra. After running through the steps [here](http://gethue.com/start-developing-hue-on-a-mac-in-a-few-minutes/) I am receiving the same error. For openssl here is what I find. 

Thoughts on what I'm missing?

` 
hue $ find . -name openssl
./desktop/core/ext-py/cryptography-1.3.1/build/lib.macosx-10.12-intel-2.7/cryptography/hazmat/backends/openssl
./desktop/core/ext-py/cryptography-1.3.1/build/lib.macosx-10.12-intel-2.7/cryptography/hazmat/bindings/openssl
./desktop/core/ext-py/cryptography-1.3.1/src/_cffi_src/openssl
./desktop/core/ext-py/cryptography-1.3.1/src/cryptography/hazmat/backends/openssl
./desktop/core/ext-py/cryptography-1.3.1/src/cryptography/hazmat/bindings/openssl
`

**Comment by bsullins** [comment]
Here is what I have for openssl installed

```
$ which openssl
/Users/ben/anaconda3/bin/openssl
```

**Comment by cogons** [comment]
> brew doctor
> brew prune (if openssllink is broken)
> cd /usr/local/include 
> ln -s ../opt/openssl/include/openssl .

it works for me on Sierra.

**Comment by deepix** [comment]
Setting the following worked:

```
export LDFLAGS=-L/usr/local/opt/openssl/lib
export CPPFLAGS=-I/usr/local/opt/openssl/include
```
I have installed openssl via `brew install`.
