### ISSUE TITLE
hue Fiile Browser Cannot access

### ISSUE THREAD

**Issue by M2shad0w** [cloudera/hue#387]
### error
```Cannot access: /user/hunliji. Note: you are a Hue admin but not a HDFS superuser, "hdfs" or part of HDFS supergroup, "supergroup".

RemoteException: User: hadoop is not allowed to impersonate hunliji (error 500)```

### syslog is below

```
[29/May/2016 18:08:28 -0700] middleware   INFO     Processing exception: {
  "RemoteException" : {
    "message" : "User: hue is not allowed to impersonate hunliji",
    "exception" : "AuthorizationException",
    "javaClassName" : "org.apache.hadoop.security.authorize.AuthorizationException"
  }
} (error 403): Traceback (most recent call last):
  File "/opt/hue-3.10.0/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/hue-3.10.0/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/opt/hue-3.10.0/apps/jobbrowser/src/jobbrowser/views.py", line 121, in jobs
    raise PopupException(ex)
PopupException: {
  "RemoteException" : {
    "message" : "User: hue is not allowed to impersonate hunliji",
    "exception" : "AuthorizationException",
    "javaClassName" : "org.apache.hadoop.security.authorize.AuthorizationException"
  }
} (error 403)
[29/May/2016 18:08:28 -0700] connectionpool DEBUG    "GET /ws/v1/cluster/apps?user=hunliji&finalStatus=UNDEFINED&limit=10000&user.name=hue&doAs=hunliji HTTP/1.1" 403 226
```

### my config
hadoop is in ha mode

and i do as the [gethue-site](http://gethue.com/how-to-configure-hue-in-your-hadoop-cluster)

in hdfs-site.xml

```xml
<property>
<name>dfs.webhdfs.enabled</name>
<value>true</value>
</property>
```
and in  core-site.xml

```xml
<property>
  <name>hadoop.proxyuser.hue.hosts</name>
  <value>*</value>
</property>
<property>
  <name>hadoop.proxyuser.hue.groups</name>
  <value>*</value>
</property>
<property>
    <name>hadoop.proxyuser.httpfs.hosts</name>
    <value>*</value>
</property>
<property>
    <name>hadoop.proxyuser.httpfs.groups</name>
    <value>*</value>
</property>
```

in  httpfs-site.xml

```xml
<configuration>
<!-- Hue HttpFS proxy user setting -->
<property>
  <name>httpfs.proxyuser.hue.hosts</name>
  <value>*</value>
</property>
<property>
  <name>httpfs.proxyuser.hue.groups</name>
  <value>*</value>
</property>
</configuration>
```

and in hue.ini 

```sh
55   # Webserver runs as this user
  56   server_user=hue
  57   server_group=hue
  58
  59   # This should be the Hue admin and proxy user
  60   default_user=hue
  61
  62   # This should be the hadoop cluster admin
  63   #default_hdfs_superuser=hadoop
```
```sh
685 [hadoop]
 686
 687   # Configuration for HDFS NameNode
 688   # ---------------------------------------------------------     ---------------
 689   [[hdfs_clusters]]
 690     # HA support by using HttpFs
 691
 692     [[[default]]]
 693       # Enter the filesystem uri
 694       fs_defaultfs=hdfs://cluster # hdfs://master:8020
 695
 696       # NameNode logical name.
 697       logical_name=cluster
 698
 699       # Use WebHdfs/HttpFs as the communication mechanism.
 700       # Domain should be the NameNode or HttpFs host.
 701       # Default port is 14000 for HttpFs.
 702       webhdfs_url=http://master:14000/webhdfs/v1
```

**Comment by romainr** [comment]
You need below as you are running Hue has hadoop apparently:

`<property>
  <name>hadoop.proxyuser.hadoop.hosts</name>
  <value>*</value>
</property>
<property>
  <name>hadoop.proxyuser.hadoop.groups</name>
  <value>*</value>
</property>`
