### ISSUE TITLE
How disable autocomplete feature in beeswax web-url

### ISSUE THREAD

**Issue by lynch0227** [cloudera/hue#389]
Hi All,

When I run the complex query in beeswax web-url, the CPU is become too high.
I suspect that because of autocomplete coding, now I want to disable that feature.
How can I do this?

**Comment by enricoberti** [comment]
hi!
do you have an example of a complex query for us so we can have a look? on which version of Hue do you experience this?

**Comment by romainr** [comment]
This was https://github.com/cloudera/hue/commit/cd345bd5efabfd9cd8244d203d568b1547279c93
