### ISSUE TITLE
Webpage language in chinese

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#390]
Hi:

  I have a question about webpage language.
  in Hue webpage, It will display some Chinese language, and some English language
  Can I force all words to English, but do not change my browsers language?

  
![lang](https://cloud.githubusercontent.com/assets/7900367/16066846/73de04aa-32e9-11e6-9310-a34c2a43e0a5.png)

thanks.

**Comment by romainr** [comment]
In your profile, Step2, change 'Language Preference'?

**Comment by polingsky** [comment]
you means to change browser language?

**Comment by romainr** [comment]
No, on the /useradmin/users/edit/romain page of Hue, Step 2

**Comment by polingsky** [comment]
My hue version is 3.9

![user](https://cloud.githubusercontent.com/assets/7900367/16222331/10fa2fea-37ca-11e6-853d-4c886d281807.png)

sorry, I can't see the  Language Preference.........

**Comment by romainr** [comment]
Yes, you would need to upgrade to 3.10
