### ISSUE TITLE
Like bug in My documents page

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#391]
Hi : 

   I have a small problem,  like the image steps,
   I refresh the page, the number will recover to original number.
   is it a bug ??

![hue_problem](https://cloud.githubusercontent.com/assets/7900367/16077361/e709c72a-332a-11e6-9e35-f5b1fdfd29d5.png)

    my hue version is 3.9
    thanks.

**Comment by romainr** [comment]
The good news is that it is fixed in Hue 3.10 with the new home page! (we will have a blog post soon about this)

**Comment by romainr** [comment]
The good news is that it is fixed in Hue 3.10 with the new home page! (we will have a blog post soon about this)
