### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by JMetai** [cloudera/hue#394]
Any one has instructions to enable or integrate SSO within HUE ?

Any help is much appreciated.

**Comment by romainr** [comment]
About SSO the latest doc is http://gethue.com/single-sign-on-in-hue-with-twitter-and-oauth/

**Comment by JMetai** [comment]
Thank you. 
I have update my hue.ini file with following:
ldap_url=ldaps://abc.xyz.mycompany.com
  search_bind_authentication=false
  nt_domain=ABC.XYZ.MYCOMPANY.COM
  create_users_on_login=true
  base_dn="DC=abc,DC=xyz,DC=mycompany,DC=com"

I have updated the above LDAP settings as per http://www.cloudera.com/documentation/enterprise/5-2-x/topics/cdh_sg_hue_ldap_config.html

I am able to login with my SSO credentials, however when I try to add/sync users on hue user admin interface, it throws following error.

useradmin.ldap_access.LdapBindException
LdapBindException: Failed to bind to LDAP server as user None@ABC.XYZ.CAPITALONE.COM


Any help is appreciated. Thanks
