### ISSUE TITLE
Failed to execute goal on project livy-repl_2.10

### ISSUE THREAD

**Issue by alicegugu** [cloudera/hue#396]
Hi,

I am trying to build tags/release-3.10.0, the following error happened, anyone can help? thanks.

> [INFO] livy-main ......................................... SUCCESS [2.594s]
> [INFO] livy-core_2.10 .................................... SUCCESS [40.673s]
> [INFO] livy-repl_2.10 .................................... FAILURE [1:04.587s]
> [INFO] livy-yarn_2.10 .................................... SKIPPED
> [INFO] livy-spark_2.10 ................................... SKIPPED
> [INFO] livy-server_2.10 .................................. SKIPPED
> [INFO] livy-assembly_2.10 ................................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1:48.561s
> [INFO] Finished at: Tue Jul 05 03:31:40 UTC 2016
> [INFO] Final Memory: 23M/55M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project livy-repl_2.10: Could not resolve dependencies for project com.cloudera.hue.livy:livy-repl_2.10:jar:0.2.0-SNAPSHOT: Failed to collect dependencies for [com.cloudera.hue.livy:livy-core_2.10:jar:0.2.0-SNAPSHOT (compile), com.fasterxml.jackson.core:jackson-core:jar:2.4.4 (compile), com.fasterxml.jackson.module:jackson-module-scala_2.10:jar:2.4.4 (provided), com.fasterxml.jackson.core:jackson-databind:jar:2.4.4 (compile), commons-codec:commons-codec:jar:1.9 (compile), javax.servlet:javax.servlet-api:jar:3.1.0 (compile), org.apache.httpcomponents:httpclient:jar:4.5 (test), org.apache.spark:spark-repl_2.10:jar:1.5.0-cdh5.5.0-SNAPSHOT (provided), org.apache.spark:spark-core_2.10:jar:1.5.0-cdh5.5.0-SNAPSHOT (provided), org.eclipse.jetty:jetty-server:jar:9.2.10.v20150310 (compile), org.eclipse.jetty:jetty-servlet:jar:9.2.10.v20150310 (compile), org.json4s:json4s-ast_2.10:jar:3.2.11 (compile), org.json4s:json4s-core_2.10:jar:3.2.11 (compile), org.json4s:json4s-jackson_2.10:jar:3.2.11 (compile), org.scala-lang:scala-compiler:jar:2.10.4 (provided), org.scala-lang:scala-library:jar:2.10.4 (provided), org.scala-lang:scala-reflect:jar:2.10.4 (provided), org.scalatest:scalatest_2.10:jar:2.2.4 (test), org.scalatra:scalatra_2.10:jar:2.3.0 (compile), org.scalatra:scalatra-json_2.10:jar:2.3.0 (compile), org.scalatra:scalatra-scalatest_2.10:jar:2.3.0 (test), org.scalatra:scalatra-test_2.10:jar:2.3.0 (test), org.slf4j:slf4j-api:jar:1.6.1 (compile), org.xerial.snappy:snappy-java:jar:1.1.1.6 (test), net.sf.py4j:py4j:jar:0.8.2.1 (provided), net.databinder.dispatch:dispatch-core_2.10:jar:0.11.2 (compile)]: Failed to read artifact descriptor for org.codehaus.jackson:jackson-core-asl:jar:${cdh.jackson.version}: Could not transfer artifact org.codehaus.jackson:jackson-core-asl:pom:${cdh.jackson.version} from/to cdh.releases.repo (https://repository.cloudera.com/content/groups/cdh-releases-rcs): Illegal character in path at index 103: https://repository.cloudera.com/content/groups/cdh-releases-rcs/org/codehaus/jackson/jackson-core-asl/${cdh.jackson.version}/jackson-core-asl-${cdh.jackson.version}.pom -> [Help 1]

**Comment by zhang-z** [comment]
I also got problem with livy-repl_2.10. Error info was a little bit different:

> [ERROR] Failed to execute goal on project livy-repl_2.10: Could not resolve dependencies for project com.cloudera.hue.livy:livy-repl_2.10:jar:0.2.0-SNAPSHOT: Failed to collect dependencies at org.apache.spark:spark-repl_2.10:jar:1.5.0-cdh5.5.0-SNAPSHOT -> org.apache.spark:spark-core_2.10:jar:1.5.0-cdh5.5.0-SNAPSHOT -> org.apache.avro:avro-mapred:jar:hadoop2:1.7.6-cdh5.5.0-SNAPSHOT -> org.apache.avro:avro:jar:1.7.6-cdh5.5.0-SNAPSHOT -> org.codehaus.jackson:jackson-core-asl:jar:${cdh.jackson.version}: Failed to read artifact descriptor for org.codehaus.jackson:jackson-core-asl:jar:${cdh.jackson.version}: Could not transfer artifact org.codehaus.jackson:jackson-core-asl:pom:${cdh.jackson.version} from/to cdh.snapshots.repo (https://repository.cloudera.com/content/repositories/snapshots): Failed to transfer file: https://repository.cloudera.com/content/repositories/snapshots/org/codehaus/jackson/jackson-core-asl/$%7Bcdh.jackson.version%7D/jackson-core-asl-$%7Bcdh.jackson.version%7D.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]

**Comment by xfei6868** [comment]
same error , why has  ${cdh.jackson.version} parameter

**Comment by xfei6868** [comment]
hue-3.9,  hue-3.10 all have this problem.

At last i change to hue-cdh5.7.1-release is no this problem.

**Comment by spaztic1215** [comment]
This should now be resolved with the commit that fixes https://issues.cloudera.org/browse/HUE-4267
