### ISSUE TITLE
[3.9] Filebrowser server 500 error

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#398]
Hi~

   I use hue 3.9. and test filebrowser folder permission
1. I have create two user with a1, a2
2. a1 create a file in /user/a1 folder
3. and a1 change /user/a1 folder permission to rwxrwxrwx and select  Recursive
      to check the file a1 created in a1 home folder is changed to rwxrwxrwx
4. then a1 change /user/a1 folder permission to rwxr-x--- again, and do not select Recursive
5. use a2 user to login. and go to a1 home folder to modify the file that a1 created 

![image](https://cloud.githubusercontent.com/assets/7900367/16722893/62fe0980-477c-11e6-9aaa-62588beb09d6.png)

 click save, the hue page will display server 500, like 

![image](https://cloud.githubusercontent.com/assets/7900367/16722915/838f9b82-477c-11e6-8ebe-624cd5c65fbb.png)

from runcpserver.log, it can see

![image](https://cloud.githubusercontent.com/assets/7900367/16722932/99f53a94-477c-11e6-8e6d-365032c611f3.png)

so, the page should display like the following image rather than display server 500 error
( the image is from I delete a file that I have no permission to do the operation.)

![image](https://cloud.githubusercontent.com/assets/7900367/16722988/d4bdc470-477c-11e6-8fdf-e20faf379b91.png)

thanks.

**Comment by romainr** [comment]
Fixed in 4.2
