### ISSUE TITLE
DB Query App

### ISSUE THREAD

**Issue by JMetai** [cloudera/hue#399]
Currently db query app supports only mysql and postgresql. Is there a plan to support other databases such as Oracle, SQL Server, Teradata etc.. ?

We are currently on CDH 5.5.1 and Hue 3.10 - I believe this version supports only Mysql and Postgresql

**Comment by romainr** [comment]
Yes, this is coming http://gethue.com/custom-sql-query-editors/ and will be official in Hue 4 I think

**Comment by JMetai** [comment]
Thank you. Any plan on getting Teradata and SQL Server support in future versions ?

**Comment by romainr** [comment]
We will promote the JDBC connector in Hue 4, this will which opens up to any database out of the box

**Comment by romainr** [comment]
https://docs.gethue.com/latest/administrator/configuration/editor/
