### ISSUE TITLE
Hue does not provide the option to provide krb5.conf path

### ISSUE THREAD

**Issue by vishk123** [cloudera/hue#400]
hue does not have any option to set krb5.conf other than default /etc/krb5.conf. What is the workaround for this issue ?

**Comment by romainr** [comment]
This can be changed by:

`[desktop]`
`[[kerberos]]`
`ccache_path=/some/alternate/path/to/ticket/cache`

**Comment by vishk123** [comment]
@romainr : Request is for KRB5CCNAME ( krb5.conf). property you mentioned is cache path but not the conf path.
