### ISSUE TITLE
Disable some of the hue requirements

### ISSUE THREAD

**Issue by JMetai** [cloudera/hue#402]
Currently I am using git version of hue and solr for dashboards. I am not using hadoop, hive, oozie and etc..

I disabled hive, impala, oozie and etc.. in hue.ini file.

Hue shows errors when I login, is there a option or setting in hue.ini file to disable following:

hadoop.hdfs_clusters.default.webhdfs_url	Current value: http://localhost:50070/webhdfs/v1
Failed to access filesystem root
Resource Manager	Failed to contact an active Resource Manager: ('Connection aborted.', error(101, 'Network is unreachable'))
desktop.secret_key	Current value: 
Secret key should be configured as a random string. All sessions will be lost on restart

**Comment by romainr** [comment]
http://gethue.com/solr-search-ui-only/ ?
