### ISSUE TITLE
multiple hive query in hive editor page

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#403]
Hi~

  I have a question about hive query

 From the image, I have three hive queries in hive editor
 But when I execute it, it only run first query (create table). the last two query do not execute.
 
![hive_query](https://cloud.githubusercontent.com/assets/7900367/17050394/28cd1556-5025-11e6-9ea8-0fafba3de285.jpg)

So I want to ask the situation is normal or abnormal ?
 If in the hive query editor, only execute one hive query at the same time?

My hue version is 3.9. Thanks.

**Comment by romainr** [comment]
It looks like a bug there. Could you copy paste the query here so that I can quick try on the latest Hue?

**Comment by romainr** [comment]
Good in 3.10

**Comment by enridaga** [comment]
Hi, this seems to happen also on version 4.0, cannot test whether was fixed in 4.1 though.

**Comment by zzzharpreet** [comment]
The same issue persist in Hue4.3. I can't run multiple queries.
