### ISSUE TITLE
update the index by solr with the file in HDFS

### ISSUE THREAD

**Issue by zjline** [cloudera/hue#406]
hi 
I create a index from a file in hdfs by hue web UI.So if I want to update it from the other one file in hdfs by solr,how can I do it ?
thanks!

**Comment by romainr** [comment]
Try the 'Index file' button from the indexer app, e.g. http://demo.gethue.com/indexer/#edit/log_analytics_demo

**Comment by zjline** [comment]
There is a new index file everyday,So I should update the index everyday by manual?I hope it can update automatically from a dirctory in hdfs!
Can this be achieved？
thanks！
