### ISSUE TITLE
issue while HUE 3.10 Adding Jars to classpath for Mysql query

### ISSUE THREAD

**Issue by aibati2008** [cloudera/hue#410]
Is there any version required for mysql JDBC client drivers?
when I test the JDBC connector to mysql (leave out the id/pwd), it’s stuck in Notebook for long time. But only show the database names after I add the id/pwd in hue.ini .

my configuration related mysql as below:
    [[[mysql]]]
      name=MySql JDBC
      interface=jdbc
      options='{"url": "jdbc:mysql://192.168.64.13:3306/fmcmspider","driver": "com.mysql.jdbc.Driver"}'

my hue related process running as below:
![image](https://cloud.githubusercontent.com/assets/10130476/17580695/2c327be2-5fd3-11e6-9a9c-fe8b6d95e31e.png)

![image](https://cloud.githubusercontent.com/assets/10130476/17508696/ce56e462-5e48-11e6-92b8-042fba33414c.png)

ps: the id/pwd should by right because I can query the data when change the interface=rdbms.

Please help, thanks!

**Comment by romainr** [comment]
Could you try to add a MySQL jdbc snippet first?
There might be a bug when you try to use the assist without connecting.

When you add the snippet for the first time and execute it, it should prompt like in the picture below.

{code}
options='{"url": "jdbc:mysql://localhost:3306/hue", "driver": "com.mysql.jdbc.Driver"}'
{code}

![jdbc-connect](https://cloud.githubusercontent.com/assets/17945/17607413/7227932e-5fda-11e6-92c7-c8f5cd09d9bc.png)

**Comment by aibati2008** [comment]
yes, I have tried for times but still got the problem.
![image](https://cloud.githubusercontent.com/assets/10130476/17611249/3785e9d4-6078-11e6-8280-2fb40777beb9.png)
![image](https://cloud.githubusercontent.com/assets/10130476/17611265/55ee5956-6078-11e6-823e-4ad03517ef8a.png)

**Comment by aibati2008** [comment]
when I install and compile the version 3.11, the problem was disappear.

But still can only view the database but no tables in the left dashboard.
