### ISSUE TITLE
Compile error: cannot import name get_regions

### ISSUE THREAD

**Issue by lucasa** [cloudera/hue#412]
Today, I've got this error whem compiling the master.
My system is Ubuntu 14.04.

root@10:/home/codes/hue# make desktop
cd /home/codes/hue/maven && mvn install 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Hue Maven Parent POM 3.10.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (default) @ hue-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.3:install (default-install) @ hue-parent ---
[INFO] Installing /home/codes/hue/maven/pom.xml to /root/.m2/repository/com/cloudera/hue/hue-parent/3.10.0-SNAPSHOT/hue-parent-3.10.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.432s
[INFO] Finished at: Mon Aug 15 11:22:43 BRT 2016
[INFO] Final Memory: 6M/153M
[INFO] ------------------------------------------------------------------------
make[1]: Entrando no diretório `/home/codes/hue/desktop'
make -C core env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/core'
--- Installing desktop into virtual-env
running develop
running egg_info
writing requirements to src/desktop.egg-info/requires.txt
writing src/desktop.egg-info/PKG-INFO
writing top-level names to src/desktop.egg-info/top_level.txt
writing dependency_links to src/desktop.egg-info/dependency_links.txt
writing entry points to src/desktop.egg-info/entry_points.txt
reading manifest file 'src/desktop.egg-info/SOURCES.txt'
writing manifest file 'src/desktop.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/desktop.egg-link (link to src)
desktop 3.10.0 is already the active version in easy-install.pth
Installing hue script to /home/codes/hue/build/env/bin
Installing supervisor script to /home/codes/hue/build/env/bin

Installed /home/codes/hue/desktop/core/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/core'
make -C libs/aws env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/aws'
--- Installing aws into virtual-env
running develop
running egg_info
writing requirements to src/aws.egg-info/requires.txt
writing src/aws.egg-info/PKG-INFO
writing top-level names to src/aws.egg-info/top_level.txt
writing dependency_links to src/aws.egg-info/dependency_links.txt
writing entry points to src/aws.egg-info/entry_points.txt
reading manifest file 'src/aws.egg-info/SOURCES.txt'
writing manifest file 'src/aws.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/aws.egg-link (link to src)
aws 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/aws/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/aws'
make -C libs/hadoop env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/hadoop'
--- Installing hadoop into virtual-env
running develop
running egg_info
writing requirements to src/hadoop.egg-info/requires.txt
writing src/hadoop.egg-info/PKG-INFO
writing top-level names to src/hadoop.egg-info/top_level.txt
writing dependency_links to src/hadoop.egg-info/dependency_links.txt
writing entry points to src/hadoop.egg-info/entry_points.txt
reading manifest file 'src/hadoop.egg-info/SOURCES.txt'
writing manifest file 'src/hadoop.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/hadoop.egg-link (link to src)
hadoop 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/hadoop/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/hadoop'
make -C libs/indexer env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/indexer'
--- Installing indexer into virtual-env
running develop
running egg_info
writing requirements to src/indexer.egg-info/requires.txt
writing src/indexer.egg-info/PKG-INFO
writing top-level names to src/indexer.egg-info/top_level.txt
writing dependency_links to src/indexer.egg-info/dependency_links.txt
writing entry points to src/indexer.egg-info/entry_points.txt
reading manifest file 'src/indexer.egg-info/SOURCES.txt'
writing manifest file 'src/indexer.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/indexer.egg-link (link to src)
indexer 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/indexer/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/indexer'
make -C libs/liboauth env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/liboauth'
--- Installing liboauth into virtual-env
running develop
running egg_info
writing requirements to src/liboauth.egg-info/requires.txt
writing src/liboauth.egg-info/PKG-INFO
writing top-level names to src/liboauth.egg-info/top_level.txt
writing dependency_links to src/liboauth.egg-info/dependency_links.txt
writing entry points to src/liboauth.egg-info/entry_points.txt
reading manifest file 'src/liboauth.egg-info/SOURCES.txt'
writing manifest file 'src/liboauth.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/liboauth.egg-link (link to src)
liboauth 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/liboauth/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/liboauth'
make -C libs/liboozie env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/liboozie'
--- Installing liboozie into virtual-env
running develop
running egg_info
writing requirements to src/liboozie.egg-info/requires.txt
writing src/liboozie.egg-info/PKG-INFO
writing top-level names to src/liboozie.egg-info/top_level.txt
writing dependency_links to src/liboozie.egg-info/dependency_links.txt
writing entry points to src/liboozie.egg-info/entry_points.txt
reading manifest file 'src/liboozie.egg-info/SOURCES.txt'
writing manifest file 'src/liboozie.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/liboozie.egg-link (link to src)
liboozie 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/liboozie/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/liboozie'
make -C libs/libopenid env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/libopenid'
--- Installing libopenid into virtual-env
running develop
running egg_info
writing requirements to src/libopenid.egg-info/requires.txt
writing src/libopenid.egg-info/PKG-INFO
writing top-level names to src/libopenid.egg-info/top_level.txt
writing dependency_links to src/libopenid.egg-info/dependency_links.txt
writing entry points to src/libopenid.egg-info/entry_points.txt
reading manifest file 'src/libopenid.egg-info/SOURCES.txt'
writing manifest file 'src/libopenid.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/libopenid.egg-link (link to src)
libopenid 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/libopenid/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/libopenid'
make -C libs/librdbms env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/librdbms'
--- Installing librdbms into virtual-env
running develop
running egg_info
writing requirements to src/librdbms.egg-info/requires.txt
writing src/librdbms.egg-info/PKG-INFO
writing top-level names to src/librdbms.egg-info/top_level.txt
writing dependency_links to src/librdbms.egg-info/dependency_links.txt
writing entry points to src/librdbms.egg-info/entry_points.txt
reading manifest file 'src/librdbms.egg-info/SOURCES.txt'
writing manifest file 'src/librdbms.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/librdbms.egg-link (link to src)
librdbms 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/librdbms/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/librdbms'
make -C libs/libsaml env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/libsaml'
--- Installing libsaml into virtual-env
running develop
running egg_info
writing requirements to src/libsaml.egg-info/requires.txt
writing src/libsaml.egg-info/PKG-INFO
writing top-level names to src/libsaml.egg-info/top_level.txt
writing dependency_links to src/libsaml.egg-info/dependency_links.txt
writing entry points to src/libsaml.egg-info/entry_points.txt
reading manifest file 'src/libsaml.egg-info/SOURCES.txt'
writing manifest file 'src/libsaml.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/libsaml.egg-link (link to src)
libsaml 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/libsaml/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/libsaml'
make -C libs/libsentry env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/libsentry'
--- Installing libsentry into virtual-env
running develop
running egg_info
writing requirements to src/libsentry.egg-info/requires.txt
writing src/libsentry.egg-info/PKG-INFO
writing top-level names to src/libsentry.egg-info/top_level.txt
writing dependency_links to src/libsentry.egg-info/dependency_links.txt
writing entry points to src/libsentry.egg-info/entry_points.txt
reading manifest file 'src/libsentry.egg-info/SOURCES.txt'
writing manifest file 'src/libsentry.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/libsentry.egg-link (link to src)
libsentry 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/libsentry/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/libsentry'
make -C libs/libsolr env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/libsolr'
--- Installing libsolr into virtual-env
running develop
running egg_info
writing requirements to src/libsolr.egg-info/requires.txt
writing src/libsolr.egg-info/PKG-INFO
writing top-level names to src/libsolr.egg-info/top_level.txt
writing dependency_links to src/libsolr.egg-info/dependency_links.txt
writing entry points to src/libsolr.egg-info/entry_points.txt
reading manifest file 'src/libsolr.egg-info/SOURCES.txt'
writing manifest file 'src/libsolr.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/libsolr.egg-link (link to src)
libsolr 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/libsolr/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/libsolr'
make -C libs/libzookeeper env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/libzookeeper'
--- Installing libzookeeper into virtual-env
running develop
running egg_info
writing requirements to src/libzookeeper.egg-info/requires.txt
writing src/libzookeeper.egg-info/PKG-INFO
writing top-level names to src/libzookeeper.egg-info/top_level.txt
writing dependency_links to src/libzookeeper.egg-info/dependency_links.txt
writing entry points to src/libzookeeper.egg-info/entry_points.txt
reading manifest file 'src/libzookeeper.egg-info/SOURCES.txt'
writing manifest file 'src/libzookeeper.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/libzookeeper.egg-link (link to src)
libzookeeper 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/libzookeeper/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/libzookeeper'
make -C libs/metadata env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/metadata'
--- Installing metadata into virtual-env
running develop
running egg_info
writing requirements to src/metadata.egg-info/requires.txt
writing src/metadata.egg-info/PKG-INFO
writing top-level names to src/metadata.egg-info/top_level.txt
writing dependency_links to src/metadata.egg-info/dependency_links.txt
writing entry points to src/metadata.egg-info/entry_points.txt
reading manifest file 'src/metadata.egg-info/SOURCES.txt'
writing manifest file 'src/metadata.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/metadata.egg-link (link to src)
metadata 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/metadata/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/metadata'
make -C libs/notebook env-install
make[2]: Entrando no diretório `/home/codes/hue/desktop/libs/notebook'
--- Installing notebook into virtual-env
running develop
running egg_info
writing requirements to src/notebook.egg-info/requires.txt
writing src/notebook.egg-info/PKG-INFO
writing top-level names to src/notebook.egg-info/top_level.txt
writing dependency_links to src/notebook.egg-info/dependency_links.txt
writing entry points to src/notebook.egg-info/entry_points.txt
reading manifest file 'src/notebook.egg-info/SOURCES.txt'
writing manifest file 'src/notebook.egg-info/SOURCES.txt'
running build_ext
Creating /home/codes/hue/build/env/lib/python2.7/site-packages/notebook.egg-link (link to src)
notebook 3.10.0 is already the active version in easy-install.pth

Installed /home/codes/hue/desktop/libs/notebook/src
make[2]: Saindo do diretório `/home/codes/hue/desktop/libs/notebook'
--- Regenerating database at /home/codes/hue/desktop/desktop.db
--- Syncing/updating database at /home/codes/hue/desktop/desktop.db
Traceback (most recent call last):
  File "/home/codes/hue/build/env/bin/hue", line 9, in <module>
    load_entry_point('desktop', 'console_scripts', 'hue')()
  File "/home/codes/hue/desktop/core/src/desktop/manage_entry.py", line 59, in entry
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'desktop.settings' (Is it on sys.path? Is there an import error in the settings file?): cannot import name get_regions
make[1]: ** [/home/codes/hue/desktop/desktop.db] Erro 1
make[1]: Saindo do diretório `/home/codes/hue/desktop'
make: ** [desktop] Erro 2

**Comment by romainr** [comment]
get_regions might be from the AWS lib. Does it still error if you do a fresh clone in another directory?
