### ISSUE TITLE
make: *** [parent-pom] Error 1

### ISSUE THREAD

**Issue by kskp** [cloudera/hue#413]
Installing Hue on Centos 6.6.

[root@centos6 hue]# java -version
java version "1.7.0_111"
OpenJDK Runtime Environment (rhel-2.6.7.2.el6_8-x86_64 u111-b01)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

[root@centos6 hue]# mvn -version
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 08:51:28-0500)
Maven home: /usr/local/maven
Java version: 1.7.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.111.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-504.el6.x86_64", arch: "amd64", family: "unix"

Following the instructions given [here](https://github.com/cloudera/hue). Error occurs after giving the `make apps` command.

I want to install from source on a single machine and point it to a hadoop cluster which is running centos 7 and HDP 2.4. Could not install hue directly on the cluster due to compatibility issues.

EDIT: I installed all the dependecy softwares and then ran `make apps`, i get: `ImportError: /usr/lib64/libxml2.so.2: version `LIBXML2_2.9.0' not found (required by /root/hue/build/env/lib/python2.6/site-packages/lxml-3.3.6-py2.6-linux-x86_64.egg/lxml/etree.so)
` Is there a way around?

**Comment by romainr** [comment]
Do you have this lib? libxml2-devel
