### ISSUE TITLE
[liboauth] several bugs in liboauth backend.py related to get_request_uri method

### ISSUE THREAD

**Issue by xq262144** [cloudera/hue#414]
A little bug related to ```get_redirect_uri``` due to commit 3dd029b1c81842dea786493755c1e9eb1783b1a0.
The patch commit is https://github.com/xq262144/hue/commit/51745aaa6b10ac20b141ff074c462918bf82b91a.

P.S.:
```HTTPRequest``` object in current Django version 1.6 does not support the attribute ```scheme```, so I produce the correct scheme with the same logic backported from Django 1.7.

**Comment by romainr** [comment]
Good one, could you send a pull request?
(I also put a comment about the utility of @classmethod)

**Comment by xq262144** [comment]
Thanks, I will do it in CST evening time. Lots of work to do right now. 😄

**Comment by romainr** [comment]
Awesome, will wait!

**Comment by xq262144** [comment]
Here is my new patch, https://github.com/xq262144/hue/commit/49ffb75cfec98e883bb3291e5035a237a1721f32
And the PR is https://github.com/cloudera/hue/pull/415
😄
