### ISSUE TITLE
hue 3.9 login error 

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#416]
Hi~

  Sometimes I login hue, it will run very slow and then it will display server error 500

  In error.log, it can see the error:
  
![hue_error](https://cloud.githubusercontent.com/assets/7900367/17924189/33f512bc-6a1a-11e6-8976-8f7515344b05.png)

In hue.ini, I set the value:

app_blacklist = impala,spark,search,indexer,sqoop,zookeeper,security,rdbms,jobsub,help

does anyone knows the reason?
thanks.

**Comment by romainr** [comment]
I believe you have some older spark documents, when you go on the /home page it is trying to list them and fail as the spark app is disabled.

One way to fix it without fiddling with the DB would be to re-enable spark, then go to the app and delete them.

Or upgrade, that was fixed since :)
