### ISSUE TITLE
[notebook] character problem in notebbok api.py related to get_logs method

### ISSUE THREAD

**Issue by cycyyy** [cloudera/hue#417]
When i got my hive query in utf-8, I get a exception "ascii codec can't enconde characters in position"
i find it due to this  [commit](https://github.com/cloudera/hue/commit/6c1224abfccb68208283d270bbc392243f74a71b#diff-a556d5d94c36b5531ab9e3887110976a)

**Comment by romainr** [comment]
What is a query example?

e.g.

SELECT 'carrière'

**Comment by cycyyy** [comment]
Like this:
SELET * FROM A WHERE B = `傻`

**Comment by cycyyy** [comment]
@romainr

**Comment by romainr** [comment]
Looks like https://code.djangoproject.com/ticket/13919

**Comment by romainr** [comment]
@spaztic1215 have a look?

BTW  _set_search_field seems unused

**Comment by cycyyy** [comment]
@romainr 
i think it related to this:
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/api.py#L291
when you try to decode a unicode to str , the default decoding format ascii will make mistake(UTF-8?);

**Comment by spaztic1215** [comment]
Yep, I have a review open that should resolve this one: https://review.cloudera.org/r/8469/

**Comment by romainr** [comment]
I see, and my original issue is actually https://issues.cloudera.org/browse/HUE-4889
