### ISSUE TITLE
Hue Installation failing on Anaconda2

### ISSUE THREAD

**Issue by vijayps** [cloudera/hue#418]
I have custom hue, which i installed locally on my mac and it is running fine.

When I am tried to install hue on QA server, where initially python is not available is failed. So i installed Anaconda2 and updated PATH variable. And then i am following same steps which i used which installing hue locally, but it is failing with error:

from hue folder: make apps
--- Creating virtual environment at /work/vijay/hueProject/hue/tools/virtual-bootstrap/virtual-bootstrap.py
--- Creating virtual environment at /work/vijay/hueProject/hue/build/env
python2.7 /work/vijay/hueProject/hue/tools/virtual-bootstrap/virtual-bootstrap.py \
		-qq --system-site-packages /work/vijay/hueProject/hue/build/env
/work/vijay/hueProject/hue/build/env/bin/python2.7: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable /work/vijay/hueProject/hue/build/env/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/work/vijay/hueProject/hue' (should be u'/work/vijay/hueProject/hue/build/env')
ERROR: virtualenv is not compatible with this system or executable
make: *** [/work/vijay/hueProject/hue/build/env/stamp] Error 100

******************************
System: SLES

python -V
Python 2.7.12 :: Anaconda 4.1.1 (64-bit)

java -version
java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)

mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09456c07578223da5; 2015-11-10T10:41:47-06:00)
Maven home: /work/apache-maven-3.3.9
Java version: 1.7.0_55, vendor: Oracle Corporation
Java home: /usr/java/jdk1.7.0_55/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.0.101-0.31-default", arch: "amd64", family: "unix"

**Comment by romainr** [comment]
Hue requires Python, and in case you are compiling it, it needs these dependencies: https://github.com/cloudera/hue#development-prerequisites

**Comment by spaztic1215** [comment]
I don't believe virtualenv is compatible with conda (or Anaconda) since Anaconda acts as its own virtual environment wrapper.

**Comment by vijayps** [comment]
thanks for comments..
i installed all dependencies and compiling code... now there are new error... i think it is looking for       " -lmysqlclient" attaching complete error below:

Error:
make apps
cd /work/vijay/hueProject/hue/maven && mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hue Maven Parent POM 3.9.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (default) @ hue-parent ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ hue-parent ---
[INFO] Installing /work/vijay/hueProject/hue/maven/pom.xml to /home/c10791a/.m2/repository/com/cloudera/hue/hue-parent/3.9.0-SNAPSHOT/hue-parent-3.9.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.747 s
[INFO] Finished at: 2016-09-08T14:24:51-05:00
[INFO] Final Memory: 9M/149M
[INFO] ------------------------------------------------------------------------
make[1]: Entering directory `/work/vijay/hueProject/hue/desktop'
make -C core env-install
make[2]: Entering directory `/work/vijay/hueProject/hue/desktop/core'
--- Building egg for MySQL-python-1.2.5
running bdist_egg
running egg_info
writing MySQL_python.egg-info/PKG-INFO
writing top-level names to MySQL_python.egg-info/top_level.txt
writing dependency_links to MySQL_python.egg-info/dependency_links.txt
reading manifest file 'MySQL_python.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'MySQL_python.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying MySQLdb/release.py -> build/lib.linux-x86_64-2.7/MySQLdb
running build_ext
building '_mysql' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Dversion_info=(1,2,5,'final',1) -D__version__=1.2.5 -I/usr/include/mysql -I/opt/cloudera/parcels/Anaconda-4.0.0/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fPIC -g -fabi-version=2 -fno-omit-frame-pointer -fno-strict-aliasing
In file included from _mysql.c:44:
/usr/include/mysql/my_config.h:443:1: warning: "HAVE_WCSCOLL" redefined
In file included from /opt/cloudera/parcels/Anaconda-4.0.0/include/python2.7/Python.h:8,
                 from _mysql.c:29:
/opt/cloudera/parcels/Anaconda-4.0.0/include/python2.7/pyconfig.h:920:1: warning: this is the location of the previous definition
gcc -pthread -shared -L/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib -Wl,-rpath=/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib,--no-as-needed build/temp.linux-x86_64-2.7/_mysql.o -L/usr/lib64 -L/tmp/tmpQcQ0Zo/Anaconda-4.0.0/lib -lmysqlclient -lpthread -lm -lrt -ldl -lpython2.7 -o build/lib.linux-x86_64-2.7/_mysql.so
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: cannot find -lmysqlclient
collect2: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
make[2]: *** [/work/vijay/hueProject/hue/desktop/core/build/MySQL-python-1.2.5/egg.stamp] Error 1
make[2]: Leaving directory `/work/vijay/hueProject/hue/desktop/core'
make[1]: *** [.recursive-env-install/core] Error 2
make[1]: Leaving directory `/work/vijay/hueProject/hue/desktop'
make: *** [desktop] Error 2

**Comment by romainr** [comment]
Yes, this is about mysql and the list of packages are here https://github.com/cloudera/hue#development-prerequisites

**Comment by TylerKapushinski** [comment]
I'm having this same problem on RHEL7.  Here are my dependencies:
```
> sudo yum install gcc libxml2-devel libxslt-devel cyrus-sasl-devel cyrus-sasl-gssapi mysql-devel python-devel python-setuptools python-simplejson sqlite-devel ant

Package gcc-4.8.5-36.el7.x86_64 already installed and latest version
Package libxml2-devel-2.9.1-6.el7_2.3.x86_64 already installed and latest version
Package libxslt-devel-1.1.28-5.el7.x86_64 already installed and latest version
Package cyrus-sasl-devel-2.1.26-23.el7.x86_64 already installed and latest version
Package cyrus-sasl-gssapi-2.1.26-23.el7.x86_64 already installed and latest version
Package mysql-community-devel-5.6.46-2.el7.x86_64 already installed and latest version
Package matching python-devel-2.7.5-76.el7.x86_64 already installed. Checking for update.
Package python-setuptools-0.9.8-7.el7.noarch already installed and latest version
Package sqlite-devel-3.7.17-8.el7.x86_64 already installed and latest version
Package ant-1.9.4-2.el7.noarch already installed and latest version
Nothing to do

```

But when I try to install:

```
>PREFIX=/tech/appl/app make install

...

--- Creating new virtual environment
make -C /tech/appl/app/hue virtual-env
make[1]: Entering directory `/tech/appl/app/hue'
--- Creating virtual environment at /tech/appl/app/hue/build/env
python2.7 /tech/appl/app/hue/tools/virtual-bootstrap/virtual-bootstrap.py \
        -qq --system-site-packages /tech/appl/app/hue/build/env
ERROR: The executable /tech/appl/app/hue/build/env/bin/python2.7 is not functioning
ERROR: It thinks sys.prefix is u'/usr' (should be u'/tech/appl/app/hue/build/env')
ERROR: virtualenv is not compatible with this system or executable
make[1]: *** [/tech/appl/app/hue/build/env/stamp] Error 100
make[1]: Leaving directory `/tech/appl/app/hue'
make: *** [install-env] Error 2
```

Any suggestions?
