### ISSUE TITLE
Getting argument of type 'NoneType' is not iterable error with aggregate functions

### ISSUE THREAD

**Issue by alwinaugustin** [cloudera/hue#419]
I have imported a table from MySQL which has 10 million rows to Hive and now performing some operations in Impala to check the functionality and performance. Now I am getting an error ` argument of type 'NoneType' is not iterable` when I issue the following query. 

    select count(id) from my_table_name;

Is there anything I need to do after importing the data to fix this ? I am intended to use Impala mainly for analytics purpose and so it involves lot of SUM and COUNT functions.

**Comment by romainr** [comment]
This look similar to https://issues.cloudera.org/browse/HUE-4019

Did you give a try with Hue 3.11 or master?

**Comment by romainr** [comment]
This look similar to https://issues.cloudera.org/browse/HUE-4019

Did you give a try with Hue 3.11 or master?

**Comment by romainr** [comment]
This look similar to https://issues.cloudera.org/browse/HUE-4019

Did you give a try with Hue 3.11 or master?
