### ISSUE TITLE
[notebook] notebook hiveserver2 connector dbms type typo

### ISSUE THREAD

**Issue by xq262144** [cloudera/hue#421]
In file https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py#L609 .
Type should be `sparksql` instead of `spark-sql` to get sparksql type interpreters work for notebook.
Because `sparksql` type is hard-coded in https://github.com/cloudera/hue/blob/master/apps/beeswax/src/beeswax/server/dbms.py#L95 .

**Comment by xq262144** [comment]
@romainr

**Comment by romainr** [comment]
Good point! Would you like to send a pull request?

**Comment by romainr** [comment]
https://issues.cloudera.org/browse/HUE-4869
