### ISSUE TITLE
Move Release tar file to github

### ISSUE THREAD

**Issue by acnithin** [cloudera/hue#425]
Hello,

The Release tarball available on dropbox location will not be accessible from behind the company firewall( 
https://dl.dropboxusercontent.com/u/730827/hue/releases/3.8.1/hue-3.8.1.tgz.

Will it be possible to move that to github itself.

**Comment by romainr** [comment]
We host the latest Hue alternatively here: http://gethue.com/downloads/hue-3.11.0.tgz
