### ISSUE TITLE
Getting a blank output from Hue notebook

### ISSUE THREAD

**Issue by papant7** [cloudera/hue#426]
When running scala from Hue notebooks, I sometimes don't get output.

<img width="949" alt="screen shot 2016-09-16 at 2 36 20 pm" src="https://cloud.githubusercontent.com/assets/5388630/18577271/fc26f284-7c1a-11e6-9b6c-67042cb2c298.png">

**Comment by romainr** [comment]
What do you see in the Chrome network tab about the Ajax calls?

**Comment by papant7** [comment]
I am using Livy 0.2, spark 1.5.2 and Hue 3.10:

**Without** an output:
{"status": 1, "message": ""}

**With** output:
{"status": 0, "result": {"images": [], "type": "text", "meta": [{"comment": "", "type": "STRING_TYPE", "name": "Header"}], "data": [["res2: org.apache.spark.SparkContext = org.apache.spark.SparkContext@2bb6cadd"]]}}

Additional observation, the issue happens when there should be an error message response. Here are the output from **pyspark** of the exact command in scala:

**Without** an output:
{"status": 1, "message": "Traceback (most recent call last):\nNameError: name 'sqlContext' is not defined\n"}

**With** output:
{"status": 0, "result": {"images": [], "type": "text", "meta": [{"comment": "", "type": "STRING_TYPE", "name": "Header"}], "data": [["<pyspark.context.SparkContext object at 0x7f2f6a787650>"]]}}
