### ISSUE TITLE
The same problem is again actual: HUE-Oozie possibly corrupting deployment JAR in Java action #151

### ISSUE THREAD

**Issue by ilya-bystrov** [cloudera/hue#427]
version: 3.9.0+cdh5.7.1
Also, if I try to upload 78Mb file it wiil be truncated to 64Mb.

**Comment by romainr** [comment]
Are you using a shared workflow?

About the upload truncation, does it happen fore regular files from the File Browser?

**Comment by ilya-bystrov** [comment]
No, workflow isn't shared between multiple users.

Yes, if, for a example, I upload my Params4HiveScript.jar (78Mb), I'll get 64Mb file Params4HiveScript.jar.tmp.

**Comment by romainr** [comment]
Does uploading a file from File Browser have the same truncation?
Or is the 64MB happening when you submit the workflow? (I remember having these issues at some point)

**Comment by ilya-bystrov** [comment]
yes, it's also happens if I upload file from File Browser

**Comment by Hronom** [comment]
same
