### ISSUE TITLE
sqoop version support

### ISSUE THREAD

**Issue by cycyyy** [cloudera/hue#429]
When i use sqoop in version 1.99.7, i found that the restful api "/v1/connectors" has not been supported. But hue is using it to get connectors so that i got "get connectors error".
Can hue add support to sqoop's new version?

**Comment by cycyyy** [comment]
@romainr

**Comment by cycyyy** [comment]
i found the docs[https://sqoop.apache.org/docs/1.99.7/dev/RESTAPI.html#v1-connectors-get-get-all-connectors]

**Comment by romainr** [comment]
As soon as Sqoop2 becomes GA, Hue will support it fully
