### ISSUE TITLE
sentry with hive in hue

### ISSUE THREAD

**Issue by simran66** [cloudera/hue#430]
I have configured sentry for hive on my cluster but on trying to execute hive queries, I get 

`permissions could be missing on hive server.`

which makes sense as well and indicated that sentry is enabled. Now, 

sentry.service.admin.groups: hive, impala, hue

I log into hue using  hue user assigned to the default group. 

I see this as a note:

To be able to edit roles and privileges in Hue, the logged-in Hue user needs to belong to a group in Hue that is also an admin group in Sentry (whatever UserGroupMapping Sentry is using, the corresponding groups must exist in Hue or need to be entered manually). For example, our ‘hive’ user belongs to a ‘hive’ group in Hue and also to a ‘hive’ group in Sentry:

What exactly did I miss? Am I not expected to login into hue using hue user which belongs to default group? Please suggested. I need to be able to create role, permissions in hue for sentry. Please help. What exactly one is being asked to do through this note? 

whatever UserGroupMapping Sentry is using? Not sure

**Comment by romainr** [comment]
You should not use the 'default' as it does not exist on Unix, e.g. 'hive' (will be a Sentry super user) or any other real group

**Comment by simran66** [comment]
@romainr : Thanks. I tried logging in using hive for username and hive for password in hue. That didn't work. Where exactly do I get credentials for hive user from? Or do you want me to create a user in hue with username hive and assigned to group hive?
