### ISSUE TITLE
No databases found in hive after integration with sentry

### ISSUE THREAD

**Issue by simran66** [cloudera/hue#432]
Which user by default should be able to access databases after I have enabled sentry for hue? I have been using hue user which is the default one and after adding default group to sentry.admin.groups, I could create roles. I also created a group hive under which I created a hive user.  BUt none of the users can access any of the databases defined in hive

**Comment by romainr** [comment]
Please use http://groups.google.com/a/cloudera.org/group/hue-user for usage questions and no real issues

**Comment by simran66** [comment]
Here:
https://groups.google.com/a/cloudera.org/forum/#!topic/hue-user/rMpoke9duC8

Thanks
