### ISSUE TITLE
[3.9] oozie coordinator concurrency and throttle value can not save

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#433]
Hi~

  I discovery that if you create a coordinator job and do not change the settings Concurrency and Throttle value. Let them to be `default` value. Then save it and submit the job.

  Next, you modify the same coordinator settings Concurrency and Throttle value to be other value (like 1 ,2 , 3, ... ). Save it and submit the job.

  You will find the Concurrency and Throttle value is still in `default` value.  the save will be failed. 

  is it a bug? 

 Only the first time is default value is wrong.  

  If the first time you sent the job, you modify the Concurrency and Throttle value to be real integer. Next time the two value can be modified again. It is normal.

  thanks.

**Comment by gihad** [comment]
I have the same issue on Hue 3.10.0-amzn-0
Note that I'm running EMR's Hue.

**Comment by sai-krish** [comment]
This was fixed recently - https://issues.cloudera.org/browse/HUE-4738
and is targeted for 3.12
