### ISSUE TITLE
Cannot use hive query editor after I enabled sentry 

### ISSUE THREAD

**Issue by simran66** [cloudera/hue#435]
I have followed steps https://www.cloudera.com/documentation/enterprise/5-4-x/topics/sg_sentry_service_config.html to enable sentry service with hive.

My admin user for hue I believe is the default one 'hue' which belongs to default group. I was able to create roles and permissions in hue for sentry tables. But, all I can see there is 'server1'. No databases no tables when I am trying to created roles and permissions to sentry tables. Only server1 is what I get there. 

Now I go back to hive query editor. I cannot see any databases or tables. I though trying to execute 

grant all on server server1 to role hive;

would help. But  no matter what I try, Hive query editor always throws an error

No databases are available. Permissions could be missing.

I was trying it all with hue user. So, after reading a bit , I created a group hive in hue and then a user hive which I assigned to hive group and made it a super user in 'manage users and groups'.

I expected this to be able to access the databases at least but it does not see any databases either. How do I grant permission to the first user if none of the users can can see databases unless a user is assigned permission to do it?

If I login from beeline:

I always get with any commands I try:
Error: Error while compiling statement: FAILED: InvalidConfigurationException hive.server2.authentication can't be none in non-testing mode (state=42000,code=40000)

and testing mode isn't recommended for production I believe. I haven't altered authentication in anyway.Is it KERBEROS by default? Do I need to change it?

A snapshot:

 
![hive editor](https://cloud.githubusercontent.com/assets/4191009/18979230/aa00eb1e-86e6-11e6-8817-636c22689cae.png)

Edit 1:

For some reason I don't even know of, When I now assign role and privileges, I can now see the list of  tables of the database I have access to on the side bar in hue but every query I try to execute in the editor still gives the same error

Snapshot:

![selection_002](https://cloud.githubusercontent.com/assets/4191009/18992366/88a51120-873b-11e6-9968-f91931ccc73e.png)

**Comment by simran66** [comment]
Could I get pointers on this please? I have tried using hive group that is a system group only. Is this  a bug?Same question was posted here by someone :https://community.cloudera.com/t5/Security-Apache-Sentry/Hue-Sentry-tables-Tables-dissapear-when-enable-sentry-in-Hive/td-p/40755 . If I try his posted solution, I keep getting hive.server.authentication none is not allowed in non testing mode and I do not wish to turn testing mode on

**Comment by simran66** [comment]
This is how I solved it: [solution](http://www.yourtechchick.com/hadoop/no-databases-available-permissions-missing-error-hive-sentry/)

**Comment by romainr** [comment]
Thanks for the detailed post!
