### ISSUE TITLE
Cassandra SQL support

### ISSUE THREAD

**Issue by justchrisagain** [cloudera/hue#438]
Hi,
I can see HUE supports HBase out of the box, is it feasible to also support Cassandra?
If not, how can we connect to it? Are we suppose to configure Hive to access it or Sqoop? Or we just use the Spark libraries to read data from Cassandra?

Thanks,
CL.-

**Comment by justchrisagain** [comment]
I am also looking at configuring Impala, but with no success. Is this request completely out of context? 
I could start coding this if people find it would be useful, but I would need some guidance in the project. The idea would be to connect to Cassandra through cql3 and not the old thrift server. I can see other projects flying with blue notebooks that support this connection already.

**Comment by romainr** [comment]
How about using the Python Driver:
https://github.com/datastax/python-driver
https://wiki.apache.org/cassandra/API

and create a connector similar to the Solr one:
https://github.com/cloudera/hue/tree/master/desktop/libs/notebook/src/notebook/connectors

Then you will be able to query like with Solr SQL:
http://gethue.com/sql-editor-for-solr-sql/

**Comment by JAC2703** [comment]
Hi, did anyone make any progress with this?

**Comment by romainr** [comment]
If you have a JDBC url, it should work

**Comment by RahulPankaj** [comment]
@romainr  i built hue from source. I want cassendra connectivity to hue.
Can i do this. If yes then what should be steps.
If i need to write program then in which language it would be best and what will be the steps..

**Comment by romainr** [comment]
https://docs.gethue.com/latest/developer/editor/
https://docs.gethue.com/latest/administrator/configuration/editor/

**Comment by romainr** [comment]
https://github.com/datastax/python-driver

**Comment by arita37** [comment]
Does this driver works in HUE now ?

**Comment by romainr** [comment]
AFAIK this is not a SqlAlchemy connector so currently a 'Custom' connector would need to be used/created: https://docs.gethue.com/developer/connectors/

**Comment by arita37** [comment]
Any advice on how to create it ?
Sorry, am not familiar with HUE setup....

**Comment by romainr** [comment]
If there is no SqlAlchemy connector for Cassandra, above connector could be used for creating a specific interface that can be used by the Notebook API of Hue. Basically implementing the base API https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/base.py

https://docs.gethue.com/developer/connectors/#custom

**Comment by arita37** [comment]
Cassandra is NO-SQL, having own sql dialect...
So sql achemy not available.

**Comment by romainr** [comment]
It does have SQL https://cassandra.apache.org/doc/latest/cql/dml.html#select
Many No-SQL Databases actually have SQL, e.g. Apache HBase / Phoenix https://phoenix.apache.org/
