### ISSUE TITLE
Hue Hive interface isn't optimized for mobile 

### ISSUE THREAD

**Issue by simran66** [cloudera/hue#439]
The Hue interface isn't adaptive on mobile I believe. I tried to access it on mobile but it looks something like this:
![huesnapshot](https://cloud.githubusercontent.com/assets/4191009/19464669/d1fcfdcc-951b-11e6-97d1-3c658789c4c3.png)

**Comment by romainr** [comment]
This is one of the potential goal of Hue 4 next year, so stay tuned ;)
