### ISSUE TITLE
'CLASSPATH' message when using JDBC

### ISSUE THREAD

**Issue by mikehomee** [cloudera/hue#440]
Hi!

Would like to ask for a help.
Would like to use the JDBC query feature on HUE, but am having issue. 
Please see details below. Thanks!

![selection_239](https://cloud.githubusercontent.com/assets/5212611/19587410/c196ba50-9790-11e6-9463-d23b85c69b53.png)

  File "/home/hue/hue/build/env/lib/python2.7/UserDict.py", line 23, in **getitem**
    raise KeyError(key)
KeyError: 'CLASSPATH'

**Comment by romainr** [comment]
It means you did not export CLASSPATH=....

http://gethue.com/custom-sql-query-editors/

**Comment by mikehomee** [comment]
Hi @romainr 

I actually export the CLASSPATH via /etc/profile 

export CLASSPATH=/usr/local/phoenix-hbase/phoenix-4.4.0-HBase-1.1-client.jar:$CLASSPATH

:(

**Comment by romainr** [comment]
It is not showing up for the Hue user.
How do you start Hue?

**Comment by mikehomee** [comment]
As hue user

$hue: service hue start

see image below
![selection_240](https://cloud.githubusercontent.com/assets/5212611/19710792/92091b80-9b63-11e6-9798-d7392f57122d.png)

**Comment by romainr** [comment]
If you use CM, you could add the env variable in the "Hue Service Environment Advanced Configuration Snippet (Safety Valve)"?
