### ISSUE TITLE
Allow users to dynamically choose which tez.queue.name to submit to from Hue

### ISSUE THREAD

**Issue by leontp587** [cloudera/hue#444]
When using beeline, users may select a tez queuename to submit Hive queries to.
beeline !connect jdbc:hive2://your.host:your.port/data_base?tez.queue.name=<queue-name>

Hue's Hive editor and Oozie workflow should allow this also. Suggest allowing users to set tez.queue.name in the Hive Settings box. Running the Hive query then runs the query in the specific queue.

**Comment by romainr** [comment]
This will allow to put any setting in the Session: https://github.com/cloudera/hue/commit/d49eda039902e4db8952dfef370849e61b5fde87

And users can already put any settings at the query level by clicking on the little Cog icon on the top right of the snippet or do a 'SET tez.queue.name=<queue-name>;

There is a plan to make the queue selection even more obvious in Hue 4.

**Comment by romainr** [comment]
You ended up going with the HiveServer2 hook?
