### ISSUE TITLE
hue.ini world-readable

### ISSUE THREAD

**Issue by maaaaz** [cloudera/hue#446]
Hello hue team,

I would like to report a security vulnerability.
The `hue.ini` configuration file, where service credentials are stored, is by default (from the tarball release) **accessible to anyone** with the `other` permission set to `read`:
```
$ tar tvf hue-cdh5.8.3-release.tar.gz | grep hue\.ini
-rw-rw-r-- root/root     50852 2016-10-12 19:44 hue-cdh5.8.3-release/desktop/conf.dist/hue.ini
```
That finding can be seen on the Cloudera QuickstartVM:
```
[cloudera@quickstart ~]$ ls -al /etc/hue/conf/hue.ini 
-rw-rw-r-- 1 root root 22813 Nov 18  2015 /etc/hue/conf/hue.ini
```
I know that you put some guidelines for password management [here](http://gethue.com/storing-passwords-in-script-rather-than-hue-ini-files/) but relying on the user to restrict permissions post-installation is not a **good** security measure.
Hence I recommend that you **restrict permissions for that file to only the `hue` user (600) or the hue group in the release tarball**: with that measure, lowering the security is the user's responsibility.

If possible, it would be cool to have a CVE number to track that vulnerability.

Cheers.

**Comment by romainr** [comment]
/etc/hue/conf is done at the CDH level not Hue. 

We can however have a look at the makefile to chmod the hue.ini when doing 'make prod'.

**Comment by maaaaz** [comment]
> /etc/hue/conf is done at the CDH level not Hue.  

I haven't looked at the installation script of CDH but I doubt that it does more than a `tar xvf`

> We can however have a look at the makefile to chmod the hue.ini when doing 'make prod'.

Yes that would be one possible solution.


Cheers

**Comment by maaaaz** [comment]
It is fixed ?
