### ISSUE TITLE
Hue 3.11.0 Metastore Tables create a new table from a file

### ISSUE THREAD

**Issue by iceshadowxin** [cloudera/hue#449]
Hi,
![image](https://cloud.githubusercontent.com/assets/23698782/20560586/11a79c1a-b1b5-11e6-8ca0-62487235e89f.png)
As is shown in the picture，when I use "Create a new table from a file" I think “Input File or Location” is based on the "Load data" to use.Can we change the order of the two input fields?

**Comment by romainr** [comment]
We should make the labels clearer and indeed see for the fields order:
https://issues.cloudera.org/browse/HUE-7

**Comment by romainr** [comment]
Fixed
