### ISSUE TITLE
Hue 3.11.0  Metastore Manager refresh button

### ISSUE THREAD

**Issue by iceshadowxin** [cloudera/hue#450]
Hi,
![image](https://cloud.githubusercontent.com/assets/23698782/20561523/f2bc1cc2-b1b9-11e6-847d-ba7b23917c0a.png)
No matter where I click the refresh button, the button will be triggered.
Can we separate the two functions?

**Comment by romainr** [comment]
Are you talking about the refresh metadata option for Impala? What is the other function you are referring too?
