### ISSUE TITLE
3.11 Job browser displays only the first 1000 jobs from resource manager start

### ISSUE THREAD

**Issue by bigthinka** [cloudera/hue#451]
When the resource manager has been running for sometime and has run more than 1000 (50 * 20) jobs  the newer jobs are no longer displayed. This is because the resource manager api does not return the latest 1000 jobs when limit is set to 1000.But only returns first 1000 jobs.

I have hacked a quick solution that sets startedTimeBegin to timestamp 24 hours ago as API query param in /hue/apps/jobbrowser/src/jobbrowser/api.py about line 196. This of course is not such a great solution but works for now. 

This is with resource manager on hadoop version Hadoop 2.7.2-amzn-3 but I have seen same issue applies in cloudera

http://community.cloudera.com/t5/Web-UI-Hue-Beeswax/Hue-Job-Browser-is-not-working/m-p/46644

The worse alternative is to restart the resource manager and so clear the jobs list.

**Comment by romainr** [comment]
Yes, this is a real issue pagination is planned in https://issues.cloudera.org/browse/HUE-1176 and we should look at the sorting capabilities of YARN Resource Manager (will follow-up).

**Comment by romainr** [comment]
Fixed
