### ISSUE TITLE
[Question]Can I install hue 3.11 with CDH 5.7

### ISSUE THREAD

**Issue by WalterInSH** [cloudera/hue#452]
Hi 
I have hue 3.8 installed with CDH 5.7. I'd like to upgrade it to 3.11 so that I can use sql auto complete feature (It's awesome!)

I'm not sure if it's safe to upgrade hue to 3.11 without upgrading CDH to a higher version.

Thanks.

**Comment by romainr** [comment]
So, we don't recommend this as it should work in practice but we don't test it (so you are on your own :)

The new editor is in CDH from 5.8 and 5.9 was released last month.

**Comment by WalterInSH** [comment]
@romainr Thanks.
