### ISSUE TITLE
Hue:Awesome icon can not be displayed when the reload page in the IE browser

### ISSUE THREAD

**Issue by felix200** [cloudera/hue#456]

**Comment by romainr** [comment]
Does it happening on any page of Hue? On any Hue version?

@enricoberti

**Comment by romainr** [comment]
https://issues.cloudera.org/browse/HUE-5432

**Comment by felix200** [comment]
The Hue version is 3.11.0.
The problem is the same as  this issue.
https://issues.cloudera.org/browse/HUE-5432
thank U
