### ISSUE TITLE
can't copy 'pytz/zoneinfo/CST6CDT': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by andyZheng** [cloudera/hue#459]
error: can't copy 'pytz/zoneinfo/CST6CDT': doesn't exist or not a regular file
make[2]: *** [/home/andy/hue/desktop/core/build/pytz-2015.2/egg.stamp] Error 1
make[2]: Leaving directory `/home/andy/hue/desktop/core'
make[1]: *** [.recursive-env-install/core] Error 2
make[1]: Leaving directory `/home/andy/hue/desktop'
make: *** [desktop] Error 2

**Comment by enricoberti** [comment]
In which environment are you trying to make Hue? is it a clean git clone? otherwise try a make clean before

**Comment by andyZheng** [comment]
Yes,it is a make apps and to try a make clean before.

**Comment by andyZheng** [comment]
total 58992
drwxr-xr-x. 10 root root     4096 Dec  9 13:56 hue
-rw-r--r--.  1 root root 59827165 Dec  8 18:31 hue-master.zip
-rw-r--r--.  1 root root   573018 Dec  9 10:46 python-dev-2.7.11-alt3.x86_64.rpm
[root@node6 andy]# cd hue
[root@node6 hue]# make apps
cd /home/andy/hue/maven && mvn install 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Hue Maven Parent POM 3.11.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (default) @ hue-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ hue-parent ---
[INFO] Installing /home/andy/hue/maven/pom.xml to /root/.m2/repository/com/cloudera/hue/hue-parent/3.11.0-SNAPSHOT/hue-parent-3.11.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.486s
[INFO] Finished at: Fri Dec 09 22:06:10 CST 2016
[INFO] Final Memory: 7M/299M
[INFO] ------------------------------------------------------------------------
make[1]: Entering directory `/home/andy/hue/desktop'
make -C core env-install
make[2]: Entering directory `/home/andy/hue/desktop/core'
--- Building egg for pytz-2015.2
running bdist_egg
running egg_info
writing pytz.egg-info/PKG-INFO
writing top-level names to pytz.egg-info/top_level.txt
writing dependency_links to pytz.egg-info/dependency_links.txt
reading manifest file 'pytz.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pytz.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
error: can't copy 'pytz/zoneinfo/CST6CDT': doesn't exist or not a regular file
make[2]: *** [/home/andy/hue/desktop/core/build/pytz-2015.2/egg.stamp] Error 1
make[2]: Leaving directory `/home/andy/hue/desktop/core'
make[1]: *** [.recursive-env-install/core] Error 2
make[1]: Leaving directory `/home/andy/hue/desktop'
make: *** [desktop] Error 2

**Comment by romainr** [comment]
Is the hue a 'git clone https://github.com/cloudera/hue.git'?
Which OS are you using?
