### ISSUE TITLE
Hue launches job with wrong username and default queue in YARN

### ISSUE THREAD

**Issue by maziyarpanahi** [cloudera/hue#460]
Hello,

I am using the latest Hue 3.11 from CDH 5.9.0. I enabled Spark Notebook with Livy.
Everything works as expected but when I login with different username in Hue and run my spark scripts, I always see my applications in YARN with the same username "hdfs" and queue root.default. (I run livy as HDFS user so it can have needed permissions)

I saw in a tutorial that the user in YARN should change based on the logged in user not the user who is running Livy. Am I missing something in my configurations?

Best,
Maziyar

**Comment by romainr** [comment]
In the hue.ini, in the [spark] section the Livy impersonation should be turned on if you want the real user names to be used during submission. We also now recommend to use the livy from http://livy.io/ which just reuses Spark defaults for the queues and has impersonation with YARN on by default.

**Comment by maziyarpanahi** [comment]
Hi @romainr 

I did download the Livy from livy.io and in my hue_safety_valve.ini I have set livy_impersonation_enabled=true already. But still the YARN sees the user that runs the Livy from command line.
