### ISSUE TITLE
default page needs to be changed to notebooks instead home page in Hue

### ISSUE THREAD

**Issue by smart987** [cloudera/hue#463]
In hue I want the following notebooks page to be appeared by default instead home page when the user logs in. How can I make this page (http://localhost:8888/notebook/notebooks) to load instead home page?
![screen shot 2016-12-15 at 3 16 04 pm](https://cloud.githubusercontent.com/assets/11309381/21225179/bdb4fa42-c2f5-11e6-8de2-4817101328b2.png)

**Comment by enricoberti** [comment]
Hi!
You can change https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/views.py#L343
into
`return redirect(reverse('notebook:notebooks'))`
