### ISSUE TITLE
[HUE3.1.1] ( Create a new table manually ) may cause 500 error

### ISSUE THREAD

**Issue by daemonman** [cloudera/hue#468]
Hi,hue team.
     ( Create a new table manually ) may cause 500 error。
     create_table() in create_table.py(line 92:'has_tables': len(dbms.get(request.user).get_tables()) > 0)
     it sames that has_tables not use in create_table_manually.mako.  
     but  get_tables() will get all tables.
     if in one database,a user have not  permission to one table will case 500 error.

**Comment by romainr** [comment]
We can see if it is still the case in a new version of the create table wizard in 3.12: https://issues.cloudera.org/browse/HUE-7
