### ISSUE TITLE
Hue Notebook does not load.. Timeout issue

### ISSUE THREAD

**Issue by Nishantgoyal** [cloudera/hue#472]
Hi, 
In Apache hue version shipped with cloudera 5.7, there seems to be a bug.
Well, on first load of the notbook in apache hue web ui, the page freezes.. 
On inspecting the UI, it turns out, that there is a timeout that happens while loading a few javascript files. The 'react.js' library used has a timeout of '7' sec for a javascript to load. And as soon as this limit is reached, the ui hungs up.

**Comment by romainr** [comment]
Do you have the same on the latest Hue? http://demo.gethue.com/notebook
