### ISSUE TITLE
issues during build

### ISSUE THREAD

**Issue by sudhishiyer** [cloudera/hue#473]
I am having issues during the build and I get the following issues. These servers cannot access the python public sites

==========
$ make apps

maven build completes...
......
creating 'dist/configobj-4.6.0-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
--- Building egg for cryptography-1.3.1
Download error on https://pypi.python.org/simple/cffi/: [Errno 97] Address family not supported by protocol -- Some packages may not be found!
Couldn't find index page for 'cffi' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [Errno 97] Address family not supported by protocol -- Some packages may not be found!
No local packages or download links found for cffi>=1.4.1
=========
Is there a way to avoid reaching out to public python site to install these packages? some of these packages are already under  "desktop/core/ext-py" directories. Any thoughts?

**Comment by romainr** [comment]
This is weird as it works for me now. Could you give a retry?

On which OS?

**Comment by sudhishiyer** [comment]
Centos 6.7

The issue is here, we do not have access to public repo for python.
Everything has to be installed from local. I did a workaround by manually
installing all the packages.

run make install (fails trying to download python pkgs), then manually
download these packages and install using "python setup.py install". Run
through these process until 'make apps' complete w/o error

Sudhish

**Comment by romainr** [comment]
Yes, this is one way to do!

**Comment by AndreyEmelyanenko** [comment]
Hi! I'm facing this problem right now. Have you found any more nice way to solve this? Because all these packages are already inside "desktop/core/ext-py", how you've correctly mentioned.

**Comment by AndreyEmelyanenko** [comment]
> Yes, this is one way to do!

Hi, Romain Rigaux! Could you suggest please any other way to solve this problem? Hue falls with the same error while being built in a no-internet environment. Need your help very much..
