### ISSUE TITLE
build issue on SLES 11

### ISSUE THREAD

**Issue by sametkaradag** [cloudera/hue#474]
Hello,
When I try to build Hue on SLES 11.
I get the following error:
ip-172-31-13-196:/home/ec2-user/hue-3.9.0 # make install
--- Installing core source structure...
--- Installing Desktop core...
INSTALL_DIR=/usr/local/hue make -C desktop install
make[1]: Entering directory `/home/ec2-user/hue-3.9.0/desktop'
INSTALL_DIR=/usr/local/hue/desktop/core \
                INSTALL_CONF_DIR=/usr/local/hue/desktop/conf \
                make -C core install-bdist
make[2]: Entering directory `/home/ec2-user/hue-3.9.0/desktop/core'
--- Building egg for kerberos-1.1.1
running bdist_egg
running egg_info
/home/ec2-user/hue-3.9.0/build/env/lib/python2.6/site-packages/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  writer = ep.load(installer=installer)
writing kerberos.egg-info/PKG-INFO
writing top-level names to kerberos.egg-info/top_level.txt
writing dependency_links to kerberos.egg-info/dependency_links.txt
reading manifest file 'kerberos.egg-info/SOURCES.txt'
writing manifest file 'kerberos.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'kerberos' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fwrapv -fPIC -I/usr/include/python2.6 -c src/kerberos.c -o build/temp.linux-x86_64-2.6/src/kerberos.o sh: krb5-config: command not found
gcc: sh:: No such file or directory
gcc: krb5-config:: No such file or directory
gcc: command: No such file or directory
gcc: not: No such file or directory
gcc: found: No such file or directory
error: command 'gcc' failed with exit status 1
make[2]: *** [/home/ec2-user/hue-3.9.0/desktop/core/build/kerberos-1.1.1/egg.stamp] Error 1
make[2]: Leaving directory `/home/ec2-user/hue-3.9.0/desktop/core'
make[1]: *** [.recursive-install-bdist/core] Error 2
make[1]: Leaving directory `/home/ec2-user/hue-3.9.0/desktop'
make: *** [install-desktop] Error 2

**Comment by romainr** [comment]
You seems to be missing packages: https://github.com/cloudera/hue#development-prerequisites

**Comment by sametkaradag** [comment]
I saw this document but it does not provide the required packages for SLES. I tried packages for RHEL but some packages are not available for suse:

ip-172-31-13-196:/home/ec2-user/hue-3.9.0 # zypper install ant asciidoc cyrus-sasl-devel cyrus-sasl-gssapi cyrus-sasl-plain gcc gcc-c++ krb5-devel libffi-devel libxml2-devel libxslt-devel make mvn  mysql mysql-devel openldap-devel python-devel sqlite-devel openssl-devel gmp-devel
Refreshing service 'cloud_update'.
Loading repository data...
Reading installed packages...
'make' is already installed.
No update candidate for 'make-3.81-128.20.x86_64'. The highest available version is already installed.
'cyrus-sasl-gssapi' is already installed.
No update candidate for 'cyrus-sasl-gssapi-2.1.22-182.23.1.x86_64'. The highest available version is already installed.
'cyrus-sasl-plain' is already installed.
No update candidate for 'cyrus-sasl-plain-2.1.22-182.23.1.x86_64'. The highest available version is already installed.
'libxml2-devel' is already installed.
No update candidate for 'libxml2-devel-2.7.6-0.64.1.x86_64'. The highest available version is already installed.
'ant' is already installed.
No update candidate for 'ant-1.7.1-20.11.1.noarch'. The highest available version is already installed.
'gcc' is already installed.
No update candidate for 'gcc-4.3-62.200.2.x86_64'. The highest available version is already installed.
'openssl-devel' not found in package names. Trying capabilities.
'libopenssl-devel' providing 'openssl-devel' is already installed.
'libxslt-devel' is already installed.
No update candidate for 'libxslt-devel-1.1.24-19.23.1.x86_64'. The highest available version is already installed.
'gmp-devel' is already installed.
No update candidate for 'gmp-devel-4.2.3-10.99.x86_64'. The highest available version is already installed.
'cyrus-sasl-devel' is already installed.
No update candidate for 'cyrus-sasl-devel-2.1.22-182.23.1.x86_64'. The highest available version is already installed.
'krb5-devel' is already installed.
No update candidate for 'krb5-devel-1.6.3-133.49.112.1.x86_64'. The highest available version is already installed.
'python-devel' is already installed.
No update candidate for 'python-devel-2.6.9-39.1.x86_64'. The highest available version is already installed.
'gcc-c++' is already installed.
No update candidate for 'gcc-c++-4.3-62.200.2.x86_64'. The highest available version is already installed.
'mysql' is already installed.
No update candidate for 'mysql-5.5.53-0.30.1.x86_64'. The highest available version is already installed.
'asciidoc' is already installed.
No update candidate for 'asciidoc-8.6.8-29.24.29.noarch'. The highest available version is already installed.
'libffi-devel' is already installed.
No update candidate for 'libffi-devel-4.3-62.200.2.x86_64'. The highest available version is already installed.
'sqlite-devel' not found in package names. Trying capabilities.
'sqlite3-devel' providing 'sqlite-devel' is already installed.
'mysql-devel' not found in package names. Trying capabilities.
'libmysqlclient-devel' providing 'mysql-devel' is already installed.
'openldap-devel' not found in package names. Trying capabilities.
No provider of 'openldap-devel' found.
'mvn' not found in package names. Trying capabilities.
No provider of 'mvn' found.
Resolving package dependencies...

Nothing to do.

**Comment by romainr** [comment]
If you don't have a package for maven, you need to install it via tarball or apache-maven (it is noted in above link)

**Comment by sametkaradag** [comment]
the issue was something else for building lerberos extension.
I solved that issue by updating path variable with the location of krb5-config file, like this:
 rpm -ql krb5-devel | grep krb5-config
/usr/lib/mit/bin/krb5-config

 export PATH=$PATH:/usr/lib/mit/bin

Thanks romainr for your interest
