### ISSUE TITLE
'NoneType' object has no attribute 'update_data'

### ISSUE THREAD

**Issue by dearloki** [cloudera/hue#476]
When I type in Chinese as query conditions, application error 
'NoneType' object has no attribute 'update_data'.
hive editor and impala editor  has the same problem

**Comment by romainr** [comment]
Sounds like something that was fixed some time ago. On which Hue version are you?
Does something like 
select  '漢字'
works?

Does it work on demo.gethue.com/notebook/editor?type=hive ?

**Comment by dearloki** [comment]
It's work.
I used cdh5.9.0
Maybe old version;
