### ISSUE TITLE
Hue 3.11.0 doesn't seem to support newly added AWS regions for example us-east-2/eu-west-2/ca-central-1

### ISSUE THREAD

**Issue by Mageshw** [cloudera/hue#479]
Hue 3.11.0 doesn't seem to support newly added AWS regions for example us-east-2/eu-west-2/ca-central-1

_"""
Potential misconfiguration detected. Fix and restart Hue.

aws.aws_accounts.default.region 	Unknown region us-east-2 
aws.aws_accounts.default.region 	Unknown region eu-west-2
aws.aws_accounts.default.region 	Unknown region ca-central-1 

"""_

As per https://github.com/cloudera/hue/blob/master/desktop/libs/aws/src/aws/s3/s3fs.py, I dont see those regions being added.

if get_default_region() in (Location.EU, Location.EUCentral1, Location.USWest, Location.USWest2, Location.SAEast,
                                Location.APNortheast, Location.APSoutheast, Location.APSoutheast2, Location.CNNorth1):

Is there a plan to add these new regions as well?

**Comment by enricoberti** [comment]
Thanks for making us aware of it, created https://issues.cloudera.org/browse/HUE-5851
