### ISSUE TITLE
Have Impala use the latest get_log call

### ISSUE THREAD

**Issue by daliati** [cloudera/hue#483]
Hi!

get_log() is already fixed in impyla to use FetchResults: https://github.com/cloudera/impyla/blob/6ff1794c9c9858ebbd7f59f5075857a63b698a61/impala/hiveserver2.py#L1115-L1130, while in hue, it's still GetLog only, which does not work for impala: https://github.com/cloudera/hue/blob/c1b79cd74b29cddab5511c615cd7013fbb5f2969/apps/beeswax/src/beeswax/server/hive_server2_lib.py#L973-L981. 

Could that patch also be applied here?

thanks for looking at this!
dalia

**Comment by romainr** [comment]
Looks like we should just remove 'or self.query_server['server_name'] == 'impala''?

https://github.com/cloudera/hue/blob/35876d414745831c012210bdde417faad25f4e5d/apps/beeswax/src/beeswax/server/hive_server2_lib.py#L1219
