### ISSUE TITLE
CDH 5.10 - Hue 3.11 Spark Notebook Issue

### ISSUE THREAD

**Issue by Pradeep39** [cloudera/hue#486]
Hi- I'm running CDH 5.10 and enabled Hue Notebooks using safety valve configuration. I also installed Livy 0.3.0 and provided appropriate safety valve config in Cloudera Manager. 

It seems like the spark code in the notebook snippet is running on the cluster through Livy, but the results don't get displayed, I instead get a message that "No logs available at this moment". I was able to confirm that the code is running in the cluster ok by curling the previous session statements. 

See below and please advise if anyone has run into this problem and resolved it through configuration.
![image](https://cloud.githubusercontent.com/assets/16216080/23582559/9a23d7a2-00f2-11e7-898c-c20a21e5db3f.png)

[hdfs@ip-10-179-XXX-XXX logs]$ tail -1 2017_03_03.request.log
10.179.XXX.XXX - - [03/Mar/2017:16:12:31 +0000] "GET /sessions/16/statements/0 HTTP/1.1" 200 -
[hdfs@ip-10-179-XXX-XXX logs]$ curl 10.179.XXX.XXX:8998/sessions/16/statements/0
{"id":0,"state":"available","output":{"status":"ok","execution_count":0,"data":{"text/plain":"res0: Array[Int] = Array(2, 3, 4, 5, 6)"}

Below is the service wide hue_safety_valve config in CM:
 
[desktop]
allowed_hosts=*
app_blacklist=
 
[notebook]
show_notebooks=true
 
[spark]
'# URL of the REST Spark Job Server.
server_url=http://10.179.XXX.XXX:8998/
 
'# List of available types of snippets
languages='[{"name": "Scala", "type": "scala"},{"name": "Python", "type": "python"},{"name": "Impala SQL", "type": "impala"},{"name": "Hive SQL", "type": "hive"},{"name": "Text", "type": "text"}]'
 
'# Uncomment to use the YARN mode
livy_server_session_kind=yarn

**Comment by nonontb** [comment]
Hi,

Did you solve this problem ?I ran into exactly the same issue with CDH 5.9.3

Regards,

**Comment by nonontb** [comment]
After some debugging, result are displayed if I had a breakpoint :
```  self.checkStatus = function () {
      $.post("/notebook/api/check_status", {   <-- HERE
        notebook: ko.mapping.toJSON(notebook.getContext()),
        snippet: ko.mapping.toJSON(self.getContext())
      }, function (data) {}
```
Then I remove the breakpoint manually.

If i do the previous test  the variable self.status == "available" and result are displayed. I don't see any loading snipper in Hue.
If i don't do that the variable self.status == "waiting" and nothing  happen

Any help would be appreciated

Regards
