### ISSUE TITLE
3.12 Oozie Bundle Submission does not work for Oozie servers with non UTC timezones

### ISSUE THREAD

**Issue by tanhaoqin** [cloudera/hue#487]
Bundles are submitted with the kick off time in UTC format which is not accepted when the Oozie server is configured to use a custom timezone.

Coordinators and workflows can be submitted normally though. Is it an intended feature or a bug?

**Comment by Codelone** [comment]
Hi，I encountered the same issue. I don't know if you solved it at the time. Do you have a solution?
I change timezone to GMT+0800，Then submit error。
E1310: Bundle Job submission Error: [E1301: Could not read the bundle job definition, [Could not parse [2018-06-04T15:21Z] using [yyyy-MM-dd'T'HH:mm+0800] mask]]
