### ISSUE TITLE
Cannot modify hive.server2.proxy.user at runtime

### ISSUE THREAD

**Issue by JasonBian** [cloudera/hue#491]
Failed to open new session: java.lang.IllegalArgumentException: Cannot modify hive.server2.proxy.user at runtime. It is not in list of params that are allowed to be modified at runtime

Hadoop 2.6.0-cdh5.6.0
hive 1.1.0-cdh5.6.0

**Comment by romainr** [comment]
This is expected, you seem to be using an old Hue with an old CDH version?

**Comment by JasonBian** [comment]
@romainr my hue was clone from the master branch

**Comment by JasonBian** [comment]
when I add below property to hiveserver2 hive-site.xml,it works ok
`
<property>
   <name>hive.security.authorization.sqlstd.confwhitelist</name>
   <value>hive.server2.proxy.user</value>
</property>
`
