### ISSUE TITLE
"config-class" tag support in oozie workflow map reduce action

### ISSUE THREAD

**Issue by vishal423** [cloudera/hue#493]
I am using Hue 3.11 to create oozie workflows and wants to add a map reduce action whose configurations can be programmatically set. As per oozie workflow functional specifications, this is possible by using a class that implements OozieActionConfigurator interface. This class can be configured by specifying the `<config-class>` tag as child of `<map-reduce>` content. I tried outside hue and able to use it successfully. However, via Hue I couldn't figure any way to specify this configuration. Could you please guide if this is possible via Hue?

**Comment by romainr** [comment]
Just to be sure, do you mean how to specify
`            <config-class>com.example.MyConfigClass</config-class>`
in the editor for a MR action?

**Comment by vishal423** [comment]
@romainr , yes, I was referring to <config-class> tag.

**Comment by hsp8712** [comment]
@romainr @sai-krish  Is this feature have supported now?
