### ISSUE TITLE
put real eror message instead of undefined

### ISSUE THREAD

**Issue by antonkulaga** [cloudera/hue#494]
I often get undefined error in hue web UI while in the console I see the real reasons (for instance 413 for limitations of client request size or permissions problems or something else). Why not desplay the real reason in web UI itself then?

**Comment by romainr** [comment]
Do you see the info in the return of the ajax calls or on the /logs page of Hue?
Do you have easy ways to reproduce them?

Those sounds like bugs, the errors should be logged properly and the end user should have a useful message instead.
