### ISSUE TITLE
Can't display fontawesome's icon when I opened Hue UI with IE11 which was setup by SSL.

### ISSUE THREAD

**Issue by chenshengfeng** [cloudera/hue#498]
If I disabled SSL, IE11 can load and display font-awesome's icons when accessed Hue UI normally. but enable, all the font-awesome's icons were been blocked.

**Comment by romainr** [comment]
This is an issue with Fontawesome / IE. Do you have a load balancer for Hue?

**Comment by lixinlong** [comment]
I also found the same problem in versions 3.9.0 and 3.11.0. I have direct access to Hue and do not go through the load balancer.
