### ISSUE TITLE
workflow configure can not be import to another hue cluster!

### ISSUE THREAD

**Issue by xinghalo** [cloudera/hue#499]
the error message like this:

`{"message": "Problem installing fixture '/tmp/tmp8jiYgq.json': Document2 matching query does not exist."}`

I can import this configure to the same hue, but can not import to another hue.

**Comment by ken328** [comment]
Same problem here!

**Comment by krishnachaitanyareddy** [comment]
Same Problem here

**Comment by 8hfq** [comment]
Same Problem here

**Comment by romainr** [comment]
Which Hue version are you using?

**Comment by apekshatrivedi** [comment]
I am using HUE 4.1 And I face the same problem

**Comment by romainr** [comment]
Would recommend to try with 4.4 or master. A few bugs were fixed (even if the overall feature is not 100% ready)
