### ISSUE TITLE
Upload file to hdfs very slow. 

### ISSUE THREAD

**Issue by lixinlong** [cloudera/hue#501]
version: 3.11.0,3.12.0
Upload file to hdfs very slow.   Other users can not browse the HUE UI while uploading a large file.

**Comment by romainr** [comment]
Could you quantify more, e.g. how large is the file, for all the files or just certain files, where is Hue, where is HDFS, what is Hue CPU at this time?

We are planning to test 20GB file upload soon, so we could test for that too.

**Comment by lixinlong** [comment]
200M，HUE CPU > 100%

**Comment by romainr** [comment]
With SSL enabled?

**Comment by rshibanov** [comment]
I have same trouble.
Without SSL.

**Comment by FS1360472174** [comment]
+1,also met with this issue,it is too slow to upload just 180M jar
