### ISSUE TITLE
build error  : Post-processing 'desktop/ext/css/cui/bootstrap2.css' failed!

### ISSUE THREAD

**Issue by zengbotang** [cloudera/hue#502]
os:ubuntu 16.04
java: oracle java 1.8.0_65

exec make apps cmd to build hue and get the following error:
Post-processed 'desktop/ext/css/cui/bootstrap-responsive2.css' as 'desktop/ext/css/cui/bootstrap-responsive2.e47b2a557fdc.css'
Post-processing 'desktop/ext/css/cui/bootstrap2.css' failed!

**Comment by enricoberti** [comment]
Fixed, thanks!
