### ISSUE TITLE
Failed to execute goal on project hue-plugins

### ISSUE THREAD

**Issue by mamemoryyy111** [cloudera/hue#503]
There is something wrong with my compilation.I don't know how to deal with that problem.Someone help,I will be much appreciate！(●'◡'●)
Hue：3.9.0
Hadoop：2.7.1

Failed to execute goal on project hue-plugins: Could not resolve dependencies for project com.cloudera.hue:hue-plugins:jar:3.9.0-cdh5.6.0: The following artifacts could not be resolved: org.apache.zookeeper:zookeeper:jar:3.4.5-cdh5.6.0, org.apache.hadoop:hadoop-hdfs:jar:2.6.0-cdh5.6.0: Could not transfer artifact org.apache.zookeeper:zookeeper:jar:3.4.5-cdh5.6.0 from/to cloudera.repos (https://repository.cloudera.com/content/groups/cdh-releases-rcs): GET request of: org/apache/zookeeper/zookeeper/3.4.5-cdh5.6.0/zookeeper-3.4.5-cdh5.6.0.jar from cloudera.repos failed: SSL peer shut down incorrectly -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
make[2]: *** [/home/softwares/hue-3.9.0-cdh5.6.0/desktop/libs/hadoop/java-lib/hue-plugins-3.9.0-cdh5.6.0.jar] 错误 1
make[2]: 离开目录“/home/softwares/hue-3.9.0-cdh5.6.0/desktop/libs/hadoop”
make[1]: *** [.recursive-env-install/libs/hadoop] 错误 2
make[1]: 离开目录“/home/softwares/hue-3.9.0-cdh5.6.0/desktop”
make: *** [desktop] 错误 2

**Comment by enricoberti** [comment]
Can you access this url from the machine where you are building Hue? 
http://repository.cloudera.com/cloudera/cdh-releases-rcs/org/apache/zookeeper/zookeeper/3.4.5-cdh5.6.0/

**Comment by mamemoryyy111** [comment]
yes，I can. @enricoberti

**Comment by enricoberti** [comment]
that's weird, so there's no reason you shouldn't be able to compile... have you tried with a newer version of Hue, like 3.12 for instance?

**Comment by mamemoryyy111** [comment]
yeah，I try with the 3.12，unlucky it failed. I try many version of Hue. By the way,i modified the hadoop version in the pom.xml , is that wrong? @enricoberti

**Comment by enricoberti** [comment]
maybe that's the reason then, can you try just with a vanilla version without changes?

**Comment by mamemoryyy111** [comment]
OK, I gonna try without any changes. Thanks a lot~

**Comment by romainr** [comment]
You should keep the Hadoop versions as is, and in practice the compiled stuff won't be used (it is only for MR1 and we will remove this step at some point)

**Comment by mamemoryyy111** [comment]
there is another error，I have installed Python2.7.5 by using the centOS‘s YUM order.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.382 s
[INFO] Finished at: 2017-03-19T19:00:14+08:00
[INFO] Final Memory: 7M/59M
[INFO] ------------------------------------------------------------------------
make[1]: 进入目录“/home/softwares/hue-release-3.12.0/desktop”
make -C core env-install
make[2]: 进入目录“/home/softwares/hue-release-3.12.0/desktop/core”
--- Building egg for pytz-2015.2
running bdist_egg
running egg_info
writing pytz.egg-info/PKG-INFO
writing top-level names to pytz.egg-info/top_level.txt
writing dependency_links to pytz.egg-info/dependency_links.txt
reading manifest file 'pytz.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pytz.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
error: can't copy 'pytz/zoneinfo/America/Porto_Acre': doesn't exist or not a regular file
make[2]: *** [/home/softwares/hue-release-3.12.0/desktop/core/build/pytz-2015.2/egg.stamp] 错误 1
make[2]: 离开目录“/home/softwares/hue-release-3.12.0/desktop/core”
make[1]: *** [.recursive-env-install/core] 错误 2
make[1]: 离开目录“/home/softwares/hue-release-3.12.0/desktop”
make: *** [desktop] 错误 2

**Comment by romainr** [comment]
Om which OS are you?

if yoyu ls -l pytz/zoneinfo/America/Porto_Acre, do you see anything special?
