### ISSUE TITLE
Some oozie workflow's defining layout can't display normal, and occurs JS error "Uncaught SyntaxError: Unexpect token".

### ISSUE THREAD

**Issue by chenshengfeng** [cloudera/hue#505]
I find this problem maybe caused by workflow_json is null, but I don't know how to fix it.

**Comment by romainr** [comment]
Could you share a workflow.xml that fails?

**Comment by chenshengfeng** [comment]
As my company has a force rule of information security, I can't send the xml file to you personally. I very sorry!


发自我的 iPhone

**Comment by romainr** [comment]
On which Hue version are you?
