### ISSUE TITLE
Receiving Error "Incorrect string value: '\xC5\x9F\xC4\xB1k ...' for column 'query' at row 1" while running query from HUE Hive Query editor

### ISSUE THREAD

**Issue by shyamshaw** [cloudera/hue#506]
We are running a simple select query with one condition. The query is running fine from hive cli, beeline, zeppelin but when ruuning the same query from HUE Hive query editor, received the below error:
"Incorrect string value: '\xC5\x9F\xC4\xB1k ...' for column 'query' at row 1"
SELECT * from <table_name> WHERE <col> = 'Turkish Characters' ;
HUE Version: 3.9.0
Note: 
1.Data has some special (Turkish) Characters. Not sure how HUE handles this type of characters.
2.HUE is running in web browser which is in UTF-8,
3.Looking for any configurations in HUE for turkish character encoding.
During initial research, this issue seems to be related to HUE-4889.
Any help?

**Comment by romainr** [comment]
Could you try a 'SELECT '[replace by some Tukish characters]'
on demo.gethue.com?

Hue 3.9 is very old (we are at 3.12 and soon 4) and this issue has been very probably fixed already.

**Comment by shyamshaw** [comment]
![hue_error](https://cloud.githubusercontent.com/assets/25997673/24341062/a1427ebe-12d4-11e7-8f93-35bc65e838f7.PNG)

Still getting the same error.

**Comment by shyamshaw** [comment]
@romainr 

I have tried it on demo.gethue.com (HUE version 3.12)and it worked. Do we have any workaround for Hue 3.9?

![hue](https://cloud.githubusercontent.com/assets/25997673/24342960/950800f8-12e1-11e7-8ee9-5dc661e872f6.PNG)

**Comment by romainr** [comment]
We would need to find the list of patches and apply it on your old Hue.

Do you have any plan to upgrade?

**Comment by shyamshaw** [comment]
We don't have any plan to upgrade Hue as of now. One more point I want to mention is that we are using mysql-server-5.1.73-7.el6.x86_64 as hue backend database. Could this be an issue?

**Comment by yuriyhupalo** [comment]
can you take look to collation/encoding of mysql table desktop_document2?

**Comment by shyamshaw** [comment]
collation for table desktop_document2 is latin1_swedish_ci

**Comment by yuriyhupalo** [comment]
hope table conversion to charset utf-8 should solve your problem.

**Comment by shyamshaw** [comment]
I have set the charset to utf8 for table desktop_document2 but it didn't helped. We are still getting the same error. Any help?

**Comment by NealLee** [comment]
you should set the charset to utf8 for the feild , not only for the table.@shyamshaw

**Comment by shyamshaw** [comment]
@NealLee  Can you please let me know for which field I should set the charset to utf8?

mysql〉 show table status like 'desktop_document2';
 
 +-------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
 
 | Name | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time | Update_time | Check_time | Collation | Checksum | Create_options | Comment |
 
 +-------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
 
 | desktop_document2 | InnoDB | 10 | Compact | 140 | 26331 | 3686400 | 0 | 114688 | 10485760 | 50192 | 2017-03-31 17:14:18 | NULL | NULL | latin1_swedish_ci | NULL | | |
 
 +-------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
 
 1 row in set (0.00 sec)
 
 
 
 mysql〉 desc desktop_document2;
 
 +---------------+--------------+------+-----+---------+----------------+
 
 | Field | Type | Null | Key | Default | Extra |
 
 +---------------+--------------+------+-----+---------+----------------+
 
 | id | int(11) | NO | PRI | NULL | auto_increment |
 
 | owner_id | int(11) | NO | MUL | NULL | |
 
 | name | varchar(255) | NO | | NULL | |
 
 | description | longtext | NO | | NULL | |
 
 | uuid | varchar(36) | NO | MUL | NULL | |
 
 | type | varchar(32) | NO | MUL | NULL | |
 
 | data | longtext | NO | | NULL | |
 
 | extra | longtext | NO | | NULL | |
 
 | last_modified | datetime | NO | MUL | NULL | |
 
 | version | smallint(6) | NO | MUL | NULL | |
 
 | is_history | tinyint(1) | NO | MUL | NULL | |
 
 +---------------+--------------+------+-----+---------+----------------+
 
 11 rows in set (0.00 sec)

**Comment by shyamshaw** [comment]
@romainr Can you tell me how can I upgrade hue from 3.9 to 3.12 as hue 3.9 is a tar ball installation. Do you have any procedure to upgrade it? 

Also, in hue 3.12 there are some extra tables. How can I import the existing workflow (from hue 3.9) in 3.12?

Thanks in advance !!!

**Comment by shyamshaw** [comment]
@romainr @NealLee @yuriyhupalo 

I have installed hue 3.12 and configured MySQL as a backend database but still I am facing the same issue. Please let me know if you need any additional information. 
Appreciate your urgent help.

![capture1](https://cloud.githubusercontent.com/assets/25997673/24895614/007d3d02-1eaf-11e7-8e16-b6f33c8925d2.PNG)
 
![capture2](https://cloud.githubusercontent.com/assets/25997673/24895644/1b4f77c6-1eaf-11e7-90b1-74e12e576b2d.PNG)

Hue Version : 3.12
MySql : mysql-community-server-5.6.35-2.el7.x86_64

**Comment by shyamshaw** [comment]
Just to add one more point, queries are running fine when we are using sqlite as a hue database.

**Comment by shyamshaw** [comment]
@romainr @yuriyhupalo @NealLee 

Any further suggestions?

**Comment by NealLee** [comment]
<img width="948" alt="wx20170417-145200 2x" src="https://cloud.githubusercontent.com/assets/1488014/25081534/88b67922-237d-11e7-83e5-9936efbe9a5d.png">

Sorry to reply late! Please check the attached file.

**Comment by shyamshaw** [comment]
@NealLee 

Thanks for the update. I set charset to utf8 for the field but we are still facing the same issue.

**Comment by shyamshaw** [comment]
@NealLee 

It worked in Hue 3.12 after setting the charset to utf8 for the field. Can you also help me in importing the existing workflows from 3.9 to 3.12 as there are six extra tables in Hue 3.12.

Thanks in advance!!!
