### ISSUE TITLE
IE crashes when using Hue Search box

### ISSUE THREAD

**Issue by sahnz0r** [cloudera/hue#507]
Typing anything into the Search box in Hue causes Internet Explorer to crash every time. In Chrome it is fine.

This has been tested for:
- IE  11.0.9600.18617
- Hue 3.12 (via demo.gethue.com)
- Hue 3.11

IE will crash each time.

![image](https://cloud.githubusercontent.com/assets/4759846/24385801/de325ca2-13b7-11e7-95e0-354d90e6d371.png)

**Comment by enricoberti** [comment]
Thanks for letting us know! https://issues.cloudera.org/browse/HUE-6133
