### ISSUE TITLE
query one table in hive against several rows and export but no resultset in the csv file?

### ISSUE THREAD

**Issue by anddyhuaa** [cloudera/hue#508]
i use a hive query and there are two rows in the table,then i download it in csv format,but no resultset  in the csv file?  i see values=[] in the debug log

HUE version :3.11 

`[28/Mar/2017 14:43:43 +0800] thrift_util  DEBUG    Thrift call <class 'TCLIService.TCLIService.Client'>.FetchResults returned in 1ms: TFetchResultsResp(status=TStatus(errorCode=None, errorMessage=None, sqlState=None, infoMessages=None, statusCode=0), results=TRowSet(rows=[], columns=[TColumn(i32Val=None, byteVal=None, i16Val=None, i64Val=None, stringVal=TStringColumn(nulls='\x00', values=[]), boolVal=None, doubleVal=None, binaryVal=None), TColumn(i32Val=None, byteVal=None, i16Val=None, i64Val=TI64Column(nulls='\x00', values=[]), stringVal=None, boolVal=None, doubleVal=None, binaryVal=None)], startRowOffset=0), hasMoreRows=False)
`

**Comment by romainr** [comment]
Which Hive are you using?

**Comment by anddyhuaa** [comment]
i am using 1.2.1, i have found the answers already,just configure 
hive_server_host=<FQDN of HiveServer2>
,HS2 support but beewax do not when exporting several rows with limit statement

**Comment by romainr** [comment]
Weird though, it should work, e.g. http://demo.gethue.com/notebook/editor?type=hive
