### ISSUE TITLE
Importing the existing workflows from HUE 3.9 to 3.12

### ISSUE THREAD

**Issue by ChaitanyaManthena** [cloudera/hue#511]
Hi All,

Could you please help to import the existing workflows, coordinators and bundles to an higher version of Hue 3.12 from Hue 3.9 as I saw there are new tables been added and not able to migrate those.

Thanks in advance.

Chaitanya

**Comment by romainr** [comment]
This is unfortunately not supported and now Hue 3 is deprecated (latest version is Hue 4.5)
