### ISSUE TITLE
Schedule as workflow creates empty workflows.

### ISSUE THREAD

**Issue by EsharEditor** [cloudera/hue#512]
Hi:
   Schedule as workflow creates empty workflows in Hue-3.9.0. There is a JS error in Workflow editor. I have noticed this Issue in https://issues.cloudera.org/browse/HUE-3793, but I did‘t find any patches for this Bug. Can you help me with some ideas? 
![image](https://cloud.githubusercontent.com/assets/20943153/24781628/8bf4b796-1b73-11e7-8974-136c8b7d562f.png)

**Comment by romainr** [comment]
Sounds like an old bug. Do you have it on http://demo.gethue.com? (Hue 3.12)

**Comment by EsharEditor** [comment]
Hi:
  It's an old bug on HUE 3.9.0, I need a patch for this bug,Do you have it?
