### ISSUE TITLE
Receiving error when trying to select data from an ACID table in HUE

### ISSUE THREAD

**Issue by shyamshaw** [cloudera/hue#513]
I have created an ACID table in hive but when I am trying to select the data from the table in HUE, it is failing. 
![error](https://cloud.githubusercontent.com/assets/25997673/24855786/459c7c40-1e00-11e7-940d-497640f20b29.PNG)

Hue version : 3.12

hive> create table test2 (x int, y string) clustered by (x) into 2 buckets stored as ORC tblproperties ("transactional" = "true");
OK
Time taken: 1.916 seconds

hive> SET hive.support.concurrency=true;
hive> SET hive.enforce.bucketing=true;
hive> SET hive.exec.dynamic.partition.mode=nonstrict;
hive> SET hive.txn.manager=org.apache.hadoop.hive.ql.lockmgr.DbTxnManager;

hive> select * from test2;
OK
1       a
1       b
Time taken: 0.85 seconds, Fetched: 2 row(s)

**Comment by romainr** [comment]
The issue is with your HiveServer2 default properties,

e.g.

Execute
SET hive.support.concurrency=true;
SET hive.enforce.bucketing=true;
SET hive.exec.dynamic.partition.mode=nonstrict;
SET hive.txn.manager=org.apache.hadoop.hive.ql.lockmgr.DbTxnManager;

in Hue, then type your query.

**Comment by shyamshaw** [comment]
@romainr 

Thanks for the quick response. Now, I am able to view the data in HUE. 👍
