### ISSUE TITLE
why the page load too slowly than 3.8?

### ISSUE THREAD

**Issue by lonely7345** [cloudera/hue#521]
open evey page is so slowly ,  and somtime the white page. some js error. and static resouce load from server evey time. and somtime load error

[
![aaa](https://cloud.githubusercontent.com/assets/120727/25188758/bb1e4ce0-2559-11e7-845a-4f5f1bff61d3.jpeg)
](url)

**Comment by enricoberti** [comment]
are you behind a proxy? how's hue configured?

**Comment by lonely7345** [comment]
beind the nginx. 
all the dubug is disabled

**Comment by romainr** [comment]
And if you access Hue directly on port 8888 do you have the same?
