### ISSUE TITLE
hue hbase bug

### ISSUE THREAD

**Issue by 13917467529** [cloudera/hue#523]
1.在hue中的hbase筛选框进行筛选，将筛选出来的结果表逐个打√，然后点击disable
2.disable之后，点击全选按钮
3.清除筛选框的条件，显示只有若干个表是打√的
4.点击drop按钮
5.结果所有表被删除

**Comment by enricoberti** [comment]
Sorry we don't have chinese speakers in the team, can you try in English please?

**Comment by 13917467529** [comment]
Follow the steps below on the hbase managerment page in hue:
Step 1: try input some key words into the filter textbox for search hbase table;
Step 2: set value of each checkbox to true one by one, and click the disable button;
Step 3: click the "select all" checkbox;
Step 4: clear the words in the filter box, you'll see only several checkboxs' valus is true;
Step 5: click the drop button and waiting, finally you'll find every hbase table was deleted.
But fortunately, I found this in development environment.

**Comment by enricoberti** [comment]
Thank you! Created https://issues.cloudera.org/browse/HUE-6217 to keep track of it

**Comment by romainr** [comment]
This is https://github.com/cloudera/hue/commit/2d0709e3f727f115ec7ee24497e3122b2c07cf3a

**Comment by enricoberti** [comment]
不好了！ 已经解决了！ 我错了！:)

**Comment by 13917467529** [comment]
Bravo!! But there is still one question puzzled me —— can I upgrade my hue to fix this bug without upgrade whole CDH?

**Comment by 13917467529** [comment]
I saw it is resolved at version 3.12.0 and I found it at version 3.9.0. Never mind, I'll remind my team not to do such actions like I'v done.
