### ISSUE TITLE
Hue installing problem on CentOS 6.7

### ISSUE THREAD

**Issue by CatonChen** [cloudera/hue#524]
Already install all the objects in Development Prerequisites mentioned, but still get an error when run "make apps" command.

> make[1]: Entering directory `/hadoop/ambari-bundle/hue-master/desktop'
> make -C core env-install
> make[2]: Entering directory `/hadoop/ambari-bundle/hue-master/desktop/core'
> --- Building egg for pycrypto-2.6.1
> running bdist_egg
> running egg_info
> /hadoop/ambari-bundle/hue-master/build/env/lib/python2.6/site-packages/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
>   writer = ep.load(installer=installer)
> writing pycrypto.egg-info/PKG-INFO
> writing top-level names to pycrypto.egg-info/top_level.txt
> writing dependency_links to pycrypto.egg-info/dependency_links.txt
> writing pycrypto.egg-info/PKG-INFO
> writing top-level names to pycrypto.egg-info/top_level.txt
> writing dependency_links to pycrypto.egg-info/dependency_links.txt
> reading manifest file 'pycrypto.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'pycrypto.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> error: can't copy 'lib/Crypto/SelfTest/Random/OSRNG/test_posix.py': doesn't exist or not a regular file
> make[2]: *** [/hadoop/ambari-bundle/hue-master/desktop/core/build/pycrypto-2.6.1/egg.stamp] Error 1
> make[2]: Leaving directory `/hadoop/ambari-bundle/hue-master/desktop/core'
> make[1]: *** [.recursive-env-install/core] Error 2
> make[1]: Leaving directory `/hadoop/ambari-bundle/hue-master/desktop'
> make: *** [desktop] Error 2

[root@hdps004 hue]# python --version
Python 2.6.6
[root@hdps004 hue]# java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (rhel-2.5.5.4.el6-x86_64 u79-b14)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
[root@hdps004 hue]# mvn -v
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T03:39:06+08:00)
Maven home: /hadoop/ambari-bundle/apache-maven-3.5.0
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-573.el6.x86_64", arch: "amd64", family: "unix"

Can someone give any help on this ? 
Thanks.

**Comment by romainr** [comment]
'error: can't copy 'lib/Crypto/SelfTest/Random/OSRNG/test_posix.py': doesn't exist or not a regular file'?

ls desktop/core/ext-py/pycrypto-2.6.1/lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -l
-rw-rw-r-- 1 romain romain 1777 Jul  1  2016 desktop/core/ext-py/pycrypto-2.6.1/lib/Crypto/SelfTest/Random/OSRNG/test_posix.py

**Comment by CatonChen** [comment]
The file is under the right path as below.

> [root@hdps004 hue]# ls desktop/core/ext-py/pycrypto-2.6.1/lib/Crypto/SelfTest/Random/OSRNG/ -l
> total 24
> -rw-r--r-- 1 root root 2082 Feb 23 06:54 __init__.py
> -rw-r--r-- 1 root root 1795 Feb 23 06:54 test_fallback.py
> -rw-r--r-- 1 root root 1746 Feb 23 06:54 test_generic.py
> -rw-r--r-- 1 root root 1764 Feb 23 06:54 test_nt.py
> **-rw-r--r-- 1 root root 1777 Feb 23 06:54 test_posix.py**
> -rw-r--r-- 1 root root 1777 Feb 23 06:54 test_winrandom.py

But build process can't copy it ...
This is strange! 
Is any way to work around?
Thanks.

**Comment by CatonChen** [comment]
I meet above issue only when I was using zip package downloaded from gethue.com or GitHub.
So, I am still not sure why the issue occur.

I find a work around way to solve this issue.
I use git to clone the hue source code directly from GitHub, and then build it, finally it is succeeded.
And I see build process need to download many objects from a public repository, so do the hue team consider the case that install hue with no access internet ?
Can anyone tell me what need to prepare to install hue offline?
Thank you very much.
