### ISSUE TITLE
How to change hue log dirctory

### ISSUE THREAD

**Issue by shyamshaw** [cloudera/hue#528]
Hi Everyone,

I have installed Hue 3.12 (latest) using tar ball. Currently hue logs are getting stored under /usr/local/hue/logs and I want to change the hue log directory. I checked the hue.ini but didn't find any property which I can set to change the log location.

Any help?

Thanks in advance!!

**Comment by romainr** [comment]
Have you looked at https://github.com/cloudera/hue/blob/master/desktop/conf/log.conf?

**Comment by shyamshaw** [comment]
@romainr 
I exported the DESKTOP_LOG_DIR to /var/log/.. and restarted hue but the logs are still writing to /usr/local/hue/logs. When I am hard coded the log path in log.conf then it was able to write to custom log location.

I even set the variable DESKTOP_LOG_DIR in .bashrc file and source it but didn't worked.

**Comment by cricket007** [comment]
In the INI file that I have, there's this line

```sh
su -s /bin/bash $USER -c "$DAEMON $DAEMON_OPTS"
```

Which, looking at the other variables, you see that `supervisor -l <log_dir>` is the argument that is used. 

Also, refer [`man supervisor`](http://manpages.ubuntu.com/manpages/zesty/man1/supervisor.1.html)

>        -l FILE, --logfile=FILE
>              Filename path to use as the supervisord activity log.

```sh
HUE_HOME=/usr/local/hue/                
NAME=hue-server                           
BIN=$HUE_HOME/build/env/bin              
DAEMON=$BIN/supervisor                        
LOGDIR=/var/log/hue                      
PIDFILE=/var/run/hue/$NAME.pid
USER=hue
EXEC=$HUE_HOME/build/env/bin/python
DAEMON_OPTS="-p $PIDFILE -l $LOGDIR -d"
```
