### ISSUE TITLE
Impala query fails if no / incorrect database selected in dropdown

### ISSUE THREAD

**Issue by alexespencer** [cloudera/hue#529]
If no database (or a different database) is selected in the dropdown box on the left of the query, the query fails with invalid syntax. The query being submitted is of the from "select * from database_name.table_name" - so the dropdown should be irrelevant.

**Comment by romainr** [comment]
Could you send a screenshot? we never saw this isssue

**Comment by alexespencer** [comment]
![no database error](https://cloud.githubusercontent.com/assets/7407677/25810581/6e5306fe-3408-11e7-8bee-03137536ae4b.JPG) Hi - here you can see no database is selected. If I select the right database, this strange error goes away. I can close my ticket if you think it's a Hue version issue - we are a few version behind...

**Comment by romainr** [comment]
Seems a pretty old version, would recommend to upgrade as there is a new Editor released one year ago that fixes a lot of these issues (and did not hear about this one in a while): http://gethue.com/sql-editor/
demo.gethue.com/notebook/editor?type=impala

**Comment by alexespencer** [comment]
Likely to be version related - closing ticket.
