### ISSUE TITLE
Solr indexing problems

### ISSUE THREAD

**Issue by firefoxx007** [cloudera/hue#534]
Hello. I'm using HUE 3.11 and Solr 4. And I faced two problems:
1. Using HUE dashboards, I faced the problem while opening documents. Everytime I try to open any doc, I have an error "This document does not have any index id". This error vanishes after changing parameters of search, restarting Solr or, sometimes, moving to the next dashboard page (though I don't know what exactly makes it start working fine). All the documents have unique index id, there are no unindexed fields. May be anyone knows the answer how to fix it.
2. We noticed this strange behavior using Cloudera Search.
If we search on a single collection we can easly retrive the document data by "expanding" the corrispondent record. If we use a collection alias we can retrive only documents from the first linked collection in the alias.
Thanks.

**Comment by romainr** [comment]
Hue gets the unique key of the collection in the get_collection Ajax call that you can see in the Chrome console network tab.

There, in the collection object you would see the field that could be run from the schema:
`idField : "id"`

Is it empty in your case? 

(I could not try to reproduce it, but maybe there is a corner case)
