### ISSUE TITLE
Windows browser is not on hue

### ISSUE THREAD

**Issue by maxiulin** [cloudera/hue#536]
I configured the hue configuration file ip and port, but still can not visit, suggesting that can not access this site

[root@localhost /]# cd hue-release-3.6.0
[root@localhost hue-release-3.6.0]# build/env/bin/supervisor &
[1] 2706
[root@localhost hue-release-3.6.0]# starting server with options {'ssl_certificate': None, 'workdir': None, 'server_name': 'localhost', 'host': '192.168.56.2', 'daemonize': False, 'threads': 10, 'pidfile': None, 'ssl_private_key': None, 'server_group': 'hue', 'ssl_cipher_list': 'DEFAULT:!aNULL:!eNULL:!LOW:!EXPORT:!SSLv2', 'port': 8001, 'server_user': 'hue'}

**Comment by romainr** [comment]
3.6 is very old Hue. 

Make sure
  http_host=0.0.0.0
  http_port=8000
so that the server listen from other hosts. Then 192.168.56.2:8000 should open Hue

**Comment by maxiulin** [comment]
Thank you very much！The firewall of my centos is opened that can access this site!
