### ISSUE TITLE
Unable to modify ACLs for '/' (root directory)

### ISSUE THREAD

**Issue by gorden2** [cloudera/hue#538]
My client tried to add File ACLs to root directory, but the console reported a <code>WebApplicationException:None</code> Error. 

After a throughout investigation, I think I might find the source for that.

Before we dive into the cause, let's look at the basic command to modifyAclEntries through HDFS rest API first.
The Webhdfs rest API use the following syntax for <a href="https://hadoop.apache.org/docs/r2.6.1/hadoop-project-dist/hadoop-hdfs/WebHDFS.html#Modify_ACL_Entries">modifyAclEntries</a> operation.
<code>curl -i -X PUT "http://\<HOST\>:\<PORT\>/webhdfs/v1/\<Path\>?op=MODIFYACLENTRIES&aclspec=\<ACLSPEC\>"</code>
Here for the root directory, the \<Path\> should be replaced as  <code>/</code>, not "" (which causes WebApplicationException)
But for "Get ACL Status" operation the \<Path\> can either be <code>/</code> or ""

Now here might be the problem.
I found that Hue uses <code>hue/desktop/core/src/desktop/lib/rest/resource.py</code> and <code>hue/desktop/core/src/desktop/lib/rest/http_client.py</code> to send the PUT request.
The suspicious part is <a href="https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/lib/rest/http_client.py#L163">here</a> and the <code>normpath</code> method. This may cause the <code>/</code> to behave strangely. 

So can someone help to find a solution for this?

Note: I am not a native English Speaker and this is my first time posting issues on Github, so please be patient about my expressions and layout.

Thanks!

**Comment by gorden2** [comment]
Information Updates:
This issue only happens when Hue uses Httpfs as the default namenode. And some debug info confirms my assumption:
<code>DEBUG    "PUT /webhdfs/v1/?aclspec=&op=REMOVEACLENTRIES&user.name=hue&doas=hdfs HTTP/1.1" 500 None</code>

**Comment by romainr** [comment]
In practice Hue is making the same call when it is using HttpFs or WebHdfs. 

Probably WebHdfs accepts "" but HttpFs needs a "/". We could see for sending the "/" all the time or log an HDFS bug
