### ISSUE TITLE
OperationalError at /accounts/login/

### ISSUE THREAD

**Issue by VathsalRavi** [cloudera/hue#542]
I Tried to follow http://gethue.com/hadoop-hue-3-on-hdp-installation-tutorial/ 
Installed on top of Hortonworks 2.5.3. 
I get the first login page but after that i get below error

`OperationalError at /accounts/login/
no such column: useradmin_userprofile.first_login
Request Method:	POST
Request URL:	http://mst-1:8000/accounts/login/
Django Version:	1.6.10
Exception Type:	OperationalError
Exception Value:	
no such column: useradmin_userprofile.first_login
Exception Location:	/usr/local/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/backends/sqlite3/base.py in execute, line 452
Python Executable:	/usr/local/hue/build/env/bin/python2.6
Python Version:	2.6.6`

**Comment by romainr** [comment]
sudo -u hue <HUE_HOME>/build/env/bin/hue migrate 
?

**Comment by VathsalRavi** [comment]
Thanks I fixed the issue.
