### ISSUE TITLE
Hue 3.10 Remote Access

### ISSUE THREAD

**Issue by Cheeka1979** [cloudera/hue#548]
Greetings,

I am trying to access hue remotely using ./hue runserver remoteaddress:8000 &.

I am having hadoop 2.7.1 and hue version 3.10.0.

When I open it in Mozilla it doesn't show the login screen, but shows the 

KeyError at /accounts/login/

'default'

Request Method: 	GET
Request URL: 	http://remoteaddress:8000/accounts/login/?next=/
Django Version: 	1.6.10
Exception Type: 	KeyError
Exception Value: 	

'default'

Exception Location: 	/usr/hue-3.10.0/desktop/libs/hadoop/src/hadoop/cluster.py in get_hdfs, line 86
Python Executable: 	/usr/hue-3.10.0/build/env/bin/python2.7
Python Version: 	2.7.5
Python Path: 	

['/usr/hue-3.10.0/build/env/bin',
 '/usr/hue-3.10.0/apps/about/src',
 '/usr/hue-3.10.0/apps/beeswax/gen-py',
 '/usr/hue-3.10.0/apps/beeswax/src',
 '/usr/hue-3.10.0/apps/filebrowser/src',
 '/usr/hue-3.10.0/apps/hbase/gen-py',
 '/usr/hue-3.10.0/apps/hbase/src',
 '/usr/hue-3.10.0/apps/help/src',
 '/usr/hue-3.10.0/apps/impala/gen-py',
 '/usr/hue-3.10.0/apps/impala/src',
 '/usr/hue-3.10.0/apps/jobbrowser/src',
 '/usr/hue-3.10.0/apps/jobsub/src',
 '/usr/hue-3.10.0/apps/metastore/src',
 '/usr/hue-3.10.0/apps/oozie/src',
 '/usr/hue-3.10.0/apps/pig/src',
 '/usr/hue-3.10.0/apps/proxy/src',
 '/usr/hue-3.10.0/apps/rdbms/src',
 '/usr/hue-3.10.0/apps/search/src',
 '/usr/hue-3.10.0/apps/security/src',
 '/usr/hue-3.10.0/apps/spark/src',
 '/usr/hue-3.10.0/apps/sqoop/src',
 '/usr/hue-3.10.0/apps/useradmin/src',
 '/usr/hue-3.10.0/apps/zookeeper/src',

At the end It shows -> You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page

**Comment by romainr** [comment]
Did you configure the [hadoop] section of your hue.ini?
http://gethue.com/how-to-configure-hue-in-your-hadoop-cluster/

**Comment by Cheeka1979** [comment]
Thanks romainr for your help. Yes. 

hdfs-site.xml ->
<property>
<name>dfs.webhdfs.enabled</name>
<value>true</value>
</property>

core-site.xml-> ->
<property>
<name>hadoop.proxyuser.hue.hosts</name>
<value>*</value>
</property>
<property>
<name>hadoop.proxyuser.hue.groups</name>
<value>*</value>
</property>

httpfs-site.xml ->
<property>
  <name>httpfs.proxyuser.hue.hosts</name>
  <value>*</value>
</property>
<property>
  <name>httpfs.proxyuser.hue.groups</name>
  <value>*</value>
</property>

**Comment by romainr** [comment]
And do you have?

[desktop]
 http_host=0.0.0.0

**Comment by Cheeka1979** [comment]
Yes, The problem was syncdb hue. That is needed to up your hue, ( even after a system restart). then ./hue runserver remoteserver:8000 & started by hue. Thanks for your  help.
