### ISSUE TITLE
python 3

### ISSUE THREAD

**Issue by antonkulaga** [cloudera/hue#552]
The whole world already moved to python 3 and keeping python 2 just because of Hue is becoming inconvenient.

**Comment by romainr** [comment]
Which OS are you on?

Hue still needs to support the default Python of older OS. It should move forward with the dropping of Python 2.6 later this year, and it will be a good time to investigate Python 3 compatibility at this time too.

**Comment by NoraGithub** [comment]
Today is the last day of `this year`.

**Comment by NoraGithub** [comment]
last **workday**

**Comment by romainr** [comment]
https://issues.cloudera.org/browse/HUE-8737

**Comment by elukey** [comment]
Is there any plan to release a CDH 5.X version with python3 support for Hue given https://www.python.org/doc/sunset-python-2/ ?

**Comment by romainr** [comment]
As of today, there is no plan for CDH5/6, only CDP (the new distribution).
