### ISSUE TITLE
How to change owner of workflows and co-ordinators in hue (MySql as backend database)

### ISSUE THREAD

**Issue by shyamshaw** [cloudera/hue#555]
@romainr We have reviewed the steps which you provided in below link to change the owner of workflows with sqlite as backend database. 
http://gethue.com/how-to-manage-the-hue-database-with-the-shell/

Can we also have the steps for MySql as backend database? Also hue has been installed using tarball.

Hue Version: 3.9

Thanks in advance!

**Comment by enricoberti** [comment]
Well, for 3.9 the DB doesn't matter, it's just Python code

`# First move the objects`
`from desktop.models import Document2`
`from django.contrib.auth.models import User`
 
`u1 = User.objects.get(username='bob')`
`u2 = User.objects.get(username='joe')`
 
`Document2.objects.filter(owner=u1, type='oozie-workflow2')`
`> [<Document2: MyWf - bob>]`
 
`Document2.objects.filter(owner=u1, type='oozie-workflow2').update(owner=u2)`
`> 1`
 
`Document2.objects.filter(owner=u1, type='oozie-workflow2')`
`> []`
 
`Document2.objects.filter(owner=u2, type='oozie-workflow2')`
`> [<Document2: MyWf - joe>]`
 
`wfs = Document2.objects.filter(owner=u2, type='oozie-workflow2')`
