### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by ehiggs** [cloudera/hue#556]
The dependencies listed in [devtools.mk](http://archive.cloudera.com/desktop-sdk-python-packages) are wildly out of date. IPython 0.10 (current supporting 2.7 is 5.4.1), ipdb 0.1 (current is 0.10.

For the general health of a project, we shouldn't depend on >=7 year old versions of packages.

**Comment by enricoberti** [comment]
I think it's probably because of all the different (old) platforms we have to support.
Opened [https://issues.cloudera.org/browse/HUE-6822](https://issues.cloudera.org/browse/HUE-6822) to track it
