### ISSUE TITLE
open notebook in hue home just jump to new notebook

### ISSUE THREAD

**Issue by liruikaiyao** [cloudera/hue#557]
when I want to open a saved notebook on home page, it will jump to open a new notebook not my saved one, only if you  open the saved notebook from left sidebar documents, then you can open your saved notebook, I think it's a bug?

**Comment by enricoberti** [comment]
hi! do you have more info for us? which version? or from master? what browser are you experiencing this in?

**Comment by cammette** [comment]
I encountered the same problem，the version of hue is 4.0.1，and used hue4 web view

**Comment by cammette** [comment]
my solution is: hue.mako 995 line
`if (window.location.getParameter('notebook') !== '') {`
changed as
` if (page.current.indexOf("notebook=")>=0) {`

**Comment by enricoberti** [comment]
Thanks! Actually it's a bug just when the notebook app has not been loaded yet, I opened https://issues.cloudera.org/browse/HUE-7138 to keep track of it
