### ISSUE TITLE
Content Security Policy directive: "connect-src 'self'

### ISSUE THREAD

**Issue by maziyarpanahi** [cloudera/hue#559]
Hi,

I updated my CDH to 5.11.1 two weeks ago and ever since I see "error" notifications whenever I need to use file browser. For instance, if I want to add new table in Metastore I get the "error" notification when I click in the "Path" field. And this is what I see in my browser console:

Refused to connect to 'http://my-hue-domain/filebrowser/view=/user/my-username?format=json' because it violates the following Content Security Policy directive: "connect-src 'self'".

My Hue is behind an nginx but I have no configs for CSP in my nginx nor in my Hue configurations and it was fine before CDH 5.11.0.

Here is the screenshot of what exactly happens:

<img width="1516" alt="screenshot 2017-07-11 11 54 21" src="https://user-images.githubusercontent.com/5762953/28062899-b42fd4dc-662f-11e7-8aae-93e839aa16b1.png">

Many thanks,

**Comment by enricoberti** [comment]
As a workaround, you can override the security policies
https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L103
So in your case you can specify `connect-src *`

I'm assigning this to @ranade1 though to check if there's a bug :)
