### ISSUE TITLE
[Errno 22] Unknown scheme s3, available schemes: ['hdfs', 's3a']

### ISSUE THREAD

**Issue by ckljohn** [cloudera/hue#560]
I am using AWS EMR 5.5 with HUE 3.12.

I created a Hive DB located on s3.
I am using s3 but not s3a because s3a is not making use of EMRFS consistent view (something like s3 guard) and the SSE encryption is not enforced.

The error appears at 
http://localhost:8888/filebrowser/view=s3%3A//mybucket/
[Errno 22] Unknown scheme s3, available schemes: ['hdfs', 's3a']

**Comment by romainr** [comment]
You would also need to configure the S3 credentials to have the Hue S3 Browser work:
http://gethue.com/introducing-s3-support-in-hue/

**Comment by ckljohn** [comment]
I am installing hue on EMR which I have provided the the master node with IAM role.
I can access s3 with the "File browsers" tab.

When I try to click on the "Location" in the DB description in "Metastore Manager", it redirect me to "http://localhost:8888/filebrowser/view=s3%3A//mybucket/" and error pops out.

Here is how I define the DB
`CREATE DATABASE database_name LOCATION "s3://mybucket/;`
which is totally fine for Hive.

**Comment by rentaow** [comment]
Hue does support use of EmrFs which is why you can't use s3 scheme.

**Comment by romainr** [comment]
When you define the table, could you use 's3a'?

`...LOCATION "s3a://mybucket/;`

**Comment by ckljohn** [comment]
Thank you @rentaow 
In this case, there is no reason to use s3 with HUE.
