### ISSUE TITLE
Hue seems to contain GPL code

### ISSUE THREAD

**Issue by oflebbe** [cloudera/hue#568]
Hi,

Hue seems to contain GPL code:
https://github.com/cloudera/hue/blob/master/desktop/core/ext-py/enum-0.4.4/setup.py

Because of this I had to propose to remove HUE from Apache Bigtop.

https://lists.apache.org/thread.html/7e293ce2ddd3654db73ada0de2a3e44999a89ff7a4e91bd629355bd3@%3Cdev.bigtop.apache.org%3E

**Comment by enricoberti** [comment]
We've had this reviewed before, and it's either GPL or Python license

https://github.com/cloudera/hue/blob/master/desktop/core/ext-py/enum-0.4.4/PKG-INFO#L8

**Comment by oflebbe** [comment]
I have to admit that I misread the last line and accidentally checked with the current version at pypi (not the one included in hue) . The current version is GPL only. 

The last line of the license header reads " or, at your option, the terms of the Python license."  This may work as dual licensing with PSF license.

Ok, thanks for pointing. Let me think about it a bit.

**Comment by enricoberti** [comment]
No worries! I remember exactly the situation from our Cloudera internal Palamida scan, also together with
https://github.com/cloudera/hue/blob/master/desktop/core/ext-py/MySQL-python-1.2.5/INSTALL#L249
and this false positive
https://github.com/cloudera/hue/blob/master/desktop/core/ext-py/lxml-3.3.6/LICENSES.txt

**Comment by romainr** [comment]
And also we will finally have a Django rebase and bump the minimum Python version to 2.7 which would allow to remove bunch of old libs that false positive sometimes.
Added a note to https://issues.cloudera.org/browse/HUE-3287
