### ISSUE TITLE
request: Dark Mode

### ISSUE THREAD

**Issue by r-richmond** [cloudera/hue#569]
A dark mode would be greatly appreciated as its much easier on the eyes.

**Comment by enricoberti** [comment]
Just the editor or the whole Hue? In case it's just the editor, there's a hidden setting you can change from the browser console: 
$.totalStorage("hue.ace.theme", ThemeName) 
where ThemeName is any valid Ace editor theme names (ie: "ace/theme/tomorrow_night"). Refresh the browser and voila, you have a dark theme!

**Comment by r-richmond** [comment]
Thanks for the tip that definitely helps!

However, I still feel like the rest of the interface would be nice to have dark as well. (especially as the white box around the dark theme is quite loud)

<img width="1015" alt="screen shot 2017-07-24 at 5 09 13 pm" src="https://user-images.githubusercontent.com/9246654/28550034-28826d46-7093-11e7-9686-c1af9affdb2d.png">

for reference github: through stylish
<img width="918" alt="screen shot 2017-07-24 at 5 12 47 pm" src="https://user-images.githubusercontent.com/9246654/28550077-6b342b20-7093-11e7-8842-65d63328a995.png">

**Comment by enricoberti** [comment]
Unfortunately we cannot fit this in the roadmap, but feel free to create a stylish theme for it, it shouldn't be that complicated imho!

**Comment by qianxuanyon** [comment]
> 只是编辑还是整个色相？如果只是编辑器，可以在浏览器控制台中更改一个隐藏设置：
> $ .totalStorage（“ hue.ace.theme”，ThemeName）
> ，其中ThemeName是任何有效的Ace编辑器主题名称（即：“ ace / theme /明天晚上”）。刷新浏览器，瞧，您的主题很暗！

1. $.totalStorage("hue.ace.theme", "ace/theme/tomorrow_night")
![image](https://user-images.githubusercontent.com/29041881/67753858-5cb29780-fa70-11e9-9524-f6d9839925f4.png)

2. Refresh the browser  no effect
![image](https://user-images.githubusercontent.com/29041881/67754020-ac915e80-fa70-11e9-9b56-fb552f35b2ea.png)

**Comment by romainr** [comment]
How about the bottom section of http://gethue.com/additional-sql-improvements-in-hue-4-3/? (only for editor indeed so far)
