### ISSUE TITLE
centos7 make apps  i am crazy ，who help me？

### ISSUE THREAD

**Issue by ffzhihua** [cloudera/hue#572]
i am crazy ，who help me？
--- Installing development tool: ipython[0.10]
/usr/local/hue/build/env/bin/python2.7 /usr/local/hue/build/env/bin/easy_install -f http://archive.cloudera.com/desktop-sdk-python-packages/ \
   -H pypi.python.org,archive.cloudera.com -qq ipython==0.10
/usr/local/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'ipdb (0.1dev-r1716)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/usr/local/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'django (debug-toolbar-0.8.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/usr/local/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'django-debug (toolbar-0.8.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/usr/local/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'ipdb-0.1dev (r1716)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/usr/local/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'logilab (astng-0.20.1)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/usr/local/hue/build/env/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'logilab (common-0.51.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
error: None
make[2]: *** [ipython[0.10]] Error 1
make[2]: Leaving directory `/usr/local/hue/desktop'
make[1]: *** [/usr/local/hue/build/.devtools] Error 2
make[1]: Leaving directory `/usr/local/hue/desktop'
make: *** [desktop] Error 2

**Comment by romainr** [comment]
Does it still happen? (sometimes the pip mirrors are down)

**Comment by pholien** [comment]
you can install the packages in file desktop/devtools.mk by using pip, and then delete the packages.

**Comment by meolu** [comment]
after I install the dev libs in `desktop/devtools.mk`, the same problem is solved
