### ISSUE TITLE
Django server makes me crazy

### ISSUE THREAD

**Issue by gouchaoer** [cloudera/hue#574]
centos7, cpu 16core, 32G memory
docker pull the latest image, run server
But it is really instable, the server always gone or blocking for a long time.
Why not use java? Django is a toy.
How can a python-cli with GIL serves static files and process http request at the same time?

**Comment by romainr** [comment]
Sorry it does not work for you, but we have successful installs with hundreds of users. Maybe you should have a look to http://gethue.com/performance-tuning/ and the docker image is not meant for a production usage, but more for a quick testing of the latest Hue.

**Comment by idzikovsky** [comment]
@gouchaoer UR fun. Rly. Made my day.
