### ISSUE TITLE
E0504: App directory [user/hue/oozie/workspaces/hue-oozie-1501307582.31] does not exist

### ISSUE THREAD

**Issue by maxiulin** [cloudera/hue#575]
Hello,I try to run the shell in oozie by hue.when I submit the workflow,I find the error.
Error submitting workflow shell test: E0504: App directory [user/hue/oozie/workspaces/hue-oozie-1501307582.31] does not exist
please help me,thanks!

**Comment by enricoberti** [comment]
please make sure you have the right permissions on HDFS for hue to be able to create Oozie wf directories
