### ISSUE TITLE
cdh5.11.1-hue copy coordinator  error

### ISSUE THREAD

**Issue by wzxwf** [cloudera/hue#576]
cdh5.11.1-hue copy coordinator  error:
{ "message": "The copy of the deployment directory failed: FileNotFoundException: File /user/hue/oozie/workspaces/hue-oozie-1501678732.95 does not exist. (error 404).", "traceback": [ [ "/opt/cloudera/parcels/CDH-5.11.1-1.cdh5.11.1.p0.4/lib/hue/apps/oozie/src/oozie/models2.py", 100, "import_workspace", "fs.copy_remote_dir(source_deployment_dir, self.deployment_dir, owner=owner)" ], [ "/opt/cloudera/parcels/CDH-5.11.1-1.cdh5.11.1.p0.4/lib/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", 208, "copy_remote_dir", "return op(src, dst, *args, **kwargs)" ], [ "/opt/cloudera/parcels/CDH-5.11.1-1.cdh5.11.1.p0.4/lib/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", 653, "copy_remote_dir", "for stat in self.listdir_stats(source):" ], [ "/opt/cloudera/parcels/CDH-5.11.1-1.cdh5.11.1.p0.4/lib/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", 207, "listdir_stats", "json = self._root.get(path, params)" ], [ "/opt/cloudera/parcels/CDH-5.11.1-1.cdh5.11.1.p0.4/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", 100, "get", "return self.invoke(\"GET\", relpath, params, headers=headers, allow_redirects=True, clear_cookies=clear_cookies)" ], [ "/opt/cloudera/parcels/CDH-5.11.1-1.cdh5.11.1.p0.4/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", 80, "invoke", "clear_cookies=clear_cookies)" ], [ "/opt/cloudera/parcels/CDH-5.11.1-1.cdh5.11.1.p0.4/lib/hue/desktop/core/src/desktop/lib/rest/http_client.py", 196, "execute", "raise self._exc_class(ex)" ] ], "detail": null, "title": "Error" }

**Comment by enricoberti** [comment]
@sai-krish double check if it's a legit bug? :)

**Comment by l-j** [comment]
Hello guys, is anyone working on this issue? I have exactly the same problem at CDH 5.12.1.

If I create a new coordinator and later try to copy it I get the exception mentioned above. But if try to copy coordinator created before the upgrade to CDH 5.12.1 (it was CDH 5.5.4) everything work as expected.

**Comment by dorroddorrod** [comment]
We are experiencing the same issue , any updates on this issue?

**Comment by dscarlat** [comment]
Same issue in CDH 5.14.2:

 "message": "The copy of the deployment directory failed: FileNotFoundException: File /user/hue/oozie/workspaces/hue-oozie-1529010470.74 does not exist. (error 404).", "traceback": [ [ "/opt/cloudera/parcels/CDH-5.14.2-1.cdh5.14.2.p0.3/lib/hue/apps/oozie/src/oozie/models2.py", 101, "import_workspace", "fs.copy_remote_dir(source_deployment_dir, self.deployment_dir, owner=owner)" ], [ "/opt/cloudera/parcels/CDH-5.14.2-1.cdh5.14.2.p0.3/lib/hue/desktop/core/src/desktop/lib/fs/proxyfs.py", 212, "copy_remote_dir", "return op(src, dst, *args, **kwargs)" ], [ "/opt/cloudera/parcels/CDH-5.14.2-1.cdh5.14.2.p0.3/lib/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", 715, "copy_remote_dir", "for stat in self.listdir_stats(source):" ], [ "/opt/cloudera/parcels/CDH-5.14.2-1.cdh5.14.2.p0.3/lib/hue/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py", 248, "listdir_stats", "json = self._root.get(path, params, headers)" ], [ "/opt/cloudera/parcels/CDH-5.14.2-1.cdh5.14.2.p0.3/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", 106, "get", "return self.invoke(\"GET\", relpath, params, headers=headers, allow_redirects=True, clear_cookies=clear_cookies)" ], [ "/opt/cloudera/parcels/CDH-5.14.2-1.cdh5.14.2.p0.3/lib/hue/desktop/core/src/desktop/lib/rest/resource.py", 83, "invoke", "clear_cookies=clear_cookies)" ], [ "/opt/cloudera/parcels/CDH-5.14.2-1.cdh5.14.2.p0.3/lib/hue/desktop/core/src/desktop/lib/rest/http_client.py", 211, "execute", "raise self._exc_class(ex)" ] ], "detail": null, "is_embeddable": false, "title": "Error" }
