### ISSUE TITLE
Mysql always loading

### ISSUE THREAD

**Issue by NextMark** [cloudera/hue#579]
I install hue 4.0.0 with github doc, but when i run it with build/env/bin/supervisor and log in, then click on Mysql button, it always loading, my pseudo-distributed.ini is:
 [[[mysql]]]
      name = MySQL
      interface=jdbc
      options='{"url": "jdbc:mysql:/localhost:3306/test", "driver": "com.mysql.jdbc.Driver", "user": "root", "password": "root"}'

![image](https://user-images.githubusercontent.com/5387163/29207813-1aef7536-7eba-11e7-9e04-5a49673c62b5.png)

**Comment by enricoberti** [comment]
It looks like there's a JS error. Please make sure you clear your browser cache and try to reload.
If not, can you please take a screenshot of the browser console too?
Thanks!

**Comment by NextMark** [comment]
Hi enricoberti
the screenshot like

![20170811175635](https://user-images.githubusercontent.com/5387163/29208879-7316d520-7ebe-11e7-90b4-ca9fbed838e0.png)

**Comment by enricoberti** [comment]
Thanks! Does this happen also after a clear cache of Chrome?

**Comment by NextMark** [comment]
Yes, never success.

**Comment by enricoberti** [comment]
I just tried with a fresh 4.0.1 release and it works with no problems (after clearing the browser cache)
