### ISSUE TITLE
non ASCII character

### ISSUE THREAD

**Issue by grozeille** [cloudera/hue#583]
It's not directly a bug in HUE.
I'm using a tool that read the file as ASCII, not UTF8, in order to modify the config file for deployment automation.
It fails because of non ASCII character at that line:
https://github.com/cloudera/hue/blob/f30e9f75011f777458873fbc4c807bd2d100a4cb/desktop/conf/pseudo-distributed.ini.tmpl#L109

"Double quotes" are not standard.
Since other "double quotes" are standard in the file, I suggest to avoid non ASCII character in that file.

**Comment by enricoberti** [comment]
Thanks!
It's gonna be pushed to master soon: https://review.cloudera.org/r/11385/bugs/HUE-7139/
