### ISSUE TITLE
make apps giving me this error

### ISSUE THREAD

**Issue by mhassaanmughal** [cloudera/hue#586]
Using Ubuntu 16.04 

build/temp.linux-x86_64-2.7/_openssl.c:73024:29: note: (near initialization for ‘_cffi_struct_unions[133].alignment’)
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
/var/www/vhosts/hue-4.0.0/Makefile.sdk:120: recipe for target '/var/www/vhosts/hue-4.0.0/desktop/core/build/cryptography-1.3.1/egg.stamp' failed
make[2]: *** [/var/www/vhosts/hue-4.0.0/desktop/core/build/cryptography-1.3.1/egg.stamp] Error 1
make[2]: Leaving directory '/var/www/vhosts/hue-4.0.0/desktop/core'
Makefile:69: recipe for target '.recursive-env-install/core' failed
make[1]: *** [.recursive-env-install/core] Error 2
make[1]: Leaving directory '/var/www/vhosts/hue-4.0.0/desktop'
Makefile:73: recipe for target 'desktop' failed
make: *** [desktop] Error 2

**Comment by junqueira** [comment]
I made the same mistake to make  :\
Exception: Version mismatch: this is the 'cffi' package version 1.10.0, located in '/home/dengo/projects/cloudera/hue/desktop/core/ext-py/cryptography-1.3.1/.eggs/cffi-1.10.0-py2.7-linux-x86_64.egg/cffi/api.pyc'.  When we import the top-level '_cffi_backend' extension module, we get version 1.5.2, located in '/usr/lib/python2.7/dist-packages/_cffi_backend.x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
/home/dengo/projects/cloudera/hue/Makefile.sdk:120: recipe for target '/home/dengo/projects/cloudera/hue/desktop/core/build/cryptography-1.3.1/egg.stamp' failed
make[2]: *** [/home/dengo/projects/cloudera/hue/desktop/core/build/cryptography-1.3.1/egg.stamp] Error 1
make[2]: Leaving directory '/home/dengo/projects/cloudera/hue/desktop/core'
Makefile:106: recipe for target '.recursive-env-install/core' failed
make[1]: *** [.recursive-env-install/core] Error 2
make[1]: Leaving directory '/home/dengo/projects/cloudera/hue/desktop'
Makefile:148: recipe for target 'desktop' failed
make: *** [desktop] Error 2

**Comment by godwinxunwang** [comment]
Same error here: 
-----------------------
gcc -pthread -shared -B /home/xun/anaconda2/compiler_compat -L/home/xun/anaconda2/lib -Wl,-rpath=/home/xun/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/Modules/LDAPObject.o build/temp.linux-x86_64-2.7/Modules/ldapcontrol.o build/temp.linux-x86_64-2.7/Modules/common.o build/temp.linux-x86_64-2.7/Modules/constants.o build/temp.linux-x86_64-2.7/Modules/errors.o build/temp.linux-x86_64-2.7/Modules/functions.o build/temp.linux-x86_64-2.7/Modules/schema.o build/temp.linux-x86_64-2.7/Modules/ldapmodule.o build/temp.linux-x86_64-2.7/Modules/message.o build/temp.linux-x86_64-2.7/Modules/version.o build/temp.linux-x86_64-2.7/Modules/options.o build/temp.linux-x86_64-2.7/Modules/berval.o -L/usr/local/openldap-2.3/lib -L/home/xun/anaconda2/lib -R/usr/local/openldap-2.3/lib -lldap_r -llber -lsasl2 -lssl -lcrypto -lpython2.7 -o build/lib.linux-x86_64-2.7/_ldap.so
gcc: error: unrecognized command line option ‘-R’
error: command 'gcc' failed with exit status 1
/home/xun/hue/Makefile.sdk:120: recipe for target '/home/xun/hue/desktop/core/build/python-ldap-2.3.13/egg.stamp' failed
make[2]: *** [/home/xun/hue/desktop/core/build/python-ldap-2.3.13/egg.stamp] Error 1
make[2]: Leaving directory '/home/xun/hue/desktop/core'
Makefile:153: recipe for target '.recursive-install-bdist/core' failed
make[1]: *** [.recursive-install-bdist/core] Error 2
make[1]: Leaving directory '/home/xun/hue/desktop'
Makefile:192: recipe for target 'install-desktop' failed
make: *** [install-desktop] Error 2
-------------------------

**Comment by brafaelsilva** [comment]
Any update on this error message ? i have the same issue and i'm out of ideas on how to proceed.

**Comment by romainr** [comment]
Which exact error? On which OS?

**Comment by fchiriac** [comment]
It fails for me as well : 

building 'pysqlite2._sqlite' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DMODULE_NAME="pysqlite2.dbapi2" -DSQLITE_OMIT_LOAD_EXTENSION=1 -I/usr/include/python2.7 -c src/module.c -o build/temp.linux-x86_64-2.7/src/module.o
x86_64-linux-gnu-gcc: error trying to exec 'cc1': execvp: No such file or directory
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
/compile/hue/hue/Makefile.sdk:120: recipe for target '/compile/hue/hue/desktop/core/build/pysqlite/egg.stamp' failed
make[2]: *** [/compile/hue/hue/desktop/core/build/pysqlite/egg.stamp] Error 1
make[2]: Leaving directory '/compile/hue/hue/desktop/core'
Makefile:107: recipe for target '.recursive-env-install/core' failed
make[1]: *** [.recursive-env-install/core] Error 2
make[1]: Leaving directory '/compile/hue/hue/desktop'
Makefile:148: recipe for target 'desktop' failed
make: *** [desktop] Error 2

root@opbigbuild02:/compile/hue/hue# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

root@opbigbuild02:/compile/hue/hue# java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

root@opbigbuild02:/compile/hue/hue# python --version
Python 2.7.14

**Comment by Sathiyarajan** [comment]
Any updates on this above mentioned issues? I am also getting it while compiling it in the following environment?
![image](https://user-images.githubusercontent.com/16596464/54132667-a7789400-443a-11e9-987f-15b3df54273e.png)

**Comment by romainr** [comment]
Do you have all the dependencies?

http://cloudera.github.io/hue/latest/admin-manual/manual.html#dependencies

**Comment by Sathiyarajan** [comment]
After following the @romainr  comments I can compile the hue binaries:
FYI:
sudo apt-get install git ant gcc g++ libffi-dev libkrb5-dev libmysqlclient-dev libsasl2-dev libsasl2-modules-gssapi-mit libsqlite3-dev libssl-dev libxml2-dev libxslt-dev make maven libldap2-dev python-dev python-setuptools libgmp3-dev

run the above step in your ubuntu and start proceeding. we can close this issue.
