### ISSUE TITLE
Unable to download hue-4.0.1 tarball - File not found

### ISSUE THREAD

**Issue by shyamshaw** [cloudera/hue#591]
Hi Everyone,

Currently we are using HUE 3.12 and planning to use HUE 4.0 (latest). When we try to download the tarball, we are receiving **File Not Found** issue. 

Could you please provide us the link from where we can download the tarballl.

We are using below link for download
https://dl.dropboxusercontent.com/u/730827/hue/releases/4.0.1/hue-4.0.1.tgz

![image](https://user-images.githubusercontent.com/25997673/30026217-8e318bbe-9199-11e7-8ebc-ddd4a3955b58.png)

**Comment by mcfunk** [comment]
Same issue here. Is there another link for the tarball?

**Comment by mcfunk** [comment]
looks like they are on https://gethue.com/downloads/hue-<RELEASE>.tgz

So 4.0.1 is https://gethue.com/downloads/hue-4.0.1.tgz
@shyamshaw

**Comment by shyamshaw** [comment]
@mcfunk 

Thanks for the link. 
Are you able to download the tar ball using above link because when I am trying to download using your link, it is redirecting me to the previous link.

**Comment by enricoberti** [comment]
@shyamshaw @mcfunk we have fixed and updated all the download links for any release. Sorry for the inconvenience!

**Comment by shyamshaw** [comment]
@enricoberti 

Thanks a lot!! We are able to download the tarball now.
