### ISSUE TITLE
500 Server error bug in Hue 4.0 Notebook

### ISSUE THREAD

**Issue by maziyarpanahi** [cloudera/hue#592]
Hi,

I have my Hue server behind Nginx with forced HTTPS. Ever since I upgraded to CDH 5.12 I can't use Notebooks in Hue 4.0. It gives me `500 Server error` in Chrome/Firefox (not in Safari!).

The console of the Chrome/Firefox suggests: 
`Mixed Content: The page at 'https://huedomain/hue/notebook?notebook=51472' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://huedomain/notebook/?is_embeddable=true'. This request has been blocked; the content must be served over HTTPS.`

I even tried setting `secure_content_security_policy=""` in my ini file but still the same result.

The reason I think this might be a bug (or miss config some where) is that if I switch back to Hue 3 on the same browser everything works as it's expected. I can use my Notebooks again.

Many thanks,
Maziyar

**Comment by jgermond** [comment]
We have the same problem.
We added the following directive in nginx : proxy_redirect ~^http://(.*)$ https://$1

**Comment by maziyarpanahi** [comment]
Big thank you for the workaround @jgermond! 
Many thanks mate, now I can set is_hue_4 back to true :)
