### ISSUE TITLE
Question: Embed Hue dashboard in custom application

### ISSUE THREAD

**Issue by malejpavouk** [cloudera/hue#596]
Hi,

does Hue have a support for embedding into custom applications? We like the dashboarding capabilities that Hue offers, and we'd like to make it part of our app - using iframe (or some other mechanism). 

Does Hue already have this feaure? Or is it at least planned? Or we are on our own? (if so, can you please share any hints).

Thank you in advance!

**Comment by romainr** [comment]
A revamp of the chart is coming. First step will be to make it easier to share links/reports. Embedding is not decided yet but might come afterwards.
