### ISSUE TITLE
HUE cannot get UDF

### ISSUE THREAD

**Issue by hsh075623201** [cloudera/hue#597]
when I use hive-cli to execute `show functions` ,it can show UDF
but, when I use HUE to execute,No UDFs

how can I setting UDF in global ENV?
Thanks in advance.

**Comment by romainr** [comment]
'show functions' works for me. Does it work for you on http://demo.gethue.com?

**Comment by hsh075623201** [comment]
Hi romainr:
  
  The problem confused me is not the `show funcitons` command.
  when I execute `show functions` command ,I can get some default functions ,but can not get UDFs,
 so how can I set UDFs in global enviroment to get UDFs by using `show functions`

thanks in advance.

**Comment by romainr** [comment]
It should be the same. Are you Hue and Beeline pointing to the same HiveServer2?
