### ISSUE TITLE
[search] Feature Request: Counter custom query

### ISSUE THREAD

**Issue by malejpavouk** [cloudera/hue#598]
Hi,

I noticed that its not possible to specify custom query for counter in the dashboard. 
Motivation:
- Currently Counter widget can be used only for retrieval for rather simple statistics (count, unique, median...)
- But sometimes we need to show more advanced aggregates on the dashboard (with respect to filtering and time selection)

Example: Our customers are often using a business metrics called Net Promoter Score, which is based on customer rating. 
The formula for calculation of NPS is really simple (and this calculation can be done is Solr):

> (nr_of_high_scores/nr_all_scores - nr_of_low_scores/nr_all_scores)*100

Having this on "customer reviews" dashboard would greatly improve its value, as it would be easy to explore, what was "NPS in our German Branch, in november, by customers from retail segment".

----
Is there any plan to introduce such feature in Hue?

Thanks!

**Comment by romainr** [comment]
The counter widget is going to support any formula (https://issues.cloudera.org/browse/HUE-3664)
And the pivot graph could even compute the NPS by categories (by customer by segment by ...)

That way we can have the NPS for the overall dashboard and its filter, and can visualize multiple NPS at the same times by categories.

I could see the need of adding a query facet on the counter widget for static report (KPI style) though. Those static report will come just after the analytics dynamic dashboards.

Does it make sense or I missed something? :)

**Comment by malejpavouk** [comment]
Sounds good :-). Thanks for a quick answer.
