### ISSUE TITLE
Unable to connect to JDBC DB that does not require a password

### ISSUE THREAD

**Issue by ChrisMcPherson** [cloudera/hue#599]
I am unable to connect to Presto DB from Hue. Presto does not require/allow a password property unless LDAP is configured and Hue will force the password property through the password prompt if one is not specified in the configuration. I would like the option to turn off the requirement for a password property (i.e. disable the password prompt) for JDBC connections in Hue.

**Comment by romainr** [comment]
We should probably tweak the logic around here for this: https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/jdbc.py#L74
