### ISSUE TITLE
I cant integrate hue with my cluster 

### ISSUE THREAD

**Issue by HelalHAH** [cloudera/hue#604]
i change every localhost in file hue.ini with ip of master machine in hadoop but it doent see users of other machines

**Comment by romainr** [comment]
Could you make sure that you are modifying the correct ini file?

cf. http://gethue.com/how-to-configure-hue-in-your-hadoop-cluster/

**Comment by HelalHAH** [comment]
@romainr thanks i changed hue.ini but I fiigure out that in Development version: desktop/conf/pseudo-distributed.ini i have to change this file
