### ISSUE TITLE
Changing language in Notebook results in aceSqlWorker loop

### ISSUE THREAD

**Issue by maziyarpanahi** [cloudera/hue#608]
Hello,

When I try to change the language inside the notebook it results aceSqlWorker.js loop that lasts over 10 seconds in browser. I have tested this in 3 different browsers (Chrome, Safari and Firefox).

Here is the screenshots after 10 seconds with over 2500 requests asking for aceSqlWorker.js from the server:

![image](https://user-images.githubusercontent.com/5762953/31825610-1b4bea48-b5b3-11e7-8280-acf160a8205a.png)

PS: I can easily create new language block from the wheel, it's just when I try to change the language on existing block that causes the loop.

I am using the latest Hue from the latest CDH (5.12.1)

Many thanks,
Maziyar

**Comment by maziyarpanahi** [comment]
Something else that might be useful in terms of environment and versioning. This happens in the Hue demo as well. To reproduce this problem:

1- Visit http://demo.gethue.com/hue/notebook
2- Create a block in any language (ex: Hive)
3- Try to change the language from the top left of the block to something else
4- You can see in the console-network the loop

![image](https://user-images.githubusercontent.com/5762953/31826089-6a1b9f32-b5b4-11e7-8a34-0c08da25e4f3.png)

![image](https://user-images.githubusercontent.com/5762953/31826092-6c8ae3f4-b5b4-11e7-9bff-80de14eb80e6.png)

**Comment by JohanAhlen** [comment]
Hi Maziyar,

Thanks for reporting this! It's not just the workers, it seems to be all the related resources. I'll take a look and hopefully I'll have a fix later today.

Cheers,
Johan

**Comment by JohanAhlen** [comment]
This should be fixed with: https://github.com/cloudera/hue/commit/1458daa660e797c491f99f555cce7c71ff01501e
