### ISSUE TITLE
hue  cant view or upload any  files 

### ISSUE THREAD

**Issue by HelalHAH** [cloudera/hue#609]
i install hue with my cluster 
when i upload file it gives me this error I found that  it send name of machines to host instead of ip of master so it does not upload any file 
![image](https://user-images.githubusercontent.com/14796568/31859217-e867990e-b708-11e7-8181-b12397ca97c0.png)

**Comment by romainr** [comment]
It should redirect to the Datanodes, please be sure that they are up
