### ISSUE TITLE
[Search] Question: Do Solr fields used in search need to be stored?

### ISSUE THREAD

**Issue by malejpavouk** [cloudera/hue#613]
Hi,

I am currently investigating how we can break our quite big monolithic Solr index&stored Core into multiple smaller cores maintained by individual microservices. 

The idea is that we will have index core, which would contain all the fields across the domain, but would have everything set **stored=false**. This will be maintained by our "Search team".

And then we will have multiple smaller services (possibly even not backed by solr) holding the data. These will be maintained by some other teams.

Would it be possible to still use the Search indexed only Core in Hue? Or will there be any limitations caused by the fact that data for the documents will not be available?

Thanks!

**Comment by romainr** [comment]
Shen stored=false, the content is not in the index, so you would need to build a link to the document as a field if you want to open it back. If you are doing just analytics and use facets mostly it should be less of a problem.

**Comment by malejpavouk** [comment]
I am interested just in the widgets - Timeline, piecharts, barcharts, couter and drilldown analytics. I am quite ok that I will have just a very limited info in result/html result grid.
