### ISSUE TITLE
Hue can't finish the query (hive on spark)

### ISSUE THREAD

**Issue by changhaike** [cloudera/hue#615]
Run the query using hive on spark in HUE.After the query's result has been already displayed on the dashboard,the application's status is still running, I have to kill the applicationID manually to release Hadoop cluster computing resource. How to close the application automatically.THX.

**Comment by romainr** [comment]
Which Hive do you use? IIRC there is a patch for HiveServer2 to fix this issue.

**Comment by changhaike** [comment]
Thanks for your replay.
we use Hive 1.1.0,CDH version is 5.12.1.
