### ISSUE TITLE
notebook Chinese input support

### ISSUE THREAD

**Issue by nodew** [cloudera/hue#616]
notebook editor doesn't support Chinese well.
ace editor support Chinese inputing indeed,  but notebook editor customize it with auto-completer，which may cause the question.
there is an example:
type `测试` in the input field with macOs's Chinese input method, then type space key, you get `ce shi`, type space key again, get `ce shi 测试`

**Comment by enricoberti** [comment]
hi! are you trying on master or 4.1? we have recently fixed that https://github.com/cloudera/hue/commit/fa110b7f0f6dd27c139ebde5451cdfeee073f67d

**Comment by nodew** [comment]
@enricoberti can hue run with java 9? Run `make apps`, but get error:
```
Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.0:enforce (default) on project hue-parent: Execution default of goal org.apache.maven.plugins:maven-enforcer-plugin:1.0:enforce failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-enforcer-plugin:1.0:enforce: java.lang.ExceptionInInitializerError: null
```

**Comment by enricoberti** [comment]
@nodew we haven't tested with Java 9 yet, let me have a look!

**Comment by enricoberti** [comment]
fixed in https://issues.cloudera.org/browse/HUE-7562
thanks!

**Comment by enricoberti** [comment]
https://github.com/cloudera/hue/commit/35511ae67bf3c8b6cd34811c39e5850e7dc2bd91
