### ISSUE TITLE
how to increase allocated memory for a hive job?

### ISSUE THREAD

**Issue by ysrotciv** [cloudera/hue#619]

**Comment by romainr** [comment]
I would recommend to look on the Hive list or https://www.google.com/search?q=how+to+increase+allocated+memory+for+a+hive+job&oq=how+to+increase+allocated+memory+for+a+hive+job&aqs=chrome..69i57j69i60j69i61.132j0j7&sourceid=chrome&ie=UTF-8 and then put the property as a query setting in the Editor ;)
