### ISSUE TITLE
should hue save queries in notebook

### ISSUE THREAD

**Issue by ChenjunZou** [cloudera/hue#620]
queries in hive editor is saved to DB， 
but queries run in notebook is not saved automatically, except touching save button. 
should hue save queries run in notebook?  
probably in type: query-hive, like attached below.

query saved in notebook
![image](https://user-images.githubusercontent.com/2654887/32544606-8975597a-c43e-11e7-8f6c-1d5d77e99dd9.png)

query saved in hive-editor
![image](https://user-images.githubusercontent.com/2654887/32544630-a4919444-c43e-11e7-9404-1359105b3c9d.png)

**Comment by romainr** [comment]
The notebook does not have any history by design
