### ISSUE TITLE
Hue Notebook caches username and password no matter when it's correct or not, next time will not prompt so user cannot login

### ISSUE THREAD

**Issue by liusztc09** [cloudera/hue#621]
We configure a couple of notebooks for mysql, postgres, oracle, presto using the notebook feature. In hue.ini we removed the username and password so it will prompt to the user when using it. However, only for the first time it asks for the uname/pswd, if the user put a wrong one by mistake, we're not able to do it again as next time it will not prompt.

Has anyone run into this issue, are they cached by the dbproxy?

**Comment by jdesjean** [comment]
This is a bug. It's currently being tracked by https://issues.cloudera.org/browse/HUE-7623
