### ISSUE TITLE
HUE Problems with filters in Job Browser

### ISSUE THREAD

**Issue by demydovb** [cloudera/hue#622]
i have some problems with filters in Job Browser.

For example, when i select all jobs in the last 1 day, i see, for example job id# 1000 and job id#1001, but when i change filter to select all jobs in the last 3 days I see no jobs.

Same behavior when i filter running jobs + last 1 day - All is OK, when i change to last 2..3....5...10...etc days nothing displays.

**Comment by jdesjean** [comment]
@demydovb I cannot reproduce this issue. Can you add a few screenshots that would show the issue?
