### ISSUE TITLE
Export csv in hue 4 via jdbc interface

### ISSUE THREAD

**Issue by rohit-nsit08** [cloudera/hue#623]
Hi,

I have configured presto with jdbc interface in hue4 and I am able to execute queries via UI but unable to download results. 
The jdbc connector show that the functionality is not yet implemented
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/jdbc.py#L122

**1. Any plans for adding this functionality? 
2. Any recommendations for any alternative approach for presto?
3. We are willing to contribute and add this functionality if needed. Can someone guide us in understanding the architecture and approach to follow?**

On searching online we found one commit in this context 
https://issues.cloudera.org/browse/HUE-3996

https://github.com/cloudera/hue/commit/8c1305193d790322e4160399beddeb120e1191c6 
but unfortunately it is only for rdbms interface

**Comment by romainr** [comment]
Yes, JDBC is not implemented yet 
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/jdbc.py#L122

But should be easy to add, basically re-execute the query like in https://github.com/cloudera/hue/commit/8c1305193d790322e4160399beddeb120e1191c6#diff-de769f3fe8c3973358b4318f4b17b8beR115
(as in JDBC AFAIK we can't start refetching the same query resultset, and Hue does not cache it currently https://issues.cloudera.org/browse/HUE-7618)

Would you like to have a stab at it?

**Comment by romainr** [comment]
Note: SQL Alchemy is also being investigated as it might provide more features that the current JDBC backend https://issues.cloudera.org/browse/HUE-7621

**Comment by cryptoe** [comment]
@romainr @rohit-nsit08   I actually solved this using the jdbc backend only.
In my case a simple reexecute is not possible as the queries are quite long.
So I am changing the query to insert into table. 
For eg: "select * from abc" was changed to "create table hive.presto_results.temp_table$timestamp as select * from abc".
I am saving this variable into the snippet as a field.

On result fetch , I first check if this variable is set. If yes , I was running a select * from hive.presto_results.temp_table$timestamp limit xxx  and then returning the result to the user.


I can actually contribute it back if you guys are still interested.

**Comment by rentaow** [comment]
Is there still plans to work on this? In jdbc.py is there any way to refetch the previous query resultset for download or do we still need to re-execute query?

**Comment by jdesjean** [comment]
Hi Rentao,

We would have to refetch. I can add what was added for sqlalchemy.

Cheers,
Jean-Francois

**Comment by romainr** [comment]
One current work in progress is https://issues.cloudera.org/browse/HUE-8738 which executes the query in a worker and caches the results

https://github.com/cloudera/hue/blob/master/docs/ROADMAP.md

**Comment by rentaow** [comment]
I have an implementation working, but I'm wondering if there's any concern with just caching the result from the execute method in a global variable and reusing it in the download method? I guess if there are multiple users using the jdbc connector, the download could give wrong results?

**Comment by rentaow** [comment]
So with [HUE-8738](https://issues.cloudera.org/browse/HUE-8738), the implementation for the download will probably be different but until then, I've open a PR https://github.com/cloudera/hue/pull/832 to allow jdbc downloads if it looks okay to you guys.
