### ISSUE TITLE
How to make yarn allocate resource depend on the number of mappers and reducers?

### ISSUE THREAD

**Issue by ysrotciv** [cloudera/hue#624]
All of my hive workflows always be allocated 2 containers, how can I make it allocated dynamically depend on the number of mappers and reducers?

**Comment by romainr** [comment]
What do you mean exactly?

1 job will be from Oozie, which will submit the query to HiveServer2 which will send spawn 1 or more jobs.

**Comment by ysrotciv** [comment]
There is a hive query in workflow spend almost 10 hours every day. But it only takes several minutes if I run it in hive editor.

**Comment by ysrotciv** [comment]
`drop table if exists tmp.mpjs_ab_test_layer_data_mid;

create table tmp.mpjs_ab_test_layer_data_mid as
select appname, eventid, play_duration, use_time, parameters, custom_functions.set_difference(all_layer.layer_ids, temp.layer_ids) as layer_ids
  from (select appname, layer_ids, eventid, play_duration, use_time, parameters
          from dwd_logs.dwd_mpjs_log
         where dt='${dt}'
       ) temp
       left join tmp.mpjs_ab_test_all_layer as all_layer;`
This hql will be splitted to 248 mappers and 0 reducers if I execute it in hue editor.
But it will be splitted to 249 mappers and 1 reducers in the workflow.
Why there is one more mapper and reducer?
