### ISSUE TITLE
why do not you provide pre-built hue?

### ISSUE THREAD

**Issue by dahaian** [cloudera/hue#626]
I want to know why do not you provide pre-built hue?I built the hue with some errors.I build failed all the time.

**Comment by romainr** [comment]
Tarball releases are a little bit easier to compile http://gethue.com/hue-4-1-is-out/, if not have a look at the CDH package or CM cf. gethue.com or https://www.cloudera.com/documentation/enterprise/latest/topics/cdh_ig_cdh_hue_configure.html
