### ISSUE TITLE
HUE Problems with logs in Job Browser

### ISSUE THREAD

**Issue by dahaian** [cloudera/hue#627]
Look at the picture:
![tim 20171122111151](https://user-images.githubusercontent.com/9957813/33108232-36f54e7e-cf76-11e7-812c-2767716fc42e.png)
I click the logs .Then I got the error:
![tim 20171122111221](https://user-images.githubusercontent.com/9957813/33108376-c7511ebc-cf76-11e7-8d88-ad61825e6082.png)
The logs url is incorrect.I want to know how config logs url?
I got the correct logs url for this:
![tim 20171122112858](https://user-images.githubusercontent.com/9957813/33108672-61004bae-cf78-11e7-9cf1-3839fbc85c76.png)
![tim 20171122112512](https://user-images.githubusercontent.com/9957813/33108579-f1600ca8-cf77-11e7-89fe-57673682c2ca.png)
And My hue.ini is
![tim 20171122111724](https://user-images.githubusercontent.com/9957813/33108398-da2dff82-cf76-11e7-806d-a17ac3cdd795.png)

Any help is appreciated!

**Comment by romainr** [comment]
This is https://issues.cloudera.org/browse/HUE-7258

**Comment by dahaian** [comment]
@romainr Hi,I could not find methods for solving the issues.Can you give me a link for solving the issues?Thanks.

**Comment by dahaian** [comment]
@jdesjean  Can you help me solving the issues?Any help is appreciated.

**Comment by jdesjean** [comment]
@dahaian I believe Hue-7258 will resolve the issue. Somebody is looking into it.

**Comment by burandobata** [comment]
Looks like the issue with logs is fixed in 4.2. But url and killUrl are suffering from something similar:
![screen shot 2018-10-01 at 5 12 18 pm](https://user-images.githubusercontent.com/34664543/46297682-8fecd380-c59d-11e8-853c-0dc2164715e1.png)

**Comment by wing2fly** [comment]
https://issues.cloudera.org/browse/HUE-8558 should fix this issue. It will remove outdated url/killUrl and add trackingUrl, which will open the job in Spark history server in a new browser tab.
