### ISSUE TITLE
make apps  error

### ISSUE THREAD

**Issue by LPink777** [cloudera/hue#636]
[ERROR] Plugin org.apache.maven.plugins:maven-enforcer-plugin:1.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-enforcer-plugin:jar:1.0: Could not transfer artifact org.apache.maven.plugins:maven-enforcer-plugin:pom:1.0 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
make: *** [parent-pom] 错误 1

how do i fix it?
why does this happen？

**Comment by romainr** [comment]
could have been a problem with maven server. Is it still happening?

**Comment by LPink777** [comment]
@romainr It has been happening..

my maven version:
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T15:58:13+08:00)
Maven home: /opt/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-31-generic", arch: "amd64", family: "unix"

jdk:
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

i don't know why it happened. Is the configuretion of the problem?

**Comment by romainr** [comment]
It means you cannot connect to https://repo.maven.apache.org/maven2

**Comment by simonprewo** [comment]
@romainr @LPink777 I got the same problem...

**Comment by simonprewo** [comment]
Okay. Got it working: There seemed to a general issue with OpenJDK-Truststore. Solved it by downloading Oracle Java and replacing **/etc/ssl/certs/java/cacerts** by **/jdk-10.0.2/lib/security/cacerts**.
