### ISSUE TITLE
make apps Error

### ISSUE THREAD

**Issue by Smallcaff** [cloudera/hue#640]
I copied the 'hue' compiled by others, and put it in the same path.
when runs 'make apps' ,i get the probelm as follow:

```
/bin/bash: /storage/hue/hue-4.0.0/build/env/bin/python2.7: cannot execute binary file
--- Installing  into virtual-env
/bin/bash: /storage/hue/hue-4.0.0/build/env/bin/python2.7: cannot execute binary file
make[2]: *** [env-install] Error 126
make[1]: *** [.recursive-env-install/core] Error 2
make: *** [desktop] Error 2
```

**Comment by romainr** [comment]
Same operating system? (seems like you don't have the same Python 2.7)

**Comment by Smallcaff** [comment]
Thanks for the reply.
My system is Mac,and the other is centos.
Should I run 'make apps' in the same system?

**Comment by romainr** [comment]
Yes
