### ISSUE TITLE
'UnspecifiedConfigSection' object has no attribute 'get'

### ISSUE THREAD

**Issue by snxq1995** [cloudera/hue#641]
File "/hue/desktop/libs/notebook/src/notebook/conf.py", line 52, in get_ordered_interpreters
    if not INTERPRETERS.get():
AttributeError: 'UnspecifiedConfigSection' object has no attribute 'get'

**Comment by snxq1995** [comment]
>>> dir(INTERPRETERS)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_coerce_type', 'bind', 'default', 'default_value', 'dynamic_default', 'each', 'get_member', 'get_presentable_help_text', 'get_presentable_key', 'get_value', 'help', 'key', 'print_help', 'private', 'required', 'type', 'validate']


I check this class. It has no attribute 'get'.So how to solve this?

**Comment by romainr** [comment]
Which apps do you have in app_blacklist in hue.ini?

**Comment by snxq1995** [comment]
Actually, I copied the notebook module as a new app.Trying to keep notebook,And modify this new app.
Then,I have this problem.

I guess probably because there is no new app information configured in hue.ini, resulting in the app is not registered.

PS. setup.py has been modified.

**Comment by snxq1995** [comment]
I tracked the program by pdb.

```
(Pdb) for i in pkg_resources.iter_entry_points('desktop.sdk.application'):print(i)   
about = about
beeswax = beeswax
filebrowser = filebrowser
hbase = hbase
help = help
impala = impala
jobbrowser = jobbrowser
jobsub = jobsub
metastore = metastore
oozie = oozie
pig = pig
proxy = proxy
rdbms = rdbms
search = search
security = security
spark = spark
sqoop = sqoop
useradmin = useradmin
zookeeper = zookeeper
indexer = indexer
metadata = metadata
notebook = notebook
dashboard = dashboard
notebook = notebook
notebook = notebook
notebook = notebook
notebook = notebook

```
