### ISSUE TITLE
Import/Export: Problem installing fixture '/tmp/tmpxPRtQC.json': Document2 matching query does not exist

### ISSUE THREAD

**Issue by curious-odd-man** [cloudera/hue#648]
## Short description:
Import/Export updated Oozie workflow ends with an error: Problem installing fixture 
 /tmp/tmpxPRtQC.json': Document2 matching query does not exist.

## Hue version:
4.0 on CDH 5.12.0

## **Steps to reproduce:**

Assume there are 2 users: **User1** and **User2**

1. As **User1** - create workflow with single shell action (name it _child_)

1. As **User1** - create workflow with single sub-workflow _child_ (name it _parent_)

1. As **User1** - export workflow _parent_ to json file (using UI)

1. As **User2** - import json file from previous step

1. As **User1** - create workflow with single shell action (name it _child2_)

1. As **User1** - update _parent_: add new sub workflow _child2_

1. As **User1** - export workflow _parent_ to json file (using UI)

1. As **User2** - try import json file from previous step - you should see the error: Problem installing fixture 
 /tmp/tmpxPRtQC.json': Document2 matching query does not exist.

**Comment by guanweikai** [comment]
I also encountered this problem. What should I do?
