### ISSUE TITLE
[HUE] SSO Authentication with AWS Cognito

### ISSUE THREAD

**Issue by churrops** [cloudera/hue#651]
Hi Guys!

I am using AWS EMR for BigData Processing and I need to integrate HUE with SSO Authentication (SAML) and I would like to use AWS Cognito with Identity Provider. Any idea? In the config file "hue.ini" for exemple  I don't see any information for this. Is it possibile?

Thanks!

**Comment by colintoal** [comment]
I don't think Cognito is intended to be a provider for access to EMR. It's more meant as an identity pool for your own mobile or web based applications.

If you are deploying EMR to be used by a team, you will probably want something like Amazon Simple Directory and EMR's Kerberos support. Hue integrates well with Kerberos/LDAP based authentication pools.
