### ISSUE TITLE
Hive Issue

### ISSUE THREAD

**Issue by dmpappa** [cloudera/hue#652]
I'm testing Hive with Cloudera VM. Create a test table but when I want to browse the data it gives me this error.

"### { "traceback": [ [ "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/handlers/base.py", 112, "get_response", "response = wrapped_callback(request, *callback_args, **callback_kwargs)" ], [ "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/transaction.py", 371, "inner", "return func(*args, **kwargs)" ], [ "/usr/lib/hue/desktop/libs/notebook/src/notebook/views.py", 150, "browse", "return JsonResponse(notebook.execute(request, batch=False))" ], [ "/usr/lib/hue/desktop/libs/notebook/src/notebook/connectors/base.py", 191, "execute", "return _execute_notebook(request, notebook_data, snippet)" ], [ "/usr/lib/hue/desktop/libs/notebook/src/notebook/api.py", 146, "_execute_notebook", "raise ex" ] ] }"

someone has an idea what to do

Thanks.

**Comment by romainr** [comment]
Would need the full Hue logs to debug more and a screenshot of the /hue/about/ page
