### ISSUE TITLE
Is there any pre-built version for offline installation?

### ISSUE THREAD

**Issue by darouwan** [cloudera/hue#654]
I am trying to compile the hue without CDH on a no internet access environment. However the compiling process need to download some python libs like ciff, thus it throws out a connection error.

So any pre built version of hue can be provided?

**Comment by romainr** [comment]
You could try the CDH hue packages https://www.cloudera.com/documentation/enterprise/latest/topics/cm_ig_install_path_b.html#cmig_topic_6_6

**Comment by darouwan** [comment]
@romainr Thanks
While I want to use hue independent of CDH, can I extract the hue package from the cdh parcel?

**Comment by romainr** [comment]
This should work too, just make sure to use the same os
