### ISSUE TITLE
SpnegoDjangoBackend does not respect hadoop.security.auth_to_local

### ISSUE THREAD

**Issue by parnigot** [cloudera/hue#657]
I've configured Hue (CDH 5.12.1) to use `desktop.auth.backend.SpnegoDjangoBackend`: the authentication by itself works well, but I'm having issues with authorization to HDFS/Hive/Impala & c.

My user principal name is `parnigot@COMPANY.COM` and I've configured HDFS and all other hadoop services to map my principal to `parnigot@company.com`, via `hadoop.security.auth_to_local` in `core-site.xml` (see this [cloudera guide](https://www.cloudera.com/documentation/enterprise/5-14-x/topics/cdh_sg_kerbprin_to_sn.html)).

`SpnegoDjangoBackend` does not respect these rules, using the example above:

1. I login to my work PC as `parnigot@COMPANY.COM`
2. I open Hue in my browser, no password asked I'm automatically logged in as `parnigot`
3. Hue proxies my queries to the hadoop services as user `parnigot`, but all these services know me as `parnigot@company.com` so everything fails with authorization exception (no hdfs permission, no sentry roles)

Correct me if I'm wrong, but [here](https://github.com/cloudera/hue/blob/1559c5239cbfdde31947a6c683c2feac079d2754/desktop/core/src/desktop/auth/backend.py#L535) it always strips the realm section from the username. In my opinion Hue should respect the `auth_to_local` rules, they are standard in all other hadoop services...

**Comment by romainr** [comment]
SpnegoDjangoBackend is between your browser and the Hue server. Between Hue and the other services, the auth is with kerberos as the hue user, your username will be proxied as Hue acts as a proxy user. This means you only need to make sure Hue's has a correct ticket and hue is added to the list of hadoop proxy users in core-site.xml

**Comment by parnigot** [comment]
Hi Romain, thanks for the response.

I think I've understood correctly how the proxy user mechanism works: the issue is about Hue using the wrong target user (its behaviour is not consistent with the other tools of the ecosystem).

Continuing with the example above. If I login as `parnigot@COMPANY.COM` on a cluster node and I use all the command line tools (hdfs client, beeline, impala-shell) the `hadoop.security.auth_to_local` maps my username to `parnigot@company.com` and hdfs and all other services know me by that name.

Instead if I login to Hue with the `SpnegoDjangoBackend` I'm logged simply as `parnigot` and that is the username forwarded to the cluster services. And since the username `parnigot` is different from `parnigot@company.com` I'm not authorized to view my resources.

This was a common issue with other services in the past, for example Impala had the same problem fixed by [IMPALA-2660](https://issues.apache.org/jira/browse/IMPALA-2660).
