### ISSUE TITLE
"Document does not exist or you don't have the permission to access it."

### ISSUE THREAD

**Issue by 139634zgc** [cloudera/hue#659]
there is an error:
"Document does not exist or you don't have the permission to access it."

This error was shown to me when I want to edit other's oozie workflow. It is noteworthy that I have the permission to rerun or kill other's workflow job.
![6aaa4549155e1fa5f7b332a659406a90](https://user-images.githubusercontent.com/20762775/35851204-39d6909e-0b62-11e8-9dfb-3c81c458fda1.jpg)

**Comment by zhaoguanchen** [comment]
> I'm also encountered the same problem. how to fix it？

应该是权限问题，这句报错在desktop/core/src/desktop/models.py中，can_read_or_exception(self, user)，can_write_or_exception(self, user)两个函数
