### ISSUE TITLE
make apps error: can't copy 'pyasn1/compat/octets.py': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by yezhwi** [cloudera/hue#662]
Ubuntu:
sudo apt-get install git ant gcc g++ libffi-dev libkrb5-dev libmysqlclient-dev libsasl2-dev libsasl2-modules-gssapi-mit libsqlite3-dev libssl-dev libxml2-dev libxslt-dev make maven libldap2-dev python-dev python-setuptools libgmp3-dev

pwd:
/usr/local/hue-release-4.1.0

make apps

error:
make[1]: 正在进入目录 `/usr/local/hue-release-4.1.0/desktop'
make -C core env-install
make[2]: 正在进入目录 `/usr/local/hue-release-4.1.0/desktop/core'
--- Building egg for pyasn1-0.1.8
running bdist_egg
running egg_info
writing pyasn1.egg-info/PKG-INFO
writing top-level names to pyasn1.egg-info/top_level.txt
writing dependency_links to pyasn1.egg-info/dependency_links.txt
reading manifest file 'pyasn1.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyasn1.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
error: can't copy 'pyasn1/compat/octets.py': doesn't exist or not a regular file
make[2]: *** [/usr/local/hue-release-4.1.0/desktop/core/build/pyasn1-0.1.8/egg.stamp] 错误 1
make[2]:正在离开目录 `/usr/local/hue-release-4.1.0/desktop/core'
make[1]: *** [.recursive-env-install/core] 错误 2
make[1]:正在离开目录 `/usr/local/hue-release-4.1.0/desktop'
make: *** [desktop] 错误 2

how do i fix it?

**Comment by prayjourney** [comment]
你怎么解决的,我也遇到了同样的问题
