### ISSUE TITLE
error in hue build 

### ISSUE THREAD

**Issue by amin1994** [cloudera/hue#678]
Hi if you could help me please with this issue : 

Download error on https://pypi.infra.cloudera.com/api/pypi/pypi-public/simple/logilab-astng/: [Errno -2] Name or service not known -- Some packages may not be found!
Download error on https://pypi.infra.cloudera.com/api/pypi/pypi-public/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or download links found for logilab-astng>=0.24.3
error: Could not find suitable distribution for Requirement.parse('logilab-astng>=0.24.3')
/home/hduser/hue/desktop/devtools.mk:34: recipe for target 'pylint[0.28.0]' failed
make[2]: *** [pylint[0.28.0]] Error 1
make[2]: Leaving directory '/home/hduser/hue/desktop'
/home/hduser/hue/desktop/devtools.mk:42: recipe for target '/home/hduser/hue/build/.devtools' failed
make[1]: *** [/home/hduser/hue/build/.devtools] Error 2
make[1]: Leaving directory '/home/hduser/hue/desktop'
Makefile:148: recipe for target 'desktop' failed
make: *** [desktop] Error 2

ubuntu 16.04 

thank you !

**Comment by amin1994** [comment]
unfortunately problem still remains.

**Comment by romainr** [comment]
./build/env/bin/pip install logilab-astng

indeed probably
