### ISSUE TITLE
Error when make install

### ISSUE THREAD

**Issue by baunvb** [cloudera/hue#680]
I try to build with "PREFIX=/usr/myfolder make install", but have error:
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
error: command 'gcc' failed with exit status 1
Can you help me? Thank all

**Comment by romainr** [comment]
Which OS is it?
Did you add all the dependencies? http://cloudera.github.io/hue/latest/admin-manual/manual.html#dependencie
