### ISSUE TITLE
hbase api error :timed out

### ISSUE THREAD

**Issue by amin1994** [cloudera/hue#682]
HI could you help me to fix this erorr?
hue could not connect to hbase and send this error: api error:timed out
ubuntu 16.04
hue 4.2.0
hbase 1.2.6

thank you!

**Comment by geyingauv** [comment]
same problem but hbase 2.0

can you fixed it ?

**Comment by amin1994** [comment]
not yet.

**Comment by beenryuu** [comment]
try this
https://github.com/cloudera/hue/issues/702
