### ISSUE TITLE
make apps error : "typedef redefinition with different types" at clang

### ISSUE THREAD

**Issue by shwldus3** [cloudera/hue#684]
macOS Sierra (10.12.6)

[ERROR]
building '_openssl' extension
/usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/opt/openssl/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c build/temp.macosx-10.6-intel-2.7/_openssl.c -o build/temp.macosx-10.6-intel-2.7/build/temp.macosx-10.6-intel-2.7/_openssl.o
build/temp.macosx-10.6-intel-2.7/_openssl.c:2508:14: error: typedef redefinition with different types ('void' vs 'struct comp_method_st')
typedef void COMP_METHOD;
             ^
/usr/local/opt/openssl/include/openssl/ossl_typ.h:181:31: note: previous definition is here
typedef struct comp_method_st COMP_METHOD;
                              ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
make[2]: *** [/Users/chloenoh/Workspace/hue/desktop/core/build/cryptography-1.3.1/egg.stamp] Error 1
make[1]: *** [.recursive-env-install/core] Error 2
make: *** [desktop] Error 2

how do i fix it?
why does this happen?

**Comment by jiayihoffman** [comment]
I ran into the same problem, and waiting for a solution.

**Comment by shwldus3** [comment]
Python and openssl version is 
– Python 2.7.10
– openssl 1.0.2 (version of /usr/local/opt/openssl)

**Comment by felipepodolan** [comment]
Same error here.

**Comment by deewilcox** [comment]
I am having the same error, but with Python 3.6. @shwldus3 Were you able to resolve this issue?

**Comment by jdesjean** [comment]
Can you confirmed that you've done step 3b from http://gethue.com/start-developing-hue-on-a-mac-in-a-few-minutes/ ?

Step 3b (just for El Capitan and Sierra): export ENV variables for openssl
If you have OS X El Capitan or macOS Sierra, you need an extra mini step to be able to make Hue:
export LDFLAGS=-L/usr/local/opt/openssl/lib && export CPPFLAGS=-I/usr/local/opt/openssl/include
