### ISSUE TITLE
create table button in hive is not working in HUE3 ui

### ISSUE THREAD

**Issue by selios2000** [cloudera/hue#686]
Page not found (404)
Request Method: | GET
http://localhost:8888/indexer/importer/prefill/all/table/mytable/?sourceType=hive

in HUE4 ui, it works but when i changed HUE 3 UI
this button isn't work

**Comment by romainr** [comment]
Why do you still need to use Hue 3 UI?

**Comment by romainr** [comment]
Hue 3 UI is not actively supported so we would recommend to move to Hue 4 and describe why Hue 4 would be missing some Hue 3 functionalities
