### ISSUE TITLE
Feature: editor content read from url

### ISSUE THREAD

**Issue by lubomirmatus** [cloudera/hue#694]
I would like to propose new feature for query/text editor.

Now the Impala query editor can be opened by url `https://<host>/hue/editor/?type=impala`. It would be fine to be able also put text content for editor into url.

E.g.: `https://<host>/hue/editor/?type=impala&text=<encoded-text>`.
The text content can be compacted and encoded for example as base64url(lzstring(text)). This method is used in `imply` project (sql editor part) - the web ui for druid database.

Also add "direct link" button/text-box somewhere into editor, so the user can copy link with included text content of editor and use it externally (send by email to someone, ...).

Example: We use Impala database as backend and Hue. We have some internal tools / webapps that uses Impala, and some of them points their links to Hue Impala SQL editor. Now we are only able to put query text into clipboard, open the empty editor by url, and then let user paste text from clipboard into editor.
It would be fine to put the query text directly into url, so the editor will open with given text content.

**Comment by gfarcas** [comment]
The feature would be greatly appreciated
