### ISSUE TITLE
Want to use hue in iFrame of another website

### ISSUE THREAD

**Issue by zhaozhouyang** [cloudera/hue#698]
We deploy a hue and update the x-frame header, which can successfully load hue in iframe;
But then the web parent window jump to hue link, how can I prevent this event, where should I edit this logic?

Thank you so much

**Comment by romainr** [comment]
Curious, why would you put Hue in an iframe?

https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L183 might help

**Comment by enricoberti** [comment]
@zhaozhouyang you should also disable the clickjacking code here: https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/templates/common_header_footer_components.mako#L112

**Comment by zwbill82** [comment]
@zhaozhouyang  最后是什么样解决的？

**Comment by DesignHhuang** [comment]
> @zhaozhouyang 最后是什么样解决的？

上面不是写了么，还问。。。

**Comment by domino-alee** [comment]
@enricoberti sorry to bump this old thread but can you advise on where to look? think the files have changed in past 2 years. i'm trying to embed hue via iframe but it randomly refreshes the page and jumps to hue URL after initial load
