### ISSUE TITLE
Unable to access S3 from Hue

### ISSUE THREAD

**Issue by asvanand** [cloudera/hue#699]
Hi,

When I try to access S3 from Hue, I get below error:

`Failed to access path: "s3a://<path>" Check that you have access to read this bucket and that the region is correct: Bad Request.`

I have full access to the data if I access it directly in S3. I reckon this happens when I try to access through Hue. Do I need to make any changes in AWS security groups for Hue?

Thanks.

**Comment by jdesjean** [comment]
Hue displays buckets from all regions, but you can only access buckets to the region you are connected with. Can you confirm that the bucket was created within your region?
Can you create a new bucket and access it?
