### ISSUE TITLE
What to specify in hbase_conf_dir when hue is on different server than hbase?

### ISSUE THREAD

**Issue by metamaker** [cloudera/hue#701]
How to properly connect Hue with HBase when they are located on different hosts? I see that I need to specify hbase_conf_dir (http://gethue.com/hbase-browsing-with-doas-impersonation-and-kerberos/) that leads to hbase-site.xml config file on local FS, but obviously since both applications are located on different hosts in cluster, I can't do this. What I can do is to copy paste hbase-site.xml to Hue host machine, but this is mess - there must be one and only one source of trust to reduce complexity of configuration, especially in multiserver setups.

**Comment by romainr** [comment]
It needs to be on the Hue hosts indeed. Currently, people using Cloudera Manager or their own Unix admin tooling get this Hadoop client files automatically pushed to all the hosts

**Comment by metamaker** [comment]
@romainr Thanks for reply and explanation! Ok, this will work out, but I thought there is more elegant solution. I was experimenting with Hue in docker while HBase was in other docker container, so this configuration option immediately disturbed me :)

Not sure where I can leave feedback on project, but I really love what you have done guys. Though in some things it can be improved, still this GUI is one of the best that I saw for ad-hoc querying in Hadoop setup. Thank you for your effort!

**Comment by romainr** [comment]
Thanks, and there is no master config server to pull the configuration of all the service, hence the Hadoop client configf files to sync on all the cluster.

Feel free to send any other feedback ;)
