### ISSUE TITLE
Can't get Hue running with HBase Thrift without API authentication

### ISSUE THREAD

**Issue by metamaker** [cloudera/hue#702]
I tried running it and got stuck. The thing is that I have disabled authentication for HBase Thrift, and I have no problem running HBase commands via Thrift API by using `happybase` Python package. 

However, Hue displays error "API: Timeout error", and I am not sure what is the reason behind it.

```
hue_1    | 172.18.0.1 - - [29/May/2018 06:15:48] "POST /hbase/api/getClusters HTTP/1.1" 200 -
hue_1    | 172.18.0.1 - - [29/May/2018 06:16:18] "POST /hbase/api/getTableList/Cluster HTTP/1.1" 500
```

Stack trace for failed request
```
/hue/apps/hbase/src/hbase/api.py, getTableList, Line 141:
return [{'name': name, 'enabled': client.isTableEnabled(name, doas=self.user.username)} for name in client.getTableNames(doas=self.user.username)]

/hue/desktop/core/src/desktop/lib/thrift_util.py, wrapper, Line 386:
raise StructuredException('THRIFTSOCKET', str(e), data=None, error_code=502)
```

**hbase-site.xml**
```
<configuration>

  <property>
     <name>hbase.zookeeper.quorum</name>
     <value>hbase</value>
  </property>
  <property>
    <name>hbase.rootdir</name>
    <value>file:////data/hbase</value>
  </property>

  <property>
    <name>hbase.master.info.bindAddress</name>
    <value>hbase</value>
  </property>

  <property>
    <name>hbase.regionserver.info.bindAddress</name>
    <value>hbase</value>
  </property>
</configuration>
```

http://localhost:9095/thrift.jsp is showing information that API is up and running.

HBase Version | 1.2.4
Thrift 1.x

**hue.ini** is same as in https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini
except that I have next config for Hbase

```
[hbase]
  # Comma-separated list of HBase Thrift servers for clusters in the format of '(name|host:port)'.
  # Use full hostname with security.
  # If using Kerberos we assume GSSAPI SASL, not PLAIN.
  hbase_clusters=(Cluster|hbase:9090)

  # HBase configuration directory, where hbase-site.xml is located.
  hbase_conf_dir=/hue/desktop/conf/

  # Hard limit of rows or columns per row fetched before truncating.
  ## truncate_limit = 500

  # 'framed' is used to chunk up responses, which is useful when used in conjunction with the nonblocking server in Thrift.
  # 'buffered' used to be the default of the HBase Thrift Server.
  ## thrift_transport=framed
 # use_doas=true
```

Is it possible to run Hue HBase Browser without Kerberos?

**Comment by julioasotodv** [comment]
Hitting the exact same problem after upgrading CDH. It used to work just fine :(

**Comment by clairvoyant-rohit** [comment]
We are having same issue. Is there any workaround or solution for this ? 
After upgrading CDH to 5.15 , Hue HBASE doesn't work.

**Comment by q3ccn** [comment]
There is something wrong with thrift server. REST server works fine.

**Comment by buendiya** [comment]
Thrift server works fine. I can get table names using happybase.

**Comment by buendiya** [comment]
The hbase THRIFT_TRANSPORT is "framed" in the latest version hue which correspond to TNonblockingServer. But the default hbase thrift server is TThreadPoolServer, THRIFT_TRANSPORT should be "buffered".
After change THRIFT_TRANSPORT to "buffered" in /opt/cloudera/parcels/CDH/lib/hue/apps/hbase/src/hbase, it works.
Or maybe you can change the hbase thrift server to TNonblockingServer in cloudera hbase configration.

**Comment by zenppl** [comment]
I changed the hbase thrift server to TNonblockingServer , it works!

**Comment by peter279k** [comment]
I have the same issue, too. When I set the `thrift_transport=buffered` in the `desktop/conf/pseudo-distributed.ini` file, it worked fine for me. Thank you, @buendiya.

I appreciate your help.

**Comment by terrancesnyder** [comment]
This worked for me as well, thanks! thrift_transport=buffered in hue.ini

**Comment by zhoubh** [comment]
cdh5.15 
After change THRIFT_TRANSPORT to "buffered" in /opt/cloudera/parcels/CDH/lib/hue/apps/hbase/src/hbase/conf.py, it works!

**Comment by romainr** [comment]
FYI: this will be fixed with https://review.cloudera.org/r/13444/ by @cmconner156
