### ISSUE TITLE
Field names are preceded by comma when preceded by a struct field

### ISSUE THREAD

**Issue by BasPH** [cloudera/hue#703]
Currently running EMR 5.13 with Hue 4.1.0. When I create a table with the following structure:
```
CREATE TABLE test (
    f1 struct<f1:struct<f1:string>,f2:string>
)
```

The field `f2` is shown with a leading comma:
![image](https://user-images.githubusercontent.com/6249654/40666146-55fa2920-635f-11e8-8e56-e29cb69a617d.png)

This only happens within a struct.

**Comment by romainr** [comment]
Sounds like https://issues.cloudera.org/browse/HUE-7563, fixed in 4.2
