### ISSUE TITLE
disable debug logging django_debug_mode

### ISSUE THREAD

**Issue by bgajjela** [cloudera/hue#706]
Hello ,

Do you know how to disable DEBUG Logging for django_debug_mode in hue.ini? 

What would be the default value for django_debug_mode ?

Thanks,
Bharath

**Comment by jdesjean** [comment]
Hi Bharath,

Default value for django_debug_mode is true.

Cheers,
Jean-Francois

**Comment by bgajjela** [comment]
Hello  @jdesjean , 

Thanks for the quick response. So in order to disable  "django_debug_mode=false" will do the job ?

Thanks,
Bharath

**Comment by jdesjean** [comment]
Correct.

**Comment by bgajjela** [comment]
django_debug_mode=false will be tested . But closing this for now
