### ISSUE TITLE
Max Range of columns , Hue can handle to sample

### ISSUE THREAD

**Issue by bgajjela** [cloudera/hue#707]
Hello,

Let's say if i have 1000 columns for a table and run a simple query like below in hue it doesn't return any results like 10 records at least.

select *
from  databasename.tablename
limit 10 ; 

We running 3.12 Hue.

Thanks,
Bharath

**Comment by romainr** [comment]
3.12 is extremely old, 4.2 is the latest release and contains a lot of perf improvements on the grid result.
Also, it is difficult to visually visualize 1000+ columns, so most of the time people select only a subset
