### ISSUE TITLE
Using keycloak with oidc

### ISSUE THREAD

**Issue by xixikaikai** [cloudera/hue#716]
By using the latest codes in master branch of hue,
I can use keycloak with hue, but now, the username is not returned by hue, pls fix!

![image](https://user-images.githubusercontent.com/10403433/41766042-789fb148-7638-11e8-8fbb-e10698159cb6.png)

**Comment by xixikaikai** [comment]
@wing2fly

**Comment by wing2fly** [comment]
@xixikaikai please try with this commit: https://github.com/cloudera/hue/commit/84475b6717243cb07e8755c456930e7a01983214. You probably need to delete this one and login again. New user should be created with its preferred_username from the claim.

**Comment by wing2fly** [comment]
@xixikaikai I am closing this issue. You can reopen if you still have problem.

**Comment by xixikaikai** [comment]
What database in HUE are you using?
I used embedded sqlite which seems not worked and throws "database locked"

--------------------------------

郑  恺

**Comment by xixikaikai** [comment]
Login function is ok but now shows database locked

--------------------------------

郑  恺

**Comment by jdesjean** [comment]
It's best to use mysql, postgreSQL or Oracle. The embedded sqlite shows "database locked" from time to time.

**Comment by xixikaikai** [comment]
I've already changed my HUE to use mysql, LGTM now. Thanks a lot.

**Comment by xixikaikai** [comment]
@jdesjean But still, I do not know why the issue "database locked" happen? Do you know it?

**Comment by wing2fly** [comment]
@xixikaikai, I think you ran into the concurrency issue similar to this: https://community.cloudera.com/t5/Web-UI-Hue-Beeswax/DatabaseError-database-is-locked/td-p/14070

**Comment by xixikaikai** [comment]
@wing2fly  Thanks a lot. I think this make sense to me
