### ISSUE TITLE
Updated to latest version of master yesterday 20180704, the hue is not logout when some other plaece logout

### ISSUE THREAD

**Issue by xixikaikai** [cloudera/hue#719]

**Comment by xixikaikai** [comment]
As topic shown,
I logout in another place using keycloak(oidc)
but hue is not logged out, and the session is still useful.

Question?
Will hue detect the login state of oidc?

@wing2fly

**Comment by wing2fly** [comment]
There is a limitation on the oidc library I am using, so Hue can't detect the login state from OP. I will explore this feature later.
Does your another place (I assume it's an app) support Single-Sign out? If possible, can you share the app name?

**Comment by xixikaikai** [comment]
I've noticed that you are using the lib "mozilla_django_oidc.auth" right?
Sorry, I have not used any other lib, but I will try to use one to write a simple oidc web site for test later. I'll tell you if I have any finds.

**Comment by xixikaikai** [comment]
Also I've found that if I quit a user in another app, and login as another user, then I access HUE, HUE will not opening but recursive requesting... Maybe HUE does not know which user it will adopt? The old logged user from cookie, or the new one just logged on?
I do not know since I've not check the recursive source codes from now.

**Comment by xixikaikai** [comment]
If this bug occurs, I already just resolve by cleaning the cookie, and re-login.

**Comment by romainr** [comment]
Closing cf. above comment, feel free to re-open is issues
