### ISSUE TITLE
Using oidc login to hue, and here comes some bugs page

### ISSUE THREAD

**Issue by xixikaikai** [cloudera/hue#723]
![image](https://user-images.githubusercontent.com/10403433/42441887-cc8ce288-839b-11e8-9a90-83cc91756a23.png)

As the screen shot shown, it throws an error 
AttributeError: 'WSGIRequest' object has no attribute 'fs'

Does anyone else happen to notice this image?

**Comment by wing2fly** [comment]
@xixikaikai, I have found this bug and fix very soon.

**Comment by wing2fly** [comment]
@xixikaikai, yes you can see it https://github.com/cloudera/hue/commits/master

**Comment by xixikaikai** [comment]
@wing2fly I'll package and build one for test

**Comment by xixikaikai** [comment]
I'm afraid that this bug occur again, BTW do you have a dev run guide book?
I've to build each time in order to verify a check of latest code.

--------------------------------

郑  恺

**Comment by wing2fly** [comment]
@xixikaikai, I was busy, just commit a fix.  Can you get latest change and try?

**Comment by xixikaikai** [comment]
@wing2fly It works. Thanks!
