### ISSUE TITLE
oidc login and solr related error occures every time

### ISSUE THREAD

**Issue by xixikaikai** [cloudera/hue#726]
![image](https://user-images.githubusercontent.com/10403433/42560219-c08afc34-8528-11e8-8f97-69ea7bec9dcd.png)

in my config, I do not set up solr related service, why it is throwing out errors?

**Comment by xixikaikai** [comment]
[[engines]]

    #  [[[solr]]]
    #  Requires Solr 6+
    ##  analytics=true
    ##  nesting=false

    #  [[[sql]]]
    ##  analytics=true
    ##  nesting=false


I quoted the all solr related configs, why this happened each time I login

**Comment by romainr** [comment]
> [desktop]
> app_blacklist=search

?

**Comment by xixikaikai** [comment]
yes this is a config, but I did not set anything here by default, and solr did not throw any exception before...   I'm confused. Anyway, I will try this first.

**Comment by xixikaikai** [comment]
@romainr  thanks, this error message is not coming,
in replace, another comes...
![image](https://user-images.githubusercontent.com/10403433/42591761-3e58ae94-857a-11e8-8d86-222c4a7166cb.png)

This time it is 
'Config' object has no attribute 'get'

**Comment by xixikaikai** [comment]
blacklist can solve this
