### ISSUE TITLE
Is there any instruction of installing new python package into hue?

### ISSUE THREAD

**Issue by Atrbear** [cloudera/hue#727]

**Comment by romainr** [comment]
What is your operating system and what is the default Python?

**Comment by Atrbear** [comment]
`atrbear@atrbear:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
atrbear@atrbear:~$ python --version
Python 2.7.12
`

**Comment by Atrbear** [comment]
I also post it in `https://groups.google.com/a/cloudera.org/d/msg/hue-user/GpWTQlpe-Gk/_SD9BdDxAwAJ`
