### ISSUE TITLE
Query error of workflow

### ISSUE THREAD

**Issue by 18463105800** [cloudera/hue#730]
when I was searching the workflow's records, a strange error happended:

Apache Tomcat/6.0.53 - Error report HTTP Status 400 - type Status reportmessage description The request sent by the client was syntactically incorrect.Apache Tomcat/6.0.53 (error 400).

and then I changed the hue's version, a similar error happened:

<html><head><title>Apache Tomcat/6.0.53 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.53</h3></body></html> (error 400)

I hope someone who can give me the solution. Thank you

**Comment by 18463105800** [comment]
I have found the way to solve the problem.

**Comment by narnia26** [comment]
How you solved it??
