### ISSUE TITLE
Error running autocomplete  QueryError

### ISSUE THREAD

**Issue by xixikaikai** [cloudera/hue#732]
[18/Jul/2018 14:59:10 +0000] decorators   ERROR    Error running autocomplete
Traceback (most recent call last):
  File "/home/kay/Desktop/hue/desktop/libs/notebook/src/notebook/decorators.py", line 97, in decorator
    return func(*args, **kwargs)
  File "/home/kay/Desktop/hue/desktop/libs/notebook/src/notebook/api.py", line 573, in autocomplete
    autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested)
  File "/home/kay/Desktop/hue/desktop/libs/notebook/src/notebook/connectors/solr.py", line 47, in decorator
    raise QueryError(message)
QueryError

**Comment by xixikaikai** [comment]
I've already quoted the lines as below in desktop/libs/notebook/src/notebook/api.py

@require_POST
@check_document_access_permission()
@api_error_handler
def autocomplete(request, server=None, database=None, table=None, column=None, nested=None):
  response = {'status': -1}

  # Passed by check_document_access_permission but unused by APIs
  notebook = json.loads(request.POST.get('notebook', '{}'))
  snippet = json.loads(request.POST.get('snippet', '{}'))

  **# try:
  #   autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested)
  #   response.update(autocomplete_data)
  # except QueryExpired:
  #   pass**

  response['status'] = 0

  return JsonResponse(response)

**Comment by xixikaikai** [comment]
This line throws a exception, but I did not know how to debug, 
I just quote it.

autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested)

**Comment by sharkdtu** [comment]
I have the same problem too

**Comment by romainr** [comment]
You should have some Thrift errors above the autocomplete error that would tell the root cause of the issue
