### ISSUE TITLE
can't run make locales

### ISSUE THREAD

**Issue by lordk911** [cloudera/hue#733]
I download the latest version of hue , I want to change the languages , after run make apps , when I run make locales , I got error message : make: *** No rule to make target `locales'.  Stop.  what was wrong?

**Comment by enricoberti** [comment]
hi! i just tried on master and it works for me... can you try this instead from the root of Hue (where the makefile is)?
`make -C desktop compile-locales`

**Comment by lordk911** [comment]
hi! I've tried again, still got error , thank you all the same!
[devuser@bdp-docker-03 hue-4.2.0]$ pwd
/home/devuser/hue/hue-4.2.0
[devuser@bdp-docker-03 hue-4.2.0]$ ll
total 124
-rw-rw-r--  1 devuser devuser  2782 Jul 18 18:13 app.reg
drwxrwxr-x 22 devuser devuser   309 Jul 18 15:05 apps
drwxrwxr-x  4 devuser devuser    31 Jul 18 15:06 build
drwxrwxr-x  6 devuser devuser    88 Jul 18 18:06 desktop
drwxrwxr-x 10 devuser devuser   161 Apr  5 01:30 docs
drwxrwxr-x  3 devuser devuser    24 Apr  5 01:30 ext
-rw-rw-r--  1 devuser devuser 67991 Jul 18 19:12 hue-tmp.json
-rw-rw-r--  1 devuser devuser 11349 Apr  5 01:20 LICENSE.txt
drwxrwxr-x  2 devuser devuser   139 Jul 18 19:17 logs
-rw-rw-r--  1 devuser devuser  4930 Apr  5 01:30 Makefile
-rw-rw-r--  1 devuser devuser  8505 Apr  5 01:20 Makefile.sdk
-rw-rw-r--  1 devuser devuser  3511 Apr  5 01:20 Makefile.vars
-rw-rw-r--  1 devuser devuser  2192 Apr  5 01:30 Makefile.vars.priv
drwxrwxr-x  2 devuser devuser    21 Apr  5 01:20 maven
-rw-rw-r--  1 devuser devuser   894 Apr  5 01:20 NOTICE.txt
-rw-rw-r--  1 devuser devuser  1502 Apr  5 01:30 README
drwxrwxr-x  5 devuser devuser    89 Apr  5 01:30 tools
-rw-rw-r--  1 devuser devuser   932 Apr  5 01:20 VERSION
[devuser@bdp-docker-03 hue-4.2.0]$ make -C desktop compile-locales
make: Entering directory `/home/devuser/hue/hue-4.2.0/desktop'
make: *** No rule to make target `compile-locales'.  Stop.
make: Leaving directory `/home/devuser/hue/hue-4.2.0/desktop'
[devuser@bdp-docker-03 hue-4.2.0]$

**Comment by romainr** [comment]
Does it work from https://github.com/cloudera/hue.git ?

**Comment by romainr** [comment]
Does it work from https://github.com/cloudera/hue.git ?
