### ISSUE TITLE
How  to user&build javascript?

### ISSUE THREAD

**Issue by NoraGithub** [cloudera/hue#734]
Thank the great job of hue.
I am trying to add some features of UI to it and notice that the hue project has `package.json` inside that it seems to support the script like`npm run build`. I wonder whether there is a tutorial how to use other javascript framework(like Vue) or third party dependencies.

**Comment by enricoberti** [comment]
Hi! It's currently a work in progress, you are better off for now to include your JS files in the /static folders and reference them in the mako files. 
Would you mind sharing which functionalities you are adding to Hue? :)

**Comment by NoraGithub** [comment]
I would hope to perfect the way showing the meta info when clicking the table. I would try, thx.

**Comment by NoraGithub** [comment]
@enricoberti   When I was developing , I changed some origin KO code, and here comes some errors. Do I need to regenerating hue-bundle.js or ko.hue-bindings.js and how ?

The error message is as below:
```
ReferenceError: Unable to process binding "toggle: function(){return leftNavVisible }"
Message: leftNavVisible is not defined
    at toggle (eval at t (hue-bundle.js:formatted:9320), <anonymous>:3:59)
    at init (ko.hue-bindings.js:763)
    at hue-bundle.js:formatted:9498
    at Object.ignore (hue-bundle.js:formatted:8465)
    at hue-bundle.js:formatted:9497
    at Object.arrayForEach (hue-bundle.js:formatted:7615)
    at p (hue-bundle.js:formatted:9491)
    at l (hue-bundle.js:formatted:9417)
    at a (hue-bundle.js:formatted:9410)
    at l (hue-bundle.js:formatted:9418)
```
