### ISSUE TITLE
jquery.tmpl conflict django template

### ISSUE THREAD

**Issue by NoraGithub** [cloudera/hue#735]
As far as I know, django template engine and jquery.tmpl both use `{{}}` to render, so how to handle this kind of conflicts?
I can also use `${}` to render but it would be better if there was a tutorial for this kind of things.

Is there such a tutorial?

**Comment by enricoberti** [comment]
We use KnockoutJS for any client side templating in Hue: http://knockoutjs.com/

**Comment by NoraGithub** [comment]
Do you mean that Hue doesn't use the template system of Django (https://docs.djangoproject.com/en/2.0/topics/templates/) completely? It use knockoutjs to do all the templating?
