### ISSUE TITLE
when user do not  operation hive  for more than 7 days,  the delegation token will expired, 

### ISSUE THREAD

**Issue by xhmz** [cloudera/hue#739]

**Comment by xhmz** [comment]
the hadoop dfs.namenode.delegation.token.max-lifetime  default is 7 day,
hue store session info in table beeswax_session,
 if user do not operation hive for more than 7 days, the session in beeswax_session will expired ,but hue will use the expired session to connect hs2, it will throw expection as below:
############
org.apache.hadoop.security.token.SecretManager$InvalidToken: token expired or does not exist: owner=kai_zheng_aliyun_com, renewer=kai_zheng_aliyun_com, realUser=hive/hive.linktime.cloud@LINKTIME.CLOUD, issueDate=1532431576930, maxDate=1533036376930, sequenceNumber=1071, masterKeyId=12
#############
i must delete the rows  in beeswax_session, it will renew the session.

**Comment by xhmz** [comment]
@romainr

**Comment by xhmz** [comment]
> Whats your hive session timeout settings?

which settings should i configure? can you specify them? in hive-site.xml ?

**Comment by elukey** [comment]
Any news on this?
