### ISSUE TITLE
OIDC EXPIRY time can not  configure by pseudo-distributed.ini

### ISSUE THREAD

**Issue by xhmz** [cloudera/hue#740]
OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = 15 * 60
@romainr

**Comment by wing2fly** [comment]
I am working on oidc id token renewal. will update when it's done.

**Comment by xhmz** [comment]
@wing2fly  ok thanks

**Comment by sorsby** [comment]
@wing2fly was there any update on this? My team is running into a few issues integrating with Keycloak and the OIDC backend, I will be opening some issues once we've investigated further.
