### ISSUE TITLE
Hue very slow performance

### ISSUE THREAD

**Issue by Xin2018Cardiff** [cloudera/hue#746]
Hue is performing very slowly. The tables are taking several (>2) minutes to load. Clicking on different options in HUE is also very slow, taking minutes to load Hive. 

We have two group of users to verify this issue. Group one users have more permissions than Group two users. For example, metadata.access, notebook.access, jobsub.access and so on. Group two users are normally heavy users and usually run lots of queries on HUE.

This issue is raised by group two user as they have a much worse experience than group one users. We assumed that the performance issues are being caused by permissions based on our testing. When group two user is moved to group one we can see the improvement in load times. 

If the user is assigned to be super user (admin user) there is a vast improvement. It can reduce the page loading time from 2.5 minutes to 30 seconds.

Would you please provide us a resolution or any suggestions.

**Comment by wing2fly** [comment]
HUE-8305 should fix this issue. Closing this issue.
