### ISSUE TITLE
Editor，grammatical error annotation is in wrong position

### ISSUE THREAD

**Issue by sweepingmonk123** [cloudera/hue#747]
it seems the create table statement cause the problem

![image](https://user-images.githubusercontent.com/6657119/44711323-af956580-aae0-11e8-84a6-8906edd5949e.png)

**Comment by JohanAhlen** [comment]
Hi,

Do you get this consistently? I haven't been able to reproduce it and it always marks 'PARITION' as a syntax error when I write and modify the statements you provided. Which Hue version are you running?

Thanks,
Johan
