### ISSUE TITLE
Syntax check invalid

### ISSUE THREAD

**Issue by HSunboy** [cloudera/hue#750]
Syntax validation fails when the sql statement contains a user define function.
For example, `select my_MAX(id,name)  from customers wh1ere customers.id = 75012;`, the error in this sql statement will not be detected.
![image](https://user-images.githubusercontent.com/14886044/44979854-cd5f4080-afa0-11e8-8164-cd517f1ffc0b.png)

**Comment by JohanAhlen** [comment]
Thanks for reporting this one, I'll take a look and will track it in [HUE-8525](https://issues.cloudera.org/browse/HUE-8525).

Note though that in the correct case it would mark "customers" after "wh1ere" as the syntax error as "wh1ere" is a valid alias for customers.
