### ISSUE TITLE
JDBC connector only supports Teradata

### ISSUE THREAD

**Issue by modest** [cloudera/hue#753]
When trying to use the JDBC connector with Presto, I hit numerous query errors generated by the SQL assistant.  It turns out that the JDBC connector relies on proprietary Teradata schema tables to function.

Code:
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/jdbc.py#L191

The regression was made in this commit:
https://github.com/cloudera/hue/commit/f30e9f75011f777458873fbc4c807bd2d100a4cb#diff-97bedc523ae0da5a98d16c29a0153ae3L186

Note that the JDBC connector now references `DBC.Databases`, `dbc.tables`, and `DBC.Columns`, which are all Teradata-proprietary.

It seems that there would be 2 obvious ways to approach this in a more compatible way:
- Query using `SHOW DATABASES`, `SHOW TABLES`, and `SHOW COLUMNS`, which are widely supported.  This was the previous approach.
- Query using `SELECT fieldName from INFORMATION_SCHEMA.SCHEMATA`, `INFORMATION_SCHEMA.TABLES`, and `INFORMATION_SCHEMA.COLUMNS` which are part of ANSI/ISO 9075.  (This approach has the benefit of consistent result columns).

For something as generic as a JDBC connector, I don't understand why relying on Teradata-proprietary schemas is good design or necessary.

**Comment by romainr** [comment]
@modest @jdesjean +1 for #2 in preference, if not #1. 

I don't remember why it was changed, but in any case it should not be tied to Teradata indeed. Maybe #1 was not compatible, but not sure.

**Comment by jdesjean** [comment]
https://issues.cloudera.org/browse/HUE-8580
