### ISSUE TITLE
Hue 4.2 memory leak

### ISSUE THREAD

**Issue by har5havardhan** [cloudera/hue#754]
HI
 I am running Hue 4.2 on Amazon Emr and the memory utilised by hue keeps on increasing with time and never comes down. Is there a known issue regarding this ? If exists please suggest a fix..

Thanks

**Comment by romainr** [comment]
This might happen when you have too many query histories or past sessions. Will update the clean-up scripts there soon https://github.com/cloudera/hue/tree/master/tools/ops

**Comment by har5havardhan** [comment]
I checked for it and found that query history is not the reason for memory leak.

**Comment by zhaorongsheng** [comment]
@romainr  I used cm to control hue. Would you mind telling me which and how to run the the clean-up scripts? thanks~

**Comment by StrongZhao** [comment]
Have you solved this problem？
