### ISSUE TITLE
Hue Docker image fails immediately after startup

### ISSUE THREAD

**Issue by juv** [cloudera/hue#756]
I am trying to run the latest [Docker image ](https://hub.docker.com/r/gethue/hue/) of hue. The deployment fails immediately after startup. We are running Kubernetes 1.10. 

The error I get is:
```
Traceback (most recent call last):
  File "build/env/bin/hue", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/hue/build/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/hue/build/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "/hue/build/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/hue/build/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: desktop==4.2.0
```

**Comment by romainr** [comment]
Do you have some more error from the build?

FYI another one I have been using recently

`FROM ubuntu:16.04

RUN apt-get update -y && apt-get install -y \
  build-essential \
  libkrb5-dev \
  libmysqlclient-dev \
  libssl-dev \
  libsasl2-dev \
  libsasl2-modules-gssapi-mit \
  libsqlite3-dev \
  libtidy-0.99-0 \
  libxml2-dev \
  libxslt-dev \
  libffi-dev \
  libldap2-dev \
  libpq-dev \
  python-dev \
  python-setuptools \
  libgmp3-dev \
  libz-dev \
  software-properties-common \
  git \
  sudo \
  maven \
   && rm -rf /var/lib/apt/lists/*

RUN add-apt-repository -y ppa:webupd8team/java
RUN apt-get update -y
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
RUN apt-get install -y oracle-java8-installer

ADD hue /hue
RUN cd /hue && PREFIX=/usr/share make install
COPY conf /usr/share/hue/desktop/conf
EXPOSE 8888
RUN useradd -ms /bin/bash hue && chown -R hue /usr/share/hue
WORKDIR  /usr/share/hue
RUN ./build/env/bin/pip install psycopg2-binary
# dev tools
COPY ./startup.sh /usr/share/hue
CMD ["./startup.sh"]`

**Comment by juvlarN** [comment]
hi @romainr 
is this supposed to be a running Dockerfile? I see lines like `ADD hue /hue` which imply that files get added from the local folder - which I do not have access to? 
Also: I do not have more logs, sorry. This is all that gets printed to the console of the Kubernetes pod.
