### ISSUE TITLE
Enable sharing multiple workflows / documents at time

### ISSUE THREAD

**Issue by kcech** [cloudera/hue#758]
It would be very useful to enable bulk sharing.
We have hundreds of workflows in a multi-user environment. Sharing documents can be quite tedious sometimes.

**Comment by jdesjean** [comment]
@kcech: One option that's available at the moment is to share a folders. Put all the documents you wan t to share in a folder and then share that folder.

**Comment by kcech** [comment]
@jdesjean : Thank you for this suggestion. Sadly I cannot move existing workflows to a folder. 
Plus, this implies to have workflows always in some folder, meaning you have to anticipate that you will be sharing a workflow someday. I think it's quite user unfriendly. Especially, since you can share a single workflow anytime to anybody and the UI enables to select multiple workflows, it's hard for the users to understand you cannot bulk-share.
