### ISSUE TITLE
Hue doesn't kill presto connections upon stopping

### ISSUE THREAD

**Issue by har5havardhan** [cloudera/hue#762]
Hi
 I am running hue on master node of my cluster and it points to presto running on a different cluster. upon stopping and starting hue, it is observed that new connections are created to presto but the old connections are not killed which are holding memory and not releasing it.

**Comment by romainr** [comment]
Is Presto supporting idle session timeouts?
http://gethue.com/hadoop-tutorial-hive-and-impala-queries-life-cycle/

Note: if the user manually logs out, Impala session are closed (could do the same for other engines, even if sometimes users only close the tabs)
