### ISSUE TITLE
S3 Filesystem support cannot be configured with instance profiles on HVM EC2 Instances

### ISSUE THREAD

**Issue by colintoal** [cloudera/hue#766]
On hue 4.3 built from source, deployed to an AWS EC2 HVM based instance, the S3 File Browser remains disabled when allow_environment_credentials=True in the [[aws]][[default]] section of the INI file.

The specific issue is in:
desktop/libs/aws/src/aws/conf.py in lines 198-207 ( the has_iam_metadata function ). 

The source checks /sys/hypervisor/uuid for a GUID with a magic value that starting with EC2 to determine that it is a virtualized EC2 instance. This specific condition is not met on HVM based EC2 instances, which have an empty /sys/hypervisor folder. 

Instead, as per the latest documentation at 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html, you should use the Desktop Management Interface through dmidecode or the files at /sys/devices/virtual/dmi/id/* to identify if the instance is an EC2 instance. Many of the ../dmi/id/ files world readable, and the /sys/devices/virtual/dmi/id/sys_vendor will return "Amazon EC2" and is a reliable device file you can use to determine the VM is an EC2 instance.

I can file a PR for this, but the fix is trivial. HVM instances are popular and this bug is pernicious and fails opaquely. I hope it can be fixed quickly.

**Comment by jdesjean** [comment]
@colintoal: please go ahead and submit a PR and we'll review it ASAP.

**Comment by sqNutrien** [comment]
@colintoal Did you create a PR? I ran into the same issue - can create the PR if you haven't yet.

**Comment by sqNutrien** [comment]
I'll submit a PR for this, hopefully in the next couple days.

**Comment by sqNutrien** [comment]
@jdesjean I'm not able to find a JIRA ticket corresponding to this issue... is there one? If not do I create one? At that point can I create a feature branch? I know ultimately I need follow the stuff on https://github.com/cloudera/hue/blob/master/docs/CONTRIBUTING.md, but I'm not sure just how to get to the point where I can create a feature branch.

**Comment by jdesjean** [comment]
@sqNutrien I created a JIRA for you https://issues.cloudera.org/browse/HUE-8780. For one liner, you can just create a pull request.

**Comment by sqNutrien** [comment]
Thanks @jdesjean. My fix will be a few lines ... not too many :) Not sure what tests I'll have to modify/create - I hope to make progress on this in the next couple days.

**Comment by sqNutrien** [comment]
@jdesjean I'm not seeing the CCLA that is referenced in the hue/docs/CONTRIBUTING.md: "If it is the first time, please sign the CCLA that way we don't get sued later ;)" 

Also - looks like I fork your repo, make my changes in my fork, then submit a PR... correct?

**Comment by jdesjean** [comment]
1) We decided to remove the CCLA, so don't worry about it. We'll update the docs.
2) Correct.

**Comment by sqNutrien** [comment]
@jdesjean starting on this... I don't seem to have the ability to "Start" the JIRA ticket... is that something I do, or just work on it and management of JIRA is at your end?

**Comment by jdesjean** [comment]
Because I created it, you can't. Don't worry about it, I'll managed it on my end.

**Comment by sqNutrien** [comment]
@jdesjean sorry man. I don't think I'm thick, but I can't find **python2.7-devel** anywhere... trying to install it in my conda environment because I get this error when trying to build the project:

```scottqueen:hue [HUE-8780-S3-iam-is-not-detected-on-HVM-EC2-Instances] $ make apps
/Users/scottqueen/Repos/hue/Makefile.vars:42: *** "Error: must have python development packages for 2.7. Could not find Python.h. Please install python2.7-devel".  Stop.
```
Looked all over the interwebs, tried brew install,pip install, conda install.... no dice.

Any hints? Developing on a Mac.

**Comment by jdesjean** [comment]
Can you take a look at this: https://github.com/cloudera/hue/issues/251
