### ISSUE TITLE
Presto support as a first class citizen in Hue

### ISSUE THREAD

**Issue by cryptoe** [cloudera/hue#767]
I think using hue jdbc with the presto jdbc jar limits a lot of functionality like 

1. Killing queries
2. Job urls
3. Job progress
4. Job logs
5. Autocomplete q's. 
6. Export results.
7. Scalability (JVM is launched for each user?)
8. Presto has a concept of catalogs. Catalog->dbs->tables->cols->rows. Its a little hacky to add these things to the current jdbc connector and still keep the jdbc connector generic.

I was thinking of adding a separate connector preso-connector.py something like jdbc.py and use the https://pypi.org/project/presto-python-client/ as the presto-client.

Also there are no of open requests which can be targeted with this
https://github.com/cloudera/hue/issues?q=presto+is%3Aopen

Raising issue on git based on chat done on mail thead: https://mail.google.com/mail/u/0/#inbox/QgrcJHsBtQSJdkGjzqWpwkPmSLztpJBHxLl

**Comment by romainr** [comment]
FYI https://github.com/cloudera/hue/pull/800

SQL Alchemy is also being scoped for a Python native connector https://issues.cloudera.org/browse/HUE-8740
