### ISSUE TITLE
Hue4.1 web UI doesn't allow to kill a running hive (TEZ) application from job browser

### ISSUE THREAD

**Issue by phani482** [cloudera/hue#768]
Hello Team, 

Hue4.1 UI doesn't allow to kill a running hive Tez application from Job browser. The "kill" button is grayed out.

 Steps to reproduce the issue:
>Click on the Hive editor
>Run the following commands and click on Job browser
a.
set hive.execution.engine=mr
CREATE EXTERNAL TABLE testpk1(id INT,name STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' LOCATION 's3://mybucket/myfolder' ;
INSERT INTO TABLE testpk1 VALUES(1,'abc') ;
select distinct(id) FROM testpk1 ;
b.
set hive.execution.engine=tez
CREATE EXTERNAL TABLE testpk2(id INT,name STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' LOCATION 's3://mybucket/myfolder' ;
INSERT INTO TABLE testpk2 VALUES(1,'abc') ;
select distinct(id) FROM testpk2 ;

In the second case above, You will see the 'kill' button greyed out. 

<img width="1278" alt="hue4__cannot_kill_the_job_from_job_browser" src="https://user-images.githubusercontent.com/12974327/47590712-c581a400-d932-11e8-9922-6313d22b249a.png">

**Comment by taklwu** [comment]
any updates?
