### ISSUE TITLE
Hue4.1 doesn't show logs for a running Tez application like in Hue 3

### ISSUE THREAD

**Issue by phani482** [cloudera/hue#769]
Hello Team,

Hue4.1 UI doesn't show logs on a running hive Tez application from Job browser. 

Steps to reproduce the issue:

    -Click on the Hive editor
    -Run the following commands and click on Job browser
    a.
    set hive.execution.engine=mr
    CREATE EXTERNAL TABLE testpk3(id INT,name STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' LOCATION 's3://mybucket/myfolder' ;
    INSERT INTO TABLE testpk3 VALUES(1,'abc') ;
    select distinct(id) FROM testpk3 ;

<img width="1252" alt="hue4_mr_jobbrowserworks" src="https://user-images.githubusercontent.com/12974327/47590915-738d4e00-d933-11e8-8c70-855fbe426597.png">
    b.
    set hive.execution.engine=tez
    CREATE EXTERNAL TABLE testpk4(id INT,name STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' LOCATION 's3://mybucket/myfolder' ;
    INSERT INTO TABLE testpk4 VALUES(1,'abc') ;
    select distinct(id) FROM testpk4 ;

<img width="1277" alt="hue4_jobbrowser_while_job_is_running" src="https://user-images.githubusercontent.com/12974327/47590928-84d65a80-d933-11e8-9349-3ba92d9ebb6e.png">

**Comment by taklwu** [comment]
any updates?

**Comment by phani482** [comment]
I was using Hive 2.3.2 for the above tests.
I did test this using the above properties followed by restarting hive-server2, hive-hcatalog-server on Hive 2.3.2 and Hive 2.3.3. But the There is no change in the behavior of hue console.
