### ISSUE TITLE
How to display Pyspark result in table view instead of text view? (i.e., equivalent of `z.show() in Zeppelin`))

### ISSUE THREAD

**Issue by cqcn1991** [cloudera/hue#771]
Hi, I'm using Hue Editor/Notebook right now with Pyspark,
I want to know, how can I display result in table view like results from SQL, instead of text?
For example, currently the result I get is this

![default](https://user-images.githubusercontent.com/2425141/47894961-a9d14d00-dea0-11e8-9fb0-a5e016d0ae48.png)

But I want to display the results in 

![default](https://user-images.githubusercontent.com/2425141/47895027-0a608a00-dea1-11e8-9317-1e999984082f.png)

How can I do it? In Zeppelin, there is a function `z.show()` can do this (https://zeppelin.apache.org/docs/0.6.2/displaysystem/basicdisplaysystem.html#table). What is the equivalent in Hue Editor/Notebook

Thanks

**Comment by romainr** [comment]
Hum, not sure if Livy can return the info as a table too, it would be then easier to offer to display it like a SQL result.
