### ISSUE TITLE
Why does this ‘aus.topo.js’ file fail to load, server status 500

### ISSUE THREAD

**Issue by zuoakang** [cloudera/hue#772]
### Please help me to see this question
> Version

- hue-cdh6.0.0-release

![image](https://user-images.githubusercontent.com/22383362/47996931-25e3c300-e135-11e8-9573-35f413cf75a9.png)

![image](https://user-images.githubusercontent.com/22383362/47997037-78bd7a80-e135-11e8-8c15-8dbf35c4fca9.png)

**Comment by TimKingNF** [comment]
I have the same question. And I try to fetch this js use Safari and CURL or Edge. 
Safari and CURL fetch success. But Chrome and Edge not.

**Comment by zuoakang** [comment]
@TimKingNF When I###  change the file name,It be fine.

> aus.topo.js > aus_bak.topo.js
