### ISSUE TITLE
invalid literal for int() with base 10 'possible misconfiguration' when I use SQL editor in webUI

### ISSUE THREAD

**Issue by saito96** [cloudera/hue#777]
I'm using HUE 4.3. And I get an error when query using editor SQL.
I think it is an error from python code: https://stackoverflow.com/questions/1841565/valueerror-invalid-literal-for-int-with-base-10. Can you help me to fix it or update to clear this error. Thank team.

**Comment by romainr** [comment]
Why SQL language are you using?

**Comment by ShomyLiu** [comment]
@saito96  Maybe that there are letters ornumbers mixed in your sql password?  You can try with a explict string:
```
password="password123"
```
rather than: `password=password123`
