### ISSUE TITLE
HUE 4.2: HIVE Editor: Viewing table sample requires [USE] permission on [default]

### ISSUE THREAD

**Issue by nutle** [cloudera/hue#781]
I have a user that has all the rights to use tables on a certain database without problems. However, for some reason, the HUE function of viewing a small sample of the table (pressing the "info" icon) requires [USE] permission for the [default] database, which has nothing to do with the tables in that certain database. Is this a bug? Or is there a reason for that?

Note that the user is able to select without problems, and is also allowed to view the source data for those tables in hdfs (since they are external).

**Comment by adhiyanaw** [comment]
may be u have to put the schema of database first, 
or, u can make refresh browser(if using browser version).
