### ISSUE TITLE
nessus scan error:CGI Generic SQL Injection (blind)

### ISSUE THREAD

**Issue by ZHUVV** [cloudera/hue#783]
Hi all:
An vulnerability was found in a nessus scan, as following:
Anyone knows how to fix it?
Thank you

Using the GET HTTP method, Nessus found that :

+ The following resources may be vulnerable to blind SQL injection :

+ The 'next' parameter of the /accounts/login/ CGI :

/accounts/login/?username=&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqsqiSrOO
L6gMQB8&password=154487&server=LDAPSERVER1.ZDH.COM&next=%2fzz&csrfmiddle
waretoken=HT8l42nhvNJZs7bQdqsqiSrOOL6gMQB8&password=154487&server=LDAPSE
RVER1.ZDH.COM&next=%2fyy

-------- output --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/"/>

  </form>
-------- vs --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/yy"/>

  </form>
------------------------

/accounts/login/?username=&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqsqiSrOO
L6gMQB8&password=154487&server=LDAPSERVER1.ZDH.COM&next=%2fzz&csrfmiddle
waretoken=HT8l42nhvNJZs7bQdqsqiSrOOL6gMQB8&password=154487&server=LDAPSE
RVER1.ZDH.COM&next=%2fyy {2}

-------- output --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/"/>

  </form>
-------- vs --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/yy"/>

  </form>
------------------------

/accounts/login/?username=&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqsqiSrOO
L6gMQB8&password=154487&server=LDAPSERVER1.ZDH.COM&next=%2fzz&csrfmiddle
waretoken=HT8l42nhvNJZs7bQdqsqiSrOOL6gMQB8&password=154487&server=LDAPSE
RVER1.ZDH.COM&next=%2fyy {3}

-------- output --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/"/>

  </form>
-------- vs --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/yy"/>

  </form>
------------------------

/accounts/login/?username=190226&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqs
qiSrOOL6gMQB8&password=&server=LDAPSERVER1.ZDH.COM&next=%2fzz190226&csrf
middlewaretoken=HT8l42nhvNJZs7bQdqsqiSrOOL6gMQB8&password=&server=LDAPSE
RVER1.ZDH.COM&next=%2fyy

-------- output --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/"/>

  </form>
-------- vs --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/yy"/>

  </form>
------------------------

/accounts/login/?username=190226&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqs
qiSrOOL6gMQB8&password=&server=LDAPSERVER1.ZDH.COM&next=%2fzz190226&csrf
middlewaretoken=HT8l42nhvNJZs7bQdqsqiSrOOL6gMQB8&password=&server=LDAPSE
RVER1.ZDH.COM&next=%2fyy {2}

-------- output --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/"/>

  </form>
-------- vs --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/yy"/>

  </form>
------------------------

/accounts/login/?username=190226&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqs
qiSrOOL6gMQB8&password=&server=LDAPSERVER1.ZDH.COM&next=%2fzz190226&csrf
middlewaretoken=HT8l42nhvNJZs7bQdqsqiSrOOL6gMQB8&password=&server=LDAPSE
RVER1.ZDH.COM&next=%2fyy {3}

-------- output --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/"/>

  </form>
-------- vs --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/yy"/>

  </form>
------------------------

/accounts/login/?username=190226&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqs
qiSrOOL6gMQB8&password=154487&server=LDAPSERVER1.ZDH.COM&next=%2fzz19022
6&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqsqiSrOOL6gMQB8&password=154487&s
erver=LDAPSERVER1.ZDH.COM&next=%2fyy

-------- output --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/"/>

  </form>
-------- vs --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/yy"/>

  </form>
------------------------

/accounts/login/?username=190226&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqs
qiSrOOL6gMQB8&password=154487&server=LDAPSERVER1.ZDH.COM&next=%2fzz19022
6&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqsqiSrOOL6gMQB8&password=154487&s
erver=LDAPSERVER1.ZDH.COM&next=%2fyy {2}

-------- output --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/"/>

  </form>
-------- vs --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/yy"/>

  </form>
------------------------

/accounts/login/?username=190226&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqs
qiSrOOL6gMQB8&password=154487&server=LDAPSERVER1.ZDH.COM&next=%2fzz19022
6&csrfmiddlewaretoken=HT8l42nhvNJZs7bQdqsqiSrOOL6gMQB8&password=154487&s
erver=LDAPSERVER1.ZDH.COM&next=%2fyy {3}

-------- output --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/"/>

  </form>
-------- vs --------

      <input type="submit" class="btn btn-primary" value="Sign In"/>
    <input type="hidden" name="next" value="/yy"/>

  </form>
------------------------

**Comment by AlienationX** [comment]
me too, What did you solve?

operator will shut down this this web service. oh no, help!!!
