### ISSUE TITLE
 Unable to edit and save replicated workflows  and Schedule

### ISSUE THREAD

**Issue by wzxwf** [cloudera/hue#786]
Unable to edit and save replicated workflows  and Schedule
on hue-cdh6.0
error message
{ "traceback": [ [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/core/handlers/exception.py", 41, "inner", "response = get_response(request)" ], [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/core/handlers/base.py", 249, "_legacy_get_response", "response = self._get_response(request)" ], [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/core/handlers/base.py", 187, "_get_response", "response = self.process_exception_by_middleware(e, request)" ], [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/core/handlers/base.py", 185, "_get_response", "response = wrapped_callback(request, *callback_args, **callback_kwargs)" ], [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/utils/decorators.py", 185, "inner", "return func(*args, **kwargs)" ], [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/apps/oozie/src/oozie/decorators.py", 113, "decorate", "return view_func(request, *args, **kwargs)" ], [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/apps/oozie/src/oozie/decorators.py", 103, "decorate", "return view_func(request, *args, **kwargs)" ], [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/apps/oozie/src/oozie/views/editor2.py", 206, "save_workflow", "workflow_doc = _save_workflow(workflow, layout, request.user, fs=request.fs)" ], [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/apps/oozie/src/oozie/models2.py", 3680, "_save_workflow", "workflow_doc1 = workflow_doc.doc.get()" ], [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/db/models/manager.py", 85, "manager_method", "return getattr(self.get_queryset(), name)(*args, **kwargs)" ], [ "/opt/cloudera/parcels/CDH-6.0.0-1.cdh6.0.0.p0.537114/lib/hue/build/env/lib/python2.7/site-packages/Django-1.11-py2.7.egg/django/db/models/query.py", 379, "get", "self.model._meta.object_name" ] ] }

**Comment by romainr** [comment]
Should be fixed by https://github.com/cloudera/hue/pull/831
