### ISSUE TITLE
[oozie] Args cannot contain spaces

### ISSUE THREAD

**Issue by andreaferretti** [cloudera/hue#79]
It seems that the Hue interface for Oozie does not support spaces in args.

Namely, I am trying to add arguments with spaces in a Java action. Apparently the parser just splits the arguments string at spaces and escapes them. For instance `--time "30 seconds"` results in

    <arg>--time</arg>
    <arg>&quot;30</arg>
    <arg>seconds&quot;</arg>

while `--time 30\ seconds` turns into

    <arg>--time</arg>
    <arg>30\</arg>
    <arg>seconds</arg>

Neither results in

    <arg>--time</arg>
    <arg>30 seconds</arg>

**Comment by thomaswmeier** [comment]
I found a way to pass a space character as an oozie arg parameter.  You have to double escape the octal value for the space character, i.e., "\\040".  So, let's say you want the arg parameter to be "Problem solved", you would need to enter "Problem\\040solved".

The octal value for a space character is 040.  For a bash script it would be \040.  From oozie it needs to be \\040.

**Comment by thomaswmeier** [comment]
Funny thing happened.  After I wrote the comment above, I realized that it only showed a single back slash.  So, I need to escape my comment, too!  What I meant to say is this:

 I found a way to pass a space character as an oozie arg parameter. You have to double escape the octal value for the space character, i.e., "\\\040". So, let's say you want the arg parameter to be "Problem solved", you would need to enter "Problem\\\040solved".

The octal value for a space character is 040. For a bash script it would be \040. From oozie it needs to be \\\040.
