### ISSUE TITLE
Unable to connect to database on host

### ISSUE THREAD

**Issue by MartinMa28** [cloudera/hue#790]
![hue problems masked](https://user-images.githubusercontent.com/31215089/50417969-0f6c0500-0864-11e9-8e35-6e5c325918fb.jpeg)

When trying to add Hue into my cluster, somehow, I encountered this problem. Other three databases for Hive, Activity Monitor, and Oozie work fine. And I have checked the access of databases. I am sure I can connect to the database for hue from the command line. This problem has stopped me for a few days, please tell me how to get rid of it if you know anything related.
Thanks.

**Comment by romainr** [comment]
Can you connect to this MySQL DB from the command line from another host using the same credentials as in the screenshot?

**Comment by MartinMa28** [comment]
Thanks for your reply. I have circumvented this problem by using MariaDB. I think those configurations should work for MySQL 5.7, but I was using MySQL 8.0 at that time. Probably, it's better to have some instructions for MySQL 8.0 in the official documentation.
