### ISSUE TITLE
hue4.3-  Workflow cannot submit sqoop tasks

### ISSUE THREAD

**Issue by chinayangze** [cloudera/hue#792]
hue4.3-  Workflow cannot submit sqoop tasks

Workflow submission failed: 'statement'

**Comment by wzxwf** [comment]
this is a bug .  Action.data['properties']['statement'] was not found in action.data  
vi /opt/cloudera/parcels/CDH-6.1.0-1.cdh6.1.0.p0.770702/lib/hue/desktop/libs/liboozie/src/liboozie/submission2.py

  elif action.data['type'] in ('spark', 'spark-document') or (
           action.data['type'] in ('sqoop', 'sqoop-document') and action.data['properties']['statement'] in '--hive-import'):

 I changed   'action.data['properties']['statement'] in '--hive-import')'  to  ' action.data['properties']['command'] in '--hive-import') '   
 
It works fine

**Comment by wing2fly** [comment]
It has been fixed in https://issues.cloudera.org/browse/HUE-8717
