### ISSUE TITLE
Hue 4.3 - Page not found (404) : saml2/login

### ISSUE THREAD

**Issue by theagape** [cloudera/hue#797]
Hi,

I'm building and deploying Hue 4.3 (release-4.3.0). After setting all the details about SAML, then tried access https://[hue_base] then I got the redirected url and error message :

1. redirected url : `https://[hue_base]` --> `https://[hue_base]/saml2/login/?next=/`
2. error message : 

```
Request Method: | GET
http://[hue_base]/saml2/login/?next=/
1. ^hue/accounts/login [name='desktop_auth_views_dt_login']
2. ^accounts/login/$
3. ^accounts/logout/$
.... [other patterns skipped because it's long list] ....
The current path, saml2/login/, didn't match any of these.
```

How can I fix this problem?

**Comment by romainr** [comment]
There was a bunch of fixes lately and we know master is working fine at Cloudera. Any chance you could try with master?

**Comment by wing2fly** [comment]
This issue is fixed HUE-8662 and HUE-8663
