### ISSUE TITLE
Unable to connect to Presto due missing TABLE_COMEMNT column

### ISSUE THREAD

**Issue by kokosing** [cloudera/hue#799]
Today, I got Hue working with the Presto JDBC drive – yay! Anyway, as soon as I fire up Hue and click on a database, I see that Hue executes a query to the Hive catalog but this error occurs:

The query that gets submitted to Presto:
```
SELECT TABLE_NAME, TABLE_COMMENT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=x
```
 
Here’s the error in Presto:
```
An error occurred while calling o11.execute. : java.sql.SQLException: Query failed (#20190204_183807_00002_k4e8j):

line 1:20: Column 'table_comment' cannot be resolved
```

**Comment by kokosing** [comment]
See: https://github.com/prestosql/presto/pull/192

**Comment by i-love-doufunao** [comment]
Thanks @kokosing 
But there may be another problem not to fix,
`  def get_columns_full(self, database, table):
    columns, description = query_and_fetch(self.db, "SELECT COLUMN_NAME, DATA_TYPE, COLUMN_COMMENT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='%s' AND TABLE_NAME='%s'" % (database, table))
    return [{"comment": col[2] and col[2].strip(), "type": col[1], "name": col[0] and col[0].strip()} for col in columns]`
There is not column named 'COLUMN_COMMENT' but 'COMMENT' in INFORMATION_SCHEMA.COLUMNS.

**Comment by kokosing** [comment]
@i-love-doufunao https://github.com/cloudera/hue/pull/800/files#diff-03b7dbd45ab6cf309522418bf06746f8R35 already fixes this. Thanks for noticing this.

**Comment by romainr** [comment]
+1 and thanks for fixing it

**Comment by piperck** [comment]
goods job
