### ISSUE TITLE
(hue 3.6.0 )make apps error , can not build hue

### ISSUE THREAD

**Issue by polingsky** [cloudera/hue#80]
when i want to make apps
it shows some error like this

[ERROR] /home/cloud-user/hue/desktop/libs/hadoop/java/src/main/gen-java/org/apache/hadoop/thriftfs/jobtracker/api/Jobtracker.java:[147,92] cannot find symbol
  symbol:   class ThriftTaskID
  location: interface org.apache.hadoop.thriftfs.jobtracker.api.Jobtracker.Iface
[ERROR] /home/cloud-user/hue/desktop/libs/hadoop/java/src/main/gen-java/org/apache/hadoop/thriftfs/jobtracker/api/ThriftTaskInProgress.java:[73,10] cannot find symbol
  symbol:   class ThriftTaskID
  location: class org.apache.hadoop.thriftfs.jobtracker.api.ThriftTaskInProgress
[ERROR] /home/cloud-user/hue/desktop/libs/hadoop/java/src/main/gen-java/org/apache/hadoop/thriftfs/jobtracker/api/ThriftTaskInProgress.java:[245,5] cannot find symbol
  symbol:   class ThriftTaskID
  location: class org.apache.hadoop.thriftfs.jobtracker.api.ThriftTaskInProgress
[ERROR] /home/cloud-user/hue/desktop/libs/hadoop/java/src/main/gen-java/org/apache/hadoop/thriftfs/jobtracker/api/ThriftTaskInProgress.java:[515,10] cannot find symbol
  symbol:   class ThriftTaskID
  location: class org.apache.hadoop.thriftfs.jobtracker.api.ThriftTaskInProgress
[ERROR] /home/cloud-user/hue/desktop/libs/hadoop/java/src/main/gen-java/org/apache/hadoop/thriftfs/jobtracker/api/ThriftTaskInProgress.java:[519,41] cannot find symbol
  symbol:   class ThriftTaskID
  location: class org.apache.hadoop.thriftfs.jobtracker.api.ThriftTaskInProgress

[ERROR] location: class org.apache.hadoop.mapred.ThriftJobTrackerPlugin.JTThriftUtils
[ERROR] /home/cloud-user/hue/desktop/libs/hadoop/java/src/main/java/org/apache/hadoop/mapred/ThriftJobTrackerPlugin.java:[1266,66] incompatible types
[ERROR] required: org.apache.hadoop.mapred.TaskAttemptID
[ERROR] found:    org.apache.hadoop.mapred.TaskID
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
make[2]: **\* [/home/cloud-user/hue/desktop/libs/hadoop/java-lib/hue-plugins-3.6.0-SNAPSHOT.jar] Error 1
make[2]: Leaving directory `/home/cloud-user/hue/desktop/libs/hadoop'
make[1]: *** [.recursive-env-install/libs/hadoop] Error 2
make[1]: Leaving directory`/home/cloud-user/hue/desktop'
make: **\* [desktop] Error 2

how can i fix the problem???
i install HUE 3.5.0 is ok, but when i install HUE 3.6.0, it occurs above error.
it very confused me!

**Comment by maxiulin** [comment]
怎么转换的格式啊
