### ISSUE TITLE
hue use httpfs error

### ISSUE THREAD

**Issue by yyblove** [cloudera/hue#801]
Httpfs error, when I request `http://hadoop:14000/webhdfs/v1/user/hadoopuser?user.name=hadoopuser&op=GETFILESTATUS&doas=hadoop`
it response 
```
{
  "RemoteException": {
    "message": "User: hadoopuser is not allowed to impersonate hadoop",
    "exception": "AuthorizationException",
    "javaClassName": "org.apache.hadoop.security.authorize.AuthorizationException"
  }
}
```
But when I remove the `doas` parameters, the request is successful.
why add the `doas` parameter to the httpfs request?

**Comment by jdesjean** [comment]
Impersonation must be configured:
https://www.cloudera.com/documentation/enterprise/latest/topics/admin_hdfs_proxy_users.html
Unfortunately, we don't have a flag to turn this off.

Cheers,
Jean-Francois
