### ISSUE TITLE
Hue failed to upload any files when submit spark jar(4.3.0)

### ISSUE THREAD

**Issue by i-love-doufunao** [cloudera/hue#802]
When choosing 'Spark Submit Job',then error happens:
![hue_upload_error](https://user-images.githubusercontent.com/42244960/52778491-1a336100-3081-11e9-9383-cb3844d6a222.png)
I trace the code and It looks like that the 'json' is invalid.So I try to print the 'json' and find it is html format??
Exception:
![exception](https://user-images.githubusercontent.com/42244960/52778754-b1001d80-3081-11e9-9e8d-691f9f168e8c.png)
the 'json' value:
![json](https://user-images.githubusercontent.com/42244960/52778780-be1d0c80-3081-11e9-8454-f41c53381305.png)
So any suggestions? Thanks!

**Comment by romainr** [comment]
Which Hadoop distribution are you using?

**Comment by i-love-doufunao** [comment]
@romainr I used HDP platform for version 3.0.0 and Hadoop version is 3.1.0.
