### ISSUE TITLE
Hue Livy Server session is not working as expected

### ISSUE THREAD

**Issue by bgajjela** [cloudera/hue#806]
Hello,

Whenever you start a livy session by running a pyspark or R or scala session in hue notebook, session is persisting with an application id but whenever you navigate to different tabs in hue and comeback to notebook livy session ends up in zombie state and application id still remains intact.

In short: How can we navigate to notebook which was opened previously before (assuming that application id still remains intact which is true in my case)

Thanks,
Bharath

**Comment by bgajjela** [comment]
More Information on above problem:

Even though livysession is open , Sessions window in hue notebook doesn't show anything about those livy sessions.

**Comment by romainr** [comment]
Yes, I am not sure that those are being refreshed. One way to fix it, when opening up the notebook, create_session should return the list of the existing ones by getting them via Livy API https://github.com/cloudera/hue/blob/master/apps/spark/src/spark/job_server_api.py#L109.

**Comment by snakecy** [comment]
> Yes, I am not sure that those are being refreshed. One way to fix it, when opening up the notebook, create_session should return the list of the existing ones by getting them via Livy API https://github.com/cloudera/hue/blob/master/apps/spark/src/spark/job_server_api.py#L109.

when kerberos is open, the job preview part dosen't show anything about the sessions.
