### ISSUE TITLE
the user in hue with wrong authorized.

### ISSUE THREAD

**Issue by snakecy** [cloudera/hue#813]
error:

```
yarn_models  ERROR    Failed to get Spark Job executors: 403 Client Error: Forbidden for url: http://node:18081/api/v1/applications/application_1553155012971_0004/1/executors
user "hue" is not authorized (error 403)
```

**Comment by wing2fly** [comment]
Please check if Yarn has Kerberos enable and update hue config https://github.com/cloudera/hue/blob/master/desktop/conf/pseudo-distributed.ini.tmpl#L1063

**Comment by snakecy** [comment]
> Please check if Yarn has Kerberos enable and update hue config https://github.com/cloudera/hue/blob/master/desktop/conf/pseudo-distributed.ini.tmpl#L1063



yes , i have configure this parameter.  security is enabled.
 
i set livy.superusers = hue,livy
then , Q1 is :
```
YARN RM returned a failed response: 403 Client Error: Forbidden for url: http://node:8088/ws/v1/cluster/apps/application_1553162378546_0012/state?doAs=test Unauthorized attempt to kill appid application_1553162378546_0012 by remote user hue/node@DOMAIN.COM (error 403)
```
and in the jobbrowser part has no task list.

and , after this set yarn.admin.acl = yarn,hue
the jobbrowser part list turns out.

then ,Q2 is :
```
yarn_models  ERROR    Failed to get Spark Job executors: 403 Client Error: Forbidden for url: http://node:18081/api/v1/applications/application_1553155012971_0004/1/executors
user "hue" is not authorized (error 403)
```

that's when the user open a livy session,  eg. pyspark, and submit this task , when finished, the user could not close the session, and the Q2 is out.
