### ISSUE TITLE
latest/admin-manual/manual.html#installation page not found

### ISSUE THREAD

**Issue by chozee** [cloudera/hue#818]
http://cloudera.github.io/hue/latest/admin-manual/manual.html#installation

**Comment by romainr** [comment]
From the README.md I guess, link is now fixed: http://cloudera.github.io/hue/latest/administrator/installation/

Thanks!

**Comment by chozee** [comment]
> From the README.md I guess, link is now fixed: http://cloudera.github.io/hue/latest/administrator/installation/
> 
> Thanks!

Thanks!
