### ISSUE TITLE
centos6.5 can't install python2.7-devel

### ISSUE THREAD

**Issue by wuli-IU** [cloudera/hue#820]
I was facing the issue when excuting make apps:
    "Error: must have python development packages for 2.7. Could not find Python.h. Please install python2.7-devel". Stop.
     the default version of python-devel is 2.6.6 in centos6.5, how can i upgrade it to 2.7 ?

**Comment by wuli-IU** [comment]
"Error: must have python development packages for 2.7. Could not find Python.h. Please install python2.7-devel".  Stop.

**Comment by wuli-IU** [comment]
the default version of python-devel is 2.6.6 in centos6.5, how can i upgrade it to 2.7

**Comment by romainr** [comment]
Only Centos 6.8 and more are tested/supported starting from Hue 4.3
http://cloudera.github.io/hue/latest/administrator/installation/dependencies/#centos-6-8-6-9-os

If you need Hue 4.2 or less
