### ISSUE TITLE
ReOpen of #460 Spark launches in default queue in yarn

### ISSUE THREAD

**Issue by alericmckearn** [cloudera/hue#828]
https://github.com/cloudera/hue/blob/f4200095475573b3df73a95aeb495436d5df0c28/desktop/libs/notebook/src/notebook/connectors/spark_shell.py#L44

Why Reopen => With the changes to YARN in 3.0 (especially docker), Hue may need to own more of these properties instead of blacklisting them in Livy.  Additionally, Livy [blacklisting](https://github.com/cloudera/livy/blob/9ae24d08738652ba5fd817780711d01b110d74a9/conf/spark-blacklist.conf.template) will need to be extended from not only properties, but values in properties or values in properties by user.

**Use Cases**
Queues => Queue for GPU, Queue for CPU
Spark Settings => Multiple docker container types to solve individual use cases (docker for tensorflow, docker for pandas/numpy or whatever python 3.x library we don't want to install everywhere, Internal connection to Yarn Services by connecting their docker to a specific overlay network.

General Code Flow:
Default values for the livy spark call are overridable from hue.ini (so add to conf.py)
The values pre-populate the pyspark session boxes for change
example => spark.yarn.appMasterEnv.YARN_CONTAINER_RUNTIME_DOCKER_IMAGE:foo

Issues:  The primary issue is Limiting the Docker Images available to be pulled into the cluster.  There is some protection in yarn with approved repos, but this still allows a user to pull in a production code docker container and do "bad things".  This isn't something that can be handled through hue alone but will probably need a combination of hue/livy.

**Comment by romainr** [comment]
This would make sense to have those more configurable via ini.

About Livy itself, the project was moved to https://livy.incubator.apache.org/ so probably better to coordinate there too.

**Comment by alericmckearn** [comment]
https://github.com/cloudera/hue/pull/859

**Comment by alericmckearn** [comment]
This is the first pass that just exposes the base variables.

Tasks left:
--tweaking the knockout view model to pre-populate the boxes
--getting the session window boxes to be a little more long string friendly
--adding the ability (probably via roles) to restrict certain variables to certain user types
--adding a special section for docker that is populated from a pre-defined list in hue.ini
