### ISSUE TITLE
Documentation/Code mismatch for HBase SSL

### ISSUE THREAD

**Issue by alericmckearn** [cloudera/hue#838]
The confusing line here is "full name with security".  Suggestion is to change wording from:

Use full hostname with security.

"Use full hostname.  If hbase.thrift.ssl.enabled in hbase-site is set to true, https will be used otherwise it will use http"

https://github.com/cloudera/hue/blob/79dfa617e63c188848ffc19dd084a9d3233f91a8/apps/hbase/src/hbase/api.py#L104

https://github.com/cloudera/hue/blob/79dfa617e63c188848ffc19dd084a9d3233f91a8/desktop/conf.dist/hue.ini#L1376

**Comment by jdesjean** [comment]
Agreed! Please do a pull request.

**Comment by alericmckearn** [comment]
https://github.com/alericmckearn/hue/pull/1

**Comment by jdesjean** [comment]
If you push to cloudera/hue:master, I can merge it.

**Comment by alericmckearn** [comment]
moved it to master

**Comment by romainr** [comment]
Fixed in https://github.com/cloudera/hue/pull/840, thank you everybody!
