### ISSUE TITLE
SQL queries cannot display results, and the terminal will often display "gc: uncollectable <instancemethod 0x7f64642*****>"

### ISSUE THREAD

**Issue by IVitamin-C** [cloudera/hue#846]
Hello
When I was making SQL query, I could not display the result, and the terminal displayed "gc: uncollectable <instancemethod 0x7f93ec24fb90>"

I copied the parameter from hue4.3 to hue4.4
In the same cluster, hue4.4 cannot be queried and there is no queried SQL in the yarn
At the same time, gc frequently occurs in the terminal, which is not found in hue4.3. The computer memory is sufficient

How should this problem be solved
Thanks

hue4.4
![image](https://user-images.githubusercontent.com/35019926/56376422-5aa68b00-623a-11e9-86c2-28a767d29cf1.png)

![image](https://user-images.githubusercontent.com/35019926/56375883-35fde380-6239-11e9-9596-c850fec5bb38.png)
![image](https://user-images.githubusercontent.com/35019926/56376050-8f661280-6239-11e9-8c4a-06e9cdaa6bc3.png)
hue4.3

![image](https://user-images.githubusercontent.com/35019926/56376198-d227ea80-6239-11e9-9f1d-5460c4398349.png)

**Comment by romainr** [comment]
Task Server is a work in progress still, it is recommended to keep it off

[desktop]
[[task_server]]
enabled=true


PS: @jdesjean The "leak" messages I was talking about the other day

**Comment by IVitamin-C** [comment]
Thanks.

**Comment by IVitamin-C** [comment]
But after I carried out the operation according to you, I found that the situation of my last problem appeared again,

[desktop]
[[task_server]]
enabled=true
![image](https://user-images.githubusercontent.com/35019926/56400281-adf1fb00-6285-11e9-9f26-2db546298085.png)

[desktop]
[[task_server]]
enabled=false
![image](https://user-images.githubusercontent.com/35019926/56400328-f14c6980-6285-11e9-87ac-1e20c9048a8f.png)
![image](https://user-images.githubusercontent.com/35019926/56400346-0aedb100-6286-11e9-9f8f-e235380c3637.png)

This is the problem I mentioned in the last issue, I thought it has been solved,
[issues/845](https://github.com/cloudera/hue/issues/845)

yarn conf

![image](https://user-images.githubusercontent.com/35019926/56400674-b0edeb00-6287-11e9-977b-979ae50a868d.png)

**Comment by IVitamin-C** [comment]
And "gc: uncollectable"  occurs only when task server is turned on

**Comment by IVitamin-C** [comment]
I deleted the database hue created in mysql before, and after re-creating it, it can run normally without any error of 'statement'
