### ISSUE TITLE
Hue memory leak serious

### ISSUE THREAD

**Issue by fsilent** [cloudera/hue#848]
I use Hue3.11.0, and runcpserver process has memory leak, More than 150 G of memory has been consumed。
 I find when I refresh hivequery page, the memory grows。and I keep retrying, and when I find that the memory is full, the memory will drop.  and the log show"Retrying with a new session because for...Invalid SessionHandle"。

log when I query, always show Check status,but get a QueryError fail
[26/Apr/2019 12:06:14 +0800] api          INFO     Check status for 319, but get a QueryError fail.
[26/Apr/2019 12:06:15 +0800] views        INFO     requst Server is: hive
[26/Apr/2019 12:06:15 +0800] hiveserver2  WARNING  Could not close previous multiquery query

**Comment by hueadmin** [comment]
Would recommend to move to 4.4 version (2.5 years more recent): http://cloudera.github.io/hue/latest/#releases

Read about queries lifecycles: http://gethue.com/hadoop-tutorial-hive-and-impala-queries-life-cycle/

And follow this jira that should move a lot of the resource fragmentation: https://issues.cloudera.org/browse/HUE-2142

**Comment by romainr** [comment]
Would recommend to move to 4.4 version (2.5 years more recent): http://cloudera.github.io/hue/latest/#releases

Read about queries lifecycles: http://gethue.com/hadoop-tutorial-hive-and-impala-queries-life-cycle/

And follow this jira that should move a lot of the resource fragmentation: https://issues.cloudera.org/browse/HUE-2142

**Comment by fsilent** [comment]
i set close_queries=true in hue,ini， but i can`t use ./build/env/bin/hue close_queries 0 command. 
I set hive.server2.session.check.interval=3000,  hive.server2.idle.session.timeout=3000, hive.server2.idle.operation.timeout=0 in hiveserver hive-site.xml and restart hiveserver, but when I refresh queryEditor there's still an increase in memory. But occasionally there's little growth.
Is there any way to replace the close_queries command?
Thank you very much!

**Comment by fsilent** [comment]
When I delete the query history, the deletion does not fall. 
Create a new user, login hue and delete the user. 
And Using the old user to delete the history is successful, then the memory is no longer growing.

So, is memory growth because there are too many query records?
