### ISSUE TITLE
How can you use spark SQL to display databases and tables in the left-hand column of the database display?

### ISSUE THREAD

**Issue by IVitamin-C** [cloudera/hue#850]
Hello, 
How can you use spark SQL to display databases and tables in the left-hand column of the database display? When I used spark thriftserver, port 10000, the hive metastore I used, but I can see which databases are available through SQL query, but only the default database is displayed in the left-hand column. 
Thanks.

**Comment by TimKingNF** [comment]
How you solve this question?

**Comment by IVitamin-C** [comment]
This is done by modifying the code in hiveserver.py, but because I did not write the code, the programmer who modified it is submitting it for official review

**Comment by TimKingNF** [comment]
Could you show me the code or links about this error?  I can't find it in PR.

**Comment by IVitamin-C** [comment]
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/hiveserver2.py

**Comment by TimKingNF** [comment]
I try to rebuild my hue. But the problem is still. 

When I access the url `http://localhost:8000/notebook/api/autocomplete/default` with request's body like
```
snippet: {"type":"sparksql","source":"data"}
cluster: {"interface":"all","server_host":"all","type":"direct","id":"default","name":"default"}
```

 It calls `TCLIService.GetTables` (https://github.com/cloudera/hue/blob/fd5cbb9edf88ace944d021ada8e0a6d3972686ca/apps/beeswax/src/beeswax/server/hive_server2_lib.py#L790), But return empty results in results.

And Spark-hive-thrift2 log like this.
```
2019-05-20 17:43:11 INFO  HiveMetaStore:746 - 3: get_databases: default
2019-05-20 17:43:11 INFO  audit:371 - ugi=hadoop        ip=unknown-ip-addr      cmd=get_databases: default
2019-05-20 17:43:11 INFO  HiveMetaStore:746 - 3: get_databases: default
2019-05-20 17:43:11 INFO  audit:371 - ugi=hadoop        ip=unknown-ip-addr      cmd=get_databases: default
2019-05-20 17:43:11 INFO  HiveMetaStore:746 - 3: get_tables: db=default pat=*
2019-05-20 17:43:11 INFO  audit:371 - ugi=hadoop        ip=unknown-ip-addr      cmd=get_tables: db=default pat=*
2019-05-20 17:43:11 INFO  HiveMetaStore:746 - 3: get_multi_table : db=default tbls=
2019-05-20 17:43:11 INFO  audit:371 - ugi=hadoop        ip=unknown-ip-addr      cmd=get_multi_table : db=default tbls=
```

I'm not sure what caused the problem, it looks like some configuration error or others.

**Comment by IVitamin-C** [comment]
This is because hiveserver2 and spark-thriftserver are different when it comes to library table status updates, so you need an additional method to get the library and table status updates

**Comment by TimKingNF** [comment]
How can I resolve this problem? Thx !!!

**Comment by IVitamin-C** [comment]
The programmer who modified it is submitting it for official review.Please wait for the official code modification

**Comment by TimKingNF** [comment]
Okay! Thx for your answer.

**Comment by IVitamin-C** [comment]
Hue-8843 is available through code review, but currently only runs spark- SQL on spark-thriftserver.If you configure hive to run on the same port, there will still be problems, but the basic problem has been solved @TimKingNF
