### ISSUE TITLE
How to use pyspark in hue notebook?

### ISSUE THREAD

**Issue by digitalbull** [cloudera/hue#857]
We googled a lot,  add some config,

```
[desktop]
use_new_editor=true

[notebook]
show_notebooks=true
```
Then we can open notebook, but can't  import pyspark.

How can we get the use pysarpk in Hue notebook?

**Comment by IVitamin-C** [comment]
If you want to use pyspark in hue, you first need livy, which is 0.5.0 or higher.
Configure livy services and start them up,
If you need to use pyspark to connect hive to get data, you need to set "livy. Repl. Enable-hive -context = true" in livy.conf.
Then configure in hue：
![image](https://user-images.githubusercontent.com/35019926/57435490-1eca7880-7270-11e9-8f7a-4829d74ae82d.png)
At this time, there will be a pyspark job start in hue, and then start editing your code, and then start running. It should be noted that remember to close 'sparkContext' to release resources after all jobs have finished running
![image](https://user-images.githubusercontent.com/35019926/57436257-ed52ac80-7271-11e9-8eea-291729a76214.png)

**Comment by digitalbull** [comment]
I find the highest version on https://github.com/cloudera/livy is 0.4.0, where can i get 0.5.0 or higher ?

**Comment by digitalbull** [comment]
Hi IVitamin-C, 

I have the livy 0.6.0 installed, and the log:

```
19/05/09 18:01:25 INFO server.AccessManager: AccessControlManager acls disabled;users with view permission: ;users with modify permission: ;users with super permission: ;other allowed users: *
19/05/09 18:01:25 INFO utils.LineBufferedStream: WARNING: User-defined SPARK_HOME (/opt/cloudera/parcels/CDH-6.2.0-1.cdh6.2.0.p0.967373/lib/spark) overrides detected (/opt/cloudera/parcels/CDH/lib/spark).
19/05/09 18:01:25 INFO utils.LineBufferedStream: WARNING: Running spark-class from user-defined location.
19/05/09 18:01:26 INFO utils.LineBufferedStream: Welcome to
19/05/09 18:01:26 INFO utils.LineBufferedStream:       ____              __
19/05/09 18:01:26 INFO utils.LineBufferedStream:      / __/__  ___ _____/ /__
19/05/09 18:01:26 INFO utils.LineBufferedStream:     _\ \/ _ \/ _ `/ __/  '_/
19/05/09 18:01:26 INFO utils.LineBufferedStream:    /___/ .__/\_,_/_/ /_/\_\   version 2.4.0-cdh6.2.0
19/05/09 18:01:26 INFO utils.LineBufferedStream:       /_/
19/05/09 18:01:26 INFO utils.LineBufferedStream:                         
19/05/09 18:01:26 INFO utils.LineBufferedStream: Using Scala version 2.11.12, OpenJDK 64-Bit Server VM, 1.8.0_212
19/05/09 18:01:26 INFO utils.LineBufferedStream: Branch HEAD
19/05/09 18:01:26 INFO utils.LineBufferedStream: Compiled by user jenkins on 2019-03-14T07:01:24Z
19/05/09 18:01:26 INFO utils.LineBufferedStream: Revision HEAD
19/05/09 18:01:26 INFO utils.LineBufferedStream: Url 
19/05/09 18:01:26 INFO utils.LineBufferedStream: Type --help for more information.
19/05/09 18:01:26 INFO recovery.StateStore$: Using BlackholeStateStore for recovery.
19/05/09 18:01:26 INFO sessions.BatchSessionManager: Recovered 0 batch sessions. Next session id: 0
19/05/09 18:01:26 INFO sessions.InteractiveSessionManager: Recovered 0 interactive sessions. Next session id: 0
19/05/09 18:01:26 INFO sessions.InteractiveSessionManager: Heartbeat watchdog thread started.
19/05/09 18:01:26 INFO util.log: Logging initialized @1490ms
19/05/09 18:01:26 INFO server.Server: jetty-9.3.24.v20180605, build timestamp: 2018-06-06T01:11:56+08:00, git hash: 84205aa28f11a4f31f2a3b86d1bba2cc8ab69827
19/05/09 18:01:26 INFO handler.ContextHandler: Started o.e.j.s.ServletContextHandler@1522d8a0{/,file:///opt/apache-livy-0.6.0-incubating-bin/src/main/org/apache/livy/server,AVAILABLE}
19/05/09 18:01:26 INFO server.AbstractNCSARequestLog: Opened /opt/apache-livy-0.6.0-incubating-bin/logs/2019_05_09.request.log
19/05/09 18:01:26 INFO server.AbstractConnector: Started ServerConnector@77a98a6a{HTTP/1.1,[http/1.1]}{0.0.0.0:8998}
19/05/09 18:01:26 INFO server.Server: Started @1674ms
19/05/09 18:01:26 INFO server.WebServer: Starting server on http://cdh.n1.com:8998

```

I set up hue_safety_valve.ini like:

```
[desktop]
use_new_editor=true
[notebook]
show_notebooks=true
[spark]
name=Scala
interface=livy
[pyspark]
name=PySpark
interface=livy
[r]
name=R
interface=livy

```
but i still can't get the Scala, PySpark

![m](https://user-images.githubusercontent.com/50133976/57446179-b6d35c80-7286-11e9-9762-d9fabef81e3a.png)

Another question, in notebook,  i can't get any space let me to code.

![Screenshot from 2019-05-09 18-18-48](https://user-images.githubusercontent.com/50133976/57446321-02860600-7287-11e9-841e-70d66c6bf0af.png)

**Comment by IVitamin-C** [comment]
Your hue. Ini did not follow the correct naming convention

**Comment by digitalbull** [comment]
Could you please get more detail ?

**Comment by IVitamin-C** [comment]
[notebook]

 ## Show the notebook menu or not
  show_notebooks=true

  ## Flag to enable the selection of queries from files, saved queries into the editor or as snippet.
  enable_external_statements=true

  ## Flag to enable the bulk submission of queries as a background task through Oozie.
  enable_batch_execute=true

  ## Flag to turn on the SQL indexer.
  enable_sql_indexer=false

  ## Flag to turn on the Presentation mode of the editor.
  enable_presentation=true

  ## Flag to enable the SQL query builder of the table assist.
  enable_query_builder=true

  ## Flag to enable the creation of a coordinator for the current SQL query.
  enable_query_scheduling=false

  ## Main flag to override the automatic starting of the DBProxy server.
  # enable_dbproxy_server=true

  ## Classpath to be appended to the default DBProxy server classpath.
  # dbproxy_extra_classpath=

  ## Comma separated list of interpreters that should be shown on the wheel. This list takes precedence over the
  ## order in which the interpreter entries appear. Only the first 5 interpreters will appear on the wheel.
  # interpreters_shown_on_wheel=

  # One entry for each type of snippet.
  [[interpreters]]
    # Define the name and how to connect and execute the language.

    [[[hive]]]
      # The name of the snippet.
      name=Hive
      # The backend connection to use to communicate with the server.
      interface=hiveserver2

    [[[impala]]]
      name=Impala
      interface=hiveserver2

    [[[mysql]]]
      name = MySQL
      interface=sqlalchemy
      ## https://docs.sqlalchemy.org/en/latest/dialects/mysql.html
      ## options='{"url": "mysql://root:root@localhost:3306/hue"}'
      options='{"url": "mysql://hue:hue@localhost:3306/hue"}'

    [[[sparksql]]]
      name=SparkSql
      interface=hiveserver2
    [[[spark]]]
      name=Scala
      interface=livy

    [[[pyspark]]]
      name=PySpark
      interface=livy

    [[[r]]]
      name=R
      interface=livy

**Comment by digitalbull** [comment]
Thanks the kindly repay,  now i got,

![Screenshot from 2019-05-09 19-42-09](https://user-images.githubusercontent.com/50133976/57451045-b17c0f00-7292-11e9-9797-f52f7c3df138.png)

So, I think maybe I need to do some setup which let hue in CDH know the livy, in my CDH there is no livy, the entry backend by livy is not working. have any ideal about it?

**Comment by IVitamin-C** [comment]
Due to the performance of the virtual machine, I did not use CDH, so I am sorry that I cannot give better advice, my configuration is based on my own cluster.

**Comment by IVitamin-C** [comment]
You can try this website's approach. https://cloud.tencent.com/developer/article/1078797

**Comment by IVitamin-C** [comment]
You can try this website's approach, 
https://plenium.wordpress.com/2017/11/13/install-hue-spark-notebook-with-livy-on-cloudera/

**Comment by romainr** [comment]
If using Cloudera Manager, you would need to un blacklist spark:

```
[desktop]
app_blacklist=

[notebook]
  show_notebooks=true

 [[interpreters]]
    # Define the name and how to connect and execute the language.

    [[[impala]]]
      name=Impala
      interface=hiveserver2

    [[[hive]]]
      # The name of the snippet.
      name=Hive
      interface=hiveserver2

    [[[sql]]]
      name=SparkSql
      interface=livy

    [[[pyspark]]]
      name=PySpark
      interface=livy

[spark]
	livy_server_host=livy-host.com
```

Will see for updating the documentation. Note that SparkSql support is getting better.

Selecting an existing Livy session for a notebook is not implemented yet.

**Comment by IVitamin-C** [comment]
Hello, when can I get the database and table information using spark thriftserver, just like using hiveserver2 Thanks 
@romainr

**Comment by digitalbull** [comment]
@romainr @IVitamin-C  thanks. It works.
