### ISSUE TITLE
How to use a mobile phone get data from hue

### ISSUE THREAD

**Issue by FivredSeven** [cloudera/hue#858]
i am a android developer.  I want to use a android phone to get hue data, but i meet some problem .
for example   I request beeswax/query_histroy by okhttp  and expect response Content-type application/json data, but  I get the response Content-Type is text/javascripe.

what can I do?

**Comment by romainr** [comment]
There is not clean public API until https://issues.cloudera.org/browse/HUE-1450. For now have you tried to mimick what you see in the Chrome developer console 'Network tab' 'XHR' request for this call?

**Comment by FivredSeven** [comment]
> There is not clean public API until https://issues.cloudera.org/browse/HUE-1450. For now have you tried to mimick what you see in the Chrome developer console 'Network tab' 'XHR' request for this call?

Hi romainr:
    thank you for reply.
    I have tried for it.The request is http://10.16.4.179:8888/beeswax/query_history?format=json. In Chrome Network tab 'XHR',request header like this:
    
    ```
Accept: application/json, text/javascript, */*; q=0.01
    Accept-Encoding: gzip, deflate
    Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
    Connection: keep-alive
    Cookie: __utmz=93547165.1550022297.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmc=93547165; __utma=93547165.2037611540.1550022297.1557478896.1557718665.135; __utmt=1; csrftoken=kqEpp01TMgRS72dySFgGWDjEROwatJUF; sessionid=gm18pf5nirb6ieussjbpnxk4czltc1ci; __utmb=93547165.3.10.1557718665
    Host: 10.16.4.179:8888
    Referer: http://10.16.4.179:8888/beeswax/
    User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like 
    Gecko) Chrome/66.0.3359.139 Mobile Safari/537.36
    X-CSRFToken: kqEpp01TMgRS72dySFgGWDjEROwatJUF
    X-Requested-With: XMLHttpRequest
```
and the response like this
    ```
    Content-Language: zh-cn
    Content-Length: 159776
    **Content-Type: application/json**
    Date: Mon, 13 May 2019 03:44:06 GMT
    Server: CherryPy/3.1.2 WSGI Server
    Vary: Accept-Language, Cookie
    X-Frame-Options: SAMEORIGIN
    ```


then my mobile phone request is as same as chrome, but the response is **Content-Type: text/javascript**

I do not know what the problem is

**Comment by romainr** [comment]
Would recommend to do the equivalent of http://cloudera.github.io/hue/latest/developer/api/

**Comment by FivredSeven** [comment]
> Would recommend to do the equivalent of http://cloudera.github.io/hue/latest/developer/api/

I am sorry that  I can not open this page.Maybe the Internet is not allowed
