### ISSUE TITLE
Hue automatically quits?

### ISSUE THREAD

**Issue by zfs9521** [cloudera/hue#864]
My hue will quit after running for a while, and then I need to reboot every time to use it.

**Comment by romainr** [comment]
Please share the logs, version, and check the usage memory if it grows. I

**Comment by zfs9521** [comment]
I am using a remote cloud server connected by ssh. Using the supervisor > /home/hadoop/app/hue/log/hue.log 2>&1 & command, and then closing the terminal tool, hue can't access it.

**Comment by zfs9521** [comment]
Oh, I changed the command to nohup supervisor > /home/hadoop/app/hue/log/hue.log 2>&1 &, this problem has been solved, thank you.
