### ISSUE TITLE
/Users/hemprasadkenderi/PycharmProjects/hue/build/env/bin/2to3-

### ISSUE THREAD

**Issue by hemprasadk** [cloudera/hue#868]
I am trying to compile Hue and getting the following error

/Library/Developer/CommandLineTools/usr/bin/make -C core env-install
/bin/bash: /Users/hemprasadkenderi/PycharmProjects/hue/build/env/bin/2to3-: No such file or directory
/bin/bash: /Users/hemprasadkenderi/PycharmProjects/hue/build/env/bin/2to3-: No such file or directory
/bin/bash: /Users/hemprasadkenderi/PycharmProjects/hue/build/env/bin/2to3-: No such file or directory
/bin/bash: /Users/hemprasadkenderi/PycharmProjects/hue/build/env/bin/2to3-: No such file or directory
/bin/bash: /Users/hemprasadkenderi/PycharmProjects/hue/build/env/bin/2to3-: No such file or directory
/bin/bash: /Users/hemprasadkenderi/PycharmProjects/hue/build/env/bin/2to3-: No such file or directory
/bin/bash: /Users/hemprasadkenderi/PycharmProjects/hue/build/env/bin/2to3-: No such file or directory
/bin/bash: /Users/hemprasadkenderi/PycharmProjects/hue/build/env/bin/2to3-: No such file or directory
--- Building egg for Babel-2.5.1
/bin/bash: /Users/hemprasadkenderi/PycharmProjects/hue/build/env/bin/2to3-: No such file or directory
make[2]: *** [/Users/hemprasadkenderi/PycharmProjects/hue/desktop/core/build/Babel-2.5.1/egg.stamp] Error 127
make[1]: *** [.recursive-env-install/core] Error 2
make: *** [desktop] Error 2

**Comment by romainr** [comment]
Did you install the dependencies https://docs.gethue.com/latest/administrator/installation/dependencies/ ?

**Comment by ankit167** [comment]
@romainr 404 not found.
Could you help update the link?
