### ISSUE TITLE
Uncaught ReferenceError: x is not defined

### ISSUE THREAD

**Issue by chozee** [cloudera/hue#872]
Environment:
Centos6.9
npm 6.7.0
HUE 4.3.0

Databases can't show on the left of the query of hive in Notebook .
The error is 
`Uncaught ReferenceError: x is not defined`
in ko.foreachVisible.js :
`    let visibleEntryCount = 0;
    let incrementLimit = 0; // The diff required to re-render, set to visibleCount below
    let elementIncrement = 0; // Elements to add on either side of the visible elements, set to 3x visibleCount

    const updateVisibleEntryCount = function() {
      // TODO: Drop the window innerHeight limitation.
      // Sometimes after resizeWrapper() is called the reported innerHeight of the $container is the same as
      // the wrapper causing the binding to render all the items. This limits the visibleEntryCount to the
      // window height.
      const newEntryCount = Math.ceil(
        Math.min($(window).innerHeight(), $container.innerHeight()) / entryMinHeight
      );
      if (newEntryCount !== visibleEntryCount) {
        const diff = newEntryCount - visibleEntryCount;
        elementIncrement = options.elementIncrement || 25;
        incrementLimit = options.incrementLimit || 5;
        visibleEntryCount = newEntryCount;
        endIndex += diff;
        huePubSub.publish('foreach.visible.update', id);
      }
    };`

**Comment by romainr** [comment]
Still there with Hue 4.4 or master (~4.5)?
