### ISSUE TITLE
Hue got the hive real-time log

### ISSUE THREAD

**Issue by prosscode** [cloudera/hue#873]
I thought about how Hue got the real-time log when executing hive sql. What point should I get from knowing?

**Comment by jdesjean** [comment]
Could you please clarify your question?

**Comment by prosscode** [comment]
> Could you please clarify your question?

sorry.
I want to find out how the real-time log is obtained when hive SQL is executed. The execution engine is MR.So far I've traced all of the api. py under desktop/libs/notebook from the web requests and found this code `logs = smart_str(db.get_log(notebook, snippet, startFrom=startFrom, size=size))`.
I want to keep track of it. what else can i do?
thanks.
