### ISSUE TITLE
Hue 4.4 Centos 6.9 Python erro when Make and Build Application

### ISSUE THREAD

**Issue by eurocley** [cloudera/hue#874]
Dear Cloudera Hue friends.  
As a data arch was requested to me install this HUE tool as a test application for evaluation by my director, infortunelly I found some problems follow the instructions installation web site, in this case  by quick install from GIT, the same problema happen when I try compile using mavem from source code.  
Please someonte can keep on eye in this version release, because it's look no stable,  and any help will be really apreciate and welcome.

Best regards, thank you. 
Cleyson Barros from Lisbon - EU
[Issue Report Hue 4v4.docx](https://github.com/cloudera/hue/files/3228263/Issue.Report.Hue.4v4.docx)

**Comment by romainr** [comment]
Please make sure you installed the dependencies https://docs.gethue.com/latest/administrator/installation/dependencies/ or use the Docker / Kubernetes versions https://github.com/cloudera/hue#docker

**Comment by eurocley** [comment]
Hello Romain
All dependencies are installed according information in the dependencies section of installation manual. 
I not understand why this error show up one time all is done properly, please check the images in the DOC to check the case before close it.  May be this happen only by a simple change in the source code. 
Best regards, 
Cleyson
