### ISSUE TITLE
set up concurrent_user_session_limit=1 on hue.ini but  not effective after setting up

### ISSUE THREAD

**Issue by royluoyu** [cloudera/hue#875]
I set concurrent_user_session_limit=1(default value is 0) on hue.ini, restart the service after setup
 but  not effective 

hue version:cdh6.1+4.3.0

**Comment by jdesjean** [comment]
What results are you expecting and not seeing?

**Comment by royluoyu** [comment]
I want to use this parameter to control that each account can only be logged in by one person at the same time

**Comment by jdesjean** [comment]
What authentication backend are you using?
[desktop]
[[auth]]
backend=

How are you testing that this parameter has no effect?
