### ISSUE TITLE
how to limit hive query history records

### ISSUE THREAD

**Issue by fsilent** [cloudera/hue#876]
When you get the Hive query history, all records for a user are found and placed in memory. If a user has a particularly large number of records, the memory can be particularly high. How do I limit the number of history records returned to memory, such as 20 records

![image](https://user-images.githubusercontent.com/9815890/58679816-a13de800-8397-11e9-8fb1-18c008f2f2ee.png)

**Comment by romainr** [comment]
Are you sure about this?
The query history should have a limit 50 per default:
`Request URL: http://demo.gethue.com/notebook/api/get_history?doc_type=hive&limit=50&page=1&doc_text=&is_notification_manager=false&_=1559319046886
`

**Comment by fsilent** [comment]
But I have a question, when there are only 10 historical records, hue memory consumes 80MB, and when there are 10,000 records, there is 200 MB of memory, which looks like the more history, the higher the memory footprint, what is the reason of this?

**Comment by romainr** [comment]
I would recommend to profile Hue to be exactly sure of what is happening, e.g. SQL query generated 
http://gethue.com/get-a-mode-to-allow-easy-profiling-of-requests/

**Comment by fsilent** [comment]
I found out the reason, when I commented out the three lines, the memory no longer grew. I use Hue 3.11.0, How do I change the code here?
![image](https://user-images.githubusercontent.com/9815890/58772936-cd52a680-85ed-11e9-8924-135d43686ef7.png)

**Comment by fsilent** [comment]
![image](https://user-images.githubusercontent.com/9815890/58774044-481dc080-85f2-11e9-813b-bf152f74281f.png)
I add this parameter when query history and the problem resolved.

**Comment by romainr** [comment]
Hue 3.11 is extremely old, would recommend to use 4.5 instead.

In master the default is not to includd trashed history: https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/models.py#L989
