### ISSUE TITLE
Unable login using "supervisor" after hue is compiled.

### ISSUE THREAD

**Issue by IVitamin-C** [cloudera/hue#878]
hello
Unable login using "supervisor" after hue is compiled.
“Http404: "/usr/local/hue/build/static/desktop/js/bundles/login/login-bundle-b93a261a199a39dfd42e.js" does not exist“
![image](https://user-images.githubusercontent.com/35019926/58755429-71691e80-8516-11e9-9114-b0160658fb4f.png)
![image](https://user-images.githubusercontent.com/35019926/58755432-88a80c00-8516-11e9-8f34-b31257d85875.png)
version:hue master lastest.
I have tried it many times and get the same result every time.
Thanks!

**Comment by romainr** [comment]
There is an issue with the static file collection, I am looking at it

**Comment by romainr** [comment]
And should be fixed after https://review.cloudera.org/r/14002/

**Comment by IVitamin-C** [comment]
Thanks,Romain

**Comment by romainr** [comment]
https://issues.cloudera.org/browse/HUE-8866 pushed to master.

Please re-open if needed.
