### ISSUE TITLE
[desktop] notebook/browse/  view gives 404 response in hue 4.4

### ISSUE THREAD

**Issue by dncnbuck** [cloudera/hue#884]
I am trying to access the `hue/notebook/browse/<database>/<table>` endpoint in hue 4.4 in order to browse table results. 

It appears that the `hue/notebook/browse/<database>/<table>` view is no longer working in hue 4.4 and I receive a 404 response

From desktop/lib/notebook/urls.py I can see the url is still present

```python
url(r'^browse/(?P<database>\w+)/(?P<table>\w+)/(?P<partition_spec>.+?)?$', notebook_views.browse, name='browse'),
```

Is there some way of still accessing this view with a get request?

**Comment by romainr** [comment]
How do you access the page?

Currently: right click on a table in the left assist and "Open in Editor" calls it under the cover

**Comment by dncnbuck** [comment]
We are truing to access the the page from a direct url link, which would open the editor with a limit 100 query. 
For example the url 
https://demo.gethue.com/hue/notebook/browse/foo/bar
 would result in an editor with the executed query 
 "SELECT * FROM `foo`.`bar` LIMIT 100"

We recently upgraded from version 3.12 where this endpoint was accessible and I would love to find a way to have this view accessible once again.

**Comment by romainr** [comment]
Indeed, it is not implemented, and probably need changes in

https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/templates/hue.mako#L521
https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/js/onePageViewModel.js#L593
