### ISSUE TITLE
Webpack-cli ^3.2.1 throws error on opencollective.js on second make apps

### ISSUE THREAD

**Issue by alericmckearn** [cloudera/hue#891]
Error: Cannot find module '/data/hue/node_modules/webpack-cli/bin/opencollective.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.10.0-957.12.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! webpack-cli@3.3.4 postinstall: `node ./bin/opencollective.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-cli@3.3.4 postinstall script 'node ./bin/opencollective.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/opencollective.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-cli
npm ERR! There is likely additional logging output above.

**Comment by alericmckearn** [comment]
basically, what is happening here is that webpack-cli is trying to prompt us to donate during the npm install and it is locked out.  there is a fix in later versions that suppresses this during install.

**Comment by romainr** [comment]
@JohanAhlen ?

**Comment by alericmckearn** [comment]
looks like you can get around it with npm install webpack-cli --ignore-scripts

**Comment by alericmckearn** [comment]
https://github.com/webpack/webpack-cli/issues?q=is%3Aissue+opencollective+is%3Aclosed

**Comment by JohanAhlen** [comment]
I'm not able to reproduce this, it seems like your node version is a bit old. Last comment in https://github.com/webpack/webpack-cli/issues/889 suggests that it should be >6.

I run node v11.3.0 and npm v6.4.1

**Comment by alericmckearn** [comment]
an an FYI, yum install npm downloads node 6.12, npm 3.12.

I upgraded to the latest version of both and will restart.

**Comment by alericmckearn** [comment]
12.4/6.9.0 works.  
for rhel
curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -
yum install nodejs
