### ISSUE TITLE
Hue 4.4 missing AceSqlWorker

### ISSUE THREAD

**Issue by alericmckearn** [cloudera/hue#892]
![image](https://user-images.githubusercontent.com/6674285/59971830-c35efc00-9538-11e9-9cd8-a80af424d09c.png)

Based on where it is looking for the ace js, it looks like it should be in the workers webpack

![image](https://user-images.githubusercontent.com/6674285/59971610-11bdcc00-9534-11e9-8256-391edca67e19.png)

I know this works as this is the webpack load from gethue.com demo

![image](https://user-images.githubusercontent.com/6674285/59971617-31ed8b00-9534-11e9-90e0-a7695e4776d7.png)

so is make ace supposed to modify the workers config?

**Comment by romainr** [comment]
They should be there cf. these https://github.com/cloudera/hue/blob/release-4.4.0/Makefile#L157 but maybe the prod tarball has an issue, would need to check.

When in dev, `npm run dev` or `make apps`.

**Comment by alericmckearn** [comment]
Tried:
--make apps (as the server directory)

--make apps
--make install
--copy webpacks

--make ace
--make apps

--make ace
--make apps
--make install
--copy webpacks

i'll try npm dev run

**Comment by JohanAhlen** [comment]
aceSqlSyntaxWorker.js is not a static resource and it's served by a Hue API:

https://github.com/cloudera/hue/blob/master/desktop/core/src/desktop/urls.py#L121

But it seems like that request generates a 500 error for you so check the Hue logs to see why it fails.

Those workers do require some webpack bundles and they're generated with "npm run webpack-workers".

**Comment by alericmckearn** [comment]
works in current master.  closing
