### ISSUE TITLE
4.4: Make Install doesn't copy webpacks to /usr/local/hue

### ISSUE THREAD

**Issue by alericmckearn** [cloudera/hue#893]
when you copy the webpacks.json they point to the build directory (so it can't be deleted).

**Comment by romainr** [comment]
Hum, was it tried from Hue 4.4 or master?

A good example is:
https://github.com/cloudera/hue/blob/master/tools/docker/hue/Dockerfile#L50

where now it should copy and generates the bundles:
https://github.com/cloudera/hue/blob/master/Makefile#L215

But 4.4 is probably broken. Will check with 4.5 as we should release it next week I think.

**Comment by alericmckearn** [comment]
yeah i'm testing everything on master right now.  these just came up as i was tracking down that ace error.

**Comment by alericmckearn** [comment]
confirming this works correctly in master

**Comment by romainr** [comment]
Good, so if it is fine on master, we can close this one and see for a 4.5 release in early July.
