### ISSUE TITLE
[HBase Brower] api error throw when search hbase with rowkey startwith '0'

### ISSUE THREAD

**Issue by linwukang** [cloudera/hue#894]
search hbase with rowkey startwith '0', '010001' for example, got api error exception due to the failure of convert requet to json object. the parameters queries pass to the method getRowQuerySet in 'apps/hbase/src/hbase/api.py, line 217' is an unicode object rather than a Python list.

**Comment by romainr** [comment]
Thanks!

https://github.com/cloudera/hue/commit/70d518e13d76a8c9464f2a0b3a4364087a3180fc
