### ISSUE TITLE
[SQL Editor] failed to list query history when there're some chinese in comment

### ISSUE THREAD

**Issue by linwukang** [cloudera/hue#896]
exception thrown when there're some chinese in sql editor, for example:

``` sql
--- test
--- 这是一条测试语句
show tables;
```

it is because ace.js cannot get correct charactor width for the line contains chinese, exception will throw in line 73 of 'desktop/core/src/desktop/js/ko/bindings/ko.highlight.js', i think we should catch the exception.

**Comment by romainr** [comment]
Merged!

**Comment by linwukang** [comment]
@romainr tks 👍

**Comment by qshian** [comment]
It happened in hue 4.10.0 again，How can I fix it
