### ISSUE TITLE
Scroll to column in result set does not update the horizontal scroll bar

### ISSUE THREAD

**Issue by aiweaver** [cloudera/hue#898]
Scroll to column in result set does not update the horizontal scroll bar
Hue Version: 4.4

It seems that previous versions of Hue had the same problem.
When I move the horizontal scroll bar to the right in the Result window after querying the Hive Query, the result is invisible.

https://issues.cloudera.org/browse/HUE-4073

![image](https://user-images.githubusercontent.com/38370899/59994795-27e09f00-9690-11e9-9ba6-c23baf815cce.png)

**Comment by linwukang** [comment]
we hit the same issue,  haven't found a way to fix it.

**Comment by romainr** [comment]
It is a tricky bug somewhere. In case it gives a hint, if you slightly resize the window it usually displays the content

**Comment by linwukang** [comment]
> It is a tricky bug somewhere. In case it gives a hint, if you slightly resize the window it usually displays the content

it seems that there're some problem in jquery.huedatatable.js line 439-446, startCol in line 441 is not changed as expected (startCol always is 1 in line 447), not familiar with javascript, working in process to figure it out.

**Comment by linwukang** [comment]
@romainr  I think this bug is located at line 443 of jquery.huedatatable.js. The way to calculate endCol is not correct. when use position() (according to https://api.jquery.com/position/),  '$t.parent()' and '${this}' (the table header element) are not in the same coordinate system, we should add the horizontal  offset of '$t' (the result table) to the header element to make the condition meaningful (compare in the same coordinate system).

**Comment by romainr** [comment]
@JohanAhlen for the context in the PR

**Comment by romainr** [comment]
Closed with https://github.com/cloudera/hue/pull/904

**Comment by psaoji** [comment]
@romainr @aiweaver I am still facing this issue after applying the update from [https://github.com/cloudera/hue/pull/904](url). Could you please advise ? Would appreciate your help.

**Comment by matagyula** [comment]
Greetings, 
I too am facing the same issue, running Hue version 4.4.0 - as part of CDH 6.3.0. I manually edited the following files 

`/opt/cloudera/parcels/CDH-6.3.0-1.cdh6.3.0.p0.1279813/lib/hue/build/static/desktop/js/jquery.huedatatable.js
/opt/cloudera/parcels/CDH-6.3.0-1.cdh6.3.0.p0.1279813/lib/hue/desktop/core/src/desktop/js/jquery/plugins/jquery.huedatatable.js
/opt/cloudera/parcels/CDH-6.3.0-1.cdh6.3.0.p0.1279813/lib/hue/desktop/core/src/desktop/static/desktop/js/jquery.huedatatable.js
`
Applying the fix from #904 but the same issue persists - horizontal scrolling jumps to the furthest column on the right, the table does not refresh and the results aren't shown. Any ideas? :)

**Comment by zevektor** [comment]
Hi,

I am experiencing the same problem on the EMR 5.24.0 version that comes with Hue 4.4.0.

I applied the changes suggested in #904 but the issue still persists.

**Comment by romainr** [comment]
Should be this one https://github.com/cloudera/hue/pull/960#issuecomment-541232722

**Comment by zevektor** [comment]
Thanks for the hint, @romainr!
#960 slightly changes the behavior of the horizontal scrollbar, but it still instantly scrolls to the right and the preview data is still not shown for the columns to the right.

**Comment by swordspoet** [comment]
> Thanks for the hint, @romainr!
> #960 slightly changes the behavior of the horizontal scrollbar, but it still instantly scrolls to the right and the preview data is still not shown for the columns to the right.

I am using Hue 4.2.0, there is still not shown preview data after changing.

**Comment by zevektor** [comment]
@swordspoet Hue 4.2.0 was working fine for us.

**Comment by userxiaozhu** [comment]
> Thanks for the hint, @romainr!
> #960 slightly changes the behavior of the horizontal scrollbar, but it still instantly scrolls to the right and the preview data is still not shown for the columns to the right.

I have the same question, how did you fix it ?

**Comment by Akhilsnaik** [comment]
@userxiaozhu  , Might be You need to have : https://issues.cloudera.org/browse/HUE-9027 in your Hue-4.4.0 .
Please use latest Hue where the issue is fixed.

**Comment by basebase** [comment]
Hello, this problem also occurred in my CDH6.X+HUE4.2.0, I tried to manually repair the following files

The initial path is: /opt/cloudera/parcels/CDH-6.3.21.cdh6.3.2.p0.1605554/lib/hue

desktop/core/src/desktop/js/jquery/plugins/jquery.huedatatable.js
desktop/core/src/desktop/js/jquery/plugins/jquery.horizontalscrollbar.js
desktop/core/src/desktop/static/desktop/css/hue.css
desktop/core/src/desktop/static/desktop/css/hue3-extra.css
desktop/core/src/desktop/static/desktop/js/jquery.horizontalscrollbar.js
desktop/core/src/desktop/static/desktop/less/components/hue-scrollbar.less

But unfortunately, I still can't display it, can you help me please? Or can CDH upgrade HUE independently?

**Comment by basebase** [comment]
> @swordspoet Hue 4.2.0 was working fine for us.

Did you solve your problem? Can you guide me?
