### ISSUE TITLE
I am using the Hue Cli - load data to import workflows the same can be done via UI but not command line.

### ISSUE THREAD

**Issue by apekshatrivedi** [cloudera/hue#901]
I get the following error:

`django.core.serializers.base.DeserializationError: Problem installing fixture '/home/cdhadmin/hue-documents.json': Document2 matching query does not exist.`

Command used: /build/env/bin/hue loaddata hue-document.json.

**Comment by romainr** [comment]
Dup of https://github.com/cloudera/hue/issues/499
