### ISSUE TITLE
Hue cli commands don't work anymore?

### ISSUE THREAD

**Issue by ddrgrievous** [cloudera/hue#902]
https://github.com/cloudera/hue/blob/master/apps/useradmin/src/useradmin/management/commands/import_ldap_group.py

It seems that with the upgrade of django we switched this over to args parse and now when I try to send in my group as a positional argument I get an error saying the argument isn't valid.  The args parser doesn't look for a group.  If I add:

    parser.add_argument("--group", help=_t("Name of Group"),
                              action="store",
                              default=None)

to the add_arguments method I am able to pass in my group. (EX hue import_ldap_group --group "My Group" --import-members) Am I missing something or is this a bug?  In previous versions of hue it would work with me passing the group name as the first argument like this 
hue import_ldap_group  "My Group" --import-members

**Comment by romainr** [comment]
Thanks for the report and indeed it seems like a bug after the move to Django 1.11 in Hue 4.0, and to accept group as an arg like before:

        parser.add_argument('group', nargs='+', type=str)

https://docs.djangoproject.com/en/2.2/howto/custom-management-commands/#accepting-optional-arguments

Should work?

We probably need to do the same for https://github.com/cloudera/hue/blob/master/apps/useradmin/src/useradmin/management/commands/import_ldap_user.py

Would you be able to send a pull request?

**Comment by romainr** [comment]
Hey @ddrgrievous, does above help?

**Comment by ddrgrievous** [comment]
Hi Romainr,

That makes sense to me.  Unfortunately due to corporate policies I can't make a contribution to the project since I found the issue during work hours.

**Comment by romainr** [comment]
https://issues.cloudera.org/browse/HUE-8946
