### ISSUE TITLE
[Upgrade] Upgrade from Hue 4.1 to Hue 4.4 cause user creation unavailable 

### ISSUE THREAD

**Issue by linwukang** [cloudera/hue#906]
the reason is that,  the field `last_login` in the table `auth_user` cannot be null in hue 4.2 while nullable in hue4.4. After upgraded hue from 4.2 to 4.4 (with both `syncdb` and `migrate`
executed), the schema is NOT changed any more. 

fix this with the sql below (mysql):
``` sql
ALTER TABLE auth_user MODIFY last_login datetime null;
```
Maybe we should add this into `migrate` command.

**Comment by jdesjean** [comment]
can you confirm that you ran:
hue migrate --fake-initial

**Comment by linwukang** [comment]
> can you confirm that you ran:
> hue migrate --fake-initial

Hi, @jdesjean I just run `hue migrate`, i should run `hue migrate --fake-initial` instead, right?

**Comment by jdesjean** [comment]
Correct.

**Comment by linwukang** [comment]
So, how can I closed this issue?

**Comment by linwukang** [comment]
Perfect.

**Comment by SharpLu** [comment]
@linwukang 
Does it work to you when you execute hue migrate --fake-initial?

I'm trying to upgrade my exists HUE 4.2 to HUE 4.4 in AWS EMR,
when I execute below command it shows success, but I didn't see any data migrated from hue 4.2 to hue 4.4, do you have any suggestion?
$ sudo /usr/lib/hue/build/env/bin/hue migrate --fake-initial

Operations to perform:
  Apply all migrations: admin, auth, axes, beeswax, contenttypes, desktop, django_openid_auth, jobsub, oozie, sessions, sites, useradmin
Running migrations:
  Applying contenttypes.0001_initial... FAKED
  Applying auth.0001_initial... FAKED
  Applying admin.0001_initial... FAKED
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying axes.0001_initial... FAKED
  Applying axes.0002_auto_20151217_2044... OK
  Applying axes.0003_auto_20160322_0929... OK
  Applying axes.0004_auto_20190514_1321... OK
  Applying beeswax.0001_initial... FAKED
  Applying desktop.0001_initial... FAKED
  Applying desktop.0002_initial... FAKED
  Applying desktop.0003_initial... OK
  Applying desktop.0004_initial... OK
  Applying desktop.0005_initial... FAKED
  Applying desktop.0006_initial... FAKED
  Applying desktop.0007_initial... FAKED
  Applying django_openid_auth.0001_initial... FAKED
  Applying jobsub.0001_initial... FAKED
