### ISSUE TITLE
Hive or Impala Editor in Chrome browser auto filling word

### ISSUE THREAD

**Issue by zhoubh** [cloudera/hue#908]
Hello,
 I have got a problem when open Hive or Impala Editor in Chrome browser , the database blank will always auto fill  words like 'yarn',  just like the picture .
Any help will be great .
Thank you.

![image](https://user-images.githubusercontent.com/9634733/60335236-02c19880-99d0-11e9-84b7-4592ff6e515e.png)

**Comment by romainr** [comment]
Do you still have it on the latest Hue version? (Master) Should be fixed in
the upcoming one 4.5 or by disabling autofill

**Comment by zhoubh** [comment]
Hi,

Our Hue version  4.2.0+cdh6.2.0 and 3.9.0+cdh6.0.1 both have this problem.
And I just find "Disable  SQL Editor Autocompleter" , but  can't resolve it.
Any method can disabling autofill ?
Thanks a lot.

**Comment by hombin** [comment]
Maybe you could use "onfocus" to solve this.

In "desktop/core/src/desktop/js/ko/components/ko.inlineAutocomplete.js"

change 41 to 45:
`clearable: { value: searchInput, onClear: onClear },
          css: { 'inline-autocomp-magnify-input': showMagnify }">
        <input class="inline-autocomp-autocomp" disabled type="text" autocomplete="do-not-autocomplete" data-bind="
          value: inlineAutocomplete,
          css: { 'inline-autocomp-magnify-input': showMagnify }">`

to:
`clearable: { value: searchInput, onClear: onClear },
          css: { 'inline-autocomp-magnify-input': showMagnify }"
          readonly onfocus="this.removeAttribute('readonly');">
        <input class="inline-autocomp-autocomp" disabled type="text" autocomplete="do-not-autocomplete" data-bind="
          value: inlineAutocomplete,
          css: { 'inline-autocomp-magnify-input': showMagnify }"
          readonly onfocus="this.removeAttribute('readonly');">`

**Comment by zhoubh** [comment]
@hombin , wow ,  that help me . I found  the js in "/opt/cloudera/parcels/CDH/lib/hue/desktop/core/src/desktop/templates/ko_components/ko_inline_autocomplete.mako",   after replace, resolved it .

**Comment by stefansjs** [comment]
Can somebody help explain this to me? Is desktop/core/src/desktop/js/ko/components/ko.inlineAutocomplete.js a file on the web server, or on my local chrome installation? I'm unclear if I'm fixing this server-side or client-side

**Comment by romainr** [comment]
It is on the webserver in the Hue project.
Also do not forget "after this, you need "make apps" to upgrade js webpack files." or run 

```
npm run webpack
npm run webpack-workers
npm run webpack-login
```

https://docs.gethue.com/developer/development/#javascript
