### ISSUE TITLE
Support for rendering HTML files.

### ISSUE THREAD

**Issue by pedro93** [cloudera/hue#915]
**tl,dr:** Does HUE's File Browser render HTML files? 

**Context:**
The use-case is the following, I have an HDFS cluster with multiple large datasets (300GB++ each).
For each dataset, I am compiling a data report (general statistics about the dataset, cardinality of fields, time range, histograms, etc...) in HTML form so that users may quickly browse and understand each dataset. 
The aim is to have in the folder of each dataset, the associated HTML report to be quickly perused as a form of a data catalog.

Is this possible with HUE? From the documentation, It seems like the answer is no but wanted to confirm.
If not, is this in the backlog? Is it hard to do?

Thank you!

**Comment by romainr** [comment]
Adding something like 'text/html' to the list of files to inlines instead of direct download might work (and would be worth sending in a pull request):

https://github.com/cloudera/hue/blob/master/apps/filebrowser/src/filebrowser/views.py#L91
