### ISSUE TITLE
Does Hue support python3?

### ISSUE THREAD

**Issue by fsilent** [cloudera/hue#925]
Does Hue support python3?

**Comment by romainr** [comment]
This is currently a work in progress (70% done) in https://issues.cloudera.org/browse/HUE-8737 by @wing2fly

**Comment by fsilent** [comment]
This is good news, can I know when 4.5.0 will be released?

**Comment by romainr** [comment]
4.5 will probably be at the end of July or early August (but might no include Python 3, not sure yet)

**Comment by fsilent** [comment]
thanks very much~
