### ISSUE TITLE
Hue execute hive query very slowly, log shows waited for thrift client to ip:21066

### ISSUE THREAD

**Issue by fsilent** [cloudera/hue#935]
![image](https://user-images.githubusercontent.com/9815890/62220519-be685480-b3e2-11e9-9f44-e7a1688032cb.png)

Hue execute hive query very slowly, log shows waited for thrift client to ip:21066

version:3.11.0

**Comment by romainr** [comment]
Hue 3 is not supported anymore, and Hue 4 has a lot of optimization.

Please also share the load, number of users etc... and check that Hive is not overwhelmed and blocking the RPC calls (later can be common).
