### ISSUE TITLE
When can Hue support python3?

### ISSUE THREAD

**Issue by fsilent** [cloudera/hue#939]
https://issues.cloudera.org/browse/HUE-8737

I noticed that python3 has been put into version 4.6.0, which means have to wait about half a year to support the python3 version?

**Comment by alericmckearn** [comment]
Another alternative is to allow yarn to run docker and then run the spark session in a python3 docker container.  It also has the added benefit of you not having to maintain every pip package under the sun on a cluster.

just add these params to the session:

spark.yarn.appMasterEnv.YARN_CONTAINER_RUNTIME_DOCKER_IMAGE=<image>
spark.executorEnv.YARN_CONTAINER_RUNTIME_DOCKER_IMAGE=<image>
spark.executorEnv.YARN_CONTAINER_RUNTIME_TYPE=docker
spark.yarn.appMasterEnv.YARN_CONTAINER_RUNTIME_TYPE=docker

I'm working on some changes to the session screen to make it a little more straightforward to use docker.

**Comment by romainr** [comment]
cf. comment https://issues.cloudera.org/browse/HUE-8737?focusedCommentId=221851&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-221851
