### ISSUE TITLE
Hive's history queries cannot be downloaded,My hue version is :3.9.0+cdh5.14.0+7830

### ISSUE THREAD

**Issue by lidaxia0** [cloudera/hue#942]
![QQ图片20190811181953](https://user-images.githubusercontent.com/42379199/62832673-b02cfa80-bc64-11e9-9512-1bd20ed24146.png)

**Comment by romainr** [comment]
This is very probably a little bug fixed in newer versions

**Comment by lidaxia0** [comment]
May I ask, do I have to update the version to solve it? Thank you




------------------ 原始邮件 ------------------
发件人: "Romain Rigaux"<notifications@github.com>; 
发送时间: 2019年8月11日(星期天) 晚上11:02
收件人: "cloudera/hue"<hue@noreply.github.com>; 
抄送: "我叫李大侠"<1045761107@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [cloudera/hue] Hive's history queries cannot be downloaded,My hueversion is :3.9.0+cdh5.14.0+7830 (#942)




This is very probably a little bug fixed in newer versions
