### ISSUE TITLE
Zookeeper browser in hue 4

### ISSUE THREAD

**Issue by nomoo** [cloudera/hue#943]
Hue version: 4.3.0

using hue as standalone app.

Can't get it to work, already have all relevant sections in ini file, cluster is not kerberized.
I don't see any 'zookeeper browser' in menu.

'zookeeper' is in 'Installed Applications' but '/hue/zookeeper/' link shows 404

Does it work in hue 4 ?

**Comment by romainr** [comment]
The app was not ported to Hue 4, but any contribution would be welcomed.

**Comment by evgenii-tregubov** [comment]
@romainr   Done in https://github.com/arenadata/hue/pull/26
