### ISSUE TITLE
CDH 6.3 Files in /var/log/hue not being updated

### ISSUE THREAD

**Issue by matagyula** [cloudera/hue#953]
Greetings,
After a successful upgrade from CDH 5.15 to CDH 6.3 we've encountered a problem where the hue logs are not being updated. Using Hue itself the logs are accessible via the Web UI, but for some reason they are not being synchronized with /var/log/hue.
Is there a config file or some setting I should check? Comparing the configuration of our 5.15 cluster to our 6.3 cluster, there seem to be no differences regarding logging configuration.
Thank you for your help in advance!
Kind regards,
Gyuszi

**Comment by jdesjean** [comment]
@matagyula There's a KB article for this issue: https://my.cloudera.com/knowledge/Logs-not-updating-in-varloghue-after-upgrade-to-CDH-6?id=87842

**Comment by matagyula** [comment]
@jdesjean Cheers, just what I was looking for. I'll make a habit of checking KB articles in the future :) 
Thank you, the issue is now resolved.
