### ISSUE TITLE
editor- table scrollbar can't works fluently in windows

### ISSUE THREAD

**Issue by daisy0123** [cloudera/hue#955]
![hue](https://user-images.githubusercontent.com/11910330/63633681-b8cafb00-c67e-11e9-9d3b-dd8dbc3739e5.png)

please help me solve the problem, thanks

**Comment by romainr** [comment]
Fixed in https://github.com/cloudera/hue/commit/979aeea1cb718db8776430c4cb67086c1dbd39a3
