### ISSUE TITLE
Workflow drag icon error

### ISSUE THREAD

**Issue by helloxteen** [cloudera/hue#963]
Hi,this is my configuration.
hue:latest docker
hadoop:2.5.6
hive:2.3.6
oozie:4.3.1
when i using wokflow and drag icon to workflow, it's abnormal，like photo below and web console throw error
![image](https://user-images.githubusercontent.com/29169986/64400308-57ebeb80-d09e-11e9-95bc-116f19357895.png)

the official demo like this，it will pop a window
![image](https://user-images.githubusercontent.com/29169986/64400372-9a152d00-d09e-11e9-8cc3-34c68ddc67fc.png)

please help me

**Comment by helloxteen** [comment]
hue version print wrong

**Comment by JohanAhlen** [comment]
Hi,

thanks for reporting the issue, it's now been fixed with https://github.com/cloudera/hue/commit/997bdf6064bd89f5400eb869f95169f835093566

Cheers,
Johan
