### ISSUE TITLE
Error accessing the database: Snippet type custom is not configured

### ISSUE THREAD

**Issue by mario1oreo** [cloudera/hue#966]
Error accessing the database: Snippet type custom is not configured

Hue 4.5     
tar hue.4.5gz build to install
config_jars_libs_path /user/hdfs/libext/libs
put  mysql-connector-java.jar into /user/oozie/libext/jdbc_drivers
chmod 755 to all

use imporer to import data from MySQL 
type External Database
model customer
driver MySQL
host 10.42.16.58
port 3306
user surpt
pwd surpt

then click test connect

error message :
连接失败：Error accessing the database: Snippet type custom is not configured.

log:  nothing wrong

**Comment by arman1371** [comment]
also i have this problem in importing data with hue
did you find the solution ?

**Comment by jessequinn** [comment]
any resolution on this? Postgres also returns this message on importing an external database.

**Comment by Akhilsnaik** [comment]
@jessequinn  ,  the error is due to something not configured well in hue.ini file (or pseudo ini if using the dev version)
Please look into that.

**Comment by jessequinn** [comment]
it's more than likely related to oozie. I am configuring this now.

**Comment by xingon** [comment]
same question...anybody knows it?

**Comment by tencentemr** [comment]
some problem here,how to slove it?
hue 4.6.0

![image](https://user-images.githubusercontent.com/60807629/108612005-6effd400-741f-11eb-9cf2-ce108c9a4dba.png)

**Comment by jessequinn** [comment]
@tencentemr you need to configure the source in the `.ini`

**Comment by tencentemr** [comment]
> @tencentemr you need to configure the source in the `.ini`

Hey jersey thanx your reply
Could u show me the code how to configure ini file.for example if I wanna use customizable jdbc or hostname on this section?

**Comment by tencentemr** [comment]
> @tencentemr you need to configure the source in the `.ini`

@jessequinn 

Hey jersey thanx your reply
Could u show me the code how to configure ini file.for example if I wanna use customizable jdbc or hostname on this session?

**Comment by ajs6f** [comment]
@jessequinn Could you please explain a bit more about what you mean by "configure the source"? I see several sections mentioning MySQL as available for use as the db backend for Hue (obviously not what we're talking about) or as a subsection in the `librdbms` section. Is the `librbdms` section what you mean? Thanks for any help!

**Comment by divincode** [comment]
@ajs6f did u find the solution for the problem?

**Comment by ajs6f** [comment]
@divincode Nope, and we've given up on this. We aren't using Hue heavily now. Good luck, and please do comment here if you _do_ figure it out.
