### ISSUE TITLE
Python3 support for CDH 5.x

### ISSUE THREAD

**Issue by elukey** [cloudera/hue#968]
Hi!

Is there any plan to make a CDH 5.x release to allow Python 3.5+ given https://www.python.org/doc/sunset-python-2/ ? Hue is also currently relying on very old dependencies that would need to get upgraded if possible :)

**Comment by romainr** [comment]
As of today, there is no plan for CDH5/6, only CDP (the new distribution).

**Comment by elukey** [comment]
@romainr thanks a lot for the answer. Last question - is it possible to use the Hue package on CDH6 with packages in CDH5 as workaround, or due to the Hadoop 2->3 switch nothing will ever work? I am trying to understand if I can workaround this issue, we are not ready to migrate to CDH6 yet but we'd like to avoid running python2 until we do it.

**Comment by elukey** [comment]
@romainr thanks a lot for the answer. Can I ask why the update will not even be present in CDH6 given the promise of cloudera to support it up to 2022? Running python2 after the next January is not really an option (https://www.python.org/doc/sunset-python-2/).

**Comment by romainr** [comment]
Please follow https://issues.cloudera.org/browse/HUE-8737 and contact Cloudera support(here it is upstream Hue which is a bit different from Cloudera's distribution)
