### ISSUE TITLE
mysql8.0  with Hue  “my_conf.h”,not find that file

### ISSUE THREAD

**Issue by AlexanderGPY** [cloudera/hue#971]
makeapps:

_mysql.c:44:23: Error：my_config.h：no such file or directory
 #include "my_config.h"

mysql-devel  is already  installed
mysql-python-1.2.5 is already installed

but it doesn't work
Is hue not supporting mysql8.X?
or which version is supported ?

On centos7.X
PLEASE！

**Comment by JSbiu** [comment]
看这个
https://blog.csdn.net/qq_38924171/article/details/101426144#commentBox

**Comment by AlexanderGPY** [comment]
> https://blog.csdn.net/qq_38924171/article/details/101426144#commentBox

it abs solved my question!
tks 4 u answer!

**Comment by romainr** [comment]
And this issue should go away with https://issues.cloudera.org/browse/HUE-8737
