### ISSUE TITLE
Old UI  Endpoint (3.*) is not Available in Hue 4.4 (including increasing concurrency)

### ISSUE THREAD

**Issue by Am1rr3zA** [cloudera/hue#976]
I have just upgraded our EMR cluster: 
in the old cluster, we had 
`Oozie 4.3.0, Hue 3.11.0`
and in the current cluster, we have
`Oozie 5.1.0, Hue 4.4.0`
In the new Hue UI, we have noticed a couple of old endpoints are not available anymore which is very inconvenient.

We can not see the list of running coordinator and workflow anymore by hitting these paths

> http://MASTER-IP-ADDRESS:8888/oozie/list_oozie_coordinators/
> http://MASTER-IP-ADDRESS:8888/oozie/list_oozie_workflows/
> http://MASTER-IP-ADDRESS:8888/oozie/editor/coordinator/list/
> http://MASTER-IP-ADDRESS:8888/oozie/editor/workflow/list/

And more importantly, I can not find any way to increase the job concurrency (which we used to do pretty easy on coordinator page on the old Hue UI)

![Screen Shot 2019-10-03 at 11 24 31 AM](https://user-images.githubusercontent.com/3633422/66140641-75926f00-e5d0-11e9-8b41-e0b0637998e4.png)

**Comment by romainr** [comment]
cc @wing2fly
