### ISSUE TITLE
HUE is using de the default YARN queue.

### ISSUE THREAD

**Issue by fguiet** [cloudera/hue#981]
I am using Hue 4.5 (Open Source), each time I am trying to launch a Scala, Spark, PySpark query editor, it ends up with following error : The Spark session could not be created in the cluster

Indeed, when I connect to my Livy Server I can see the following error : Failed to submit application_1570430934619_0007 to YARN : Application rejected by queue placement policy.

I changed the default queue policy on my Hortonwork Hadoop Cluster. How can I specify the YARN Queue to use in Hue so it can call the Livy API correctly (ie with the good queue to use) ?

**Comment by alericmckearn** [comment]
repeat of #460 - i messed up the PR thinking that notebooks were separate from the main pyspark page.  desktop/libs/notebook/src/notebook/connectors/spark_shell.py

{
      "name": "queue",
      "nice_name": _("Queue"),
      "help_text": _("The YARN queue to submit to, only in cluster mode (Default: default)"),
      "type": "string",
      "is_yarn": True,
      "multiple": False,
      "defaultValue": "default",
      "value": "",
    }

i'll see if i can get some time to fix the pr and get this configurable.

**Comment by fguiet** [comment]
Thank you alericmckearn.

What I have just done to fix this issue is changed the default value for YARN name queue is the file desktop/libs/notebook/src/notebook/connectors/spark_shell.py

So now I have:

```
{
      "name": "queue",
      "nice_name": _("Queue"),
      "help_text": _("The YARN queue to submit to, only in cluster mode (Default: default)"),
      "type": "string",
      "is_yarn": True,
      "multiple": False,
      "defaultValue": 'root.LAB',
      "value": 'root.LAB',
}
```

**Comment by fguiet** [comment]
How can I change Default Livy parameter when it is creating the Spark Session with Scala Notebook ?
Is this related to : https://issues.cloudera.org/browse/HUE-2727
Thank you
