### ISSUE TITLE
'Sync Workflow' button missing  in Hue 4

### ISSUE THREAD

**Issue by louisdecharson** [cloudera/hue#982]
Hi,

I am looking for the button "Sync workflow" in Hue 4 (I am using CDH 5.15.1) in the Coordinator schedule page.
In Hue 3, there was a button (see screenshot) but it's not there anymore in Hue 4.
How can one synchronize a coordinator with the workflow ? 
![sync_workflows](https://user-images.githubusercontent.com/3234544/66325823-36de1b00-e928-11e9-8fb2-378b678cf557.PNG)

The use-case is to update the queries inside the workflow folder after changing one of them.

Best,

Louis

**Comment by romainr** [comment]
@wing2fly just did https://issues.cloudera.org/browse/HUE-8980

**Comment by louisdecharson** [comment]
Many thanks for the swift follow-up @romainr !
If I get you correctly, there's no way one can sync the workflow (even without the button) before version 4.6.0 ?

**Comment by wing2fly** [comment]
@louisdecharson Right, you will need the buttons.
