### ISSUE TITLE
Hook up Settings properties for Spark Submit Jar and Spark Submit Python

### ISSUE THREAD

**Issue by fguiet** [cloudera/hue#984]
Settings properties for `Spark Submit Jar` and `Spark Submit Python` are not taken into account.

I mean `queue`, `executors` and the like properties. Moreover 2 importants parameters are missing (see Livy Rest Api documentation) : driverMemory, executorMemory

Fix can be done easily by modifying the file `spark_batch.py`
I did it on my own and it is working. I tried to add fields (ie driverMemory, executorMemory) but...I need to rebuild js files into a bundle (so it is taken into account) and I don't know how to it  (npm webpack seems to do the job....)

Below, what I have changed in `spark_batch.py` to make it work

```
if snippet['type'] == 'jar':
        properties = {
            'file': snippet['properties'].get('app_jar'),
            'className': snippet['properties'].get('class'),
            'args': snippet['properties'].get('arguments'),
            **Add new properties here**
        }
    elif snippet['type'] == 'py':
        properties = {
            'file': snippet['properties'].get('py_file'),
            'args': snippet['properties'].get('argument', []),
            **Add new properties here**
        }
    else:
        properties = {
            'file': snippet['properties'].get('app_jar'),
            'className': snippet['properties'].get('class'),
            'args': snippet['properties'].get('arguments'),
            'pyFiles': snippet['properties'].get('py_file'),
            'files': snippet['properties'].get('files'),
            # driverMemory
            # driverCores
            # executorMemory
            # executorCores
            # archives
        }
```

Thank you
Fred

**Comment by romainr** [comment]
Hey Fred, do you think you could just send a pull request?

**Comment by fguiet** [comment]
Was about to do it...but don't have a dev environment set up. Can you tell me what do you use ? Pycharm? Vs code ?
