### ISSUE TITLE
npm ERR! errno ECONNREFUDED

### ISSUE THREAD

**Issue by AndreyEmelyanenko** [cloudera/hue#985]
Error occurs, while building HUE release-4.5 in NO-internet environment. How it can be fixed?

--- Generating /ws/build/hue/rpm/BUILD/hue-release-4.5.0/desktop/conf/pseudo-distributed.ini
sed -e 's:$HADOOP_HOME:/usr/lib/hadoop:' /ws/build/hue/rpm/BUILD/hue-release-4.5.0/desktop/conf/pseudo-distributed.ini.tmpl > /ws/build/hue/rpm/BUILD/hue-release-4.5.0/desktop/conf/pseudo-distributed.ini
make[1]: Leaving directory `/ws/build/hue/rpm/BUILD/hue-release-4.5.0/desktop'
make[1]: Entering directory `/ws/build/hue/rpm/BUILD/hue-release-4.5.0'
npm install
make[1]: Leaving directory `/ws/build/hue/rpm/BUILD/hue-release-4.5.0'

RPM build errors:
npm ERR! Linux 3.10.0-957.21.3.el7.x86_64
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install"
npm ERR! node v0.10.44
npm ERR! npm  v2.15.0
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED
npm ERR!     at errnoException (net.js:905:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:896:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   parent: 'hue' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /ws/build/hue/rpm/BUILD/hue-release-4.5.0/npm-debug.log
make[1]: *** [npm-install] Error 1
make: *** [apps] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.QmZnXL (%build)
    Bad exit status from /var/tmp/rpm-tmp.QmZnXL (%build)

FAILURE: Build failed with an exception.

As I guess, npm tries to install packages from https://registry.npmjs.org/, which is unreachable. What's the best way to solve this?

Thanks in advance!

**Comment by romainr** [comment]
It won't work without Internet, you would need an internal proxy that hosts these packages or tweak npm to have those downloaded beforehand so that it fetches them locally.

**Comment by AndreyEmelyanenko** [comment]
> It won't work without Internet, you would need an internal proxy that hosts these packages or tweak npm to have those downloaded beforehand so that it fetches them locally.

I made on server with internet:
`npm install --no-bin-links`
got a node_modules dir with all modules

Then copied it to root directory of hue project on remote server and got the following error while `npm run webpack`:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node/bin/node',
1 verbose cli   '/usr/local/node/bin/npm',
1 verbose cli   'run',
1 verbose cli   'webpack' ]
2 info using npm@2.15.0
3 info using node@v0.10.44
4 verbose node symlink /usr/local/node/bin/node
5 verbose run-script [ 'prewebpack', 'webpack', 'postwebpack' ]
6 info prewebpack hue@4.4.0
7 info webpack hue@4.4.0
8 verbose unsafe-perm in lifecycle true
9 info hue@4.4.0 Failed to exec webpack script
10 verbose stack Error: hue@4.4.0 webpack: `webpack --config webpack.config.js`
10 verbose stack Exit status 8
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/node-v0.10.44-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/node-v0.10.44-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:766:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
11 verbose pkgid hue@4.4.0
12 verbose cwd /ws/build/hue/rpm/BUILD/hue-release-4.5.0
13 error Linux 3.10.0-957.21.3.el7.x86_64
14 error argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "run" "webpack"
15 error node v0.10.44
16 error npm  v2.15.0
17 error code ELIFECYCLE
18 error hue@4.4.0 webpack: `webpack --config webpack.config.js`
18 error Exit status 8
19 error Failed at the hue@4.4.0 webpack script 'webpack --config webpack.config.js'.
19 error This is most likely a problem with the hue package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     webpack --config webpack.config.js
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs hue
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls hue
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by AndreyEmelyanenko** [comment]
Yeah, the only solution I've found - run `npm install --no-bin-links` on host with internet, and then copy-paste `desktop/core/src/desktop/static/desktop/js/bundles/*` and `webpack-stats*` to the remote host. Looks like a fit workaround.

Just a wish - it would be excellent, if hue could be build without internet! 
Thanks
