### ISSUE TITLE
Docker starts hue, unable to find the resource MySQL

### ISSUE THREAD

**Issue by uzdz** [cloudera/hue#986]
I use pull to pull the docker image and start it.However, MySQL was not found in sources after startup.Why？

![image](https://user-images.githubusercontent.com/28328355/66918462-fe3df000-f051-11e9-819d-9b6d711568cf.png)

Just now I used the following command:

docker pull gethue/hue:latest

**Comment by romainr** [comment]
Docker Hue does not boot any MySql so it was removed. Will put back a Sqlite interpreter.

If you need to point to an external MySql to query it, this should help: https://github.com/cloudera/hue/tree/master/tools/docker/hue#configuration (and should be one command with docker-compose)
