### ISSUE TITLE
Snippet type hive is not configured

### ISSUE THREAD

**Issue by AndreyEmelyanenko** [cloudera/hue#988]
HI!

Installed hue 4.5 and hive 2.3.3. Trying to use hive via hue and get the error: 
`snippet type hive is not configured`

How to fix, what's the problem?

Thanks in advance!

**Comment by romainr** [comment]
Do you have this one uncommented in the hue.ini?
https://github.com/cloudera/hue/blob/master/desktop/conf.dist/hue.ini#L907

(or pseudo ini if using the dev version)

**Comment by AndreyEmelyanenko** [comment]
Yes, my [[interpreters]] is below: 

  # One entry for each type of snippet. The first 5 will appear in the wheel.
  [[interpreters]]
    # Define the name and how to connect and execute the language.
    [[[hive]]]
      # The name of the snippet.
      name=Hive
      # The backend connection to use to communicate with the server.
      interface=hiveserver2
    [[[text]]]
      name=Text
      interface=text
    [[[markdown]]]
      name=Markdown
      interface=text

**Comment by AndreyEmelyanenko** [comment]
I guess, it may be caused by some problems with my build, but I can't define what's wrong.
