### ISSUE TITLE
TSocket read 0 bytes

### ISSUE THREAD

**Issue by AndreyEmelyanenko** [cloudera/hue#990]
Facing error `TSocket read 0 bytes` while trying to use Databases tab in HUE 4.5. And `Error loading entries` instead Databases. In Administration tab I see: 
`Hive | The application won't work without a running HiveServer2.`
thrift server is running. 
Need help..

**Comment by romainr** [comment]
Please use https://discourse.gethue.com/ for debugging/usage questions
