### ISSUE TITLE
404 when create new hive table

### ISSUE THREAD

**Issue by AndreyEmelyanenko** [cloudera/hue#999]
Hi!

When in HUE click 'Tables' tab and then small plus-icon, saying 'Create table' in Hive - I get "404 Page not found". But at the same time I can create Databases and tables via big buttons on the right, like '+ New', and via query in hive editor. What's the problem?
Thanks in advance
HUE 4.5
Hive 2.3.3

Andrey

**Comment by AndreyEmelyanenko** [comment]
URL under plus-button: http://localhost:8888/hue/False/?sourceType=hive&namespace=default
correct URL should be: http://localhost:8888/hue/indexer/importer/prefill/manual/database//?sourceType=hive&namespace=default&compute=default

**Comment by elisabetao** [comment]
Hi Andrey,

This is fixed with HUE-8945 [useradmin] Fix global_js_constants apps  : 
https://github.com/cloudera/hue/commit/85dd1064d82b26f2efcad18bdd6652dc9c9c1070#diff-122102bcd47f43ee9e4a0ceac7fe8018 in Hue 4.6

Hope this helps,
Elisabeta

**Comment by romainr** [comment]
Thanks for the report and thanks for the link Elisabeta!
